### ISSUE TITLE
`Error: Sorry, this model works only on 2GB+ GPU` on GPU with 2GB dedicated VRAM

### ISSUE THREAD

**Issue by Ludoboii** [iperov/DeepFaceLab#1]
## Expected behavior
Start training.

## Actual behavior
The script shows this output:
```
Running trainer.

Loading model...
/home/giovanni/virtualenv/faceswap/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-06-05 12:48:16.247626: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-05 12:48:16.644955: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-06-05 12:48:16.645801: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce 840M major: 5 minor: 0 memoryClockRate(GHz): 1.124
pciBusID: 0000:01:00.0
totalMemory: 1.96GiB freeMemory: 1.80GiB
2018-06-05 12:48:16.645834: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-06-05 12:48:30.618264: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-05 12:48:30.618302: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-06-05 12:48:30.618312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-06-05 12:48:30.661743: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1562 MB memory) -> physical GPU (device: 0, name: GeForce 840M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Using TensorFlow backend.
Error: Sorry, this model works only on 2GB+ GPU
Traceback (most recent call last):
  File "/home/giovanni/git_repos/DeepFaceLab/mainscripts/Trainer.py", line 41, in trainerThread
    **in_options)
  File "/home/giovanni/git_repos/DeepFaceLab/models/ModelBase.py", line 108, in __init__
    self.onInitialize(**in_options)
  File "/home/giovanni/git_repos/DeepFaceLab/models/Model_H64/Model.py", line 18, in onInitialize
    self.set_vram_batch_requirements( {2:2,3:4,4:8,5:16,6:32,7:32,8:32,9:48} )
  File "/home/giovanni/git_repos/DeepFaceLab/models/ModelBase.py", line 323, in set_vram_batch_requirements
    raise Exception ('Sorry, this model works only on %dGB+ GPU' % ( keys[0] ) )
Exception: Sorry, this model works only on 2GB+ GPU
```
However my GPU does have 2GBs of dedicated VRAM (the script says `totalMemory: 1.96GiB`, which is more than 2GB), it's an Nvidia GeForce 840M. I imagine the problem could be that only 1.80GiB are free, but I have no idea how to free more memory. I don't know if it's possible to use the integrated Intel Graphics GPU to handle my laptop's graphics and use the Nvidia GPU exclusively for tensorflow, I haven't found out anything so far, but I'm still researching this topic.

## Steps to reproduce
```
$ python main.py train --training-data-src-dir ./data-old/person1 --training-data-dst-dir ./data-old/person2 --model-dir ./face-models --model H64 --write-preview-history --save-interval-min 30
```
## Other relevant information
- **Operating system and version:** elementary OS 0.4.1 Loki, Built on "Ubuntu 16.04.3 LTS", Linux 4.13.0-43-generic
- **Python version:** 3.5.2

**Comment by iperov** [comment]
check last commit

**Comment by Ludoboii** [comment]
Thanks, works perfectly now.

**Comment by shadowzoom** [comment]
@Ludoboii hi, how i figured it out for working? I have the same gpu but i can't run it... What cuda toolkit you have and what driver version you have?
