### ISSUE TITLE
Error starting training with SAE

### ISSUE THREAD

**Issue by jslurm** [iperov/DeepFaceLab#104]
Downloaded the newest prebuilt to try SAE. Getting the following error when I try to run training:

```
Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 258, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "F:\fakes\DeepFaceLab_build_09_01_2019\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\iter_utils.py", line 39, in process_func
    gen_data = next (self.generator_func)
  File "F:\fakes\DeepFaceLab_build_09_01_2019\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\samples\SampleGeneratorFace.py", line 61, in batch_func
    raise ValueError('No training data provided.')
ValueError: No training data provided.
```

**Comment by jslurm** [comment]
Looks like I didn't properly extract source faces. Working now.

**Comment by zsoltszabo77** [comment]
How? What should i do?
Pls Help
