### ISSUE TITLE
RTX2070 can't extract

### ISSUE THREAD

**Issue by z1146335535** [iperov/DeepFaceLab#130]
It work perfectly fine in my last video card which is 970. However it doesn't work when i change my video card to RTX2070.

Running extractor.

Performing 1st pass...
Running on GeForce RTX 2070.
Exception while initialization: Traceback (most recent call last):
  File "F:\DeepFaceLabTorrent_build_26_01_2019\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 225, in subprocess
    fail_message = self.onClientInitialize(client_dict)
  File "F:\DeepFaceLabTorrent_build_26_01_2019\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 271, in onClientInitialize
    self.e.__enter__()
  File "F:\DeepFaceLabTorrent_build_26_01_2019\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\DLIBExtractor.py", line 17, in __enter__
    self.dlib_cnn_face_detector ( np.zeros ( (self.scale_to, self.scale_to, 3), dtype=np.uint8), 0 )
RuntimeError: Error while calling cudnnConvolutionForward( context(), &alpha, descriptor(data), data.device(), (const cudnnFilterDescriptor_t)filter_handle, filters.device(), (const cudnnConvolutionDescriptor_t)conv_handle, (cudnnConvolutionFwdAlgo_t)forward_algo, forward_workspace, forward_workspace_size_in_bytes, &beta, descriptor(output), output.device()) in file D:\Python365\_internal\bin\dlib\dlib\dnn\cudnn_dlibapi.cpp:1056. code: 8, reason: CUDNN_STATUS_EXECUTION_FAILED

You have no capable GPUs. Try to close programs which can consume VRAM, and run again.
None
Performing 2nd pass...
Running on GeForce RTX 2070.
F:\DeepFaceLabTorrent_build_26_01_2019\DeepFaceLabTorrent\_internal\bin\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-02-02 00:42:02.750164: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-02-02 00:42:02.885410: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.86
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.57GiB
2019-02-02 00:42:02.890623: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2019-02-02 00:42:03.581177: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-02 00:42:03.584359: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2019-02-02 00:42:03.586164: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
2019-02-02 00:42:03.588706: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6311 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:01:00.0, compute capability: 7.5)
Using TensorFlow backend.
Traceback (most recent call last):
  File "F:\DeepFaceLabTorrent_build_26_01_2019\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\main.py", line 127, in <module>
    arguments.func(arguments)
  File "F:\DeepFaceLabTorrent_build_26_01_2019\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\main.py", line 42, in process_extract
    manual_window_size=arguments.manual_window_size
  File "F:\DeepFaceLabTorrent_build_26_01_2019\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 512, in main
    extracted_faces = ExtractSubprocessor (extracted_rects, 'landmarks', image_size, face_type, debug, multi_gpu=multi_gpu, cpu_only=cpu_only, manual=False).process()
  File "F:\DeepFaceLabTorrent_build_26_01_2019\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 137, in process
    self.progress_bar = tqdm( total=self.onHostGetProgressBarLen(), desc=self.onHostGetProgressBarDesc(), ascii=True )  
  File "F:\DeepFaceLabTorrent_build_26_01_2019\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 128, in onHostGetProgressBarLen
    return len (self.input_data)
TypeError: object of type 'NoneType' has no len()

**Comment by gessyoo** [comment]
@z1146335535, the RTX series won't be fully supported until tensorflow-gpu 1.13 is officially released.  Your card needs CUDA 10, this repro relies on CUDA 9.

**Comment by wanshun123** [comment]
Tensorflow 1.13 has been pre-released (https://github.com/tensorflow/tensorflow/releases/tag/v1.13.0-rc0) - can anyone with an RTX try running on that?

**Comment by TeaDrinkingHacker** [comment]
Tensorflow 1.13 has been released (not a rc).  I have an RTX, how would I be able to try and run DFL on it as a test so I can report back here to the group?

**Comment by TeaDrinkingHacker** [comment]
> Tensorflow 1.13 has been pre-released (https://github.com/tensorflow/tensorflow/releases/tag/v1.13.0-rc0) - can anyone with an RTX try running on that?

Point me in the right direction please, how can I test DFL with the latest release of TF 1.13?

**Comment by DuyTheDao** [comment]
same boat here.

**Comment by ExpertAdvisor** [comment]
wanshun123 how did you get it working with your rtx graphics card? could you provide the solution, thanks.
