### ISSUE TITLE
AttributeError: module 'tensorflow.python.ops.image_ops' has no attribute 'ssim'

### ISSUE THREAD

**Issue by 4DeepThought2** [iperov/DeepFaceLab#14]
## Expected behavior

Training should work

## Actual behavior

Training fails with this error:
```
Running trainer.

Loading model...
C:\Users\Singularity\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated
as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-08-14 19:42:44.666474: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Using TensorFlow backend.
Error: module 'tensorflow.python.ops.image_ops' has no attribute 'ssim'
Traceback (most recent call last):
  File "Z:\DeepFaceLab\mainscripts\Trainer.py", line 41, in trainerThread
    **in_options)
  File "Z:\DeepFaceLab\models\ModelBase.py", line 108, in __init__
    self.onInitialize(**in_options)
  File "Z:\DeepFaceLab\models\Model_DF\Model.py", line 41, in onInitialize
    self.autoencoder_src.compile(optimizer=optimizer, loss=[dssimloss, 'mse'] )
  File "C:\Users\Singularity\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 830, in compile
    sample_weight, mask)
  File "C:\Users\Singularity\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 429, in weighted
    score_array = fn(y_true, y_pred)
  File "Z:\DeepFaceLab\nnlib\__init__.py", line 34, in __call__
    loss = (1.0 - tf.image.ssim (y_true*mask, y_pred*mask, 1.0)) / 2.0
AttributeError: module 'tensorflow.python.ops.image_ops' has no attribute 'ssim'
PS Z:\DeepFaceLab`
```

## Steps to reproduce

Latest repo - CUDA 9, everything updated, 1080GT

## Other relevant information
Windows 10
python 3.6.4

**Comment by 4DeepThought2** [comment]
Updated Tensorflow to latest
