### ISSUE TITLE
Build DeepFaceLabCUDA_build_23_02_2019 trainer  SAE gives an error on defaults DF and VG

### ISSUE THREAD

**Issue by wasyleque** [iperov/DeepFaceLab#161]
Loading: 100%|####################################################################| 3931/3931 [00:11<00:00, 340.71it/s]
Error: integer division or modulo by zero
Traceback (most recent call last):
  File "C:\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\mainscripts\Trainer.py", line 39, in trainerThread
    **in_options)
  File "C:\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\models\ModelBase.py", line 151, in __init__
    self.sample_for_preview = self.generate_next_sample()
  File "C:\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\models\ModelBase.py", line 311, in generate_next_sample
    return [next(generator) for generator in self.generator_list]
  File "C:\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\models\ModelBase.py", line 311, in <listcomp>
    return [next(generator) for generator in self.generator_list]
  File "C:\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\samples\SampleGeneratorFace.py", line 57, in __next__
    generator = self.generators[self.generator_counter % len(self.generators) ]
ZeroDivisionError: integer division or modulo by zero
Done.
Press any key to continue . . .

**Comment by iperov** [comment]
no samples in aligned

**Comment by wasyleque** [comment]
you`re right, i dont know how did that happened

**Comment by StefanDukic** [comment]
I've the same problem. Maby because I have Cuda 10.0 and Deepfacelab has 2 versions: One for Cuda 10.1 that I have installed or for 9.2.
