### ISSUE TITLE
[Linux] hang at doing align in Ubuntu

### ISSUE THREAD

**Issue by xinshangbo** [iperov/DeepFaceLab#168]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior
I expected the following command to run successfully:

python3 ./main.py extract --input-dir ./workspace/data_dst --output-dir ./workspace/data_dst/align

## Actual behavior
The following command hang:

python3 ./main.py extract --input-dir ./workspace/data_dst --output-dir ./workspace/data_dst/align

The above command hang with the message below:

Running extractor.
Performing 1st pass...
Running on Tesla P100-PCIE-16GB.
Process Process-1:

## Steps to reproduce
When run the Extract command in Ubuntu system, the command hang with the following message:

Running extractor.

Performing 1st pass...
Running on Tesla P100-PCIE-16GB.
Process Process-1:

I have run the command successfully in MacOS 10.x

## Other relevant information
- python3 ./main.py extract --input-dir ./workspace/data_dst --output-dir ./workspace/data_dst/align
- Linux Ubuntu 16.04 64 bit 
- Python 3.5.2
- GPU: Tesla P100-PCIE-16GB or 1060 (neither work)

**Comment by oracle9i88** [comment]
try https://github.com/lbfs/DeepFaceLab_Linux

**Comment by lbfs** [comment]
Install python3.6 and python3.6-dev and run python3.6 -m pip install -r requirements-cuda.txt
You may need to add a ppa to get these. 
I noticed the program hangs when using 3.5.2 which is the default that Ubuntu 16.04 ships with.
Let me know how it works out for you.

**Comment by sicilyliulc** [comment]
python main.py extract --input-dir workspace/data_dst --output-dir workspace/data_dst/aligned/
Performing 1st pass...
Running on GeForce GTX 1080 Ti #1.
Running on GeForce GTX 1080 Ti #0.
Running on GeForce GTX 1080 Ti #4.
Running on GeForce GTX 1080 Ti #2.
Running on GeForce GTX 1080 Ti #3.
100%|###########################################################################################| 7195/7195 [04:06<00:00, 29.16it/s]
Performing 2nd pass...
Running on GeForce GTX 1080 Ti.
Using TensorFlow backend.
100%|###########################################################################################| 7195/7195 [12:45<00:00,  9.40it/s]
Performing 3rd pass...
Running on CPU2.
Running on CPU3.
Running on CPU4.
Running on CPU1.
Running on CPU0.
Running on CPU5.
Running on CPU7.
Running on CPU6.
  0%|                                                                                                      | 0/7195 [00:00<?, ?it/s]Exception while process data [/data4/liucui/project/DeepFaceLab_Linux-master/workspace/data_dst/video-frame-4328.jpg]: Traceback (most recent call last):
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 18, in load_raw
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data4/liucui/project/DeepFaceLab_Linux-master/workspace/data_dst/aligned/video-frame-4328_0.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data4/liucui/project/DeepFaceLab_Linux-master/joblib/SubprocessorBase.py", line 67, in _subprocess_run
    result = self.process_data (data)
  File "/data4/liucui/project/DeepFaceLab_Linux-master/mainscripts/Extractor.py", line 177, in process_data
    source_landmarks = image_landmarks.tolist()
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 158, in embed_data
    inst = DFLJPG.load_raw (filename)
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 21, in load_raw
    raise FileNotFoundError(data)
UnboundLocalError: local variable 'data' referenced before assignment

Exception while process data [/data4/liucui/project/DeepFaceLab_Linux-master/workspace/data_dst/video-frame-2620.jpg]: Traceback (most recent call last):
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 18, in load_raw
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data4/liucui/project/DeepFaceLab_Linux-master/workspace/data_dst/aligned/video-frame-2620_0.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data4/liucui/project/DeepFaceLab_Linux-master/joblib/SubprocessorBase.py", line 67, in _subprocess_run
    result = self.process_data (data)
  File "/data4/liucui/project/DeepFaceLab_Linux-master/mainscripts/Extractor.py", line 177, in process_data
    source_landmarks = image_landmarks.tolist()
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 158, in embed_data
    inst = DFLJPG.load_raw (filename)
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 21, in load_raw
    raise FileNotFoundError(data)
UnboundLocalError: local variable 'data' referenced before assignment

Exception while process data [/data4/liucui/project/DeepFaceLab_Linux-master/workspace/data_dst/video-frame-5733.jpg]: Traceback (most recent call last):
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 18, in load_raw
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data4/liucui/project/DeepFaceLab_Linux-master/workspace/data_dst/aligned/video-frame-5733_0.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data4/liucui/project/DeepFaceLab_Linux-master/joblib/SubprocessorBase.py", line 67, in _subprocess_run
    result = self.process_data (data)
  File "/data4/liucui/project/DeepFaceLab_Linux-master/mainscripts/Extractor.py", line 177, in process_data
    source_landmarks = image_landmarks.tolist()
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 158, in embed_data
    inst = DFLJPG.load_raw (filename)
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 21, in load_raw
    raise FileNotFoundError(data)
UnboundLocalError: local variable 'data' referenced before assignment

Exception while process data [/data4/liucui/project/DeepFaceLab_Linux-master/workspace/data_dst/video-frame-4972.jpg]: Traceback (most recent call last):
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 18, in load_raw
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data4/liucui/project/DeepFaceLab_Linux-master/workspace/data_dst/aligned/video-frame-4972_0.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data4/liucui/project/DeepFaceLab_Linux-master/joblib/SubprocessorBase.py", line 67, in _subprocess_run
    result = self.process_data (data)
  File "/data4/liucui/project/DeepFaceLab_Linux-master/mainscripts/Extractor.py", line 177, in process_data
    source_landmarks = image_landmarks.tolist()
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 158, in embed_data
    inst = DFLJPG.load_raw (filename)
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 21, in load_raw
    raise FileNotFoundError(data)
UnboundLocalError: local variable 'data' referenced before assignment

Exception while process data [/data4/liucui/project/DeepFaceLab_Linux-master/workspace/data_dst/video-frame-1367.jpg]: Traceback (most recent call last):
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 18, in load_raw
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data4/liucui/project/DeepFaceLab_Linux-master/workspace/data_dst/aligned/video-frame-1367_0.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data4/liucui/project/DeepFaceLab_Linux-master/joblib/SubprocessorBase.py", line 67, in _subprocess_run
    result = self.process_data (data)
  File "/data4/liucui/project/DeepFaceLab_Linux-master/mainscripts/Extractor.py", line 177, in process_data
    source_landmarks = image_landmarks.tolist()
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 158, in embed_data
    inst = DFLJPG.load_raw (filename)
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 21, in load_raw
    raise FileNotFoundError(data)
UnboundLocalError: local variable 'data' referenced before assignment

Exception while process data [/data4/liucui/project/DeepFaceLab_Linux-master/workspace/data_dst/video-frame-6577.jpg]: Traceback (most recent call last):
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 18, in load_raw
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data4/liucui/project/DeepFaceLab_Linux-master/workspace/data_dst/aligned/video-frame-6577_0.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data4/liucui/project/DeepFaceLab_Linux-master/joblib/SubprocessorBase.py", line 67, in _subprocess_run
    result = self.process_data (data)
  File "/data4/liucui/project/DeepFaceLab_Linux-master/mainscripts/Extractor.py", line 177, in process_data
    source_landmarks = image_landmarks.tolist()
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 158, in embed_data
    inst = DFLJPG.load_raw (filename)
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 21, in load_raw
    raise FileNotFoundError(data)
UnboundLocalError: local variable 'data' referenced before assignment

Exception while process data [/data4/liucui/project/DeepFaceLab_Linux-master/workspace/data_dst/video-frame-2680.jpg]: Traceback (most recent call last):
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 18, in load_raw
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data4/liucui/project/DeepFaceLab_Linux-master/workspace/data_dst/aligned/video-frame-2680_0.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data4/liucui/project/DeepFaceLab_Linux-master/joblib/SubprocessorBase.py", line 67, in _subprocess_run
    result = self.process_data (data)
  File "/data4/liucui/project/DeepFaceLab_Linux-master/mainscripts/Extractor.py", line 177, in process_data
    source_landmarks = image_landmarks.tolist()
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 158, in embed_data
    inst = DFLJPG.load_raw (filename)
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 21, in load_raw
    raise FileNotFoundError(data)
UnboundLocalError: local variable 'data' referenced before assignment

Exception while process data [/data4/liucui/project/DeepFaceLab_Linux-master/workspace/data_dst/video-frame-5845.jpg]: Traceback (most recent call last):
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 18, in load_raw
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data4/liucui/project/DeepFaceLab_Linux-master/workspace/data_dst/aligned/video-frame-5845_0.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data4/liucui/project/DeepFaceLab_Linux-master/joblib/SubprocessorBase.py", line 67, in _subprocess_run
    result = self.process_data (data)
  File "/data4/liucui/project/DeepFaceLab_Linux-master/mainscripts/Extractor.py", line 177, in process_data
    source_landmarks = image_landmarks.tolist()
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 158, in embed_data
    inst = DFLJPG.load_raw (filename)
  File "/data4/liucui/project/DeepFaceLab_Linux-master/utils/DFLJPG.py", line 21, in load_raw
    raise FileNotFoundError(data)
UnboundLocalError: local variable 'data' referenced before assignment


-------------------------
Images found:        7195
Faces detected:      0
-------------------------
Done.

**Comment by sicilyliulc** [comment]
when extract face，output-dir/aligned has no file。

**Comment by lbfs** [comment]
@sicilyliulc did you delete any frames while extraction was still occurring?

**Comment by sicilyliulc** [comment]
> @sicilyliulc did you delete any frames while extraction was still occurring?

It turned out that I had no authority，now，it‘’s ok。

**Comment by sicilyliulc** [comment]
when train ，
python main.py train --training-data-src-dir workspace/data_src/aligned/ --training-data-dst-dir workspace/data_dst/aligned/ --model-dir workspace/model/ --model H128
Running trainer.

You have multi GPUs in a system: 
[0] : GeForce GTX 1080 Ti
[1] : GeForce GTX 1080 Ti
[2] : GeForce GTX 1080 Ti
[3] : GeForce GTX 1080 Ti
[4] : GeForce GTX 1080 Ti
[5] : GeForce GTX 1080 Ti
[6] : GeForce GTX 1080 Ti
[7] : GeForce GTX 1080 Ti
Which GPU idx to choose? ( skip: best GPU ) : best GPU
-1
Loading model...

Model first run. Enter model options as default for each run.
Write preview history? (y/n ?:help skip:n) : n  
Target iteration (skip:unlimited/default) : 
0
Batch_size (?:help skip:0) : 0
Feed faces to network sorted by yaw? (y/n ?:help skip:n) : n
Flip faces randomly? (y/n ?:help skip:y) : y
Src face scale modifier % ( -30...30, ?:help skip:0) : 0
Use lightweight autoencoder? (y/n, ?:help skip:n) : n
Use pixel loss? (y/n, ?:help skip: n/default ) : n
Using TensorFlow backend.
Loading: 100%|#################################################################################| 4673/4673 [00:09<00:00, 512.32it/s]
Loading: 100%|#################################################################################| 7188/7188 [00:15<00:00, 452.88it/s]
===== Model summary =====
== Model name: H128
==
== Current iteration: 0
==
== Model options:
== |== batch_size : 4
== |== sort_by_yaw : False
== |== random_flip : True
== |== lighter_ae : False
== |== pixel_loss : False
== Running on:
== |== [0 : GeForce GTX 1080 Ti]
=========================
Saving....
Starting. Press "Enter" to stop training and save model.
2019-03-27 03:13:09.803056: E tensorflow/stream_executor/cuda/cuda_dnn.cc:332] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Segmentation fault (core dumped)

**Comment by lbfs** [comment]
You've somehow have broken dependencies or a corrupted install. Has nothing to do with DeepFaceLab or this issue.
