### ISSUE TITLE
Extract not running on GTX 1050 TI/Windows 10 

### ISSUE THREAD

**Issue by deepkeks** [iperov/DeepFaceLab#176]
I've tried every CUDA build in the Mega, but I get the same result each time. 

I am using a GTX 1050 Ti with the most recent driver from GeForce.com (dated only just a few days ago). 

Issue is that after extracting frames from a video, I'm unable to extract faces using either DLIB or MT. 
Depending on the version downloaded, I get either  (from RTX safe build)
> ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
or I get errors saying no GPU is compatible.

After 12 hours of digging and reading and installing this or that, I am lost.

**Comment by deepkeks** [comment]
Here is the stacktrace:

> Performing 1st pass...
Exception: Traceback (most recent call last):
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\joblib\SubprocessorBase.py", line 55, in _subprocess_run
    self.on_initialize(client_dict)
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 44, in on_initialize
    nnlib.import_all (device_config)
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\nnlib\nnlib.py", line 485, in import_all
    nnlib.import_keras(device_config)
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\nnlib\nnlib.py", line 160, in import_keras
    nnlib._import_tf(device_config)
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\nnlib\nnlib.py", line 125, in _import_tf
    import tensorflow as tf
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Exception: Traceback (most recent call last):
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\joblib\SubprocessorBase.py", line 55, in _subprocess_run
    self.on_initialize(client_dict)
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 44, in on_initialize
    nnlib.import_all (device_config)
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\nnlib\nnlib.py", line 485, in import_all
    nnlib.import_keras(device_config)
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\nnlib\nnlib.py", line 160, in import_keras
    nnlib._import_tf(device_config)
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\nnlib\nnlib.py", line 125, in _import_tf
    import tensorflow as tf
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.


Traceback (most recent call last):
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\main.py", line 135, in <module>
    arguments.func(arguments)
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\main.py", line 33, in process_extract
    'multi_gpu' : arguments.multi_gpu,
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 562, in main
    extracted_rects = ExtractSubprocessor ([ (x,) for x in input_path_image_paths ], 'rects', image_size, face_type, debug, multi_gpu=multi_gpu, cpu_only=cpu_only, manual=False, detector=detector).run()
  File "C:\Users\deepkex\Downloads\rtxgoodtogo\DeepFaceLabCUDA\_internal\bin\DeepFaceLab\joblib\SubprocessorBase.py", line 170, in run
    raise Exception ( "Unable to start subprocesses." )
Exception: Unable to start subprocesses.
Press any key to continue . . .

**Comment by iperov** [comment]
CPU model ?

**Comment by deepkeks** [comment]
CPU is AMD Phenom 2 x4  @ 2.8ghz

**Comment by iperov** [comment]
it has no AVX instructions.
very old cpu

**Comment by deepkeks** [comment]
Rather than close the ticket, can you explain what that means? Because I had thought that we were looking at the GPU to do the work, not the CPU.

**Comment by iperov** [comment]
again

it has no AVX instructions.

**Comment by iperov** [comment]
what you cannot understand?

**Comment by deepkeks** [comment]
Well, I don't know what AVX is, and I don't know how that plays into my GPU, being a separate device. This means I just can't use the software? Does something need compiled differently? Am I forced to choose between new CPU and using FakeApp instead?

**Comment by wintdkyo** [comment]
Most likely yes. Most mid-tier CPUs and above have AVX instruction, and it is a necessity to do most Deep Learning stuff, even if the heavy lifting is done on the GPU.

**Comment by iperov** [comment]
this is requirement of tensorflow, not mine.

**Comment by deepkeks** [comment]
Would FX-6300 CPU be compatible? Is there any other option for me while I wait for shipping?

**Comment by iperov** [comment]
https://www.amd.com/en/products/cpu/fx-6300 yes it has AVX

**Comment by deepkeks** [comment]
Thank you. I will order this today and use fakeapp while I wait. Unfortunate, Fakeapp is garbage and this program is much better.

**Comment by iperov** [comment]
@deepkeks try openclSSE build from mega

**Comment by wanshun123** [comment]
Had this issue as well and using the DeepFaceLabOpenCLSSE_build_03_04_2019.exe build instead of DeepFaceLabCUDA9SSE_build_03_04_2019.exe fixed it.

**Comment by iperov** [comment]
DeepFaceLabCUDA9SSE_build_03_04_2019.exe does not work?
