### ISSUE TITLE
I pressed "Enter" but the training didn`t stopped and nothing was saved

### ISSUE THREAD

**Issue by xdx3000** [iperov/DeepFaceLab#179]
The training did worked, the loss was decreasing, but when I pressed "Enter", the training didn`t stopped and nothing is saved

the output was below:

python main.py train --training-data-src-dir workspace\faceA --training-data-dst-dir workspace\faceB --model-dir workspace\model --no-preview --model H64

>Running trainer.
Loading model...
Model first run. Enter model options as default for each run.
Write preview history? (y/n ?:help skip:n/default) :
n
Target epoch (skip:unlimited/default) :
0
Batch_size (?:help skip:0/default) :
0
Feed faces to network sorted by yaw? (y/n ?:help skip:n) :
n
Flip faces randomly? (y/n ?:help skip:y) :
y
Src face scale modifier % ( -30...30, ?:help skip:0) :
0
Use lightweight autoencoder? (y/n, ?:help skip:n) : y
Use pixel loss? (y/n, ?:help skip: n/default ) :
n
E:\Anaconda3\envs\faceswap\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-03-03 22:28:36.477112: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 750 Ti major: 5 minor: 0 memoryClockRate(GHz): 1.189
pciBusID: 0000:01:00.0
totalMemory: 2.00GiB freeMemory: 1.89GiB
2019-03-03 22:28:36.492712: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-03-03 22:28:37.459913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-03 22:28:37.459913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2019-03-03 22:28:37.459913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-03-03 22:28:37.475513: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1642 MB memory) ->
 physical GPU (device: 0, name: GeForce GTX 750 Ti, pci bus id: 0000:01:00.0, compute capability: 5.0)
Using TensorFlow backend.
Loading: 100%|##################################################################################################################################| 242/242 [00:00<00:00, 620.51it/s]
Loading: 100%|##################################################################################################################################| 118/118 [00:00<00:00, 756.41it/s]
===== Model summary =====
== Model name: H64
==
== Current epoch: 0
==
== Model options:
== |== batch_size : 4
== |== sort_by_yaw : False
== |== random_flip : True
== |== lighter_ae : True
== |== pixel_loss : False
== Running on:
== |== [0 : GeForce GTX 750 Ti]
==
== WARNING: You are using 2GB GPU. Result quality may be significantly decreased.
== If training does not start, close all programs and try again.
== Also you can disable Windows Aero Desktop to get extra free VRAM.
==
=========================
Saving...
Starting. Press "Enter" to stop training and save model.
2019-03-03 22:28:49.879535: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.61GiB. The caller indicates that thi
s is not a failure, but may mean that there could be performance gains if more memory were available.
2019-03-03 22:28:49.926335: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.15GiB. The caller indicates that thi
s is not a failure, but may mean that there could be performance gains if more memory were available.
2019-03-03 22:28:49.941935: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.15GiB. The caller indicates that thi
s is not a failure, but may mean that there could be performance gains if more memory were available.
2019-03-03 22:28:49.957535: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.15GiB. The caller indicates that thi
s is not a failure, but may mean that there could be performance gains if more memory were available.
2019-03-03 22:28:49.973135: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.15GiB. The caller indicates that thi
s is not a failure, but may mean that there could be performance gains if more memory were available.
2019-03-03 22:28:50.035536: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.08GiB. The caller indicates that thi
s is not a failure, but may mean that there could be performance gains if more memory were available.
2019-03-03 22:28:50.082336: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.08GiB. The caller indicates that thi
s is not a failure, but may mean that there could be performance gains if more memory were available.
2019-03-03 22:28:50.097936: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.08GiB. The caller indicates that thi
s is not a failure, but may mean that there could be performance gains if more memory were available.
2019-03-03 22:28:50.160336: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.08GiB. The caller indicates that thi
s is not a failure, but may mean that there could be performance gains if more memory were available.
2019-03-03 22:28:50.222736: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.05GiB. The caller indicates that thi
s is not a failure, but may mean that there could be performance gains if more memory were available.
Training [#000706][0390ms] loss_src:1.636 loss_dst:1.237

**Comment by xdx3000** [comment]
solved. I just removed "--no-preview" and press Enter in the preview window.

**Comment by iperov** [comment]
for windows use prebuild app

**Comment by joepadmiraal** [comment]
In case somebody has the same issue:
You have to press enter while the preview window is active.
So not in the console window.

**Comment by tillyjoos** [comment]
where does it save when you stop it?

**Comment by maddy123-star** [comment]
Hi, I am getting the following error while training the model. Can someone suggest me the solution?

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "C:\Work\Misc\DFL\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
    from tensorflow.python.ops import init_ops
  File "C:\Work\Misc\DFL\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Work\Misc\DFL\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Work\Misc\DFL\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Work\Misc\DFL\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Work\Misc\DFL\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Work\Misc\DFL\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: The paging file is too small for this operation to complete.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by marshalleq** [comment]
What about if you are running no preview, i.e. you have no GUI, how to stop it then?
