### ISSUE TITLE
SEA setting error can't create model

### ISSUE THREAD

**Issue by sktbest** [iperov/DeepFaceLab#201]
Running trainer.

Loading model...

Model first run. Enter model options as default for each run.
Write preview history? (y/n ?:help skip:n) :
n
Target iteration (skip:unlimited/default) :
0
Batch_size (?:help skip:0) :
0
Feed faces to network sorted by yaw? (y/n ?:help skip:n) : y
Flip faces randomly? (y/n ?:help skip:y) : y
Src face scale modifier % ( -30...30, ?:help skip:0) :
0
Resolution ( 64-256 ?:help skip:128) :
128
Half or Full face? (h/f, ?:help skip:f) : f
Learn mask? (y/n, ?:help skip:y) : y
Optimizer mode? ( 1,2,3 ?:help skip:1) :
1
AE architecture (df, liae ?:help skip:df) :
df
AutoEncoder dims (32-1024 ?:help skip:512) :
512
Encoder dims per channel (21-85 ?:help skip:42) :
42
Decoder dims per channel (10-85 ?:help skip:21) :
21
Add residual blocks to decoder? (y/n, ?:help skip:n) :
n
Remove gray border? (y/n, ?:help skip:n) :
n
Use lightweight encoder? (y/n, ?:help skip:n) : y
Use multiscale decoder? (y/n, ?:help skip:n) :
n
Use pixel loss? (y/n, ?:help skip: n ) :
n
Face style power ( 0.0 .. 100.0 ?:help skip:0.00) :
0.0
Background style power ( 0.0 .. 100.0 ?:help skip:0.00) :
0.0
Using TensorFlow backend.
Error: The `padding` argument must be one of "valid", "same" (or "causal" for Conv1D). Received: zero
Traceback (most recent call last):
File "E:\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 41, in trainerThread
device_args=device_args)
File "E:\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\models\ModelBase.py", line 138, in __init__
self.onInitialize()
File "E:\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\models\Model_SAE\Model.py", line 186, in onInitialize
self.encoder = modelify(SAEModel.DFEncFlow(resolution, self.options['lighter_encoder'], ae_dims=ae_dims, ch_dims=e_ch_dims, **common_flow_kwargs) ) (Input(bgr_shape))
File "E:\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\nnlib\nnlib.py", line 206, in func
return keras.models.Model (tensor, model_functor(tensor))
File "E:\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\models\Model_SAE\Model.py", line 633, in func
x = downscale_sep(dims*2)(x)
File "E:\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\models\Model_SAE\Model.py", line 496, in func
return LeakyReLU(0.1)(SeparableConv2D(dim, kernel_size=5, strides=2, padding=padding)(x))
File "E:\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
return func(*args, **kwargs)
File "E:\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\layers\convolutional.py", line 1690, in __init__
**kwargs)
File "E:\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\layers\convolutional.py", line 1318, in __init__
**kwargs)
File "E:\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\layers\convolutional.py", line 111, in __init__
self.padding = conv_utils.normalize_padding(padding)
File "E:\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\utils\conv_utils.py", line 58, in normalize_padding
'(or "causal" for Conv1D). Received: ' + str(padding))
ValueError: The `padding` argument must be one of "valid", "same" (or "causal" for Conv1D). Received: zero
Done.

Where am I wrong?
Can anyone help me thank you
Or what do you recommend for the settings?
My graphics card is GTX1080
Batch_size I choose 4 or continue error

**Comment by iperov** [comment]
will fix
dont use lightweight encoder
