### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero - TeslaV100 - Latest build

### ISSUE THREAD

**Issue by 4DeepThought2** [iperov/DeepFaceLab#208]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

Start training

## Actual behavior

error

## Steps to reproduce

SAE training

## Other relevant information
Tesla V-100 

```
Loading model...

Model first run. Enter model options as default for each run.
Write preview history? (y/n ?:help skip:n) : n
Target iteration (skip:unlimited/default) :
0
Batch_size (?:help skip:0) : 4
Feed faces to network sorted by yaw? (y/n ?:help skip:n) :
n
Flip faces randomly? (y/n ?:help skip:y) : ?
Predicted face will look more naturally without this option, but src faceset should cover all face directions as dst faceset.
Flip faces randomly? (y/n ?:help skip:y) : n
Src face scale modifier % ( -30...30, ?:help skip:0) :
0
Resolution ( 64-256 ?:help skip:128) : 200
Half or Full face? (h/f, ?:help skip:f) :
f
Learn mask? (y/n, ?:help skip:y) :
y
Optimizer mode? ( 1,2,3 ?:help skip:1) :
1
AE architecture (df, liae ?:help skip:df) :
df
AutoEncoder dims (32-1024 ?:help skip:512) : 888
Encoder dims per channel (21-85 ?:help skip:42) : 77
Decoder dims per channel (10-85 ?:help skip:38) : 70
Add residual blocks to decoder? (y/n, ?:help skip:n) : ?
These blocks help to get better details, but require more computing time.
Add residual blocks to decoder? (y/n, ?:help skip:n) : y
Remove gray border? (y/n, ?:help skip:n) : ?
Removes gray border of predicted face, but requires more computing resources.
Remove gray border? (y/n, ?:help skip:n) : y
Use multiscale decoder? (y/n, ?:help skip:n) : y
Use pixel loss? (y/n, ?:help skip: n ) : n
Face style power ( 0.0 .. 100.0 ?:help skip:0.00) :
0.0
Background style power ( 0.0 .. 100.0 ?:help skip:0.00) :
0.0
Using TensorFlow backend.
Loading: 100%|########################################################################################################################| 1887/1887 [00:03<00:00, 509.57it/s]
Loading: 0it [00:00, ?it/s]
Error: integer division or modulo by zero
Traceback (most recent call last):
  File "C:\Users\adrian_valentino93\Downloads\DeepFaceLabCUDA10.1SSE_build_03_26_2019\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 44, in trai
nerThread
    device_args=device_args)
  File "C:\Users\adrian_valentino93\Downloads\DeepFaceLabCUDA10.1SSE_build_03_26_2019\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\models\ModelBase.py", line 167, in __init
__
    self.sample_for_preview = self.generate_next_sample()
  File "C:\Users\adrian_valentino93\Downloads\DeepFaceLabCUDA10.1SSE_build_03_26_2019\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\models\ModelBase.py", line 357, in genera
te_next_sample
    return [next(generator) for generator in self.generator_list]
  File "C:\Users\adrian_valentino93\Downloads\DeepFaceLabCUDA10.1SSE_build_03_26_2019\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\models\ModelBase.py", line 357, in <listc
omp>
    return [next(generator) for generator in self.generator_list]
  File "C:\Users\adrian_valentino93\Downloads\DeepFaceLabCUDA10.1SSE_build_03_26_2019\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\samples\SampleGeneratorFace.py", line 57,
 in __next__
    generator = self.generators[self.generator_counter % len(self.generators) ]
ZeroDivisionError: integer division or modulo by zero
Done.
Press any key to continue . . .
```

**Comment by 4DeepThought2** [comment]
Bad file in dst folder

**Comment by StefanDukic** [comment]
How did you solve it? I have the same problem.

**Comment by WanderknightPlus** [comment]
me too I've written an email to wpgdream@gmail.com ,i am waitting for help
