### ISSUE TITLE
Tesla V100 - Latest Build Failure on default settings - (residual yes, remove grey yes) -  Failed to get convolution algorithm.

### ISSUE THREAD

**Issue by 4DeepThought2** [iperov/DeepFaceLab#209]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

Trainer initiates. 

## Actual behavior

Error

## Steps to reproduce

Default settings aside from:
```
== |== d_residual_blocks : True
== |== remove_gray_border : True
== |== multiscale_decoder : True
```
Fails with following error:

```
Using TensorFlow backend.
Loading: 100%|#######################################################################################################################################################| 1887/1887 [00:03<00:00, 529.69it/s]
Loading: 100%|#######################################################################################################################################################| 1739/1739 [00:03<00:00, 542.90it/s]
===== Model summary =====
== Model name: SAE
==
== Current iteration: 0
==
== Model options:
== |== batch_size : 4
== |== sort_by_yaw : False
== |== random_flip : False
== |== resolution : 128
== |== face_type : f
== |== learn_mask : True
== |== optimizer_mode : 1
== |== archi : df
== |== ae_dims : 512
== |== e_ch_dims : 42
== |== d_ch_dims : 21
== |== d_residual_blocks : True
== |== remove_gray_border : True
== |== multiscale_decoder : True
== |== pixel_loss : False
== |== face_style_power : 0.0
== |== bg_style_power : 0.0
== Running on:
== |== [0 : Tesla V100-SXM2-16GB]
=========================
Starting. Press "Enter" to stop training and save model.
2019-03-28 17:40:47.964864: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-28 17:40:48.822328: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-28 17:40:49.701328: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-28 17:40:49.920646: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-28 17:40:49.936656: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-28 17:40:49.953078: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-28 17:40:49.966779: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-28 17:40:49.987888: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-28 17:40:50.005159: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-28 17:40:50.019720: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-28 17:40:50.034442: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-28 17:40:50.050539: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-28 17:40:50.065826: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-28 17:40:50.079934: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-28 17:40:50.093847: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-03-28 17:40:50.110914: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Error: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node model_1/conv2d_1/convolution}} = Conv2D[T=DT_FLOAT, _class=["loc:@gradients/AddN_93"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gp
u=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/model_1/conv2d_1/convolution_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer, conv2d_1/kernel/read)]]
         [[{{node Mean_13/_1213}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_inca
rnation=1, tensor_name="edge_9099_Mean_13", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Traceback (most recent call last):
  File "C:\Users\adrian_valentino93\Downloads\DeepFaceLabCUDA10.1SSE_build_03_26_2019\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 93, in trainerThread
    iter, iter_time = model.train_one_iter()
  File "C:\Users\adrian_valentino93\Downloads\DeepFaceLabCUDA10.1SSE_build_03_26_2019\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\models\ModelBase.py", line 362, in train_one_iter
    losses = self.onTrainOneIter(sample, self.generator_list)
  File "C:\Users\adrian_valentino93\Downloads\DeepFaceLabCUDA10.1SSE_build_03_26_2019\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\models\Model_SAE\Model.py", line 375, in onTrainOneIter
    src_loss, dst_loss, = self.src_dst_train (feed)
  File "C:\Users\adrian_valentino93\Downloads\DeepFaceLabCUDA10.1SSE_build_03_26_2019\DeepFaceLabCUDA10.1SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in _
_call__
    return self._call(inputs)
  File "C:\Users\adrian_valentino93\Downloads\DeepFaceLabCUDA10.1SSE_build_03_26_2019\DeepFaceLabCUDA10.1SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _
call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\adrian_valentino93\Downloads\DeepFaceLabCUDA10.1SSE_build_03_26_2019\DeepFaceLabCUDA10.1SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1439, in _
_call__
    run_metadata_ptr)
  File "C:\Users\adrian_valentino93\Downloads\DeepFaceLabCUDA10.1SSE_build_03_26_2019\DeepFaceLabCUDA10.1SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528
, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed
above.
         [[{{node model_1/conv2d_1/convolution}} = Conv2D[T=DT_FLOAT, _class=["loc:@gradients/AddN_93"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gp
u=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/model_1/conv2d_1/convolution_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer, conv2d_1/kernel/read)]]
         [[{{node Mean_13/_1213}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_inca
rnation=1, tensor_name="edge_9099_Mean_13", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Done.
```

## Other relevant information
Latest CUDA toolkit
Latest DFL build

**Comment by iperov** [comment]
>Steps to reproduce
Default settings aside from:
== |== d_residual_blocks : True
== |== remove_gray_border : True
== |== multiscale_decoder : True

cannot reproduce.

**Comment by dpfks** [comment]
Also happens to me sometimes. Mostly when I try to run 2 different GPU training at once.

**Comment by 4DeepThought2** [comment]
Ill try on my 1080Ti tonight.  Previous build had no issues.  Maybe just related to the Tesla V100?

**Comment by iperov** [comment]
I have no Tesla V100 to check the problem.

**Comment by 4DeepThought2** [comment]
I understand.  I'll see if it works on 1080 first, and then report back.

**Comment by 4DeepThought2** [comment]
PS.  If you want a Tesla to test on, I can give you access.  Ive completely cleared out my workspace, redownloaded the 3.26 (SSE and AVX) builds, re-extracted, reran face extraction, same error with all defaults set.

**Comment by iperov** [comment]
> Latest CUDA toolkit

why you installed cuda?

**Comment by 4DeepThought2** [comment]
Because that is how you get the drivers for 2016 on a Tesla V100 through Google Cloud.  Been working that way for 3-4 months.

**Comment by iperov** [comment]
what ?

**Comment by iperov** [comment]
what is 2016 
what is google cloud

how that relevant for windows builds

**Comment by 4DeepThought2** [comment]
Windows Server 2016
Google Cloud Platform = Free access to Tesla V100 for 120 hours at a time.

```

SEND FEEDBACK
Compute Engine   Documentation
Adding or Removing GPUs
Google Compute Engine provides graphics processing units (GPUs) that you can add to your virtual machine instances. You can use these GPUs to accelerate specific workloads on your instances such as machine learning and data processing.

For more information about what you can do with GPUs and what types of GPU hardware are available, read GPUs on Compute Engine.

Before you begin
If you want to use the command-line examples in this guide:
Install or update to the latest version of the gcloud command-line tool.
Set a default region and zone.
If you want to use the API examples in this guide, set up API access.
Read about GPU pricing on Compute Engine to understand the cost to use GPUs on your instances.
Read about restrictions for instances with GPUs to learn how these instances function differently than most instances.
Learn how instances function when you schedule them to terminate for host maintenance events. If you add GPUs to your instances, you must also set the instance to terminate during host maintenance.
Check the quotas page to ensure that you have enough GPUs available for your project. If you need additional GPU quota, request a quota increase.
Creating an instance with a GPU
Before you create an instance with a GPU, select which boot disk image you want to use for the instance, and ensure that the appropriate GPU driver is installed.

If you are using GPUs for machine learning, you can use a Deep Learning VM image for your instance. The Deep Learning VM images have GPU drivers pre-installed, and include packages such as TensorFlow and PyTorch. You can also use the Deep Learning VM images for general GPU workloads. For information on the images available, and the packages installed on the images, see the Deep Learning VM documentation.

You can also use any public image or custom image, but some images might require a unique driver or install process that is not covered in this guide. You must identify what drivers are appropriate for your images.

For steps to install drivers, see installing GPU drivers.

Note: Check the quotas page to ensure that you have enough GPUs available in your project. If you require additional GPU quota, request a quota increase. If your project has an established billing history, it will receive quota automatically after you submit the request.
When you create an instance with one or more GPUs, you must set the instance to terminate on host maintenance. Instances with GPUs cannot live migrate because they are assigned to specific hardware devices. See GPU restrictions for details.

Create an instance with one or more GPUs using the Google Cloud Platform Console, the gcloud command-line tool, or the API.

CONSOLE GCLOUD API
Go to the VM instances page.
GO TO THE VM INSTANCES PAGE

Click Create instance.
Select a zone where GPUs are available. See the list of available zones with GPUs.
In the Machine type section, select the machine type that you want to use for this instance. Alternatively, you can specify custom machine type settings later.
In the Machine type section, click Customize to see advanced machine type options and available GPUs.
Click GPUs to see the list of available GPUs.
Specify the GPU type and the number of GPUs that you need.
If necessary, adjust the machine type to accommodate your desired GPU settings. If you leave these settings as they are, the instance uses the predefined machine type that you specified before opening the machine type customization screen.
To configure your boot disk, in the Boot disk section, click Change.
In the OS images tab, choose an image.
Click Select to confirm your boot disk options.
Optionally, you can include a startup script to install the GPU driver while the instance starts up. In the Automation section, include the contents of your startup script under Startup script. See installing GPU drivers for example scripts.
Configure any other instance settings that you require. For example, you can change the Preemptibility settings to configure your instance as a preemptible instance. This reduces the cost of your instance and the attached GPUs. Read GPUs on preemptible instances to learn more.
At the bottom of the page, click Create to create the instance.
If you used a startup script to automatically install the GPU device driver, verify that the GPU driver installed correctly.

If you did not use a startup script to install the GPU driver during instance creation, manually install the GPU driver on your instance so that your system can use the device.

Adding or removing GPUs on existing instances
You can add or detach GPUs on your existing instances, but you must first stop the instance and change its host maintenance setting so that it terminates rather than live-migrating. Instances with GPUs cannot live migrate because they are assigned to specific hardware devices. See GPU restrictions for details.

Also be aware that you must install GPU drivers on this instance after you add a GPU. The boot disk image that you used to create this instance determines what drivers you need. You must identify what drivers are appropriate for the operating system on your instance's persistent boot disk images. Read installing GPU drivers for details.

You can add or remove GPUs from an instance using the Google Cloud Platform Console or the API.

CONSOLE API
You can add or remove GPUs from your instance by stopping the instance and editing your instance's configuration.

Verify that all of your critical applications are stopped on the instance. You must stop the instance before you can add a GPU.

Go to the VM instances page to see your list of instances.

GO TO THE VM INSTANCES PAGE

On the list of instances, click the name of the instance where you want to add GPUs. The instance details page opens.

At the top of the instance details page, click Stop to stop the instance.

After the instance stops running, click Edit to change the instance properties.

If the instance has a shared-core machine type, you must change the machine type to have one or more vCPUs. You cannot add accelerators to instances with shared-core machine types.

In the Machine type section, click Customize to see advanced machine type options and available GPUs.

Click GPUs to see the list of available GPUs.

Select the number of GPUs and the GPU model that you want to add to your instance. Alternatively, you can set the number of GPUs to None to remove existing GPUs from the instance.

If you added GPUs to an instance, set the host maintenance setting to Terminate. If you removed GPUs from the instance, you can optionally set the host maintenance setting back to Migrate VM instance.

At the bottom of the instance details page, click Save to apply your changes.

After the instance settings are saved, click Start at the top of the instance details page to start the instance again.

Next install the GPU driver on your instance so that your system can use the device.

Creating groups of GPU instances using instance templates
You can use instance templates to create managed instance groups with GPUs added to each instance. Managed instance groups use the template to create multiple identical instances. You can scale the number of instances in the group to match your workload.

For steps to create an instance template, see Creating instance templates.

If you create the instance template using the Console, customize the machine type, and select the type and number of GPUs that you want to add to the instance template.

If you are using the gcloud command-line tool, include the --accelerators and --maintenance-policy TERMINATE flags. Optionally, include the --metadata startup-script flag and specify a startup script to install the GPU driver while the instance starts up. For sample scripts that work on GPU instances, see installing GPU drivers.

The following example creates an instance template with 2 vCPUs, a 250GB boot disk with Ubuntu 16.04, an NVIDIA® Tesla® K80 GPU, and a startup script. The startup script installs the CUDA Toolkit with its recommended driver version.

gcloud beta compute instance-templates create gpu-template \
    --machine-type n1-standard-2 \
    --boot-disk-size 250GB \
    --accelerator type=nvidia-tesla-k80,count=1 \
    --image-family ubuntu-1604-lts --image-project ubuntu-os-cloud \
    --maintenance-policy TERMINATE --restart-on-failure \
    --metadata startup-script='#!/bin/bash
    echo "Checking for CUDA and installing."
    # Check for CUDA and try to install.
    if ! dpkg-query -W cuda-10-0; then
      curl -O http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_10.0.130-1_amd64.deb
      dpkg -i ./cuda-repo-ubuntu1604_10.0.130-1_amd64.deb
      apt-get update
      apt-get install cuda-10-0 -y
    fi'
After you create the template, use the template to create an instance group. Every time you add an instance to the group, it starts that instance using the settings in the instance template.

If you are creating a regional managed instance group, be sure to select zones that specifically support the GPU model that you want. For a list of GPU models and available zones, see GPUs on Compute Engine. The following example creates a regional managed instance group across two zones that support the nvidia-tesla-k80 model.

gcloud beta compute instance-groups managed create example-rmig \
    --template gpu-template --base-instance-name example-instances \
    --size 30 --zones us-east1-c,us-east1-d
Note: If you are choosing specific zones, use the gcloud beta component because the zone selection feature is currently in Beta.

To learn more about managing and scaling groups of instances, read Creating Groups of Managed Instances.

Installing GPU drivers
After you create an instance with one or more GPUs, your system requires device drivers so that your applications can access the device. This guide shows the ways to install NVIDIA proprietary drivers on instances with public images.

You can install GPU drivers through one of the following options:

Use sample scripts to install the drivers. You can either specify these scripts as startup scripts on your instances or run these scripts directly on your instances through the terminal.
For Windows Server instances or instances where you cannot use these scripts, install the driver manually.
Installing GPU drivers using scripts
Each version of CUDA requires a minimum GPU driver version or a later version. To check the minimum driver required for your version of CUDA, see CUDA Toolkit and Compatible Driver Versions.

NVIDIA GPUs running on Google Compute Engine must use the following driver versions:

Linux instances:

NVIDIA 410.79 driver or greater
Windows Server instances:

NVIDIA 411.98 driver or greater
For most driver installs, you can obtain these drivers by installing the NVIDIA CUDA Toolkit.
```

You cannot download standard Nvidia driver packs, they dont work.  The CUDA Toolkit is required, which then installs the correct/latest version of the Nvidia drivers

**Comment by iperov** [comment]
so you thought you install cuda to system and it will work for dfl ?

**Comment by 4DeepThought2** [comment]
It does.  Ive been doing it this way for about 2 months.  3.26 is the first build that has failed.

**Comment by iperov** [comment]
it does not

**Comment by iperov** [comment]
DFL replaces system paths and use it own cuda dlls

**Comment by 4DeepThought2** [comment]
Ok.  Well I can tell you absolutely, without question, it does.  Installing the CUDA 10.1 Toolkit for Server 2016 is the ONLY way to get Nvidia drivers on a Tesla V100.

**Comment by 4DeepThought2** [comment]
https://mrdeepfakes.com/forums/thread-tesla-v100-stress-testing-dfl

**Comment by iperov** [comment]
stop spamming me links

**Comment by 4DeepThought2** [comment]
apologies. sorry for helping, I thought you would want test data, because that is what im doing with your repo.

**Comment by iperov** [comment]
no matter what cuda version you installed, DFL always use it own.

**Comment by 4DeepThought2** [comment]
correct.  CUDA kit 10.1 is the only way to obtain nvidia **drivers** on a Tesla V100...  CUDA is irrelevant in this ticket.

**Comment by iperov** [comment]
cmd - ver

what output in 2016?

**Comment by 4DeepThought2** [comment]
```
C:\>systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows Server 2016 Datacenter
OS Version:                10.0.14393 N/A Build 14393
```

**Comment by iperov** [comment]
wtf

```
C:\Users\Administrator>ver

Microsoft Windows [Version 6.1.7601]
```

**Comment by iperov** [comment]
man, I asked you post output of `ver`
is it too hard ?

**Comment by 4DeepThought2** [comment]
Thats just OS major version branding for consumer builds.  They are all built off the same kernel 10.0.  Windows 10, Windows 2016 and Windows 2019 are all exactly the same kernel.  Only difference is features.  I've been running DFL on Server 2016 for at least 8 months now.  But if you want, I will try the consumer build, albeit there should be zero difference.

**Comment by iperov** [comment]
wtf

**Comment by iperov** [comment]
last chance

cmd - ver

**Comment by 4DeepThought2** [comment]
its going to be the same result..

```
C:\>ver

Microsoft Windows [Version 10.0.14393]
```

**Comment by iperov** [comment]
finally. You are wasting my time like a hell

**Comment by 4DeepThought2** [comment]
6.1 = 10.0 - both built off 10.0 kernel (Redstone 5).  They are identical, only difference is more features.   DO you want me to try on the consumer build to prove the test?

**Comment by iperov** [comment]
did I sayd something ????? wtf man ? 
are you crazy or what?

**Comment by iperov** [comment]
ROFL
disliking me ? bye then
