### ISSUE TITLE
Unable to start subprocesses. GTX 1060.

### ISSUE THREAD

**Issue by devdawg0822** [iperov/DeepFaceLab#231]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior
I'm supposed to end up with extracted faces from my video.
## Actual behavior
I get an error when running the face extract after extracting frames. This is the error:
Performing 1st pass...
Running on GeForce GTX 1060 with Max-Q Design #1.
Running on GeForce GTX 1060 with Max-Q Design #2.
Running on GeForce GTX 1060 with Max-Q Design #0.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
fatal   : Memory allocation failure
22020101919-9-004-04-10-4 1-10 11099 19:5:52:5:221::511.559..099200172361984:66 ::  EE  Ett eetnnessnoosrroffrllfoolwwo//wss/ttsrrteereaaammm___eeexxxeeecccuuutttooorrr///cccuudduaad//acc/uucdduaad__add_nndnnn..ncc.ccc::c33:773337]]3 C]o  uCCloouldud l ndno ot tncrote  atccerear teae tcceuu ddcnnunnd  nhhnaa nnhddallneed::l  eCC:UU DDCNNUNND__NSSNTT_AASTTTUUASST__UIISNN_TTIEENRRTNNERNAAALLL___EEERRRRRROOORRR

fatal   : Memory allocation failure
2019-04-10 19:52:15.2290021920-17048:-9 1-E00  4t1-e91n:0s52o :r11f95l:.o59w22/:3s13t58r.8e9:a2 m3E_3 e3tx4ee:nc suEot rotfrel/nocswuo/drsaft/lrcoeuwad/mas__tedrxneenacut.moc_rce/:xc3eu7cd3ua]t/ ocCruo/dula_dcunddn a.n/cocctu: d3ca7r_3ed]an tnCo.euc lccd:u 3dn7no3nt]   haCcroneadutlee cudnn handle:l: d CUDNN_CUS DTANnTN_UoSS_TATtIU NScT_rERNIeANaLTE_teER cuRRdNOnARnL
 h_EaRROR
ndle: CUDNN_STATUS_INTERNAL_ERROR
Exception: Traceback (most recent call last):
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\joblib\SubprocessorBase.py", line 59, in _subprocess_run
    self.on_initialize(client_dict)
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\mainscripts\Extractor.py", line 71, in on_initialize
    self.e.__enter__()
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\facelib\MTCExtractor.py", line 82, in __enter__
    faces, pnts = detect_face ( np.zeros ( (self.scale_to, self.scale_to, 3)), self.min_face_size, self.pnet_fun, self.rnet_fun, self.onet_fun, [ self.thresh1, self.thresh2, self.thresh3 ], self.scale_factor )
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\facelib\MTCExtractor.py", line 136, in detect_face
    out = pnet([img_y])
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv1/convolution}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv1/convolution-0-TransposeNHWCToNCHW-LayoutOptimizer, conv1/kernel/read)]]

Exception: Traceback (most recent call last):
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\joblib\SubprocessorBase.py", line 59, in _subprocess_run
    self.on_initialize(client_dict)
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\mainscripts\Extractor.py", line 71, in on_initialize
    self.e.__enter__()
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\facelib\MTCExtractor.py", line 82, in __enter__
    faces, pnts = detect_face ( np.zeros ( (self.scale_to, self.scale_to, 3)), self.min_face_size, self.pnet_fun, self.rnet_fun, self.onet_fun, [ self.thresh1, self.thresh2, self.thresh3 ], self.scale_factor )
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\facelib\MTCExtractor.py", line 136, in detect_face
    out = pnet([img_y])
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv1/convolution}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv1/convolution-0-TransposeNHWCToNCHW-LayoutOptimizer, conv1/kernel/read)]]

Exception: Traceback (most recent call last):
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\joblib\SubprocessorBase.py", line 59, in _subprocess_run
    self.on_initialize(client_dict)
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\mainscripts\Extractor.py", line 71, in on_initialize
    self.e.__enter__()
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\facelib\MTCExtractor.py", line 82, in __enter__
    faces, pnts = detect_face ( np.zeros ( (self.scale_to, self.scale_to, 3)), self.min_face_size, self.pnet_fun, self.rnet_fun, self.onet_fun, [ self.thresh1, self.thresh2, self.thresh3 ], self.scale_factor )
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\facelib\MTCExtractor.py", line 136, in detect_face
    out = pnet([img_y])
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv1/convolution}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv1/convolution-0-TransposeNHWCToNCHW-LayoutOptimizer, conv1/kernel/read)]]
         [[{{node softmax_1/truediv/_305}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_111_softmax_1/truediv", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Traceback (most recent call last):
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\main.py", line 213, in <module>
    arguments.func(arguments)
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\main.py", line 35, in process_extract
    'multi_gpu' : arguments.multi_gpu,
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\mainscripts\Extractor.py", line 725, in main
    data = ExtractSubprocessor ([ ExtractSubprocessor.Data(filename) for filename in input_path_image_paths ], 'rects-'+detector, image_size, face_type, debug_dir, multi_gpu=multi_gpu, cpu_only=cpu_only, manual=False).run()
  File "A:\macheese\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\joblib\SubprocessorBase.py", line 187, in run
    raise Exception ( "Unable to start subprocesses." )
Exception: Unable to start subprocesses.
## Steps to reproduce
I have tried with all CUDA9 builds, but no luck. I extracted at 5 frames, and now when I try to extract faces, I get the above error.
## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ... cmd.exe
- **Operating system and version:** Windows 10 Pro 1809
- **Python version:** 3.7

**Comment by iperov** [comment]
unable to reproduce
