### ISSUE TITLE
Converting with alpha leads to termination

### ISSUE THREAD

**Issue by tfis2** [iperov/DeepFaceLab#237]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

Converting all images with alpha mask

## Actual behavior

Stop in the middle of th e process

## Steps to reproduce
Merged: LIAEF, Overlay, FAN-dst, erode 50, blur 100, size -3, rct

## Other relevant information
Converting:  17%|##########5                                                    | 4862/29023 [15:04<1:14:55,  5.38it/s]Error: input depth must be evenly divisible by filter depth: 4 vs 3
         [[{{node model_1/conv2d_1/convolution}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model_1/conv2d_1/convolution-0-TransposeNHWCToNCHW-LayoutOptimizer, conv2d_1/kernel/read)]]
Traceback (most recent call last):
  File "E:\DeepFaceLabCUDA10.1SSE_build_04_07_2019\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\mainscripts\Converter.py", line 276, in main
    debug                  = args.get('debug',False)
  File "E:\DeepFaceLabCUDA10.1SSE_build_04_07_2019\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\joblib\SubprocessorBase.py", line 241, in run
    self.on_tick()
  File "E:\DeepFaceLabCUDA10.1SSE_build_04_07_2019\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\mainscripts\Converter.py", line 202, in on_tick
    self.converter.on_host_tick()
  File "E:\DeepFaceLabCUDA10.1SSE_build_04_07_2019\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\converters\ConverterMasked.py", line 113, in on_host_tick
    self.predictor_func_host.obj.process_messages()
  File "E:\DeepFaceLabCUDA10.1SSE_build_04_07_2019\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\joblib\SubprocessFunctionCaller.py", line 30, in process_messages
    result = self.func (obj)
  File "E:\DeepFaceLabCUDA10.1SSE_build_04_07_2019\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\models\Model_LIAEF128\Model.py", line 119, in predictor_func
    x, mx = self.convert ( [ face[np.newaxis,...] ] )
  File "E:\DeepFaceLabCUDA10.1SSE_build_04_07_2019\DeepFaceLabCUDA10.1SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "E:\DeepFaceLabCUDA10.1SSE_build_04_07_2019\DeepFaceLabCUDA10.1SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "E:\DeepFaceLabCUDA10.1SSE_build_04_07_2019\DeepFaceLabCUDA10.1SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "E:\DeepFaceLabCUDA10.1SSE_build_04_07_2019\DeepFaceLabCUDA10.1SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: input depth must be evenly divisible by filter depth: 4 vs 3
         [[{{node model_1/conv2d_1/convolution}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model_1/conv2d_1/convolution-0-TransposeNHWCToNCHW-LayoutOptimizer, conv2d_1/kernel/read)]]
Done.

**Comment by iperov** [comment]
what is alpha mask ?

**Comment by iperov** [comment]
why 4862/29023 succesfully converted ?

**Comment by tfis2** [comment]
Sorry, I meant alpha-channel=transparency mask used to convert head only for further process in video software. 4862 has been converted, then program stops.

**Comment by iperov** [comment]
so this is only 1 buggy frame
how I should to reproduce it?

**Comment by tfis2** [comment]
OK. Next time I try deleting the frames, where conversion stops.

**Comment by spiegelball** [comment]
Maybe its the "size=-3" argument because of 3 not divisible by 4?

**Comment by iperov** [comment]
what is `"size=-3" argument` ?

**Comment by tfis2** [comment]
I found out (by taking a look in the debug folder), that in frame 4863 the same face was marked twice.

**Comment by lukegalea** [comment]
@tfis2 How did you resolve this? I have frames that were marked twice as well, but it's not clear what to do with those frames now that I have them.

**Comment by lukegalea** [comment]
@tfis2 I wonder if this should be re-opened. It seems to me that you should be able to have the same face more than once in a single frame.

**Comment by tfis2** [comment]
@lukegalea 
It ist possible to have the same face twice in one fram (in front of a mirror for example). But in this case. The same face on the SAME POSITION has been marked twice, which leads to termination in the conversion process if using alpha masks.

BTW: I don't use alpha mask anymore. I do normal conversion an create my aplha mask by creating a difference mask of the original footage.
