### ISSUE TITLE
KeyError: 'target_iter'

### ISSUE THREAD

**Issue by licolane** [iperov/DeepFaceLab#243]
## Expected behavior

While FANSegmentator model works well with commits on Apr 5, 2019, When I try to train FANSEG model with last commit, KeyError is occured like below. 

## Actual behavior

```
Loading model...

Model first run. Enter model options as default for each run.
Batch_size (?:help skip:0) : 32
Error: 'target_iter'
Traceback (most recent call last):
  File "C:\Github\DeepFaceLab\mainscripts\Trainer.py", line 44, in trainerThread
    device_args=device_args)
  File "C:\Github\DeepFaceLab\models\Model_FANSEG\Model.py", line 18, in __init__
    ask_src_scale_mod=False)
  File "C:\Github\DeepFaceLab\models\ModelBase.py", line 124, in __init__
    self.target_iter = self.options['target_iter']
KeyError: 'target_iter'
Done.
```

## Other relevant information

Operating system and version : Windows10
Python version : 3.6.8 not using prebuilt windows binary

**Comment by iperov** [comment]
fixed in last commit

**Comment by licolane** [comment]
Now it works. thx.
