### ISSUE TITLE
feed faces by jaw doesnt work

### ISSUE THREAD

**Issue by jejz** [iperov/DeepFaceLab#249]
when i try training the model by feeding faces by jaw it doesnt work in the newest updates.

I always get this errors:
Error: 'Sample' object has no attribute 'yaw'
Traceback (most recent call last):
  File "/content/DeepFaceLab/mainscripts/Trainer.py", line 44, in trainerThread
    device_args=device_args)
  File "/content/DeepFaceLab/models/ModelBase.py", line 147, in __init__
    self.onInitialize()
  File "/content/DeepFaceLab/models/Model_SAE/Model.py", line 350, in onInitialize
    output_sample_types=output_sample_types ),
  File "/content/DeepFaceLab/samplelib/SampleGeneratorFace.py", line 36, in __init__
    samples = SampleLoader.load (self.sample_type, self.samples_path, sort_by_yaw_target_samples_path)
  File "/content/DeepFaceLab/samplelib/SampleLoader.py", line 50, in load
    datas[sample_type] = SampleLoader.upgradeToFaceYawSortedAsTargetSamples( SampleLoader.load(SampleType.FACE_YAW_SORTED, samples_path), SampleLoader.load(SampleType.FACE_YAW_SORTED, target_samples_path) )
  File "/content/DeepFaceLab/samplelib/SampleLoader.py", line 44, in load
    datas[sample_type] = SampleLoader.upgradeToFaceYawSortedSamples( SampleLoader.load(SampleType.FACE, samples_path) )
  File "/content/DeepFaceLab/samplelib/SampleLoader.py", line 107, in upgradeToFaceYawSortedSamples
    s_yaw = s.yaw
AttributeError: 'Sample' object has no attribute 'yaw'
Done.

when i turn off feed by jaw it works

i tried the same data on the older versions with feed by yaw. it does work.
so it looks like theres some issue in the newest updates.

**Comment by iperov** [comment]
will be fixed
