### ISSUE TITLE
You are trying to load a weight file containing 1 layers into a model with 9 layers.

### ISSUE THREAD

**Issue by oracle9i88** [iperov/DeepFaceLab#27]
Ubuntu 16.04

avatar

Using TensorFlow backend.
Error: You are trying to load a weight file containing 1 layers into a model with 9 layers.
Traceback (most recent call last):
  File "/home/oracle/DeepFaceLab/mainscripts/Trainer.py", line 41, in trainerThread
    **in_options)
  File "/home/oracle/DeepFaceLab/models/ModelBase.py", line 108, in __init__
    self.onInitialize(**in_options)
  File "/home/oracle/DeepFaceLab/models/Model_AVATAR/Model.py", line 31, in onInitialize
    self.encoder64.load_weights      (self.get_strpath_storage_for_file(self.encoder64H5))
  File "/home/oracle/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/keras/engine/topology.py", line 2667, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/oracle/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/keras/engine/topology.py", line 3365, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 1 layers into a model with 9 layers.

**Comment by LordJenQ3** [comment]
How many images have you got in the project folder ? I think Avatar conversion allows just 100, or was it 50 .... Can't remember, give it a try

**Comment by iperov** [comment]
> I think Avatar conversion allows just 100

Why do you think so?

**Comment by oracle9i88** [comment]
under win10,everything is ok

**Comment by oracle9i88** [comment]
> > I think Avatar conversion allows just 100
> 
> Why do you think so?

you are my idol

**Comment by oracle9i88** [comment]
my fault, the model is mixed
