### ISSUE TITLE
No module named 'keras_contrib'

### ISSUE THREAD

**Issue by zysttttttt** [iperov/DeepFaceLab#28]
## Expected behavior

Train success

## Actual behavior

Using TensorFlow backend.
Error: No module named 'keras_contrib'
Traceback (most recent call last):
  File "D:\AI\fake\DeepFaceLab-master\mainscripts\Trainer.py", line 41, in trainerThread
    **in_options)
  File "D:\AI\fake\DeepFaceLab-master\models\ModelBase.py", line 106, in __init__
    self.keras_contrib = gpufmkmgr.import_keras_contrib()
  File "D:\AI\fake\DeepFaceLab-master\gpufmkmgr\gpufmkmgr.py", line 107, in import_keras_contrib
    import keras_contrib
ModuleNotFoundError: No module named 'keras_contrib'

## Steps to reproduce

already import keras
can not find keras_contrib

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: python main.py train --training-data-src-dir A --training-data-dst-dir B --model-dir M --model DF
- **Operating system and version:** Windows
- **Python version:** 3.6.4

**Comment by zysttttttt** [comment]
should install git+https://www.github.com/keras-team/keras-contrib.git 
Sorry I forgot
