### ISSUE TITLE
Broken pipe error during convert process

### ISSUE THREAD

**Issue by Je11yman** [iperov/DeepFaceLab#304]
Everything is performing as expected, until I attempt converting (step 7). Using the default settings throughout the process I get this fault during the convert process:

"Error: Unable to start subprocess CPU5
Traceback (most recent call last):
  File "E:\DeepFaceLabs\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\joblib\SubprocessorBase.py", line 151, in run
    cli = self.SubprocessorCli_class(client_dict)
  File "E:\DeepFaceLabs\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\joblib\SubprocessorBase.py", line 19, in __init__
    self.p.start()
  File "multiprocessing\process.py", line 105, in start
  File "multiprocessing\context.py", line 223, in _Popen
  File "multiprocessing\context.py", line 322, in _Popen
  File "multiprocessing\popen_spawn_win32.py", line 65, in __init__
  File "multiprocessing\reduction.py", line 60, in dump
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DeepFaceLabs\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\mainscripts\Converter.py", line 329, in main
    debug                  = args.get('debug',False)
  File "E:\DeepFaceLabs\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\joblib\SubprocessorBase.py", line 178, in run
    raise Exception ("Unable to start subprocess %s" % (name))
Exception: Unable to start subprocess CPU5"

This is using the H64 train (succeeds) and convert (fails.)

Windows 10, updated,
CUDA 9.2.148.1
Geforce GTX 970 with 4Gigs
Intel Xeon X5690
18 Gigs ram

**Comment by Je11yman** [comment]
After a complete shutdown and restart the issue is resolved.
