### ISSUE TITLE
I deep fake training error

### ISSUE THREAD

**Issue by mostafa198911** [iperov/DeepFaceLab#319]
when training I get this error report any idea why? 
my pc spec core i 7 960 workstation dell t3500 ang gpu gtx 1050 2gb
.................................................................
Starting. Press "Enter" to stop training and save model.
Error: OOM when allocating tensor with shape[3,3,512,1024] and type float on /jo
b:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node training/Adam/Variable_16/Assign (defined at C:\DeepFaceLabCUDA9
.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-pac
kages\keras\backend\tensorflow_backend.py:402)  = Assign[T=DT_FLOAT, _grappler_r
elax_allocator_constraints=true, use_locking=true, validate_shape=true, _device=
"/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/Variable_16, train
ing/Adam/zeros_16)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add repor
t_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'training/Adam/Variable_16/Assign', defined at:
  File "threading.py", line 884, in _bootstrap
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\DeepFaceLab\mainscripts\Trainer.py", line 107, in trainerThread
    iter, iter_time = model.train_one_iter()
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\DeepFaceLab\models\ModelBase.py", line 472, in train_one_iter
    losses = self.onTrainOneIter(sample, self.generator_list)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\DeepFaceLab\models\Model_H64\Model.py", line 89, in onTrainOneIter
    total, loss_src_bgr, loss_src_mask, loss_dst_bgr, loss_dst_mask = self.ae.tr
ain_on_batch( [warped_src, target_src_full_mask, warped_dst, target_dst_full_mas
k], [target_src, target_src_full_mask, target_dst, target_dst_full_mask] )
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\keras\engine\training.py", line 1216, in train_
on_batch
    self._make_train_function()
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\keras\engine\training.py", line 509, in _make_t
rain_function
    loss=self.total_loss)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\DeepFaceLab\nnlib\nnlib.py", line 547, in get_updates
    ms = [K.zeros(K.int_shape(p), dtype=K.dtype(p)) for p in params]
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\DeepFaceLab\nnlib\nnlib.py", line 547, in <listcomp>
    ms = [K.zeros(K.int_shape(p), dtype=K.dtype(p)) for p in params]
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 704,
 in zeros
    return variable(v, dtype=dtype, name=name)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 402,
 in variable
    v = tf.Variable(value, dtype=tf.as_dtype(dtype), name=name)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 183,
in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 146,
in _variable_v1_call
    aggregation=aggregation)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 125,
in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\ops\variable_scope.py", line
2444, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 187,
in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 1329,
 in __init__
    constraint=constraint)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 1481,
 in _init_from_args
    validate_shape=validate_shape).op
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\ops\state_ops.py", line 221,
in assign
    validate_shape=validate_shape)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 6
1, in assign
    use_locking=use_locking, name=name)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\framework\op_def_library.py",
 line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\util\deprecation.py", line 48
8, in new_func
    return func(*args, **kwargs)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 3274,
 in create_op
    op_def=op_def)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 1770,
 in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor wit
h shape[3,3,512,1024] and type float on /job:localhost/replica:0/task:0/device:G
PU:0 by allocator GPU_0_bfc
         [[node training/Adam/Variable_16/Assign (defined at C:\DeepFaceLabCUDA9
.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-pac
kages\keras\backend\tensorflow_backend.py:402)  = Assign[T=DT_FLOAT, _grappler_r
elax_allocator_constraints=true, use_locking=true, validate_shape=true, _device=
"/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/Variable_16, train
ing/Adam/zeros_16)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add repor
t_tensor_allocations_upon_oom to RunOptions for current allocation info.

Traceback (most recent call last):
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1334
, in _do_call
    return fn(*args)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1319
, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1407
, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocat
ing tensor with shape[3,3,512,1024] and type float on /job:localhost/replica:0/t
ask:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node training/Adam/Variable_16/Assign}} = Assign[T=DT_FLOAT, _grapp
ler_relax_allocator_constraints=true, use_locking=true, validate_shape=true, _de
vice="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/Variable_16,
training/Adam/zeros_16)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add repor
t_tensor_allocations_upon_oom to RunOptions for current allocation info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\DeepFaceLab\mainscripts\Trainer.py", line 107, in trainerThread
    iter, iter_time = model.train_one_iter()
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\DeepFaceLab\models\ModelBase.py", line 472, in train_one_iter
    losses = self.onTrainOneIter(sample, self.generator_list)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\DeepFaceLab\models\Model_H64\Model.py", line 89, in onTrainOneIter
    total, loss_src_bgr, loss_src_mask, loss_dst_bgr, loss_dst_mask = self.ae.tr
ain_on_batch( [warped_src, target_src_full_mask, warped_dst, target_dst_full_mas
k], [target_src, target_src_full_mask, target_dst, target_dst_full_mask] )
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\keras\engine\training.py", line 1217, in train_
on_batch
    outputs = self.train_function(ins)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2697
, in __call__
    if hasattr(get_session(), '_make_callable_from_options'):
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 206,
 in get_session
    session.run(tf.variables_initializer(uninitialized_vars))
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 929,
 in run
    run_metadata_ptr)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1152
, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1328
, in _do_run
    run_metadata)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1348
, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocat
ing tensor with shape[3,3,512,1024] and type float on /job:localhost/replica:0/t
ask:0/device:GPU:0 by allocator GPU_0_bfc
         [[node training/Adam/Variable_16/Assign (defined at C:\DeepFaceLabCUDA9
.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-pac
kages\keras\backend\tensorflow_backend.py:402)  = Assign[T=DT_FLOAT, _grappler_r
elax_allocator_constraints=true, use_locking=true, validate_shape=true, _device=
"/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/Variable_16, train
ing/Adam/zeros_16)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add repor
t_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'training/Adam/Variable_16/Assign', defined at:
  File "threading.py", line 884, in _bootstrap
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\DeepFaceLab\mainscripts\Trainer.py", line 107, in trainerThread
    iter, iter_time = model.train_one_iter()
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\DeepFaceLab\models\ModelBase.py", line 472, in train_one_iter
    losses = self.onTrainOneIter(sample, self.generator_list)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\DeepFaceLab\models\Model_H64\Model.py", line 89, in onTrainOneIter
    total, loss_src_bgr, loss_src_mask, loss_dst_bgr, loss_dst_mask = self.ae.tr
ain_on_batch( [warped_src, target_src_full_mask, warped_dst, target_dst_full_mas
k], [target_src, target_src_full_mask, target_dst, target_dst_full_mask] )
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\keras\engine\training.py", line 1216, in train_
on_batch
    self._make_train_function()
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\keras\engine\training.py", line 509, in _make_t
rain_function
    loss=self.total_loss)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\DeepFaceLab\nnlib\nnlib.py", line 547, in get_updates
    ms = [K.zeros(K.int_shape(p), dtype=K.dtype(p)) for p in params]
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\DeepFaceLab\nnlib\nnlib.py", line 547, in <listcomp>
    ms = [K.zeros(K.int_shape(p), dtype=K.dtype(p)) for p in params]
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 704,
 in zeros
    return variable(v, dtype=dtype, name=name)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 402,
 in variable
    v = tf.Variable(value, dtype=tf.as_dtype(dtype), name=name)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 183,
in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 146,
in _variable_v1_call
    aggregation=aggregation)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 125,
in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\ops\variable_scope.py", line
2444, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 187,
in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 1329,
 in __init__
    constraint=constraint)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 1481,
 in _init_from_args
    validate_shape=validate_shape).op
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\ops\state_ops.py", line 221,
in assign
    validate_shape=validate_shape)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 6
1, in assign
    use_locking=use_locking, name=name)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\framework\op_def_library.py",
 line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\util\deprecation.py", line 48
8, in new_func
    return func(*args, **kwargs)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 3274,
 in create_op
    op_def=op_def)
  File "C:\DeepFaceLabCUDA9.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_interna
l\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 1770,
 in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor wit
h shape[3,3,512,1024] and type float on /job:localhost/replica:0/task:0/device:G
PU:0 by allocator GPU_0_bfc
         [[node training/Adam/Variable_16/Assign (defined at C:\DeepFaceLabCUDA9
.2SSE_build_06_20_2019\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-pac
kages\keras\backend\tensorflow_backend.py:402)  = Assign[T=DT_FLOAT, _grappler_r
elax_allocator_constraints=true, use_locking=true, validate_shape=true, _device=
"/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/Variable_16, train
ing/Adam/zeros_16)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add repor
t_tensor_allocations_upon_oom to RunOptions for current allocation info.

Done.
Press any key to continue . . .

**Comment by sdgandhi** [comment]
Your GPU has very low memory, and has run out (OOM = Out Of Memory). Try using the H64 model to train.

**Comment by mostafa198911** [comment]
I used the H64 when I got this error .maybe it is as you said

**Comment by Auroir** [comment]
Lower your **batch size** or reduce the dimensions for your model during initial setup.
