### ISSUE TITLE
H128 unable to run OpenCL kernal and unable to map memory (CL_MEM_OBJECT_ALLOCATION_FAILURE)

### ISSUE THREAD

**Issue by Rektroth** [iperov/DeepFaceLab#333]
## Expected behavior

Simply trying to train with H128.

## Actual behavior

The model will load and the training preview will even appear. It will go through a thousands of iterations and I'll just let it sit for a while (several hours) and absolutely no progress will be made.

After saving and exiting, the following appears:

`ERROR:plaidml:unable to run OpenCL kernel: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR:plaidml:Unable to map memory: CL_MEM_OBJECT_ALLOCATION_FAILURE
Error: Unable to map memory: CL_MEM_OBJECT_ALLOCATION_FAILURE
Traceback (most recent call last):
  File "C:\Users\Rektroth\Desktop\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 159, in trainerThread
    model_save()
  File "C:\Users\Rektroth\Desktop\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 59, in model_save
    model.save()
  File "C:\Users\Rektroth\Desktop\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\models\ModelBase.py", line 345, in save
    self.onSave()
  File "C:\Users\Rektroth\Desktop\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\models\Model_H128\Model.py", line 81, in onSave
    self.save_weights_safe( self.get_model_filename_list() )
  File "C:\Users\Rektroth\Desktop\DeepFaceLabOpenCLSSE\_internal\DeepFaceLab\models\ModelBase.py", line 420, in save_weights_safe
    model.save_weights( filename + '.tmp' )
  File "C:\Users\Rektroth\Desktop\DeepFaceLabOpenCLSSE\_internal\python-3.6.8\lib\site-packages\keras\engine\network.py", line 1121, in save_weights
    saving.save_weights_to_hdf5_group(f, self.layers)
  File "C:\Users\Rektroth\Desktop\DeepFaceLabOpenCLSSE\_internal\python-3.6.8\lib\site-packages\keras\engine\saving.py", line 572, in save_weights_to_hdf5_group
    weight_values = K.batch_get_value(symbolic_weights)
  File "C:\Users\Rektroth\Desktop\DeepFaceLabOpenCLSSE\_internal\python-3.6.8\lib\site-packages\plaidml\keras\backend.py", line 354, in batch_get_value
    return [get_value(x) for x in xs]
  File "C:\Users\Rektroth\Desktop\DeepFaceLabOpenCLSSE\_internal\python-3.6.8\lib\site-packages\plaidml\keras\backend.py", line 354, in <listcomp>
    return [get_value(x) for x in xs]
  File "C:\Users\Rektroth\Desktop\DeepFaceLabOpenCLSSE\_internal\python-3.6.8\lib\site-packages\plaidml\keras\backend.py", line 771, in get_value
    with tensor.mmap_current() as view:
  File "contextlib.py", line 81, in __enter__
  File "C:\Users\Rektroth\Desktop\DeepFaceLabOpenCLSSE\_internal\python-3.6.8\lib\site-packages\plaidml\__init__.py", line 1245, in mmap_current
    ctypes.cast(None, _MAP_BUFFER_FUNCTYPE), None)
  File "C:\Users\Rektroth\Desktop\DeepFaceLabOpenCLSSE\_internal\python-3.6.8\lib\site-packages\plaidml\__init__.py", line 777, in _check_err
    self.raise_last_status()
  File "C:\Users\Rektroth\Desktop\DeepFaceLabOpenCLSSE\_internal\python-3.6.8\lib\site-packages\plaidml\library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: Unable to map memory: CL_MEM_OBJECT_ALLOCATION_FAILURE`

## Steps to reproduce

Just run the H128 trainer and input the default values.

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: cmd.exe
- **Operating system and version:** Windows 10 Version 1809
- **Python version:** using pre-build

For full context, [here's a complete console log](https://pastebin.com/LE8fsEYf).

**Comment by Rektroth** [comment]
Ignore me. I was wondering why it wasn't using CUDA. Probably because I didn't download the CUDA build...
