### ISSUE TITLE
Error in DeepFaceLabCUDA10.1AVX_build_08_16_2019

### ISSUE THREAD

**Issue by blanuk** [iperov/DeepFaceLab#351]
Hi there

With the new Version i got an error:
`Traceback (most recent call last):
  File "M:\_x\_internal\DeepFaceLab\main.py", line 252, in <module>
    arguments.func(arguments)
  File "M:\_x\_internal\DeepFaceLab\main.py", line 223, in process_videoed_video_from_sequence
    arguments.lossless)
  File "M:\_x\_internal\DeepFaceLab\mainscripts\VideoEd.py", line 138, in video_from_sequence
    reference_file_path = Path_utils.get_first_file_by_stem (reference_file_path.parent, reference_file_path.stem)
  File "M:\_x\_internal\DeepFaceLab\utils\Path_utils.py", line 64, in get_first_file_by_stem
    for x in sorted(list(scandir(str(dir_path)))):
TypeError: '<' not supported between instances of 'nt.DirEntry' and 'nt.DirEntry'`

Any Idea?
Get this by extracting and make the mp4 file.
Train and convert work.

**Comment by iperov** [comment]
@Auroir recent changes in path_utils.py made by you

**Comment by blanuk** [comment]
copy the Path_utils.py from the version 20.06 into the new version works vor me.
maybe it have something to do with removing the sorted() ?

**Comment by iperov** [comment]
@Auroir can you please fix the issue

**Comment by Auroir** [comment]
@iperov Resolved by #353
