### ISSUE TITLE
Not able to detect faces, error

### ISSUE THREAD

**Issue by offface** [iperov/DeepFaceLab#361]
Was able to split the video into individual frames but when trying to extract faces using "4) data_src extract faces S3FD all GPU" I get error with stack trace:

Performing 1st pass...
Running on Generic GeForce GPU. Recommended to close all programs using this device.
Exception: Traceback (most recent call last):
  File "D:\DFL\DeepFaceLabCUDA9.2SSE_build_08_16_2019\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\DFL\DeepFaceLabCUDA9.2SSE_build_08_16_2019\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\DFL\DeepFaceLabCUDA9.2SSE_build_08_16_2019\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\DFL\DeepFaceLabCUDA9.2SSE_build_08_16_2019\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\joblib\SubprocessorBase.py", line 59, in _subprocess_run
    self.on_initialize(client_dict)
  File "D:\DFL\DeepFaceLabCUDA9.2SSE_build_08_16_2019\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\mainscripts\Extractor.py", line 76, in on_initialize
    nnlib.import_all (device_config)
  File "D:\DFL\DeepFaceLabCUDA9.2SSE_build_08_16_2019\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\nnlib\nnlib.py", line 840, in import_all
    nnlib.import_keras(device_config)
  File "D:\DFL\DeepFaceLabCUDA9.2SSE_build_08_16_2019\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\nnlib\nnlib.py", line 167, in import_keras
    nnlib._import_tf(device_config)
  File "D:\DFL\DeepFaceLabCUDA9.2SSE_build_08_16_2019\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\nnlib\nnlib.py", line 136, in _import_tf
    import tensorflow as tf
  File "D:\DFL\DeepFaceLabCUDA9.2SSE_build_08_16_2019\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "D:\DFL\DeepFaceLabCUDA9.2SSE_build_08_16_2019\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "D:\DFL\DeepFaceLabCUDA9.2SSE_build_08_16_2019\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "D:\DFL\DeepFaceLabCUDA9.2SSE_build_08_16_2019\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\DFL\DeepFaceLabCUDA9.2SSE_build_08_16_2019\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\DFL\DeepFaceLabCUDA9.2SSE_build_08_16_2019\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

**Comment by offface** [comment]
I just followed this video for radeon graphic cards:

https://www.youtube.com/watch?v=jqq6-VGhfFc
