### ISSUE TITLE
Avatar model train has an error

### ISSUE THREAD

**Issue by gogrkig** [iperov/DeepFaceLab#371]
hello.

I was trying to extract a 5 second video to use avatar model.

"Error: 'AVATARModel' object has no attribute 'CD'
Traceback (most recent call last):
  File "F:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\mainscripts\Trainer.py", line 49, in trainerThread
    device_args=device_args)
  File "F:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\models\Model_AVATAR\Model.py", line 21, in __init__
    ask_src_scale_mod=False)
  File "F:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\models\ModelBase.py", line 169, in __init__
    self.onInitialize()
  File "F:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\models\Model_AVATAR\Model.py", line 70, in onInitialize
    for model in [self.enc, self.decA64, self.decB64, self.C, self.D, self.CD]:
AttributeError: 'AVATARModel' object has no attribute 'CD' "

It comes out like this. According to the manual, the video length should be 10-20 minutes(x). Background must be the same(o)
Only one face appears(o).

don't an error if you use more than 10 minutes of video?

**Comment by iperov** [comment]
fixed

**Comment by iperov** [comment]
I will update builds later, or you can replace deepfacelab folder manually

**Comment by gogrkig** [comment]
Thank you for your efforts.

By the way, the following is displayed in retry

"Error: 'list' object has no attribute 'layers'
Traceback (most recent call last):
  File "F:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\mainscripts\Trainer.py", line 49, in trainerThread
    device_args=device_args)
  File "F:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\models\Model_AVATAR\Model.py", line 21, in __init__
    ask_src_scale_mod=False)
  File "F:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\models\ModelBase.py", line 169, in __init__
    self.onInitialize()
  File "F:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\models\Model_AVATAR\Model.py", line 71, in onInitialize
    for layer in model.layers:
AttributeError: 'list' object has no attribute 'layers'

**Comment by iperov** [comment]
fixed

**Comment by gogrkig** [comment]
Thank you for your quick fix. After loading the image, the following is displayed.

"Process Process-13:
Traceback (most recent call last):
  File "F:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 122, in batch_func
    x = SampleProcessor.process (sample, self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "F:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 105, in process
    params = imagelib.gen_warp_params(sample_bgr, sample_process_options.random_flip, rotation_range=sample_process_options.rotation_range, scale_range=sample_process_options.scale_range, tx_range=sample_process_options.tx_range, ty_range=sample_process_options.ty_range )
  File "F:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\imagelib\warp.py", line 8, in gen_warp_params
    raise ValueError ('TrainingDataGenerator accepts only square power of 2 images.')
ValueError: TrainingDataGenerator accepts only square power of 2 images.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 258, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "F:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\utils\iter_utils.py", line 39, in process_func
    gen_data = next (self.generator_func)
  File "F:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 124, in batch_func
    raise Exception ("Exception occured in sample %s. Error: %s" % (sample.filename, traceback.format_exc() ) )
Exception: Exception occured in sample F:\DeepFaceLabCUDA10.1AVX\workspace\data_src\aligned\02739.jpg. Error: Traceback (most recent call last):
  File "F:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 122, in batch_func
    x = SampleProcessor.process (sample, self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "F:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 105, in process
    params = imagelib.gen_warp_params(sample_bgr, sample_process_options.random_flip, rotation_range=sample_process_options.rotation_range, scale_range=sample_process_options.scale_range, tx_range=sample_process_options.tx_range, ty_range=sample_process_options.ty_range )
  File "F:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\imagelib\warp.py", line 8, in gen_warp_params
    raise ValueError ('TrainingDataGenerator accepts only square power of 2 images.')
ValueError: TrainingDataGenerator accepts only square power of 2 images.

**Comment by iperov** [comment]
TrainingDataGenerator accepts only square power of 2 images.

**Comment by gogrkig** [comment]
I am ignorant and do not understand. So I tried resizing the batch size and number of images to 32, but I can't figure out why the squares powers are output.

"ValueError: TrainingDataGenerator allows only squared powers of 2 images."
Can you tell me the correct answer how can I solve it?

=====
Run the trainer.

Loading model ...

First run of the model. Enter model options by default for each run.
Do you want to use Auto Backup? (y / n?: help skip: n):
yen
Do you want to create a preview history? (y / n?: help skip: n):
yen
Batch_size (?: Help skip: 0): 32
Avatar type (0: source, 1: full_face, 2: head ?: help skip: 0): 0
Step (0,1,2?: Help skip: 1): 1
Using the TensorFlow Backend
CA weight initialization: 100% | ####################################### ########### ### | 35/35 [02:02 <00:00, 3.51 s / it]
Load: 100% | ########################################## ######## ################### | 32/32 [00:00 <00:00, 122.92it / s]
Load: 100% | ########################################## ######## ################### | 32/32 [00:00 <00:00, 639.81it / s]
Process Process -13:

**Comment by iperov** [comment]
sry no time for that
read changelog again and again
