### ISSUE TITLE
H128 training error

### ISSUE THREAD

**Issue by dalasjoe75** [iperov/DeepFaceLab#372]
Hello

After latest update i got an error like below at Model.py of H128:

Error: invalid syntax (Model.py, line 124)
Traceback (most recent call last):
  File "/content/DeepFaceLab/mainscripts/Trainer.py", line 43, in trainerThread
    model = models.import_model(model_name)(
  File "/content/DeepFaceLab/models/__init__.py", line 4, in import_model
    module = __import__('Model_'+name, globals(), locals(), [], 1)
  File "/content/DeepFaceLab/models/Model_H128/__init__.py", line 1, in <module>
    from .Model import Model
  File "/content/DeepFaceLab/models/Model_H128/Model.py", line 124
    self.AE_convert ([ np.zeros ( (1, 128, 128, 3) ), dtype=np.float32 ) ])
                                                           ^
SyntaxError: invalid syntax
 
Thanks

**Comment by ironpanther** [comment]
I get that same "invalid syntax line 124" error using H128 now, too.  

I also now get this when trying to convert H128:

Error: 
Traceback (most recent call last):
File "C:\Fakes\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\mainscripts\Converter.py", line 484, in main
cfg = model.get_ConverterConfig()
File "C:\Fakes\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\models\ModelBase.py", line 329, in get_ConverterConfig 
raise NotImplementedError
NotImplementedError

**Comment by iperov** [comment]
thx, fixed
