### ISSUE TITLE
syntax error in "train H128.bat"

### ISSUE THREAD

**Issue by gaoyuqi** [iperov/DeepFaceLab#376]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior
when executes train H128.bat,  hope it could start training. But meet such error.
## Actual behavior

Running trainer.

Error: invalid syntax (Model.py, line 125)
Traceback (most recent call last):
  File "C:\Users\Mloong\Desktop\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 43, in trainerThread
    model = models.import_model(model_name)(
  File "C:\Users\Mloong\Desktop\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\models\__init__.py", line 4, in import_model
    module = __import__('Model_'+name, globals(), locals(), [], 1)
  File "C:\Users\Mloong\Desktop\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\models\Model_H64\__init__.py", line 1, in <module>
    from .Model import Model
  File "C:\Users\Mloong\Desktop\DeepFaceLabCUDA10.1SSE\_internal\DeepFaceLab\models\Model_H64\Model.py", line 125
    self.AE_convert ([ np.zeros ( (1, 64, 64, 3) ), dtype=np.float32 ) ])

## Steps to reproduce
 it is related to code:
 def predictor_func (self, face=None, dummy_predict=False):
        if dummy_predict:
            self.AE_convert ([ np.zeros ( (1, 128, 128, 3) ), dtype=np.float32)])
        else:
            x, mx = self.src_view ( [ face[np.newaxis,...] ] )
            return x[0], mx[0][...,0]
 
 ///
any one could give some hint and workaround on this .  it seems no error.

**Comment by iperov** [comment]
download latest build
