### ISSUE TITLE
Error in AVATAR to train

### ISSUE THREAD

**Issue by loboere** [iperov/DeepFaceLab#382]
```
/content
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Time to backup: 6 hours
Running trainer.

Loading model...

Model first run. Enter model options as default for each run.
Enable autobackup? (y/n ?:help skip:n) : 
n
Write preview history? (y/n ?:help skip:n) : 
n
Target iteration (skip:unlimited/default) : 
0
Batch_size (?:help skip:0) : 
0
Avatar type ( 0:source, 1:head, 2:full_face ?:help skip:1) : 2
Stage (0, 1, 2 ?:help skip:1) : 
1
Using TensorFlow backend.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

Initializing CA weights: 100% 35/35 [06:33<00:00, 11.25s/it]/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
Initializing CA weights: 100% 35/35 [06:33<00:00, 11.25s/it]
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Loading: 100% 460/460 [00:00<00:00, 649.13it/s]
Loading: 100% 489/489 [00:00<00:00, 702.72it/s]
Process Process-3:
Traceback (most recent call last):
  File "/content/DeepFaceLab/samplelib/SampleGeneratorFace.py", line 122, in batch_func
    x = SampleProcessor.process (sample, self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "/content/DeepFaceLab/samplelib/SampleProcessor.py", line 215, in process
    raise Exception ('sample %s type %s does not match model requirement %s. Consider extract necessary type of faces.' % (sample.filename, sample.face_type, target_ft) )
Exception: sample /content/workspace/data_src/aligned/00256.jpg type FaceType.FULL does not match model requirement FaceType.FULL_NO_ALIGN. Consider extract necessary type of faces.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/DeepFaceLab/utils/iter_utils.py", line 39, in process_func
    gen_data = next (self.generator_func)
  File "/content/DeepFaceLab/samplelib/SampleGeneratorFace.py", line 124, in batch_func
    raise Exception ("Exception occured in sample %s. Error: %s" % (sample.filename, traceback.format_exc() ) )
Exception: Exception occured in sample /content/workspace/data_src/aligned/00256.jpg. Error: Traceback (most recent call last):
  File "/content/DeepFaceLab/samplelib/SampleGeneratorFace.py", line 122, in batch_func
    x = SampleProcessor.process (sample, self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "/content/DeepFaceLab/samplelib/SampleProcessor.py", line 215, in process
    raise Exception ('sample %s type %s does not match model requirement %s. Consider extract necessary type of faces.' % (sample.filename, sample.face_type, target_ft) )
Exception: sample /content/workspace/data_src/aligned/00256.jpg type FaceType.FULL does not match model requirement FaceType.FULL_NO_ALIGN. Consider extract necessary type of faces.

/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
```

**Comment by iperov** [comment]
read manual

**Comment by loboere** [comment]
the manual mentions:
```
data_src mark faces S3FD best GPU.bat
dst extract unaligned faces S3FD best GPU.bat
AVATAR.bat
```
is extension "bat" is from windows
but how do i do it in linux?

**Comment by sdgandhi** [comment]
Use the linux fork (mentioned in readme). It's probably outdated though
