### ISSUE TITLE
Linux version ... problem

### ISSUE THREAD

**Issue by wasyleque** [iperov/DeepFaceLab#400]
First or continue with a different facesets (dst), what does it mean ?
```
Loading model...

Model first run. Enter model options as default for each run.
Enable autobackup? (y/n ?:help skip:n) : y
Write preview history? (y/n ?:help skip:n) : y
Choose image for the preview history? (y/n skip:n) : n
Target iteration (skip:unlimited/default) : 
0
Batch_size (?:help skip:0) : 7
Feed faces to network sorted by yaw? (y/n ?:help skip:n) : n
Flip faces randomly? (y/n ?:help skip:y) : y
Src face scale modifier % ( -30...30, ?:help skip:0) : 
0
Resolution ( 64-256 ?:help skip:128) : 
128
Half or Full face? (h/f, ?:help skip:f) : 
f
Learn mask? (y/n, ?:help skip:y) : 
y
Optimizer mode? ( 1,2,3 ?:help skip:1) : 
1
AE architecture (df, liae ?:help skip:df) : 
df
AutoEncoder dims (32-1024 ?:help skip:512) : 690
Encoder dims per channel (21-85 ?:help skip:42) : 54
Decoder dims per channel (10-85 ?:help skip:27) : 
27
Use multiscale decoder? (y/n, ?:help skip:n) : y
Use CA weights? (y/n, ?:help skip: n ) : y
Use pixel loss? (y/n, ?:help skip: n ) : n
Face style power ( 0.0 .. 100.0 ?:help skip:0.00) : 
0.0
Background style power ( 0.0 .. 100.0 ?:help skip:0.00) : 
0.0
Apply random color transfer to src faceset? (y/n, ?:help skip:n) : y
Enable gradient clipping? (y/n, ?:help skip:n) : ?
Gradient clipping reduces chance of model collapse, sacrificing speed of training.
Enable gradient clipping? (y/n, ?:help skip:n) : n
Pretrain the model? (y/n, ?:help skip:n) : ?
Pretrain the model with large amount of various faces. This technique may help to train the fake with overly different face shapes and light conditions of src/dst data. Face will be look more like a morphed. To reduce the morph effect, some model files will be initialized but not be updated after pretrain: LIAE: inter_AB.h5 DF: encoder.h5. The longer you pretrain the model the more morphed face will look. After that, save and run the training again.
Pretrain the model? (y/n, ?:help skip:n) : n
Using TensorFlow backend.
Initializing CA weights: 100%|#####################################################################################| 49/49 [01:45<00:00,  2.16s/it]
Loading: 0it [00:00, ?it/s]
Loading: 100%|#############################################################################################| 38338/38338 [00:36<00:00, 1055.09it/s]
Error: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/piotr/DeepFaceLab_Linux/mainscripts/Trainer.py", line 49, in trainerThread
    device_args=device_args)
  File "/home/piotr/DeepFaceLab_Linux/models/ModelBase.py", line 232, in __init__
    self.sample_for_preview = self.generate_next_sample()
  File "/home/piotr/DeepFaceLab_Linux/models/ModelBase.py", line 492, in generate_next_sample
    return [ generator.generate_next() for generator in self.generator_list]
  File "/home/piotr/DeepFaceLab_Linux/models/ModelBase.py", line 492, in <listcomp>
    return [ generator.generate_next() for generator in self.generator_list]
  File "/home/piotr/DeepFaceLab_Linux/samplelib/SampleGeneratorBase.py", line 25, in generate_next
    self.last_generation = next(self)
  File "/home/piotr/DeepFaceLab_Linux/samplelib/SampleGeneratorFace.py", line 58, in __next__
    generator = self.generators[self.generator_counter % len(self.generators) ]
ZeroDivisionError: integer division or modulo by zero
```

**Comment by iperov** [comment]
no aligned files in src folder

**Comment by wasyleque** [comment]
Yeah You`re always right
