### ISSUE TITLE
Can't use previously created model after today's update

### ISSUE THREAD

**Issue by dophin17543** [iperov/DeepFaceLab#411]
Traceback (most recent call last):
  File "/content/DeepFaceLab/mainscripts/Trainer.py", line 49, in trainerThread
    device_args=device_args)
  File "/content/DeepFaceLab/models/ModelBase.py", line 169, in __init__
    self.onInitialize()
  File "/content/DeepFaceLab/models/Model_SAE/Model.py", line 344, in onInitialize
    loaded, not_loaded = self.load_weights_safe(not_loaded)
  File "/content/DeepFaceLab/models/ModelBase.py", line 422, in load_weights_safe
    model.load_weights(filename)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 1030, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 18 layers into a model with 16 layers.

**Comment by BolshoiPedro** [comment]
Same error here with Colab:

"ValueError: You are trying to load a weight file containing 18 layers into a model with 16 layers."

**Comment by blanuk** [comment]
== 13.09.2019 ==
SAE: removed multiscale decoder, because it's not effective

Maybe its because of that

**Comment by dophin17543** [comment]
I also got error messages when starting a new SAE model

Error: integer division or modulo by zero
Traceback (most recent call last):
  File "/content/DeepFaceLab/mainscripts/Trainer.py", line 49, in trainerThread
    device_args=device_args)
  File "/content/DeepFaceLab/models/ModelBase.py", line 233, in __init__
    self.sample_for_preview = self.generate_next_sample()
  File "/content/DeepFaceLab/models/ModelBase.py", line 495, in generate_next_sample
    return [ generator.generate_next() for generator in self.generator_list]
  File "/content/DeepFaceLab/models/ModelBase.py", line 495, in <listcomp>
    return [ generator.generate_next() for generator in self.generator_list]
  File "/content/DeepFaceLab/samplelib/SampleGeneratorBase.py", line 25, in generate_next
    self.last_generation = next(self)
  File "/content/DeepFaceLab/samplelib/SampleGeneratorFace.py", line 58, in __next__
    generator = self.generators[self.generator_counter % len(self.generators) ]
ZeroDivisionError: integer division or modulo by zero

**Comment by chervonij** [comment]
@dophin17543 @blanuk @BolshoiPedro 

You can partially save your trained model.

If you have a LIAE model, then you delete the decoder files from the model and continue training. DFL will generate a new decoder, but the encoder is already trained and the model will recover faster than if you train from scratch.

If DF, then everything is a little more complicated. With the new decoder, the model crashes. But you can temporarily enable pixel loss for 20-30 iterations before starting train. Then turn it off and continue training as usual.

**Comment by BolshoiPedro** [comment]
Thank you @chervonij , I will try that.

**Comment by devilishj** [comment]
Maybe create a new repository with the previous version and a new ipynb so all the Colab users with trained base models aren't completely screwed!!!!

**Comment by chervonij** [comment]
@devilishj 
It's not Colab problem.
This changes on SAE model.

**Comment by devilishj** [comment]
@chervonij 
I got that... was suggesting to make the previous version available for use... along with a new ipynb to clone from it.

**Comment by chervonij** [comment]
@devilishj 
Why do you need this?
If you really need the previous version of SAE, you can find it in the commit history and manually replace it in your DFL instance. But I do not see the point in this, if you can work with the current version.

**Comment by devilishj** [comment]
@chervonij
I have previous version on my desktop, I was more suggesting because of all the confused and angry people in other forums, completely confused on how to get their base models to load within Colab without having to completely start over.

**Comment by chervonij** [comment]
@devilishj 
I understand how insulting it is that models need to be trained anew. But this is part of the development of technology. iperov works to make the model better, and if he says that multiscale decoder is inefficient, then most likely it is.

I did not do anything ) 
Only proposed a solution that would preserve some progress in DF models.

**Comment by utkdub** [comment]
> @dophin17543 @blanuk @BolshoiPedro
> 
> You can partially save your trained model.
> 
> If you have a LIAE model, then you delete the decoder files from the model and continue training. DFL will generate a new decoder, but the encoder is already trained and the model will recover faster than if you train from scratch.
> 
> If DF, then everything is a little more complicated. With the new decoder, the model crashes. But you can temporarily enable pixel loss for 20-30 iterations before starting train. Then turn it off and continue training as usual.

No need to make pixel loss on for DF model. Looks like in your case it got collapsed. Just delete the decoder files and run the model. it will reload the CA weights and starts training. No collapse happen. But if you keep running pixel loss then COLLAPSE will surely occur if not stopped on right time !

**Comment by utkdub** [comment]
I have placed new trained model based on DF 200k iterations on new decoder link Mrdeepfakes . You guys can download. (By the thread made by VirGin Boi)

**Comment by chervonij** [comment]
@utkdub 
Not just me. In the Colab thread on mrdeepfakes we discussed this. 
In people with the DF model, the model crashed.

And I said that pixel loss needs to be turned on temporarily, in this case.

Thanks for the model)

**Comment by DittoDFL** [comment]
Check MrDeepFakes guide section.

There's a guide on how to use older versions of DFL on Colab.
