### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by Enderpman** [iperov/DeepFaceLab#42]
## Expected behavior

I was trying to extract data from data_src.mp4.

## Actual behavior

Running extractor.

Performing 1st pass...
Running on GeForce GTX 1070.
100%|████████████████████████████████████████████████████████████████████████████████| 655/655 [01:37<00:00,  6.83it/s]
Performing 2nd pass...
Running on GeForce GTX 1070.
100%|████████████████████████████████████████████████████████████████████████████████| 655/655 [01:36<00:00,  6.82it/s]
Performing 3rd pass...
Running on CPU0.
Running on CPU1.
Running on CPU2.
Running on CPU3.
Running on CPU4.
Running on CPU5.
Running on CPU6.
Running on CPU7.
Running on CPU8.
Running on CPU9.
Running on CPU10.
Running on CPU11.
  0%|                                                                                          | 0/655 [00:00<?, ?it/s]Exception while process data [D:\boba\DeepFaceLabTorrent\workspace\data_src\00005.png]: Traceback (most recent call last):
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 233, in subprocess
    result = self.onClientProcessData (data)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 302, in onClientProcessData
    facelib.LandmarksProcessor.draw_rect_landmarks (debug_image, rect, image_landmarks, self.image_size, self.face_type)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 203, in draw_rect_landmarks
    draw_landmarks(image, image_landmarks, (0,255,0) )
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 195, in draw_landmarks
    for x, y in right_eyebrow+left_eyebrow+mouth+right_eye+left_eye+nose:
ValueError: operands could not be broadcast together with shapes (5,2) (20,2)

Exception while process data [D:\boba\DeepFaceLabTorrent\workspace\data_src\00002.png]: Traceback (most recent call last):
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 233, in subprocess
    result = self.onClientProcessData (data)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 302, in onClientProcessData
    facelib.LandmarksProcessor.draw_rect_landmarks (debug_image, rect, image_landmarks, self.image_size, self.face_type)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 203, in draw_rect_landmarks
    draw_landmarks(image, image_landmarks, (0,255,0) )
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 195, in draw_landmarks
    for x, y in right_eyebrow+left_eyebrow+mouth+right_eye+left_eye+nose:
ValueError: operands could not be broadcast together with shapes (5,2) (20,2)

Exception while process data [D:\boba\DeepFaceLabTorrent\workspace\data_src\00003.png]: Traceback (most recent call last):
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 233, in subprocess
    result = self.onClientProcessData (data)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 302, in onClientProcessData
    facelib.LandmarksProcessor.draw_rect_landmarks (debug_image, rect, image_landmarks, self.image_size, self.face_type)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 203, in draw_rect_landmarks
    draw_landmarks(image, image_landmarks, (0,255,0) )
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 195, in draw_landmarks
    for x, y in right_eyebrow+left_eyebrow+mouth+right_eye+left_eye+nose:
ValueError: operands could not be broadcast together with shapes (5,2) (20,2)

Exception while process data [D:\boba\DeepFaceLabTorrent\workspace\data_src\00004.png]: Traceback (most recent call last):
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 233, in subprocess
    result = self.onClientProcessData (data)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 302, in onClientProcessData
    facelib.LandmarksProcessor.draw_rect_landmarks (debug_image, rect, image_landmarks, self.image_size, self.face_type)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 203, in draw_rect_landmarks
    draw_landmarks(image, image_landmarks, (0,255,0) )
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 195, in draw_landmarks
    for x, y in right_eyebrow+left_eyebrow+mouth+right_eye+left_eye+nose:
ValueError: operands could not be broadcast together with shapes (5,2) (20,2)

Exception while process data [D:\boba\DeepFaceLabTorrent\workspace\data_src\00007.png]: Traceback (most recent call last):
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 233, in subprocess
    result = self.onClientProcessData (data)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 302, in onClientProcessData
    facelib.LandmarksProcessor.draw_rect_landmarks (debug_image, rect, image_landmarks, self.image_size, self.face_type)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 203, in draw_rect_landmarks
    draw_landmarks(image, image_landmarks, (0,255,0) )
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 195, in draw_landmarks
    for x, y in right_eyebrow+left_eyebrow+mouth+right_eye+left_eye+nose:
ValueError: operands could not be broadcast together with shapes (5,2) (20,2)

Exception while process data [D:\boba\DeepFaceLabTorrent\workspace\data_src\00006.png]: Traceback (most recent call last):
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 233, in subprocess
    result = self.onClientProcessData (data)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 302, in onClientProcessData
    facelib.LandmarksProcessor.draw_rect_landmarks (debug_image, rect, image_landmarks, self.image_size, self.face_type)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 203, in draw_rect_landmarks
    draw_landmarks(image, image_landmarks, (0,255,0) )
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 195, in draw_landmarks
    for x, y in right_eyebrow+left_eyebrow+mouth+right_eye+left_eye+nose:
ValueError: operands could not be broadcast together with shapes (5,2) (20,2)

Exception while process data [D:\boba\DeepFaceLabTorrent\workspace\data_src\00008.png]: Traceback (most recent call last):
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 233, in subprocess
    result = self.onClientProcessData (data)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 302, in onClientProcessData
    facelib.LandmarksProcessor.draw_rect_landmarks (debug_image, rect, image_landmarks, self.image_size, self.face_type)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 203, in draw_rect_landmarks
    draw_landmarks(image, image_landmarks, (0,255,0) )
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 195, in draw_landmarks
    for x, y in right_eyebrow+left_eyebrow+mouth+right_eye+left_eye+nose:
ValueError: operands could not be broadcast together with shapes (5,2) (20,2)

Exception while process data [D:\boba\DeepFaceLabTorrent\workspace\data_src\00009.png]: Traceback (most recent call last):
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 233, in subprocess
    result = self.onClientProcessData (data)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 302, in onClientProcessData
    facelib.LandmarksProcessor.draw_rect_landmarks (debug_image, rect, image_landmarks, self.image_size, self.face_type)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 203, in draw_rect_landmarks
    draw_landmarks(image, image_landmarks, (0,255,0) )
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 195, in draw_landmarks
    for x, y in right_eyebrow+left_eyebrow+mouth+right_eye+left_eye+nose:
ValueError: operands could not be broadcast together with shapes (5,2) (20,2)

  0%|▏                                                                                 | 1/655 [00:00<01:57,  5.55it/s]Exception while process data [D:\boba\DeepFaceLabTorrent\workspace\data_src\00011.png]: Traceback (most recent call last):
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 233, in subprocess
    result = self.onClientProcessData (data)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 302, in onClientProcessData
    facelib.LandmarksProcessor.draw_rect_landmarks (debug_image, rect, image_landmarks, self.image_size, self.face_type)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 203, in draw_rect_landmarks
    draw_landmarks(image, image_landmarks, (0,255,0) )
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 195, in draw_landmarks
    for x, y in right_eyebrow+left_eyebrow+mouth+right_eye+left_eye+nose:
ValueError: operands could not be broadcast together with shapes (5,2) (20,2)
Exception while process data [D:\boba\DeepFaceLabTorrent\workspace\data_src\00012.png]: Traceback (most recent call last):
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 233, in subprocess
    result = self.onClientProcessData (data)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 302, in onClientProcessData
    facelib.LandmarksProcessor.draw_rect_landmarks (debug_image, rect, image_landmarks, self.image_size, self.face_type)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 203, in draw_rect_landmarks
    draw_landmarks(image, image_landmarks, (0,255,0) )
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 195, in draw_landmarks
    for x, y in right_eyebrow+left_eyebrow+mouth+right_eye+left_eye+nose:
ValueError: operands could not be broadcast together with shapes (5,2) (20,2)

Exception while process data [D:\boba\DeepFaceLabTorrent\workspace\data_src\00010.png]: Traceback (most recent call last):
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 233, in subprocess
    result = self.onClientProcessData (data)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 302, in onClientProcessData
    facelib.LandmarksProcessor.draw_rect_landmarks (debug_image, rect, image_landmarks, self.image_size, self.face_type)
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 203, in draw_rect_landmarks
    draw_landmarks(image, image_landmarks, (0,255,0) )
  File "D:\boba\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 195, in draw_landmarks
    for x, y in right_eyebrow+left_eyebrow+mouth+right_eye+left_eye+nose:
ValueError: operands could not be broadcast together with shapes (5,2) (20,2)

## Steps to reproduce
I had run the batch file for step 4) data_src extract faces DLIB all GPU debug.
## Other relevant information
- **Operating system and version:** Windows 
- **Python version:** 3.7
Maybe my version of Python is too new?

**Comment by iperov** [comment]
@andenixa @NemirovD fix it please

**Comment by Enderpman** [comment]
Cool, thanks.

**Comment by NemirovD** [comment]
This issue was fixed in Issue #13 and has already been fixed in the code as Pull Request #16 . Line 195 of facelib\LandmarksProcessor.py includes the np.concatenate version of the code. Enderpman, have you pulled/cloned the latest version of the code?

**Comment by Enderpman** [comment]
Thanks, my bad.
