### ISSUE TITLE
Avatar model error stage 1 on padding

### ISSUE THREAD

**Issue by sdgandhi** [iperov/DeepFaceLab#422]
```
Error: The `padding` argument must be one of "valid", "same" (or "causal" for Conv1D). Received: zero
Traceback (most recent call last):
  File "D:\dfb\deepfacelab\_internal\DeepFaceLab\mainscripts\Trainer.py", line 50, in trainerThread
    device_args=device_args)
  File "D:\dfb\deepfacelab\_internal\DeepFaceLab\models\Model_AVATAR\Model.py", line 21, in __init__
    ask_src_scale_mod=False)
  File "D:\dfb\deepfacelab\_internal\DeepFaceLab\models\ModelBase.py", line 163, in __init__
    self.onInitialize()
  File "D:\dfb\deepfacelab\_internal\DeepFaceLab\models\Model_AVATAR\Model.py", line 59, in onInitialize
    self.decA64 = modelify(AVATARModel.DecFlow()) ( [ Input(K.int_shape(self.enc.outputs[0])[1:]) ] )
  File "D:\dfb\deepfacelab\_internal\DeepFaceLab\nnlib\nnlib.py", line 223, in func
    return keras.models.Model (tensor, model_functor(tensor))
  File "D:\dfb\deepfacelab\_internal\DeepFaceLab\models\Model_AVATAR\Model.py", line 550, in func
    x = upscale(512)(x)
  File "D:\dfb\deepfacelab\_internal\DeepFaceLab\models\Model_AVATAR\Model.py", line 724, in func
    return SubpixelUpscaler()( LeakyReLU(0.2)(Conv2D(dim * 4, kernel_size=3, strides=1, padding=padding)(x)))
  File "D:\dfb\deepfacelab\_internal\python-3.6.8\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\dfb\deepfacelab\_internal\python-3.6.8\lib\site-packages\keras\layers\convolutional.py", line 490, in __init__
    **kwargs)
  File "D:\dfb\deepfacelab\_internal\python-3.6.8\lib\site-packages\keras\layers\convolutional.py", line 111, in __init__
    self.padding = conv_utils.normalize_padding(padding)
  File "D:\dfb\deepfacelab\_internal\python-3.6.8\lib\site-packages\keras\utils\conv_utils.py", line 58, in normalize_padding
```

DeepFaceLabCUDA10.1AVX_build_09_19_2019

Followed Avatar model instructions in manual

**Comment by sdgandhi** [comment]
Workaround by changing all 'zero' to 'same' in `models\Model_AVATAR\Model.py`

Not sure if it's going to work though. Training in progress.

**Comment by iperov** [comment]
fixed
