### ISSUE TITLE
Some settings give this message for no apperant reason

### ISSUE THREAD

**Issue by GuusDeKroon** [iperov/DeepFaceLab#474]
How to fix this, settings I used to be able to run are not working out.

Error: OOM when allocating tensor with shape[16,256,176,176] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node model_4_1/conv2d_30/convolution}} = Conv2D[T=DT_FLOAT, _class=["loc:@gradients/model_4_1/conv2d_30/convolution_grad/Conv2DBackpropInput"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model_4_1/pixel_shuffler_7/NHWC, conv2d_30/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node add_19/_551}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_7329_add_19", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Traceback (most recent call last):
  File "D:\Program files (x86)\DeepFaceLab\DeepFaceLab_CUDA_10_27\_internal\DeepFaceLab\mainscripts\Trainer.py", line 109, in trainerThread
    iter, iter_time = model.train_one_iter()
  File "D:\Program files (x86)\DeepFaceLab\DeepFaceLab_CUDA_10_27\_internal\DeepFaceLab\models\ModelBase.py", line 525, in train_one_iter
    losses = self.onTrainOneIter(sample, self.generator_list)
  File "D:\Program files (x86)\DeepFaceLab\DeepFaceLab_CUDA_10_27\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 576, in onTrainOneIter
    src_loss, dst_loss, = self.src_dst_train (feed)
  File "D:\Program files (x86)\DeepFaceLab\DeepFaceLab_CUDA_10_27\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "D:\Program files (x86)\DeepFaceLab\DeepFaceLab_CUDA_10_27\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "D:\Program files (x86)\DeepFaceLab\DeepFaceLab_CUDA_10_27\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "D:\Program files (x86)\DeepFaceLab\DeepFaceLab_CUDA_10_27\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[16,256,176,176] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node model_4_1/conv2d_30/convolution}} = Conv2D[T=DT_FLOAT, _class=["loc:@gradients/model_4_1/conv2d_30/convolution_grad/Conv2DBackpropInput"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model_4_1/pixel_shuffler_7/NHWC, conv2d_30/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node add_19/_551}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_7329_add_19", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by Tesla32X** [comment]
Reduce your batchsize and try again. Your gpu is out of memory (OOM)
