### ISSUE TITLE
Hi some help with this error?

### ISSUE THREAD

**Issue by Pnukso** [iperov/DeepFaceLab#484]
Hi!
I'am trying to train H128 but after setting everything this showes up:
Traceback (most recent call last):
  File "C:\Users\dexxt\Desktop\DeepFake\DeepFaceLab_CUDA_10.1_AVX\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 139, in batch_func
    x = SampleProcessor.process (sample, self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "C:\Users\dexxt\Desktop\DeepFake\DeepFaceLab_CUDA_10.1_AVX\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 108, in process
    params = imagelib.gen_warp_params(sample_bgr, sample_process_options.random_flip, rotation_range=sample_process_options.rotation_range, scale_range=sample_process_options.scale_range, tx_range=sample_process_options.tx_range, ty_range=sample_process_options.ty_range )
  File "C:\Users\dexxt\Desktop\DeepFake\DeepFaceLab_CUDA_10.1_AVX\_internal\DeepFaceLab\imagelib\warp.py", line 8, in gen_warp_params
    raise ValueError ('gen_warp_params accepts only square images.')
ValueError: gen_warp_params accepts only square images.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 258, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "C:\Users\dexxt\Desktop\DeepFake\DeepFaceLab_CUDA_10.1_AVX\_internal\DeepFaceLab\utils\iter_utils.py", line 39, in process_func
    gen_data = next (self.generator_func)
  File "C:\Users\dexxt\Desktop\DeepFake\DeepFaceLab_CUDA_10.1_AVX\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 141, in batch_func
    raise Exception ("Exception occured in sample %s. Error: %s" % (sample.filename, traceback.format_exc() ) )
Exception: Exception occured in sample C:\Users\dexxt\Desktop\DeepFake\DeepFaceLab_CUDA_10.1_AVX\workspace\data_src\aligned\00431_0.jpg. Error: Traceback (most recent call last):
  File "C:\Users\dexxt\Desktop\DeepFake\DeepFaceLab_CUDA_10.1_AVX\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 139, in batch_func
    x = SampleProcessor.process (sample, self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "C:\Users\dexxt\Desktop\DeepFake\DeepFaceLab_CUDA_10.1_AVX\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 108, in process
    params = imagelib.gen_warp_params(sample_bgr, sample_process_options.random_flip, rotation_range=sample_process_options.rotation_range, scale_range=sample_process_options.scale_range, tx_range=sample_process_options.tx_range, ty_range=sample_process_options.ty_range )
  File "C:\Users\dexxt\Desktop\DeepFake\DeepFaceLab_CUDA_10.1_AVX\_internal\DeepFaceLab\imagelib\warp.py", line 8, in gen_warp_params
    raise ValueError ('gen_warp_params accepts only square images.')
ValueError: gen_warp_params accepts only square images.

**Comment by blanuk** [comment]
read the tutorials step by step. 
gen_warp_params accepts only square images <-- sounds like u did some crap with your training images...
