### ISSUE TITLE
Error when running on colab 

### ISSUE THREAD

**Issue by dalasjoe** [iperov/DeepFaceLab#497]
/content
Running converter.

Loading model...
Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

**Comment by TooMuchFun** [comment]
Make sure you are executing DFP on a GPU runtime instance. In the Notebook go to the menu **Runtime** --> **Change runtime type**. Select **GPU** in that menu and the VM will restart. Also be sure to install dependencies with **requirements-colab.txt** .

**Comment by TooMuchFun** [comment]
I found fix, colab has updated CUDA version. I do not know what they changed but if you run `apt install cuda=10.0.130-1` it will work again. Someone on the forum found out this.

**Comment by justinjohn0306** [comment]
It's fixed now
