### ISSUE TITLE
How i fix this Error?

### ISSUE THREAD

**Issue by GitHub-23666** [iperov/DeepFaceLab#500]
How i fix this Error?
 
1. Downloaded File "DeepFaceLab_CUDA_10.1_AVX_build_11_14_2019.exe"
2. extracted to c:\
3. run "2) extract images from video data_src.bat"
4. THIS ERROR :(

```
Traceback (most recent call last):
  File "C:\DeepFaceLab_CUDA_10.1_AVX\_internal\DeepFaceLab\main.py", line 302, in <module>
    arguments.func(arguments)
  File "C:\DeepFaceLab_CUDA_10.1_AVX\_internal\DeepFaceLab\main.py", line 207, in process_videoed_extract_video
    from mainscripts import VideoEd
  File "C:\DeepFaceLab_CUDA_10.1_AVX\_internal\DeepFaceLab\mainscripts\VideoEd.py", line 6, in <module>
    from interact import interact as io
  File "C:\DeepFaceLab_CUDA_10.1_AVX\_internal\DeepFaceLab\interact\__init__.py", line 1, in <module>
    from .interact import interact
  File "C:\DeepFaceLab_CUDA_10.1_AVX\_internal\DeepFaceLab\interact\interact.py", line 7, in <module>
    import cv2
  File "C:\DeepFaceLab_CUDA_10.1_AVX\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
Drücken Sie eine beliebige Taste . . .
```

OS: Windows 10 Pro 1909
CPU: Intel Core i7 4790K Haswell
Graphics Card: Nvidia GeForce GTX 970 | 4096 MB | Driver 441.22
RAM: 32 GB

**Comment by iperov** [comment]
try 9.2

**Comment by maximefalardeau** [comment]
Worked for me thanks.
