### ISSUE TITLE
SAEHD throws ValueError when using 'true face'

### ISSUE THREAD

**Issue by HateKudson** [iperov/DeepFaceLab#508]
First of all, thanks for the great work!!
(running on colab - also tried with older Version 176pix attempt works fine on both, 200pix doesn't)
When i train with 176pixel and dims 256/21 training with 'true face' works fine.

But when i train with 200pix and dims 320/24 it throws the following Error:

Traceback (most recent call last):
  File "/content/DeepFaceLab/mainscripts/Trainer.py", line 50, in trainerThread
    device_args=device_args)
  File "/content/DeepFaceLab/models/ModelBase.py", line 164, in __init__
    self.onInitialize()
  File "/content/DeepFaceLab/models/Model_SAEHD/Model.py", line 428, in onInitialize
    loaded, not_loaded = self.load_weights_safe(not_loaded)
  File "/content/DeepFaceLab/models/ModelBase.py", line 442, in load_weights_safe
    model.load_weights(filename)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 1058, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 2465, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py", line 1762, in assign
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/state_ops.py", line 223, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 4 and 256. Shapes are [4,4,320,256] and [256,256,4,4]. for 'Assign_118' (op: 'Assign') with input shapes: [4,4,320,256], [256,256,4,4].

**Comment by TooMuchFun** [comment]
This is weird and sometimes issues like this has cropped up for me too. I don't have a solution but try this using different facesets and if you get the error. I do know is that these small changes in dimensions (+/50px) isnt going to cause ne major diference, and def does not pay off compared to slower train time.

**Comment by HateKudson** [comment]
Thanks for the reply. 
I just wanted to play around and see how big the differences (time, quality etc) are. I will give it a try with another faceset.

**Comment by HateKudson** [comment]
I've found the issue:

had to change line 428 in 'models/Model_SAEHD/Model.py'

from:    loaded, not_loaded = self.load_weights_safe(**not_loaded**)
 to:       loaded, not_loaded = self.load_weights_safe(**loaded**)
