### ISSUE TITLE
The OpenCL met "ValueError: cannot convert float NaN to integer" when training times is above 9000

### ISSUE THREAD

**Issue by square690410** [iperov/DeepFaceLab#510]
Using OpenCL always met this problem when training time is higher.
sometime , it can recover by changed to CPU or other OpenCL device.

## Expected behavior

running training without any error.

## Actual behavior

Training will corrupt , preview window is also corrupted.

## Steps to reproduce

Run any training model.

## Other relevant information
INFO:plaidml:Analyzing Ops: 704 of 1524 operations complete
[11:03:08][#009219][1053ms][0.2637][0.1904]
Traceback (most recent call last):an]an]08]
  File "C:\Users\Leon\Downloads\DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\main.py", line 302, in <module>
    arguments.func(arguments)
  File "C:\Users\Leon\Downloads\DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\main.py", line 162, in process_train
    Trainer.main(args, device_args)
  File "C:\Users\Leon\Downloads\DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 288, in main
    lh_img = models.ModelBase.get_loss_history_preview(loss_history_to_show, iter, w, c)
  File "C:\Users\Leon\Downloads\DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\models\ModelBase.py", line 649, in get_loss_history_preview
    ph_max = int ( (plist_max[col][p] / plist_abs_max) * (lh_height-1) )
ValueError: cannot convert float NaN to integer
[11:18:11][#010042][1076ms][nan][nan]

**Comment by square690410** [comment]
Issue is gone after "Enable autobackup" and "Use lightweight autoencoder"
