### ISSUE TITLE
Training isn't working, but it used to work. Why?

### ISSUE THREAD

**Issue by Jamie1605** [iperov/DeepFaceLab#518]
I used to use DeepFaceLab and it worked perfectly fine. Yesterday I wanted to try it again, I installed DeepFaceLab, Cuda and CuDNN. But now when I try to train (I tried every way, H64, Sae, ... etc.), theres this Error:

Running trainer.

Loading model...

Model first run. Enter model options as default for each run.
Enable autobackup? (y/n ?:help skip:n) : y
Write preview history? (y/n ?:help skip:n) :
n
Target iteration (skip:unlimited/default) :
0
Batch_size (?:help skip:0) : 1
Feed faces to network sorted by yaw? (y/n ?:help skip:n) :
n
Flip faces randomly? (y/n ?:help skip:y) :
y
Src face scale modifier % ( -30...30, ?:help skip:0) :
0
Use lightweight autoencoder? (y/n, ?:help skip:n) :
n
Use pixel loss? (y/n, ?:help skip: n/default ) :
n
Using TensorFlow backend.
Loading: 100%|####################################################################| 5409/5409 [00:12<00:00, 425.83it/s]
Loading: 100%|######################################################################| 356/356 [00:00<00:00, 439.23it/s]
============= Model Summary =============
==                                     ==
==        Model name: H64              ==
==                                     ==
== Current iteration: 0                ==
==                                     ==
==----------- Model Options -----------==
==                                     ==
==        autobackup: True             ==
==       sort_by_yaw: False            ==
==       random_flip: True             ==
==        lighter_ae: False            ==
==        pixel_loss: False            ==
==        batch_size: 1                ==
==                                     ==
==------------ Running On -------------==
==                                     ==
==      Device index: 0                ==
==              Name: GeForce GTX 1050 ==
==              VRAM: 2.00GB           ==
==                                     ==
=========================================
/!\
/!\ WARNING:
/!\ You are using a GPU with 2GB or less VRAM. This may significantly reduce the quality of your result!
/!\ If training does not start, close all programs and try again.
/!\ Also you can disable Windows Aero Desktop to increase available VRAM.
/!\
Starting. Press "Enter" to stop training and save model.
2019-12-15 12:24:41.106601: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 237.97M (249527808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:24:41.112333: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 214.17M (224575232 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:24:41.118872: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 192.75M (202117888 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:24:41.164972: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 64.49M (67621632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:24:41.169588: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 64.49M (67621632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:24:51.176914: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 64.49M (67621632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:24:51.194472: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 64.49M (67621632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:24:51.210262: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 64.49M (67621632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:24:51.218788: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 64.49M (67621632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:25:01.225303: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 64.49M (67621632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:25:01.238103: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 64.49M (67621632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:25:01.252586: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 64.49M (67621632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:25:01.264183: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 64.49M (67621632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:25:11.271293: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 64.49M (67621632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:25:26.178159: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 64.49M (67621632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:25:26.194196: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 64.49M (67621632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:25:26.202083: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 64.49M (67621632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:25:36.209152: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 64.49M (67621632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:25:36.222070: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 64.49M (67621632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:25:36.228803: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 64.49M (67621632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-15 12:25:36.239554: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 64.49M (67621632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
Error: OOM when allocating tensor with shape[3,3,512,2048] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node training/Adam/Variable_14/Assign (defined at C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py:402)  = Assign[T=DT_FLOAT, _grappler_relax_allocator_constraints=true, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/Variable_14, training/Adam/zeros_14)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'training/Adam/Variable_14/Assign', defined at:
  File "threading.py", line 884, in _bootstrap
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 109, in trainerThread
    iter, iter_time = model.train_one_iter()
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\models\ModelBase.py", line 525, in train_one_iter
    losses = self.onTrainOneIter(sample, self.generator_list)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\models\Model_H64\Model.py", line 89, in onTrainOneIter
    total, loss_src_bgr, loss_src_mask, loss_dst_bgr, loss_dst_mask = self.ae.train_on_batch( [warped_src, target_src_full_mask, warped_dst, target_dst_full_mask], [target_src, target_src_full_mask, target_dst, target_dst_full_mask] )
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\keras\engine\training.py", line 1216, in train_on_batch
    self._make_train_function()
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\keras\engine\training.py", line 509, in _make_train_function
    loss=self.total_loss)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\nnlib\nnlib.py", line 867, in get_updates
    ms = [K.zeros(K.int_shape(p), dtype=K.dtype(p)) for p in params]
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\nnlib\nnlib.py", line 867, in <listcomp>
    ms = [K.zeros(K.int_shape(p), dtype=K.dtype(p)) for p in params]
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 704, in zeros
    return variable(v, dtype=dtype, name=name)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 402, in variable
    v = tf.Variable(value, dtype=tf.as_dtype(dtype), name=name)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 183, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 146, in _variable_v1_call
    aggregation=aggregation)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 125, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2444, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 187, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 1329, in __init__
    constraint=constraint)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 1481, in _init_from_args
    validate_shape=validate_shape).op
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\state_ops.py", line 221, in assign
    validate_shape=validate_shape)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 61, in assign
    use_locking=use_locking, name=name)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[3,3,512,2048] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node training/Adam/Variable_14/Assign (defined at C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py:402)  = Assign[T=DT_FLOAT, _grappler_relax_allocator_constraints=true, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/Variable_14, training/Adam/zeros_14)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Traceback (most recent call last):
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[3,3,512,2048] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node training/Adam/Variable_14/Assign}} = Assign[T=DT_FLOAT, _grappler_relax_allocator_constraints=true, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/Variable_14, training/Adam/zeros_14)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 109, in trainerThread
    iter, iter_time = model.train_one_iter()
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\models\ModelBase.py", line 525, in train_one_iter
    losses = self.onTrainOneIter(sample, self.generator_list)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\models\Model_H64\Model.py", line 89, in onTrainOneIter
    total, loss_src_bgr, loss_src_mask, loss_dst_bgr, loss_dst_mask = self.ae.train_on_batch( [warped_src, target_src_full_mask, warped_dst, target_dst_full_mask], [target_src, target_src_full_mask, target_dst, target_dst_full_mask] )
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2697, in __call__
    if hasattr(get_session(), '_make_callable_from_options'):
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 206, in get_session
    session.run(tf.variables_initializer(uninitialized_vars))
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[3,3,512,2048] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node training/Adam/Variable_14/Assign (defined at C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py:402)  = Assign[T=DT_FLOAT, _grappler_relax_allocator_constraints=true, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/Variable_14, training/Adam/zeros_14)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'training/Adam/Variable_14/Assign', defined at:
  File "threading.py", line 884, in _bootstrap
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 109, in trainerThread
    iter, iter_time = model.train_one_iter()
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\models\ModelBase.py", line 525, in train_one_iter
    losses = self.onTrainOneIter(sample, self.generator_list)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\models\Model_H64\Model.py", line 89, in onTrainOneIter
    total, loss_src_bgr, loss_src_mask, loss_dst_bgr, loss_dst_mask = self.ae.train_on_batch( [warped_src, target_src_full_mask, warped_dst, target_dst_full_mask], [target_src, target_src_full_mask, target_dst, target_dst_full_mask] )
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\keras\engine\training.py", line 1216, in train_on_batch
    self._make_train_function()
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\keras\engine\training.py", line 509, in _make_train_function
    loss=self.total_loss)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\nnlib\nnlib.py", line 867, in get_updates
    ms = [K.zeros(K.int_shape(p), dtype=K.dtype(p)) for p in params]
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\nnlib\nnlib.py", line 867, in <listcomp>
    ms = [K.zeros(K.int_shape(p), dtype=K.dtype(p)) for p in params]
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 704, in zeros
    return variable(v, dtype=dtype, name=name)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 402, in variable
    v = tf.Variable(value, dtype=tf.as_dtype(dtype), name=name)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 183, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 146, in _variable_v1_call
    aggregation=aggregation)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 125, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2444, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 187, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 1329, in __init__
    constraint=constraint)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 1481, in _init_from_args
    validate_shape=validate_shape).op
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\state_ops.py", line 221, in assign
    validate_shape=validate_shape)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 61, in assign
    use_locking=use_locking, name=name)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[3,3,512,2048] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node training/Adam/Variable_14/Assign (defined at C:\Users\jamie\Desktop\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py:402)  = Assign[T=DT_FLOAT, _grappler_relax_allocator_constraints=true, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/Variable_14, training/Adam/zeros_14)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

 What could I have done wrong? It can't be the VRAM because, it used to work, with the same PC, as I said.

- Windows 10
- I'm using the prebuilt version.

**Comment by TooMuchFun** [comment]
Yes it is the VRAM. Sorry 2GB is not enough for stable DFL use.
