### ISSUE TITLE
Win Prebuild doesn't working

### ISSUE THREAD

**Issue by Dev1lroot** [iperov/DeepFaceLab#520]
Win10 x64 1903 Nvidia GTX 1080 / Stage 3

Exception: Traceback (most recent call last):
  File "J:\DeepFaceLab\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "J:\DeepFaceLab\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "J:\DeepFaceLab\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "J:\DeepFaceLab\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\joblib\SubprocessorBase.py", line 59, in _subprocess_run
    self.on_initialize(client_dict)
  File "J:\DeepFaceLab\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\mainscripts\Extractor.py", line 87, in on_initialize
    nnlib.import_all (device_config)
  File "J:\DeepFaceLab\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\nnlib\nnlib.py", line 1160, in import_all
    nnlib.import_keras(device_config)
  File "J:\DeepFaceLab\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\nnlib\nnlib.py", line 181, in import_keras
    nnlib._import_tf(device_config)
  File "J:\DeepFaceLab\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\nnlib\nnlib.py", line 153, in _import_tf
    import tensorflow as tf
  File "J:\DeepFaceLab\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "J:\DeepFaceLab\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "J:\DeepFaceLab\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "J:\DeepFaceLab\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "J:\DeepFaceLab\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "J:\DeepFaceLab\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: The specified procedure could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by Dev1lroot** [comment]
Works only OpenCL edition, no CUDA support

**Comment by iperov** [comment]
uninstall cuda from system, if installed.
update geforce drivers
