### ISSUE TITLE
Failing to perform "data_src faceset extract"

### ISSUE THREAD

**Issue by adam-eme** [iperov/DeepFaceLab#5203]
Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce GTX 960M

[0] Which GPU indexes to choose? :
0

[wf] Face type ( f/wf/head ?:help ) :
wf
[0] Max number of faces from image ( ?:help ) :
0
[512] Image size ( 256-2048 ?:help ) :
512
[90] Jpeg quality ( 1-100 ?:help ) :
90
[n] Write debug images to aligned_debug? ( y/n ) :
n
Extracting faces...
Caching GPU kernels...
Error while subprocess initialization: Traceback (most recent call last):
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 62, in _subprocess_run
    self.on_initialize(client_dict)
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\Extractor.py", line 68, in on_initialize
    nn.initialize (device_config)
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\nn.py", line 81, in initialize
    import tensorflow.compat.v1 as tf
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    self_check.preload_check()
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\platform\self_check.py", line 61, in preload_check
    % " or ".join(missing))
ImportError: Could not find the DLL(s) 'msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads

Traceback (most recent call last):
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\main.py", line 324, in <module>
    arguments.func(arguments)
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\main.py", line 45, in process_extract
    force_gpu_idxs          = [ int(x) for x in arguments.force_gpu_idxs.split(',') ] if arguments.force_gpu_idxs is not None else None,
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\Extractor.py", line 853, in main
    device_config=device_config).run()
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 210, in run
    raise Exception ( "Unable to start subprocesses." )
Exception: Unable to start subprocesses.

**Comment by robustini** [comment]
The error clearly writes it to you, you need to install this: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads

**Comment by iperov** [comment]
download last deepfacelab build

**Comment by iperov** [comment]
DeepFaceLab_NVIDIA_RTX3000_series is outdated build
