### ISSUE TITLE
Fehler beim Ausführen des "Faceset-Extrakts" please Help

### ISSUE THREAD

**Issue by Achimdv** [iperov/DeepFaceLab#5206]
The program worked great for 1 year, but since yesterday it has been showing me this problem. Please help.
Thank you Achim

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce GTX 1060 6GB

[0] Which GPU indexes to choose? :
0

[wf] Face type ( f/wf/head ?:help ) :
wf
[512] Image size ( 256-2048 ?:help ) :
512
[90] Jpeg quality ( 1-100 ?:help ) :
90
Extracting faces...
Caching GPU kernels...
Error while subprocess initialization: Traceback (most recent call last):
  File "C:\Users\..........\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 62, in _subprocess_run
    self.on_initialize(client_dict)
  File "C:\Users\.............\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Extractor.py", line 68, in on_initialize
    nn.initialize (device_config)
  File "C:\Users\.................\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\nn.py", line 113, in initialize
    nn.tf_sess = tf.Session(config=nn.tf_sess_config)
  File "C:\Users\.................\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1596, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "C:\Users\...............Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 711, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: initialization error

Traceback (most recent call last):
  File "C:\Users\...................\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 324, in <module>
    arguments.func(arguments)
  File "C:\Users\................\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 45, in process_extract
    force_gpu_idxs          = [ int(x) for x in arguments.force_gpu_idxs.split(',') ] if arguments.force_gpu_idxs is not None else None,
  File "C:\Users\.................\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Extractor.py", line 853, in main
    device_config=device_config).run()
  File "C:\Users\.................\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 210, in run
    raise Exception ( "Unable to start subprocesses." )
Exception: Unable to start subprocesses.
Drücken Sie eine beliebige Taste . . .

**Comment by iperov** [comment]
update geforce drivers
set paging file to 8gb

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
