### ISSUE TITLE
XSeg training GPU unavailable

### ISSUE THREAD

**Issue by 1over137** [iperov/DeepFaceLab#5214]
## Expected behavior
It should be able to use GPU for training.

## Actual behavior
```Press enter in 2 seconds to override model settings.Error: Cannot assign a device for operation XSeg/conv01/conv/weight: node XSeg/conv01/conv/weight (defined at /code/DeepFaceLab_Linux/DeepFaceLab/core/leras/layers/Conv2D.py:76)  was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[XSeg/conv01/conv/weight]]
Traceback (most recent call last):
  File "/home/shaoyu/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/home/shaoyu/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1358, in _run_fn
    self._extend_graph()
  File "/home/shaoyu/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1398, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation XSeg/conv01/conv/weight: {{node XSeg/conv01/conv/weight}} was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[XSeg/conv01/conv/weight]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shaoyu/code/DeepFaceLab_Linux/DeepFaceLab/mainscripts/Trainer.py", line 58, in trainerThread
    debug=debug,
  File "/home/shaoyu/code/DeepFaceLab_Linux/DeepFaceLab/models/Model_XSeg/Model.py", line 17, in __init__
    super().__init__(*args, force_model_class_name='XSeg', **kwargs)
  File "/home/shaoyu/code/DeepFaceLab_Linux/DeepFaceLab/models/ModelBase.py", line 189, in __init__
    self.on_initialize()
  File "/home/shaoyu/code/DeepFaceLab_Linux/DeepFaceLab/models/Model_XSeg/Model.py", line 68, in on_initialize
    data_format=nn.data_format)
  File "/home/shaoyu/code/DeepFaceLab_Linux/DeepFaceLab/facelib/XSegNet.py", line 79, in __init__
    model.init_weights()
  File "/home/shaoyu/code/DeepFaceLab_Linux/DeepFaceLab/core/leras/layers/Saveable.py", line 104, in init_weights
    nn.init_weights(self.get_weights())
  File "/home/shaoyu/code/DeepFaceLab_Linux/DeepFaceLab/core/leras/ops/__init__.py", line 48, in init_weights
    nn.tf_sess.run (ops)
  File "/home/shaoyu/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 968, in run
    run_metadata_ptr)
  File "/home/shaoyu/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/shaoyu/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1369, in _do_run
    run_metadata)
  File "/home/shaoyu/.conda/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation XSeg/conv01/conv/weight: node XSeg/conv01/conv/weight (defined at /code/DeepFaceLab_Linux/DeepFaceLab/core/leras/layers/Conv2D.py:76)  was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[XSeg/conv01/conv/weight]]
```
## Steps to reproduce
Follow the instructions to go through the process, and start training XSeg model.
## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:**  Linux 
- **Python version:** 3.7

**Comment by iperov** [comment]
I don't support linux.

**Comment by nagadit** [comment]
@1over137 Hi! 
I have updated versions CUDNN and Cuda for TF 2.4. 
[Check this out.](https://github.com/nagadit/DeepFaceLab_Linux/blob/master/README.md#3-install-deepfacelab)

**Comment by robustini** [comment]
> @1over137 Hi!
> I have updated versions CUDNN and Cuda for TF 2.4.
> [Check this out.](https://github.com/nagadit/DeepFaceLab_Linux/blob/master/README.md#3-install-deepfacelab)

(base) marco@ubuntu:~$ conda create -n deepfacelab -c main python=3.8 cudnn=8.0.5 cudatoolkit=11.2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - cudnn=8.0.5
  - cudatoolkit=11.2

**Comment by robustini** [comment]
Just for test this version are found and installed:

conda create -y -n deepfacelab python=3.6.6 cudatoolkit=9.0 cudnn=7.3.1

**Comment by nagadit** [comment]
I'm now solving the problem of how you can install cuda packages in the Conda without touching the system packages.

**Comment by robustini** [comment]
> I'm now solving the problem of how you can install cuda packages in the Conda without touching the system packages.

Have you news abou that?

**Comment by robustini** [comment]
> I'm now solving the problem of how you can install cuda packages in the Conda without touching the system packages.

Have you news about that?

**Comment by ghost** [comment]
Did you ever find the answer?
