### ISSUE TITLE
Memory ERROR  ( SAEHD + RTX 3080 PLS HELP )

### ISSUE THREAD

**Issue by szdtv** [iperov/DeepFaceLab#5217]
Running trainer.

[new] No saved models found. Enter a name of a new model :
new

Model first run.

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce RTX 3080

[0] Which GPU indexes to choose? : 0
0

Caching GPU kernels...
[0] Autobackup every N hour ( 0..24 ?:help ) :
0
[n] Write preview history ( y/n ?:help ) :
n
[0] Target iteration :
0
[y] Flip faces randomly ( y/n ?:help ) :
y
[8] Batch_size ( ?:help ) :
8
[128] Resolution ( 64-640 ?:help ) : 64
64
[f] Face type ( h/mf/f/wf/head ?:help ) :
f
[liae-ud] AE architecture ( ?:help ) :
liae-ud
[256] AutoEncoder dimensions ( 32-1024 ?:help ) :
256
[64] Encoder dimensions ( 16-256 ?:help ) :
64
[64] Decoder dimensions ( 16-256 ?:help ) :
64
[22] Decoder mask dimensions ( 16-256 ?:help ) :
22
[n] Eyes and mouth priority ( y/n ?:help ) :
n
[n] Uniform yaw distribution of samples ( y/n ?:help ) :
n
[y] Place models and optimizer on GPU ( y/n ?:help ) :
y
[y] Use AdaBelief optimizer? ( y/n ?:help ) :
y
[n] Use learning rate dropout ( n/y/cpu ?:help ) :
n
[y] Enable random warp of samples ( y/n ?:help ) :
y
[0.0] GAN power ( 0.0 .. 10.0 ?:help ) :
0.0
[0.0] Face style power ( 0.0..100.0 ?:help ) :
0.0
[0.0] Background style power ( 0.0..100.0 ?:help ) :
0.0
[none] Color transfer for src faceset ( none/rct/lct/mkl/idt/sot ?:help ) :
none
[n] Enable gradient clipping ( y/n ?:help ) :
n
[n] Enable pretraining mode ( y/n ?:help ) :
n
Initializing models:  60%|#####################################8                         | 3/5 [00:09<00:06,  3.07s/it]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
  File "multiprocessing\spawn.py", line 115, in _main
  File "<string>", line 1, in <module>
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
    from tensorflow.python.ops import init_ops
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 55, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
    from ._api.v2 import compat
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\__init__.py", line 39, in <module>
    from tensorflow.python.ops import init_ops
    from . import v1  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 55, in <module>

      File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v1\__init__.py", line 34, in <module>
from ._api.v2 import compat
from . import compat  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\__init__.py", line 39, in <module>

      File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v1\compat\__init__.py", line 40, in <module>
from . import v1
from . import v2  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v1\__init__.py", line 34, in <module>

      File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v1\compat\v2\__init__.py", line 32, in <module>
from . import compat
      File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v1\compat\__init__.py", line 40, in <module>
from tensorflow._api.v2.compat.v2 import __internal__
from . import v2  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\__init__.py", line 37, in <module>

      File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v1\compat\v2\__init__.py", line 32, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
from . import compat      File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>

from tensorflow._api.v2.compat.v2 import __internal__  File "multiprocessing\spawn.py", line 105, in spawn_main

  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\compat\__init__.py", line 40, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\__init__.py", line 37, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
      File "multiprocessing\spawn.py", line 115, in _main
from . import v2      File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>

from . import compat              File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\compat\v2\__init__.py", line 331, in <module>

from tensorflow.python.ops import init_opsfrom tensorflow.python.ops import init_opsfrom tensorflow.python.ops import init_ops  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\compat\__init__.py", line 39, in <module>

    from tensorboard.summary._tf import summary  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 55, in <module>
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 55, in <module>
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 55, in <module>
from . import v1
        from ._api.v2 import compat
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorboard\summary\__init__.py", line 25, in <module>
    from ._api.v2 import compat
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    from ._api.v2 import compat
from tensorboard.summary import v1  # noqa: F401  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\__init__.py", line 39, in <module>

  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\__init__.py", line 39, in <module>

  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 674, in exec_module
from . import v1  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorboard\summary\v1.py", line 26, in <module>
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\__init__.py", line 39, in <module>
      File "<frozen importlib._bootstrap_external>", line 764, in get_code

        from . import v1  File "<frozen importlib._bootstrap_external>", line 833, in get_data
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v1\__init__.py", line 34, in <module>
from tensorboard.plugins.histogram import summary as _histogram_summaryfrom . import v1
MemoryError

  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v1\__init__.py", line 34, in <module>

from . import compat  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorboard\plugins\histogram\summary.py", line 38, in <module>
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v1\__init__.py", line 34, in <module>

        from . import compat  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v1\compat\__init__.py", line 40, in <module>
from tensorboard.plugins.histogram import summary_v2from . import compat

  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorboard\plugins\histogram\summary_v2.py", line 38, in <module>
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v1\compat\__init__.py", line 40, in <module>
from . import v2  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v1\compat\__init__.py", line 40, in <module>

    from tensorboard.util import tensor_utilfrom . import v2  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v1\compat\v2\__init__.py", line 32, in <module>

from . import v2      File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorboard\util\tensor_util.py", line 24, in <module>
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v1\compat\v2\__init__.py", line 32, in <module>

from tensorflow._api.v2.compat.v2 import __internal__          File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v1\compat\v2\__init__.py", line 32, in <module>

from tensorboard.compat.tensorflow_stub import dtypes, compat, tensor_shapefrom tensorflow._api.v2.compat.v2 import __internal__      File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\__init__.py", line 37, in <module>

from tensorflow._api.v2.compat.v2 import __internal__      File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorboard\compat\tensorflow_stub\__init__.py", line 25, in <module>
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\__init__.py", line 37, in <module>

from . import compat          File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\__init__.py", line 37, in <module>

from .dtypes import as_dtype  # noqafrom . import compat      File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\compat\__init__.py", line 40, in <module>

from . import compat      File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py", line 22, in <module>
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\compat\__init__.py", line 40, in <module>

from . import v2          File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\compat\__init__.py", line 40, in <module>

from . import pywrap_tensorflowfrom . import v2      File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\compat\v2\__init__.py", line 41, in <module>
from . import v2

      File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\compat\v2\__init__.py", line 41, in <module>
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorboard\compat\tensorflow_stub\pywrap_tensorflow.py", line 25, in <module>
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\compat\v2\__init__.py", line 41, in <module>
from tensorflow._api.v2.compat.v2 import distribute
from tensorflow._api.v2.compat.v2 import distributefrom .io import gfilefrom tensorflow._api.v2.compat.v2 import distribute  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\distribute\__init__.py", line 180, in <module>

  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\distribute\__init__.py", line 180, in <module>
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorboard\compat\tensorflow_stub\io\__init__.py", line 20, in <module>
      File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\distribute\__init__.py", line 180, in <module>
    from . import experimental
from . import experimental  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\distribute\experimental\__init__.py", line 10, in <module>
from . import gfile  # noqa

  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\distribute\experimental\__init__.py", line 10, in <module>
from . import experimentalfrom . import coordinator  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 82, in <module>

    from . import coordinator  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\distribute\experimental\__init__.py", line 10, in <module>
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\distribute\experimental\coordinator\__init__.py", line 10, in <module>
StatData = namedtuple("StatData", ["length"])

          File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\distribute\experimental\coordinator\__init__.py", line 10, in <module>
  File "collections\__init__.py", line 429, in namedtuple
from tensorflow.python.distribute.coordinator.cluster_coordinator import ClusterCoordinatorfrom . import coordinator    MemoryError

from tensorflow.python.distribute.coordinator.cluster_coordinator import ClusterCoordinator
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "F:\OYUN\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v2\compat\v2\distribute\experimental\coordinator\__init__.py", line 10, in <module>

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
from tensorflow.python.distribute.coordinator.cluster_coordinator import ClusterCoordinator  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap_external>", line 833, in get_data
  File "<frozen importlib._bootstrap_external>", line 771, in get_code
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
MemoryError  File "<frozen importlib._bootstrap_external>", line 482, in _validate_bytecode_header

  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
MemoryError  File "<frozen importlib._bootstrap_external>", line 674, in exec_module

  File "<frozen importlib._bootstrap_external>", line 771, in get_code
  File "<frozen importlib._bootstrap_external>", line 482, in _validate_bytecode_header
MemoryError

**Comment by robustini** [comment]
Quick96 training work or not?

**Comment by cyber-douglas** [comment]
Hi,

Same problem here when I try an XSeg train, with my rtx2080Ti (using the rtx2080Ti build released on the 01-04-2021, same issue with end-december builds, work only with the 12-12-2020 build).

```
Running trainer.


Model first run.

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce RTX 2080 Ti

[0] Which GPU indexes to choose? :
0

[wf] Face type ( h/mf/f/wf/head ?:help ) :
wf
[4] Batch_size ( 2-16 ?:help ) :
4
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 115, in _main
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
    from tensorflow.python.ops import init_ops
      File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 29, in <module>
from tensorflow.python.ops import init_ops
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 29, in <module>
        from tensorflow._api.v1 import compatfrom tensorflow._api.v1 import compat

  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v1\compat\__init__.py", line 21, in <module>
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v1\compat\__init__.py", line 21, in <module>
        from tensorflow._api.v1.compat import v1from tensorflow._api.v1.compat import v1

  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v1\compat\v1\__init__.py", line 626, in <module>
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v1\compat\v1\__init__.py", line 626, in <module>
    child_package_str=('tensorflow_estimator.python.estimator.api.estimator'))
child_package_str=('tensorflow_estimator.python.estimator.api.estimator'))  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow\python\tools\component_api_helper.py", line 56, in package_hook

  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow\python\tools\component_api_helper.py", line 56, in package_hook
        child_pkg = importlib.import_module(child_package_str)child_pkg = importlib.import_module(child_package_str)

  File "importlib\__init__.py", line 126, in import_module
  File "importlib\__init__.py", line 126, in import_module
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow_estimator\__init__.py", line 8, in <module>
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow_estimator\__init__.py", line 8, in <module>
        from tensorflow_estimator._api.v1 import estimatorfrom tensorflow_estimator._api.v1 import estimator

  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow_estimator\_api\v1\estimator\__init__.py", line 8, in <module>
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow_estimator\_api\v1\estimator\__init__.py", line 8, in <module>
        from tensorflow_estimator._api.v1.estimator import experimentalfrom tensorflow_estimator._api.v1.estimator import experimental

  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow_estimator\_api\v1\estimator\experimental\__init__.py", line 8, in <module>
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow_estimator\_api\v1\estimator\experimental\__init__.py", line 8, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
    from tensorflow.python.ops import init_ops
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 29, in <module>
    from tensorflow._api.v1 import compat
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v1\compat\__init__.py", line 21, in <module>
    from tensorflow._api.v1.compat import v1
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow\_api\v1\compat\v1\__init__.py", line 626, in <module>
    child_package_str=('tensorflow_estimator.python.estimator.api.estimator'))
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow\python\tools\component_api_helper.py", line 56, in package_hook
    child_pkg = importlib.import_module(child_package_str)
  File "importlib\__init__.py", line 126, in import_module
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow_estimator\__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow_estimator\_api\v1\estimator\__init__.py", line 8, in <module>
        from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builderfrom tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder

      File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow_estimator\python\estimator\__init__.py", line 25, in <module>
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow_estimator\python\estimator\__init__.py", line 25, in <module>
from tensorflow_estimator._api.v1.estimator import experimental
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow_estimator\_api\v1\estimator\experimental\__init__.py", line 8, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow_estimator\python\estimator\__init__.py", line 25, in <module>
            import tensorflow_estimator.python.estimator.estimator_libimport tensorflow_estimator.python.estimator.estimator_libimport tensorflow_estimator.python.estimator.estimator_lib


  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow_estimator\python\estimator\estimator_lib.py", line 25, in <module>
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow_estimator\python\estimator\estimator_lib.py", line 31, in <module>
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow_estimator\python\estimator\estimator_lib.py", line 25, in <module>
            from tensorflow_estimator.python.estimator.canned.boosted_trees import BoostedTreesClassifierfrom tensorflow_estimator.python.estimator.canned.dnn_linear_combined import DNNLinearCombinedClassifierfrom tensorflow_estimator.python.estimator.canned.boosted_trees import BoostedTreesClassifier


  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "D:\DeepFaceLab\DFL_rtx2080Ti_build_2021_01_04\_internal\python-3.6.8\lib\site-packages\tensorflow_estimator\python\estimator\canned\dnn_linear_combined.py", line 39, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 771, in get_code
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 482, in _validate_bytecode_header
  File "<frozen importlib._bootstrap_external>", line 833, in get_data
MemoryError
MemoryError
    from tensorflow_estimator.python.estimator.canned import linear
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 771, in get_code
  File "<frozen importlib._bootstrap_external>", line 482, in _validate_bytecode_header
MemoryError
```

This error appears also if using the given test data_src and data_dst movies.
I tried to increase the system pagefile up to 50Go but it doesn't solve the problem.
Any idea ?

Many thanks

**Comment by KobyDeuel** [comment]
Have you guys fixed this issue? I am getting it too

**Comment by rylyguy** [comment]
I'm experiencing this all of a sudden also.

**Comment by WelschCode** [comment]
I'm having this only when using GAN

**Comment by ghost** [comment]
Did you ever find the answer?
