### ISSUE TITLE
 Xseg Edit is not working.

### ISSUE THREAD

**Issue by pakasary70** [iperov/DeepFaceLab#5223]
I'm sorry for my poor English.
The laptop was shut down during the xseg (trained mask - apply).

I receive when trying to run either XSeg) data_src mask - edit.bat

Running XSeg editor.
Traceback (most recent call last):
  File "E:\DeepFaceLab_NVIDIA_build_08_02_2020 CC 3.0 SSE last build\_internal\DeepFaceLab\main.py", line 324, in <module>
    arguments.func(arguments)
  File "E:\DeepFaceLab_NVIDIA_build_08_02_2020 CC 3.0 SSE last build\_internal\DeepFaceLab\main.py", line 274, in process_xsegeditor
    exit_code = XSegEditor.start (Path(arguments.input_dir))
  File "E:\DeepFaceLab_NVIDIA_build_08_02_2020 CC 3.0 SSE last build\_internal\DeepFaceLab\XSegEditor\XSegEditor.py", line 1460, in start
    win = MainWindow( input_dirpath=input_dirpath, cfg_root_path=cfg_root_path)
  File "E:\DeepFaceLab_NVIDIA_build_08_02_2020 CC 3.0 SSE last build\_internal\DeepFaceLab\XSegEditor\XSegEditor.py", line 1170, in __init__
    self.cfg_dict = pickle.loads(self.cfg_path.read_bytes()) if self.cfg_path.exists() else {}
_pickle.UnpicklingError: invalid load key, '\x00'.
Press any key to continue . . .

What is problem Solving?

DFL Version : DeepFaceLab_NVIDIA_build_08_02_2020 CC 3.0 SSE last build
My PC : Window 10, NVIDIA 1060 6GB (Driver 460.89) RAM 22GB

**Comment by iperov** [comment]
model files are broken. Retrain from scratch.
