### ISSUE TITLE
something wrong with step 4(data_src faceset extract.bat), has anyone encountered it

### ISSUE THREAD

**Issue by lockontan** [iperov/DeepFaceLab#5224]
Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
     [0] : GeForce GTX 750 Ti

[0] Which GPU indexes to choose? : 0
0

[wf] Face type ( f/wf/head ?:help ) :
wf
[0] Max number of faces from image ( ?:help ) :
0
[512] Image size ( 256-2048 ?:help ) :
512
[90] Jpeg quality ( 1-100 ?:help ) :
90
[n] Write debug images to aligned_debug? ( y/n ) :
n
Extracting faces...
Caching GPU kernels...
Error while subprocess initialization: Traceback (most recent call last):
  File "F:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 62, in _subprocess_run
    self.on_initialize(client_dict)
  File "F:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Extractor.py", line 68, in on_initialize
    nn.initialize (device_config)
  File "F:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\nn.py", line 113, in initialize
    nn.tf_sess = tf.Session(config=nn.tf_sess_config)
  File "F:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1596,
in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "F:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 711, i
n __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: initialization error

Traceback (most recent call last):
  File "F:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 324, in <module>
    arguments.func(arguments)
  File "F:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 45, in process_extract
    force_gpu_idxs          = [ int(x) for x in arguments.force_gpu_idxs.split(',') ] if arguments.force_gpu_idxs is not
 None else None,
  File "F:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Extractor.py", line 853, in main
    device_config=device_config).run()
  File "F:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 210, in run
    raise Exception ( "Unable to start subprocesses." )
Exception: Unable to start subprocesses.

**Comment by iperov** [comment]
try build for 2080ti and earlier https://mega.nz/folder/Po0nGQrA#dbbttiNWojCt8jzD4xYaPw

**Comment by lockontan** [comment]
> try build for 2080ti and earlier https://mega.nz/folder/Po0nGQrA#dbbttiNWojCt8jzD4xYaPw

thanks, it worked
