### ISSUE TITLE
Issue during running 6) train SAEHD.bat

### ISSUE THREAD

**Issue by gyloh9210** [iperov/DeepFaceLab#5235]
Hi guys, I have ran into this issue during running 6) train SAEHD.bat. Please help me. Im using DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier btw.

```
=============== Model Summary ===============
==                                         ==
==            Model name: new_SAEHD        ==
==                                         ==
==     Current iteration: 0                ==
==                                         ==
==------------- Model Options -------------==
==                                         ==
==            resolution: 128              ==
==             face_type: wf               ==
==     models_opt_on_gpu: True             ==
==                 archi: liae-ud          ==
==               ae_dims: 256              ==
==                e_dims: 64               ==
==                d_dims: 64               ==
==           d_mask_dims: 22               ==
==       masked_training: True             ==
==       eyes_mouth_prio: False            ==
==           uniform_yaw: False            ==
==             adabelief: True             ==
==            lr_dropout: n                ==
==           random_warp: True             ==
==       true_face_power: 0.0              ==
==      face_style_power: 0.0              ==
==        bg_style_power: 0.0              ==
==               ct_mode: none             ==
==              clipgrad: False            ==
==              pretrain: False            ==
==       autobackup_hour: 0                ==
== write_preview_history: False            ==
==           target_iter: 0                ==
==           random_flip: True             ==
==            batch_size: 8                ==
==             gan_power: 0.0              ==
==        gan_patch_size: 16               ==
==              gan_dims: 16               ==
==                                         ==
==-------------- Running On ---------------==
==                                         ==
==          Device index: 0                ==
==                  Name: GeForce GTX 1650 ==
==                  VRAM: 4.00GB           ==
==                                         ==
=============================================
Starting. Press "Enter" to stop training and save model.

Trying to do the first iteration. If an error occurs, reduce the model parameters.

!!!
Windows 10 users IMPORTANT notice. You should set this setting in order to work correctly.
https://i.imgur.com/B7cmDCB.jpg
!!!
You are training the model from scratch. It is strongly recommended to use a pretrained model to speed up the training and improve the quality.

Error: OOM when allocating tensor with shape[8,128,64,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node LeakyRelu_18 (defined at C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\leras\archis\DeepFakeArchi.py:69) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[node concat_40 (defined at C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\models\Model_SAEHD\Model.py:517) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Caused by op 'LeakyRelu_18', defined at:
  File "threading.py", line 884, in _bootstrap
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\mainscripts\Trainer.py", line 58, in trainerThread
    debug=debug,
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\models\ModelBase.py", line 189, in __init__
    self.on_initialize()
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 381, in on_initialize
    gpu_pred_src_src, gpu_pred_src_srcm = self.decoder(gpu_src_code)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\leras\models\ModelBase.py", line 117, in __call__
    return self.forward(*args, **kwargs)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\leras\archis\DeepFakeArchi.py", line 158, in forward
    x = self.res2(x)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\leras\models\ModelBase.py", line 117, in __call__
    return self.forward(*args, **kwargs)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\leras\archis\DeepFakeArchi.py", line 69, in forward
    x = tf.nn.leaky_relu(x, 0.2)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2086, in leaky_relu
    return gen_nn_ops.leaky_relu(features, alpha=alpha, name=name)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 4910, in leaky_relu
    "LeakyRelu", features=features, alpha=alpha, name=name)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[8,128,64,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node LeakyRelu_18 (defined at C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\leras\archis\DeepFakeArchi.py:69) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[node concat_40 (defined at C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\models\Model_SAEHD\Model.py:517) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Traceback (most recent call last):
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[8,128,64,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node LeakyRelu_18}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node concat_40}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\mainscripts\Trainer.py", line 130, in trainerThread
    iter, iter_time = model.train_one_iter()
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\models\ModelBase.py", line 462, in train_one_iter
    losses = self.onTrainOneIter()
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 678, in onTrainOneIter
    src_loss, dst_loss = self.src_dst_train (warped_src, target_src, target_srcm, target_srcm_em, warped_dst, target_dst, target_dstm, target_dstm_em)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 538, in src_dst_train
    self.target_dstm_em:target_dstm_em,
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[8,128,64,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node LeakyRelu_18 (defined at C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\leras\archis\DeepFakeArchi.py:69) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[node concat_40 (defined at C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\models\Model_SAEHD\Model.py:517) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Caused by op 'LeakyRelu_18', defined at:
  File "threading.py", line 884, in _bootstrap
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\mainscripts\Trainer.py", line 58, in trainerThread
    debug=debug,
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\models\ModelBase.py", line 189, in __init__
    self.on_initialize()
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 381, in on_initialize
    gpu_pred_src_src, gpu_pred_src_srcm = self.decoder(gpu_src_code)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\leras\models\ModelBase.py", line 117, in __call__
    return self.forward(*args, **kwargs)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\leras\archis\DeepFakeArchi.py", line 158, in forward
    x = self.res2(x)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\leras\models\ModelBase.py", line 117, in __call__
    return self.forward(*args, **kwargs)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\leras\archis\DeepFakeArchi.py", line 69, in forward
    x = tf.nn.leaky_relu(x, 0.2)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2086, in leaky_relu
    return gen_nn_ops.leaky_relu(features, alpha=alpha, name=name)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 4910, in leaky_relu
    "LeakyRelu", features=features, alpha=alpha, name=name)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[8,128,64,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node LeakyRelu_18 (defined at C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\leras\archis\DeepFakeArchi.py:69) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[node concat_40 (defined at C:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\models\Model_SAEHD\Model.py:517) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
```

**Comment by robustini** [comment]
VRAM problem, try with this settings:

ae_dims: 128
e_dims: 32
d_dims: 32
d_mask_dims: 20

**Comment by iperov** [comment]
did you even fucking read the message?

> Trying to do the first iteration. If an error occurs, reduce the model parameters.

**Comment by gyloh9210** [comment]
> VRAM problem, try with this settings:
> 
> ae_dims: 128
> e_dims: 32
> d_dims: 32
> d_mask_dims: 20

Hey, I was wondering, will these parameters affect the output quality? or it will just take longer time because of my vram limitation?
