### ISSUE TITLE
train Quick96 does not work?

### ISSUE THREAD

**Issue by Boki420** [iperov/DeepFaceLab#5249]
Extracting images and facesets worked correctly. So I'm wondering what is the issue with the training part...

## Actual behavior

ERROR CODE:
`Running trainer.

[new] No saved models found. Enter a name of a new model :
new

Model first run.

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce RTX 3060 Ti

[0] Which GPU indexes to choose? :
0

Initializing models: 100%|####################################################################################################################################################################################| 5/5 [00:02<00:00,  1.84it/s]
Loading samples: 100%|#################################################################################################################################################################################| 1511/1511 [00:03<00:00, 503.15it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from .Sample import Sample
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\samplelib\Sample.py", line 7, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
    from core.cv2ex import *
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\cv2ex.py", line 5, in <module>
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
    from core import imagelib
      File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\imagelib\__init__.py", line 9, in <module>
from .Sample import Sample
Traceback (most recent call last):
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\samplelib\Sample.py", line 7, in <module>
  File "<string>", line 1, in <module>
    from core.cv2ex import *
      File "multiprocessing\spawn.py", line 105, in spawn_main
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\cv2ex.py", line 5, in <module>
from .morph import morph_by_points
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\imagelib\morph.py", line 3, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
    from core import imagelib
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\imagelib\__init__.py", line 9, in <module>
    from scipy.spatial import Delaunay  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>

  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\scipy\spatial\__init__.py", line 107, in <module>
    from .morph import morph_by_points
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\imagelib\morph.py", line 3, in <module>
    from .Sample import Sample
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\samplelib\Sample.py", line 4, in <module>
        import cv2
from scipy.spatial import Delaunay  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>

  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\scipy\spatial\__init__.py", line 107, in <module>
ImportError: numpy.core.multiarray failed to import
    from . import distance, transform
Traceback (most recent call last):
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\scipy\spatial\distance.py", line 125, in <module>
  File "<string>", line 1, in <module>
    from .cv2 import *
ImportError: DLL load failed: The paging file is too small for this operation to complete.
      File "multiprocessing\spawn.py", line 105, in spawn_main
from . import distance, transform  File "multiprocessing\spawn.py", line 115, in _main
    from ..special import rel_entr
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\scipy\special\__init__.py", line 637, in <module>
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>

ImportError: numpy.core.multiarray failed to import
    from .Sample import Sample
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\scipy\spatial\distance.py", line 125, in <module>
Traceback (most recent call last):
      File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\samplelib\Sample.py", line 4, in <module>
      File "<string>", line 1, in <module>
ImportError: numpy.core.multiarray failed to import
from . import _basic    import cv2
from ..special import rel_entr  File "multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):

  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>

  File "multiprocessing\spawn.py", line 115, in _main
  File "<string>", line 1, in <module>
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\scipy\special\_basic.py", line 18, in <module>
    from .cv2 import *
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\scipy\special\__init__.py", line 637, in <module>
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
ImportError: numpy.core.multiarray failed to import
        from .Sample import Sample
      File "multiprocessing\spawn.py", line 115, in _main
from . import specfun  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\samplelib\Sample.py", line 4, in <module>
from . import _basic  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>

    import cv2

    from .Sample import Sample
ImportErrorTraceback (most recent call last):
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\scipy\special\_basic.py", line 18, in <module>
  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\samplelib\Sample.py", line 4, in <module>
:   File "<string>", line 1, in <module>
    from .cv2 import *
        import cv2
DLL load failed: The paging file is too small for this operation to complete.  File "multiprocessing\spawn.py", line 105, in spawn_main
ImportError: numpy.core.multiarray failed to import
from . import specfun  File "D:\BitTorrent\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>

  File "multiprocessing\spawn.py", line 115, in _main

    from .cv2 import *
  File "multiprocessing\heap.py", line 55, in __setstate__
ImportErrorImportError: numpy.core.multiarray failed to import
OSError: : DLL load failed: The paging file is too small for this operation to complete.[WinError 1455] The paging file is too small for this operation to complete
`

## Steps to reproduce

I tried to see if different videos would behave differently, unfortunately no change.

## Other relevant information
-Windows 10 Home OS 64-bit
-GPU: Nvidia GeForce RTX 3060 Ti
-CPU: AMD Ryzen 5 5600X 6core

**Comment by NvrTdp** [comment]
"The paging file is too small for this operation to complete.[WinError 1455] The paging file is too small for this operation to complete." Search up how to increase virtual memory.

**Comment by Boki420** [comment]
> 
> 
> "The paging file is too small for this operation to complete.[WinError 1455] The paging file is too small for this operation to complete." Search up how to manually increase virtual memory.

![12](https://user-images.githubusercontent.com/62899629/105219558-e14a7380-5b56-11eb-90c4-673d3c18b616.png)

Still think virtual memory is the problem?

**Comment by NvrTdp** [comment]
> > "The paging file is too small for this operation to complete.[WinError 1455] The paging file is too small for this operation to complete." Search up how to manually increase virtual memory.
> 
> ![12](https://user-images.githubusercontent.com/62899629/105219558-e14a7380-5b56-11eb-90c4-673d3c18b616.png)
> 
> Still think virtual memory is the problem?

No idea. You have to juice it up and check.

**Comment by Boki420** [comment]
> 
> 
> No idea. You have to juice it up and check. If you have more space on the other drives I would try to move dfl folder.

**It worked!**

**Comment by pzy2000** [comment]
I set maximum size of virtual memory to 20480GB and it worked!
