### ISSUE TITLE
Trying to rename model - Not enough values to unpack...??

### ISSUE THREAD

**Issue by testerson34** [iperov/DeepFaceLab#5251]
## Expected behavior

Model should be renamed.

## Actual behavior

Enter the name of the model you want to rename : new
new
Enter new name of the model : ismay
ismay
Error: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "D:\DeepFaceLab_01_04_21\_internal\DeepFaceLab\mainscripts\Trainer.py", line 58, in trainerThread
    debug=debug,
  File "D:\DeepFaceLab_01_04_21\_internal\DeepFaceLab\models\ModelBase.py", line 109, in __init__
    model_filename, remain_filename = filepath_name.split('_', 1)
ValueError: not enough values to unpack (expected 2, got 1)

## Steps to reproduce

Run `train SAEHD` and choose to rename the model.  Enter the name of the model you want to rename, then a new name, and hit enter.  

## Other relevant information
- Windows 10
- DFL v01_04_2021

**Comment by nuxlear** [comment]
I have a same issue, and in my case I have duplicated project folders from one projects and every project worked fine before. Suddenly one of my projects failed to rename the model "new", but other can. 

There is no differences among projects and I already deleted my "new" model and replace it another one, and Nothing is changed. Both of train & merge are failed, and I have no idea for fixing it. 

I'm doing my job in Kubenetes cluster, which is Ubuntu 18.04 LTS, and the project is based on [DeepFaceLab_Linux](https://github.com/nagadit/DeepFaceLab_Linux)

**Comment by maple-jiang** [comment]
In the folder where the model is stored, each file name needs to contain at least one underline symbol("_"),
Or you can choose to modify the python code to solve this problem.

**Comment by notosapien** [comment]
I also had this problem, I hope this information will help anyone. After many test I've found out that in my model folder I've created a folder to temporary move files in and out sometimes, It seems like you should not have a folder in "model" folder only models.

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
