### ISSUE TITLE
Train SAEHD Failed

### ISSUE THREAD

**Issue by JaytimeGame** [iperov/DeepFaceLab#5252]
I've been trying to run 6) train SAEHD.bat multiple times but no succes. It always stop at 40%. 6) train Quick96.bat is working perfectly. Not sure what to do now.

##Information:
DFL Build: 01_04_2021
Computer:
-CPU: AMD Ryzen7 3700X 8-core
-RAM: 16GB
-GPU: RTX 2060
-VRAM: 6GB
-OS: Windows 10
Python: 3.7.9

##Process:
Running trainer.

[new] No saved models found. Enter a name of a new model :
new

Model first run.

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce RTX 2060

[0] Which GPU indexes to choose? :
0

[1] Autobackup every N hour ( 0..24 ?:help ) :
1
[y] Write preview history ( y/n ?:help ) :
y
[n] Choose image for the preview history ( y/n ) :
n
[0] Target iteration :
0
[y] Flip faces randomly ( y/n ?:help ) :
y
[8] Batch_size ( ?:help ) :
8
[640] Resolution ( 64-640 ?:help ) : 480
480
[wf] Face type ( h/mf/f/wf/head ?:help ) : wf
wf
[liae-ud] AE architecture ( ?:help ) :
liae-ud
[1024] AutoEncoder dimensions ( 32-1024 ?:help ) : 720
720
[256] Encoder dimensions ( 16-256 ?:help ) : 128
128
[256] Decoder dimensions ( 16-256 ?:help ) : 128
128
[256] Decoder mask dimensions ( 16-256 ?:help ) : 128
128
[y] Masked training ( y/n ?:help ) :
y
[n] Eyes and mouth priority ( y/n ?:help ) :
n
[n] Uniform yaw distribution of samples ( y/n ?:help ) :
n
[y] Place models and optimizer on GPU ( y/n ?:help ) :
y
[n] Use AdaBelief optimizer? ( y/n ?:help ) :
n
[n] Use learning rate dropout ( n/y/cpu ?:help ) :
n
[y] Enable random warp of samples ( y/n ?:help ) :
y
[0.0] GAN power ( 0.0 .. 1.0 ?:help ) :
0.0
[0.0] Face style power ( 0.0..100.0 ?:help ) :
0.0
[0.0] Background style power ( 0.0..100.0 ?:help ) :
0.0
[none] Color transfer for src faceset ( none/rct/lct/mkl/idt/sot ?:help ) :
none
[n] Enable gradient clipping ( y/n ?:help ) :
n
[n] Enable pretraining mode ( y/n ?:help ) :
n
Initializing models:  40%|#########################2                                     | 2/5 [00:55<01:23, 27.78s/it]
Error: OOM when allocating tensor with shape[720,324000] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node inter_B/dense2/weight/Initializer/random_uniform/RandomUniform (defined at C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\layers\Dense.py:47) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Original stack trace for 'inter_B/dense2/weight/Initializer/random_uniform/RandomUniform':
  File "threading.py", line 884, in _bootstrap
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Trainer.py", line 58, in trainerThread
    debug=debug,
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\ModelBase.py", line 189, in __init__
    self.on_initialize()
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 310, in on_initialize
    self.src_dst_trainable_weights = self.encoder.get_weights() + self.inter_AB.get_weights() + self.inter_B.get_weights() + self.decoder.get_weights()
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\models\ModelBase.py", line 77, in get_weights
    self.build()
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\models\ModelBase.py", line 65, in build
    self._build_sub(v[name],name)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\models\ModelBase.py", line 33, in _build_sub
    layer.build_weights()
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\layers\Dense.py", line 47, in build_weights
    self.weight = tf.get_variable("weight", weight_shape, dtype=self.dtype, initializer=kernel_initializer, trainable=self.trainable )
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1593, in get_variable
    aggregation=aggregation)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1336, in get_variable
    aggregation=aggregation)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 591, in get_variable
    aggregation=aggregation)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 543, in _true_getter
    aggregation=aggregation)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 961, in _get_single_variable
    aggregation=aggregation)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 260, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 221, in _variable_v1_call
    shape=shape)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 199, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2634, in default_variable_creator
    shape=shape)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 1668, in __init__
    shape=shape)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 1797, in _init_from_args
    initial_value = initial_value()
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\init_ops.py", line 519, in __call__
    shape, -limit, limit, dtype, seed=self.seed)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\random_ops.py", line 303, in random_uniform
    shape, dtype, seed=seed1, seed2=seed2)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gen_random_ops.py", line 738, in random_uniform
    name=name)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 3536, in _create_op_internal
    op_def=op_def)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 1990, in __init__
    self._traceback = tf_stack.extract_stack()

Traceback (most recent call last):
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[720,324000] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node inter_B/dense2/weight/Initializer/random_uniform/RandomUniform}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Trainer.py", line 58, in trainerThread
    debug=debug,
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\ModelBase.py", line 189, in __init__
    self.on_initialize()
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 611, in on_initialize
    model.init_weights()
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\layers\Saveable.py", line 104, in init_weights
    nn.init_weights(self.get_weights())
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\ops\__init__.py", line 48, in init_weights
    nn.tf_sess.run (ops)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 968, in run
    run_metadata_ptr)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1369, in _do_run
    run_metadata)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[720,324000] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node inter_B/dense2/weight/Initializer/random_uniform/RandomUniform (defined at C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\layers\Dense.py:47) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Original stack trace for 'inter_B/dense2/weight/Initializer/random_uniform/RandomUniform':
  File "threading.py", line 884, in _bootstrap
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Trainer.py", line 58, in trainerThread
    debug=debug,
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\ModelBase.py", line 189, in __init__
    self.on_initialize()
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 310, in on_initialize
    self.src_dst_trainable_weights = self.encoder.get_weights() + self.inter_AB.get_weights() + self.inter_B.get_weights() + self.decoder.get_weights()
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\models\ModelBase.py", line 77, in get_weights
    self.build()
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\models\ModelBase.py", line 65, in build
    self._build_sub(v[name],name)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\models\ModelBase.py", line 33, in _build_sub
    layer.build_weights()
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\layers\Dense.py", line 47, in build_weights
    self.weight = tf.get_variable("weight", weight_shape, dtype=self.dtype, initializer=kernel_initializer, trainable=self.trainable )
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1593, in get_variable
    aggregation=aggregation)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1336, in get_variable
    aggregation=aggregation)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 591, in get_variable
    aggregation=aggregation)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 543, in _true_getter
    aggregation=aggregation)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 961, in _get_single_variable
    aggregation=aggregation)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 260, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 221, in _variable_v1_call
    shape=shape)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 199, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2634, in default_variable_creator
    shape=shape)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 1668, in __init__
    shape=shape)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 1797, in _init_from_args
    initial_value = initial_value()
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\init_ops.py", line 519, in __call__
    shape, -limit, limit, dtype, seed=self.seed)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\random_ops.py", line 303, in random_uniform
    shape, dtype, seed=seed1, seed2=seed2)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gen_random_ops.py", line 738, in random_uniform
    name=name)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 3536, in _create_op_internal
    op_def=op_def)
  File "C:\Users\jimpi\AppData\Roaming\Sys\DeepFaceLab\2\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 1990, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by iTaKK** [comment]
You're running out of memory, your resolution is too high for 6GB VRAM.  To give you an idea, I can run a max of 224 resolution at batch 8 with 8GB VRAM.

**Comment by NvrTdp** [comment]
Resolution is one thing. Also the massive dims is out of this world. Keep them default.
