### ISSUE TITLE
GTX 1060 memory issue + Tensor Flow Error

### ISSUE THREAD

**Issue by JapaTuts** [iperov/DeepFaceLab#5255]
I'm trying to run the 5.Xseg) train
I have a GTX 1060 6GB + 16GB RAM + Ryzen 7 2700
Using python 3.6.4 (3.9 wasn't allowing me to install tensorflow)

This is what shows off to me in CMD when executing it:

> Running trainer.

Model first run.

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce GTX 1060 6GB

[0] Which GPU indexes to choose? : 0
0

[head] Face type ( h/mf/f/wf/head ?:help ) : head
head
[4] Batch_size ( 2-16 ?:help ) : 4
4
Traceback (most recent call last):
Traceback (most recent call last):
  File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
Traceback (most recent call last):
  File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
  File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
from tensorflow.python._pywrap_tensorflow_internal import *from tensorflow.python._pywrap_tensorflow_internal import *ImportError

: ImportErrorImportErrorDLL load failed: O arquivo de paginação é muito pequeno para que esta operação seja concluída.: :
DLL load failed: O arquivo de paginação é muito pequeno para que esta operação seja concluída.DLL load failed: O arquivo de paginação é muito pequeno para que esta operação seja concluída.
During handling of the above exception, another exception occurred:

Traceback (most recent call last):

During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

  File "<string>", line 1, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
  File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
        from tensorflow.python.ops import init_opsfrom tensorflow.python.ops import init_ops
  File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>

  File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
      File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
from tensorflow.python.ops import init_ops        from tensorflow.python.tools import module_util as _module_util
from tensorflow.python.tools import module_util as _module_util
  File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 41, in <module>

  File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 39, in <module>
      File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 39, in <module>
    from tensorflow.python.tools import module_util as _module_util    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 39, in <module>

  File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
      File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow    raise ImportError(msg)
raise ImportError(msg)
  File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>

ImportError    ImportError: : raise ImportError(msg)Traceback (most recent call last):
  File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: O arquivo de paginação é muito pequeno para que esta operação seja concluída.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Traceback (most recent call last):
  File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: O arquivo de paginação é muito pequeno para que esta operação seja concluída.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
ImportError
: Traceback (most recent call last):
  File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: O arquivo de paginação é muito pequeno para que esta operação seja concluída.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
    from tensorflow.python.ops import init_ops
  File "D:\.Arquivos\Programs\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 80, in <module>
    from ._api.v2 import raw_ops
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 771, in get_code
  File "<frozen importlib._bootstrap_external>", line 482, in _validate_bytecode_header
MemoryError

**Comment by NvrTdp** [comment]
Did you install python to use with other software? DFL don't require anything than the software itself to run. Messing around with python might lead to problems. Unless you need it for other purposes, I would remove all of it, clean registry, update gpu drivers and download fresh dfl version.

**Comment by JapaTuts** [comment]
> Did you install python to use with other software? DFL don't require anything than the software itself to run. Messing around with python might lead to problems. Unless you need it for other purposes, I would remove all of it, clean registry, update gpu drivers and download fresh dfl version.

No, I installed it just for DFL
I was testing some things here and realized that when I run the training on Quick96 it goes perfectly, but when I try SAEHD or X.Seg I start getting those problems
I already reainstalled my video drivers 3 times, my first try was w/out python installed and then I re extracted DFL again

**Comment by JapaTuts** [comment]
And how I can clean the registry for the DFL?
Could you explain to me?

**Comment by NvrTdp** [comment]
Not in DFL. But on your computer in general. Try downloading ccleaner, if you don't have it from before, and do some cleaning. Might be some old stuff messing up.

**Comment by JapaTuts** [comment]
Thx
I'll try, but right now I'm using Google Colab to do the training 
With the SAEHD mode I'm getting the results that I was looking for and with the advantage of using a Tesla T4 in it.
16GB of VRAM now :))
