### ISSUE TITLE
Train Quick96 FAiLS! ERROR.. Help..

### ISSUE THREAD

**Issue by Sansei901** [iperov/DeepFaceLab#5257]
No idea what to do.

##Information:
DFL build DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier
+Python3.9.1; +CUDA 11.2

Computer:
OS: Windows 10x64
CPU: Intel Core i7 -8700k 4.3 GHz
RAM: 16 GB
GPU: NVIDIA RTX2070

Running 6) train Quick96.bat

##Process
Running trainer.

[new] No saved models found. Enter a name of a new model : 123
123

Model first run.
Choose one or several GPU idxs (separated by comma).
[CPU] : CPU
[0] : GeForce RTX 2070
[0] Which GPU indexes to choose? :
0
Initializing models: 100%|###############################################################| 5/5 [00:02<00:00,  1.94it/s]
Loading samples: 100%|##############################################################| 825/825 [00:02<00:00, 304.87it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 115, in _main
  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
    from .Sample import Sample
from .Sample import Sample  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\samplelib\Sample.py", line 7, in <module>

      File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\samplelib\Sample.py", line 7, in <module>
from core.cv2ex import *
from core.cv2ex import *
  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\cv2ex.py", line 5, in <module>
  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\cv2ex.py", line 5, in <module>
        from core import imagelib from core import imagelib

  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\imagelib\__init__.py", line 9, in <module>
  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\imagelib\__init__.py", line 9, in <module>
        from .morph import morph_by_pointsfrom .morph import morph_by_points

  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\imagelib\morph.py", line 3, in <module>
  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\imagelib\morph.py", line 3, in <module>
        from scipy.spatial import Delaunayfrom scipy.spatial import Delaunay

  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\scipy\__init__.py", line 156, in <module>
  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\scipy\__init__.py", line 156, in <module>
        from . import fftfrom . import fft

  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\scipy\fft\__init__.py", line 76, in <module>
  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\scipy\fft\__init__.py", line 81, in <module>
        from ._basic import (from ._helper import next_fast_len

  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\scipy\fft\_helper.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 833, in get_data
MemoryError
    from . import _pocketfft
  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\scipy\fft\_pocketfft\__init__.py", line 3, in <module>
    from .basic import *
  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\scipy\fft\_pocketfft\basic.py", line 8, in <module>
    from . import pypocketfft as pfft
ImportError: DLL load failed: Файл подкачки слишком мал для завершения операции.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
      File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
from .Sample import Sample
from .Sample import Sample  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\samplelib\Sample.py", line 7, in <module>

      File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\samplelib\Sample.py", line 7, in <module>
from core.cv2ex import *
from core.cv2ex import *  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\cv2ex.py", line 5, in <module>

      File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\cv2ex.py", line 5, in <module>
from core import imagelib
from core import imagelib   File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\imagelib\__init__.py", line 9, in <module>

      File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\imagelib\__init__.py", line 9, in <module>
from .morph import morph_by_points
from .morph import morph_by_points  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\imagelib\morph.py", line 3, in <module>

      File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\DeepFaceLab\core\imagelib\morph.py", line 3, in <module>
from scipy.spatial import Delaunay
from scipy.spatial import Delaunay  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\scipy\spatial\__init__.py", line 107, in <module>

      File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\scipy\spatial\__init__.py", line 107, in <module>
from . import distance, transform
      File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\scipy\spatial\distance.py", line 125, in <module>
from . import distance, transform
  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\scipy\spatial\distance.py", line 125, in <module>
        from ..special import rel_entrfrom ..special import rel_entr

  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\scipy\special\__init__.py", line 637, in <module>
  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\scipy\special\__init__.py", line 637, in <module>
        from . import _basicfrom . import _basic

  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\scipy\special\_basic.py", line 20, in <module>
  File "H:\DeepFaceLab_NVIDIA_RTX2080Ti_and_earlier\_internal\python-3.6.8\lib\site-packages\scipy\special\_basic.py", line 20, in <module>
        from ._comb import _comb_intfrom ._comb import _comb_int

ImportErrorImportError: : DLL load failed: Файл подкачки слишком мал для завершения операции.DLL load failed: The page file is too small to complete the operation.

**Comment by NvrTdp** [comment]
"The page file is too small to complete the operation."
https://www.thewindowsclub.com/increase-page-file-size-virtual-memory-windows
Also you have a RTX2070, why would you even want to waste time on Quick96?

**Comment by gregtorn** [comment]
to be honest increasing pagefile doesnt help. even if you make it 20-50gb

**Comment by NvrTdp** [comment]
Also seems to be the issue whenever someone mess around with python or cuda builds. Just leave your pc as default, unless you need different version for other software than dfl.

**Comment by gregtorn** [comment]
> 
> 
> Also seems to be the issue whenever someone mess around with python or cuda builds. Just leave your pc as default, unless you need different version for other software than dfl.

i tried on new windows python only that comes with DFL, no mess with cuda and nothing works.  the same error all the time.

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?
