### ISSUE TITLE
XSeg error when trying to apply masks

### ISSUE THREAD

**Issue by JapaTuts** [iperov/DeepFaceLab#5260]
I've already made the face path in XSeg editor and trained it
But now when I try to exectue the file  _5.XSeg) data_dst trained mask - apply_  or  _5.XSeg) data_src trained mask - apply_  the CMD returns this to me

> `Applying trained XSeg model to aligned/ folder.
Traceback (most recent call last):
  File "D:\.Arquivos\Programs\DFL\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 324, in <module>
    arguments.func(arguments)
  File "D:\.Arquivos\Programs\DFL\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 285, in process_xsegapply
    XSegUtil.apply_xseg (Path(arguments.input_dir), Path(arguments.model_dir))
  File "D:\.Arquivos\Programs\DFL\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\XSegUtil.py", line 32, in apply_xseg
    raise_on_no_model_files=True)
  File "D:\.Arquivos\Programs\DFL\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\XSegNet.py", line 73, in __init__
    raise Exception(f'{model_file_path} does not exists.')
Exception: D:\.Arquivos\Programs\DFL\DeepFaceLab_NVIDIA\workspace\model\XSeg_256.npy does not exists.`

**Comment by fhrancis** [comment]
I'm having the same problem:
`Applying trained XSeg model to aligned/ folder.
Traceback (most recent call last):
  File "F:\DeepFake\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 324, in <module>
    arguments.func(arguments)
  File "F:\DeepFake\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 285, in process_xsegapply
    XSegUtil.apply_xseg (Path(arguments.input_dir), Path(arguments.model_dir))
  File "F:\DeepFake\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\XSegUtil.py", line 32, in apply_xseg
    raise_on_no_model_files=True)
  File "F:\DeepFake\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\XSegNet.py", line 73, in __init__
    raise Exception(f'{model_file_path} does not exists.')
Exception: F:\DeepFake\DeepFaceLab\DeepFaceLab_NVIDIA\workspace\model\XSeg_256.npy does not exists.`

**Comment by j-mir-prazak** [comment]
also having this error (using deepfacelab_linux)

**Comment by minixalpha** [comment]
I have the same problem when using CPU to do XSeg apply, if you use CPU, you should change the code of the file "_internal\DeepFaceLab\mainscripts\XSegUtil.py", 

from 
```python
    xseg = XSegNet(name='XSeg', 
                    load_weights=True,
                    weights_file_root=model_path,
                    data_format=nn.data_format,
                    raise_on_no_model_files=True)
```

to 

```python
    xseg = XSegNet(name='XSeg', 
                    load_weights=True,
                    weights_file_root=model_path,
                    data_format=nn.data_format,
                    place_model_on_cpu=True,
                    run_on_cpu=True,
                    raise_on_no_model_files=True)
```

this is because XSegUtil.py does not check whether you use CPU or not, and by default the code use GPU to load model, when load model fail, the exception will tell you the model does not exist, even though the model file exists.

**Comment by darkrubiks** [comment]
Rollback to a previous commit, the last one from  May 12, 2021 is giving this error

**Comment by Zeesy** [comment]
Has anyone found a solution to this? This is my traceback:
```
Traceback (most recent call last):
File "C:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\main.py", line 343, in <module>
arguments.func(arguments)
File "C:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\main.py", line 304, in process_xsegapply
XSegUtil.apply_xseg (Path(arguments.input_dir), Path(arguments.model_dir))
File "C:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\XSegUtil.py", line 57, in apply_xseg
raise_on_no_model_files=True)
File "C:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\facelib\XSegNet.py", line 73, in __init__
raise Exception(f'{model_file_path} does not exists.')
Exception: C:\DeepFaceLab_NVIDIA_RTX3000_series\workspace\model\XSeg_256.npy does not exists.
```
I'm on Windows 10, running on GPU.

**Comment by Zeesy** [comment]
> > Rollback to a previous commit, the last one from May 12, 2021 is giving this error
> 
> Has anyone found a solution to this? This is my traceback:
> 
> ```
> Traceback (most recent call last):
> File "C:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\main.py", line 343, in <module>
> arguments.func(arguments)
> File "C:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\main.py", line 304, in process_xsegapply
> XSegUtil.apply_xseg (Path(arguments.input_dir), Path(arguments.model_dir))
> File "C:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\XSegUtil.py", line 57, in apply_xseg
> raise_on_no_model_files=True)
> File "C:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\facelib\XSegNet.py", line 73, in __init__
> raise Exception(f'{model_file_path} does not exists.')
> Exception: C:\DeepFaceLab_NVIDIA_RTX3000_series\workspace\model\XSeg_256.npy does not exists.
> ```
> 
> I'm on Windows 10, running on GPU.

Solution for me - I needed to move my frames from the worskspace > data_src > frames folder I created to worskspace > data_src and everything worked fine.

**Comment by yhsharaf** [comment]
My Solution:

I placed the files '**XSeg_256.npy**', '**XSeg_data.dat**', and '**XSeg_summary.txt**' in the '**workspace/model**' directory and I was able to run '**5_XSeg_data_dst_mask_apply.sh**' successfully.

On Ubuntu 20.04

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
