### ISSUE TITLE
Using 2 GPUs for 2 different models at the same time I get this error

### ISSUE THREAD

**Issue by kilerb** [iperov/DeepFaceLab#5267]
Hi...  When I try to train 2 different models using 2 different GPUs, the first one starts, and then when it starts loading the 2nd one I get errors and it won't train at the same time.  This is what the error is on the computer that was already training....  
Traceback (most recent call last):][0.0505]
  File "multiprocessing\queues.py", line 236, in _feed
  File "multiprocessing\connection.py", line 200, in send_bytes
  File "multiprocessing\connection.py", line 280, in _send_bytes
OSError: [WinError 1450] Insufficient system resources exist to complete the requested service

The computer has good specs w/ 64gb RAM and the gpus are both nvidia A6000's with 48gb VRAM.  They run the models fine one at a time.  It's weird because I have tried this with 2 Titans (24gb) vram on models that work on those cards and they would train 2 at a time.  Any idea what would cause this?  On the computer that I start the 2nd training on I get a lot more errors.  I'll attach a screenshot of thosehere at the end.  Thank you!!!
![error](https://user-images.githubusercontent.com/6969681/106089148-3567d180-60dc-11eb-9207-360507c0f547.jpg)

**Comment by blanuk** [comment]
try to duplicate the internal folder and run one batch from internal1 and one batch from internal2

**Comment by ghost** [comment]
Did you ever find the answer?
