### ISSUE TITLE
Tensorflow Raises No OpKernel XXX ... ERROR When Initializing SAEHD Model

### ISSUE THREAD

**Issue by Omgix** [iperov/DeepFaceLab#5269]
I use Linux version, and install all requirement packages, except h5py 2.9.0 - I install version 2.10.0 instead.

However, when I start training SAEHD model, an error occured:

```bash 6_train_SAEHD.sh 
Running trainer.

[new] No saved models found. Enter a name of a new model : td
td

Model first run.

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce GTX 1080

[0] Which GPU indexes to choose? : 
0

[0] Autobackup every N hour ( 0..24 ?:help ) : 
0
[n] Write preview history ( y/n ?:help ) : 
n
[0] Target iteration : 
0
[y] Flip faces randomly ( y/n ?:help ) : 
y
[8] Batch_size ( ?:help ) : 
8
[256] Resolution ( 64-640 ?:help ) : 
256
[wf] Face type ( h/mf/f/wf/head ?:help ) : 
wf
[df] AE architecture ( ?:help ) : 
df
[256] AutoEncoder dimensions ( 32-1024 ?:help ) : 
256
[64] Encoder dimensions ( 16-256 ?:help ) : 
64
[64] Decoder dimensions ( 16-256 ?:help ) : 
64
[22] Decoder mask dimensions ( 16-256 ?:help ) : 
22
[y] Masked training ( y/n ?:help ) : 
y
[n] Eyes and mouth priority ( y/n ?:help ) : 
n
[n] Uniform yaw distribution of samples ( y/n ?:help ) : 
n
[y] Place models and optimizer on GPU ( y/n ?:help ) : 
y
[y] Use AdaBelief optimizer? ( y/n ?:help ) : 
y
[n] Use learning rate dropout ( n/y/cpu ?:help ) : 
n
[y] Enable random warp of samples ( y/n ?:help ) : 
y
[0.0] GAN power ( 0.0 .. 1.0 ?:help ) : 
0.0
[0.0] 'True face' power. ( 0.0000 .. 1.0 ?:help ) : 
0.0
[0.0] Face style power ( 0.0..100.0 ?:help ) : 
0.0
[0.0] Background style power ( 0.0..100.0 ?:help ) : 
0.0
[none] Color transfer for src faceset ( none/rct/lct/mkl/idt/sot ?:help ) : 
none
[n] Enable gradient clipping ( y/n ?:help ) : 
n
[n] Enable pretraining mode ( y/n ?:help ) : 
n


Initializing models:   0%|                                | 0/5 [00:00<?, ?it/s]
Error: No OpKernel was registered to support Op 'DepthToSpace' used by node DepthToSpace (defined at /workspace/DeepFaceLab_Linux/DeepFaceLab/core/leras/ops/__init__.py:336)  with these attrs: [data_format="NCHW", block_size=2, T=DT_FLOAT]
Registered devices: [CPU]
Registered kernels:
  device='GPU'; T in [DT_QINT8]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_VARIANT]; data_format in ["NHWC"]
  device='CPU'; T in [DT_RESOURCE]; data_format in ["NHWC"]
  device='CPU'; T in [DT_STRING]; data_format in ["NHWC"]
  device='CPU'; T in [DT_BOOL]; data_format in ["NHWC"]
  device='CPU'; T in [DT_COMPLEX128]; data_format in ["NHWC"]
  device='CPU'; T in [DT_COMPLEX64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_DOUBLE]; data_format in ["NHWC"]
  device='CPU'; T in [DT_FLOAT]; data_format in ["NHWC"]
  device='CPU'; T in [DT_BFLOAT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_HALF]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT32]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT8]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT8]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT32]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT64]; data_format in ["NHWC"]

	 [[DepthToSpace]]

Errors may have originated from an input operation.
Input Source operations connected to node DepthToSpace:
 LeakyRelu_4 (defined at /workspace/DeepFaceLab_Linux/DeepFaceLab/core/leras/archis/DeepFakeArchi.py:58)
Traceback (most recent call last):
  File "/home/zhong/anaconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/home/zhong/anaconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1358, in _run_fn
    self._extend_graph()
  File "/home/zhong/anaconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1398, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'DepthToSpace' used by {{node DepthToSpace}} with these attrs: [data_format="NCHW", block_size=2, T=DT_FLOAT]
Registered devices: [CPU]
Registered kernels:
  device='GPU'; T in [DT_QINT8]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_VARIANT]; data_format in ["NHWC"]
  device='CPU'; T in [DT_RESOURCE]; data_format in ["NHWC"]
  device='CPU'; T in [DT_STRING]; data_format in ["NHWC"]
  device='CPU'; T in [DT_BOOL]; data_format in ["NHWC"]
  device='CPU'; T in [DT_COMPLEX128]; data_format in ["NHWC"]
  device='CPU'; T in [DT_COMPLEX64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_DOUBLE]; data_format in ["NHWC"]
  device='CPU'; T in [DT_FLOAT]; data_format in ["NHWC"]
  device='CPU'; T in [DT_BFLOAT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_HALF]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT32]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT8]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT8]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT32]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT64]; data_format in ["NHWC"]

	 [[DepthToSpace]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhong/workspace/DeepFaceLab_Linux/DeepFaceLab/mainscripts/Trainer.py", line 58, in trainerThread
    debug=debug,
  File "/home/zhong/workspace/DeepFaceLab_Linux/DeepFaceLab/models/ModelBase.py", line 189, in __init__
    self.on_initialize()
  File "/home/zhong/workspace/DeepFaceLab_Linux/DeepFaceLab/models/Model_SAEHD/Model.py", line 611, in on_initialize
    model.init_weights()
  File "/home/zhong/workspace/DeepFaceLab_Linux/DeepFaceLab/core/leras/layers/Saveable.py", line 104, in init_weights
    nn.init_weights(self.get_weights())
  File "/home/zhong/workspace/DeepFaceLab_Linux/DeepFaceLab/core/leras/ops/__init__.py", line 48, in init_weights
    nn.tf_sess.run (ops)
  File "/home/zhong/anaconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 968, in run
    run_metadata_ptr)
  File "/home/zhong/anaconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/zhong/anaconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1369, in _do_run
    run_metadata)
  File "/home/zhong/anaconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'DepthToSpace' used by node DepthToSpace (defined at /workspace/DeepFaceLab_Linux/DeepFaceLab/core/leras/ops/__init__.py:336)  with these attrs: [data_format="NCHW", block_size=2, T=DT_FLOAT]
Registered devices: [CPU]
Registered kernels:
  device='GPU'; T in [DT_QINT8]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_VARIANT]; data_format in ["NHWC"]
  device='CPU'; T in [DT_RESOURCE]; data_format in ["NHWC"]
  device='CPU'; T in [DT_STRING]; data_format in ["NHWC"]
  device='CPU'; T in [DT_BOOL]; data_format in ["NHWC"]
  device='CPU'; T in [DT_COMPLEX128]; data_format in ["NHWC"]
  device='CPU'; T in [DT_COMPLEX64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_DOUBLE]; data_format in ["NHWC"]
  device='CPU'; T in [DT_FLOAT]; data_format in ["NHWC"]
  device='CPU'; T in [DT_BFLOAT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_HALF]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT32]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT8]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT8]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT32]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT64]; data_format in ["NHWC"]

	 [[DepthToSpace]]

Errors may have originated from an input operation.
Input Source operations connected to node DepthToSpace:
 LeakyRelu_4 (defined at /workspace/DeepFaceLab_Linux/DeepFaceLab/core/leras/archis/DeepFakeArchi.py:58)
```

I have installed CUDA 10.1, cuDNN 7.6.5 for CUDA 10.1, and make sure they are installed correctly, and I even change the computer! But the problem is still.

**Comment by coloneldbugger** [comment]
Did you ever find a solution to this problem?  I have encountered it with CUDA 10.2 and 11.2  on Ubuntu 16.04 and 20.04

**Comment by KernelA** [comment]
I have installed cuDNN 8 and it solved problem.
```
conda install -c nvidia cudnn=8
```

conda environment:
```
python                    3.8.8                hdb3f193_4    main
tensorflow-estimator      2.4.0                    pypi_0    pypi
tensorflow-gpu            2.4.0                    pypi_0    pypi
cudatoolkit               11.0.221             h6bb024c_0    main
cudnn                     8.0.4                cuda11.0_0    nvidia
```

**Comment by jennso** [comment]
I am having the same issue under centos 7 with python 3.6.8, I am installing centos 8.1 now and those specific versions to see if it will work, what nvidia driver are you using?

**Comment by KernelA** [comment]
I have RTX 2080 Ti with the driver version: 460.39 too.

Probably, you do not necessary use conda, but cuDNN must be installed separately in this case.

**Comment by jennso** [comment]
while trying this conda create -n deepfacelab -c main python=3.8.8 cudnn=8.0.4 cudatoolkit=11.0.221 I get 

PackagesNotFoundError: The following packages are not available from current channels:

  - cudnn=8

**Comment by jennso** [comment]
nvm found how to add the nvidia channel

**Comment by KernelA** [comment]
@jennso, try command after creating environment:
```
conda install -c nvidia cudnn=8
```

**Comment by jennso** [comment]
Hi thanks for the help I was able to make it work with this.

conda create -n deepfacelab -c main python=3.7 cudnn=8.0.4 cudatoolkit=11.0.221

adding the nvidia channel manually using conda-navigator

using driver version: NVIDIA-Linux-x86_64-460.39

and this as pip installs:

tqdm
numpy==1.19.3
h5py==2.9.0 (2.10.0)
opencv-python==4.1.0.25
ffmpeg-python==0.1.17
scikit-image==0.14.2
scipy==1.4.1
colorama
tensorflow-gpu==2.4.0
pyqt5

I was able to launch the training and all seems good so far, thanks alot :)
