### ISSUE TITLE
3090 Failed training SAEHD

### ISSUE THREAD

**Issue by Mavourn3en** [iperov/DeepFaceLab#5270]
Hey everyone, 

Someone help me address this issue please?

got this error message when starting training. 

Running trainer.

[new] No saved models found. Enter a name of a new model :
new

Model first run.

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce RTX 3090

[0] Which GPU indexes to choose? :
0

Caching GPU kernels...
[0] Autobackup every N hour ( 0..24 ?:help ) :
0
[n] Write preview history ( y/n ?:help ) :
n
[0] Target iteration :
0
[y] Flip faces randomly ( y/n ?:help ) :
y
[16] Batch_size ( ?:help ) :
16
[256] Resolution ( 64-640 ?:help ) :
256
[wf] Face type ( h/mf/f/wf/head ?:help ) :
wf
[liae-ud] AE architecture ( ?:help ) :
liae-ud
[256] AutoEncoder dimensions ( 32-1024 ?:help ) :
256
[64] Encoder dimensions ( 16-256 ?:help ) :
64
[64] Decoder dimensions ( 16-256 ?:help ) :
64
[22] Decoder mask dimensions ( 16-256 ?:help ) :
22
[y] Masked training ( y/n ?:help ) :
y
[n] Eyes and mouth priority ( y/n ?:help ) :
n
[n] Uniform yaw distribution of samples ( y/n ?:help ) :
n
[y] Place models and optimizer on GPU ( y/n ?:help ) :
y
[y] Use AdaBelief optimizer? ( y/n ?:help ) :
y
[n] Use learning rate dropout ( n/y/cpu ?:help ) :
n
[y] Enable random warp of samples ( y/n ?:help ) :
y
[0.0] GAN power ( 0.0 .. 10.0 ?:help ) :
0.0
[0.0] Face style power ( 0.0..100.0 ?:help ) :
0.0
[0.0] Background style power ( 0.0..100.0 ?:help ) :
0.0
[none] Color transfer for src faceset ( none/rct/lct/mkl/idt/sot ?:help ) :
none
[n] Enable gradient clipping ( y/n ?:help ) :
n
[n] Enable pretraining mode ( y/n ?:help ) :
n
Initializing models:  60%|#####################################8                         | 3/5 [00:10<00:06,  3.16s/it]Traceback (most recent call last):
Traceback (most recent call last):
  File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
Traceback (most recent call last):
  File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
Traceback (most recent call last):
      File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
      File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
from tensorflow.python._pywrap_tensorflow_internal import *    from tensorflow.python._pywrap_tensorflow_internal import *
from tensorflow.python._pywrap_tensorflow_internal import *
from tensorflow.python._pywrap_tensorflow_internal import *ImportError
ImportError
: ImportError: ImportErrorDLL load failed: The paging file is too small for this operation to complete.: DLL load failed: The paging file is too small for this operation to complete.: 
DLL load failed: The paging file is too small for this operation to complete.
DLL load failed: The paging file is too small for this operation to complete.
During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

During handling of the above exception, another exception occurred:

  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "D:\software\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
  File "D:\software\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
      File "D:\software\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
      File "D:\software\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
from tensorflow.python.ops import init_ops    from tensorflow.python.ops import init_ops
from tensorflow.python.ops import init_ops
from tensorflow.python.ops import init_ops  File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 41, in <module>

  File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 41, in <module>

      File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
      File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
from tensorflow.python.tools import module_util as _module_util    from tensorflow.python.tools import module_util as _module_util
from tensorflow.python.tools import module_util as _module_util
from tensorflow.python.tools import module_util as _module_util  File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 39, in <module>

  File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 39, in <module>

      File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 39, in <module>
      File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 39, in <module>
from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow  File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>

  File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>

      File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
      File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
raise ImportError(msg)    raise ImportError(msg)
raise ImportError(msg)
raise ImportError(msg)ImportError
ImportError
: ImportError: Traceback (most recent call last):
  File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The paging file is too small for this operation to complete.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.: ImportErrorTraceback (most recent call last):
  File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The paging file is too small for this operation to complete.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
: Traceback (most recent call last):
  File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The paging file is too small for this operation to complete.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Traceback (most recent call last):
  File "D:\software\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The paging file is too small for this operation to complete.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ghost** [comment]
Did you ever find the answer?
