### ISSUE TITLE
why when i run quick 96 will error occurred? THANKS 

### ISSUE THREAD

**Issue by super18863** [iperov/DeepFaceLab#5273]
Model first run.
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "opencl_amd_ellesmere.0"
Error: The Keras backend function 'random_binomial' is not yet implemented in Plaid. You can help us prioritize by letting us know if this function is important to you, and as always, contributions are welcome!
Traceback (most recent call last):
  File "F:\deep\DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 50, in trainerThread
    device_args=device_args)
  File "F:\deep\DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\models\Model_Quick96\Model.py", line 21, in __init__
    ask_random_flip=False)
  File "F:\deep\DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\models\ModelBase.py", line 145, in __init__
    self.onInitialize()
  File "F:\deep\DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\models\Model_Quick96\Model.py", line 161, in onInitialize
    self.src_train = K.function ([self.model.warped_src, self.model.target_src, self.model.target_srcm], [src_loss], self.src_dst_opt.get_updates( src_loss, self.model.src_trainable_weights) )
  File "F:\deep\DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\nnlib\nnlib.py", line 932, in get_updates
    lr_rnds = [ K.random_binomial(K.int_shape(p), p=self.lr_dropout, dtype=K.dtype(p)) for p in params ]
  File "F:\deep\DeepFaceLab_OpenCL_SSE\_internal\DeepFaceLab\nnlib\nnlib.py", line 932, in <listcomp>
    lr_rnds = [ K.random_binomial(K.int_shape(p), p=self.lr_dropout, dtype=K.dtype(p)) for p in params ]
  File "F:\deep\DeepFaceLab_OpenCL_SSE\_internal\python-3.6.8\lib\site-packages\plaidml\keras\backend.py", line 1070, in random_binomial
    _report_unimplemented('random_binomial')
  File "F:\deep\DeepFaceLab_OpenCL_SSE\_internal\python-3.6.8\lib\site-packages\plaidml\keras\backend.py", line 103, in _report_unimplemented
    raise NotImplementedError(report)
NotImplementedError: The Keras backend function 'random_binomial' is not yet implemented in Plaid. You can help us prioritize by letting us know if this function is important to you, and as always, contributions are welcome!

Thanks!

**Comment by ghost** [comment]
Did you ever find the answer?
