### ISSUE TITLE
metadata restore not compatible with Photoshop saved files...??

### ISSUE THREAD

**Issue by testerson34** [iperov/DeepFaceLab#5276]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

* Run `4.2) data_src util faceset metadata save.bat`
* Open aligned image(s) in Photoshop, make adjustments, and save.
* Run `4.2) data_src util faceset metadata restore.bat`
* Carry on using my newly enhanced faceset

## Actual behavior

When I run `4.2) data_src util faceset metadata restore.bat` I end up with the following error:

```
/!\ Exception occured while DFLJPG.load : Traceback (most recent call last):
  File "D:\ProgramFiles\DeepFaceLab_01_04_2021\_internal\DeepFaceLab\DFLIMG\DFLJPG.py", line 49, in load_raw
    raise ValueError(f"No Valid JPG info in {filename}")
ValueError: No Valid JPG info in D:\ProgramFiles\DeepFaceLab_01_04_2021\workspace\data_src\aligned\00019.jpg

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\DeepFaceLab_01_04_2021\_internal\DeepFaceLab\DFLIMG\DFLJPG.py", line 131, in load
    inst = DFLJPG.load_raw (filename, loader_func=loader_func)
  File "D:\ProgramFiles\DeepFaceLab_01_04_2021\_internal\DeepFaceLab\DFLIMG\DFLJPG.py", line 126, in load_raw
    raise Exception (f"Corrupted JPG file {filename} {e}")
Exception: Corrupted JPG file D:\ProgramFiles\DeepFaceLab_01_04_2021\workspace\data_src\aligned\00019.jpg No Valid JPG info in D:\ProgramFiles\DeepFaceLab_01_04_2021\workspace\data_src\aligned\00019.jpg

Processing:   0%|                                                                             | 0/1941 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\ProgramFiles\DeepFaceLab_01_04_2021\_internal\DeepFaceLab\main.py", line 324, in <module>
    arguments.func(arguments)
  File "D:\ProgramFiles\DeepFaceLab_01_04_2021\_internal\DeepFaceLab\main.py", line 90, in process_util
    Util.restore_faceset_metadata_folder (input_path=arguments.input_dir)
  File "D:\ProgramFiles\DeepFaceLab_01_04_2021\_internal\DeepFaceLab\mainscripts\Util.py", line 73, in restore_faceset_metadata_folder
    dflimg.set_dict(dfl_dict)
AttributeError: 'NoneType' object has no attribute 'set_dict'
```
## Steps to reproduce

* Run `4.2) data_src util faceset metadata save.bat`
* Open aligned image(s) in Photoshop, make adjustments, and save.
* Run `4.2) data_src util faceset metadata restore.bat`

## Other relevant information

* Seems to be specific to Photoshop.
* If I open the image(s) in Gimp and then export to JPG, overwriting the original, I can then restore metadata without failure.
** I much prefer Photoshop

**Comment by blanuk** [comment]
u can convert the files with irfan view or xnviewmp.

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
