### ISSUE TITLE
can't start a new XSeg training

### ISSUE THREAD

**Issue by xRoyBx** [iperov/DeepFaceLab#5281]
When i try to start/resume an XSeg training it gives me several Python/Tensorflow errors. Here's the log:

`
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
Traceback (most recent call last):
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
        Traceback (most recent call last):
          File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *from tensorflow.python.pywrap_tensorflow_internal import *  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
from tensorflow.python.pywrap_tensorflow_internal import *from tensorflow.python.pywrap_tensorflow_internal import *    from tensorflow.python.pywrap_tensorflow_internal import *from tensorflow.python.pywrap_tensorflow_internal import *

from tensorflow.python.pywrap_tensorflow_internal import *

  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
Traceback (most recent call last):
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
from tensorflow.python.pywrap_tensorflow_internal import *  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>

  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
      File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>

          File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()    _pywrap_tensorflow_internal = swig_import_helper()  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
_pywrap_tensorflow_internal = swig_import_helper()_pywrap_tensorflow_internal = swig_import_helper()
_pywrap_tensorflow_internal = swig_import_helper()
from tensorflow.python.pywrap_tensorflow_internal import *

_pywrap_tensorflow_internal = swig_import_helper()_pywrap_tensorflow_internal = swig_import_helper()  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper

  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper

  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_pywrap_tensorflow_internal = swig_import_helper()  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper

      File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
      File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>

      File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
_pywrap_tensorflow_internal = swig_import_helper()

_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)  File "imp.py", line 243, in load_module

  File "imp.py", line 243, in load_module

  File "imp.py", line 243, in load_module
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)  File "imp.py", line 243, in load_module

  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
  File "imp.py", line 343, in load_dynamic
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper

  File "imp.py", line 343, in load_dynamic
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportErrorImportError  File "imp.py", line 343, in load_dynamic
  File "imp.py", line 243, in load_module
ImportError  File "imp.py", line 343, in load_dynamic
ImportError:     : ImportErrorImportError  File "imp.py", line 343, in load_dynamic
: : DLL load failed: Il file di paging è troppo piccolo per essere completato._mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description): DLL load failed: Il file di paging è troppo piccolo per essere completato.DLL load failed: Il file di paging è troppo piccolo per essere completato.ImportErrorDLL load failed: Il file di paging è troppo piccolo per essere completato.DLL load failed: Il file di paging è troppo piccolo per essere completato.ImportError

:

:

:
During handling of the above exception, another exception occurred:

  File "imp.py", line 243, in load_module
DLL load failed: Il file di paging è troppo piccolo per essere completato.
During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

DLL load failed: Il file di paging è troppo piccolo per essere completato.
During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

DLL load failed: Il file di paging è troppo piccolo per essere completato.Traceback (most recent call last):

Traceback (most recent call last):
  File "imp.py", line 343, in load_dynamic
Traceback (most recent call last):

Traceback (most recent call last):
Traceback (most recent call last):

  File "<string>", line 1, in <module>

During handling of the above exception, another exception occurred:

  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
ImportError
During handling of the above exception, another exception occurred:

  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 105, in spawn_main
: Traceback (most recent call last):
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
DLL load failed: Il file di paging è troppo piccolo per essere completato.  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 115, in _main
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main

  File "F:\!DeepFaceLab\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "F:\!DeepFaceLab\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
  File "F:\!DeepFaceLab\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "F:\!DeepFaceLab\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
  File "multiprocessing\spawn.py", line 115, in _main

During handling of the above exception, another exception occurred:

  File "F:\!DeepFaceLab\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
        from tensorflow.python.ops import init_ops          File "multiprocessing\spawn.py", line 115, in _main
Traceback (most recent call last):
  File "F:\!DeepFaceLab\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
      File "multiprocessing\spawn.py", line 115, in _main
from tensorflow.python.ops import init_ops
from tensorflow.python.ops import init_opsfrom tensorflow.python.ops import init_ops  File "<string>", line 1, in <module>
  File "F:\!DeepFaceLab\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
    from tensorflow.python.ops import init_opsfrom tensorflow.python.ops import init_ops  File "F:\!DeepFaceLab\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>

  File "multiprocessing\spawn.py", line 105, in spawn_main

          File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
from tensorflow.python.ops import init_ops  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
from tensorflow.python.ops import init_opsfrom tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "F:\!DeepFaceLab\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-importfrom tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-importfrom tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-importfrom tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>

from tensorflow.python.ops import init_opsfrom tensorflow.python import pywrap_tensorflow  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>

        from tensorflow.python import pywrap_tensorflow
      File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
from tensorflow.python import pywrap_tensorflow  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
from tensorflow.python import pywrap_tensorflow        from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import    from tensorflow.python import pywrap_tensorflow
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>

raise ImportError(msg)
from tensorflow.python import pywrap_tensorflow
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    from tensorflow.python import pywrap_tensorflow  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>

  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>

  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
        ImportError      File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)raise ImportError(msg)
raise ImportError(msg)raise ImportError(msg): from tensorflow.python import pywrap_tensorflow
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>

ImportError

raise ImportError(msg)Traceback (most recent call last):
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: Il file di paging è troppo piccolo per essere completato.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.ImportError    ImportError: ImportErrorImportError  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>

: raise ImportError(msg): : : Traceback (most recent call last):
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: Il file di paging è troppo piccolo per essere completato.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.    ImportErrorraise ImportError(msg): Traceback (most recent call last):
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: Il file di paging è troppo piccolo per essere completato.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.Traceback (most recent call last):
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: Il file di paging è troppo piccolo per essere completato.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.Traceback (most recent call last):
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: Il file di paging è troppo piccolo per essere completato.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Traceback (most recent call last):
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: Il file di paging è troppo piccolo per essere completato.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Traceback (most recent call last):
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: Il file di paging è troppo piccolo per essere completato.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Traceback (most recent call last):

ImportError
ImportError
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
:     from tensorflow.python.pywrap_tensorflow_internal import *Traceback (most recent call last):
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: Il file di paging è troppo piccolo per essere completato.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Traceback (most recent call last):
:
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
        Traceback (most recent call last):
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: Il file di paging è troppo piccolo per essere completato.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
_pywrap_tensorflow_internal = swig_import_helper()
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "imp.py", line 343, in load_dynamic
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
ImportError    : _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)DLL load failed: Il file di paging è troppo piccolo per essere completato.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>

  File "imp.py", line 243, in load_module
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "imp.py", line 343, in load_dynamic
  File "multiprocessing\spawn.py", line 115, in _main
ImportError: DLL load failed: Il file di paging è troppo piccolo per essere completato.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "F:\!DeepFaceLab\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
    from tensorflow.python.ops import init_ops
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import  File "multiprocessing\spawn.py", line 115, in _main

  File "F:\!DeepFaceLab\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
      File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
from tensorflow.python.ops import init_ops
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
from tensorflow.python import pywrap_tensorflow
from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>

raise ImportError(msg)  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>

ImportErrorfrom tensorflow.python import pywrap_tensorflow:
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
Traceback (most recent call last):
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: Il file di paging è troppo piccolo per essere completato.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\!DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: Il file di paging è troppo piccolo per essere completato.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
`

**Comment by xRoyBx** [comment]
Can anyone help me? Maybe it's about the "tensorflow shit. IDK how to fix" hyperov refers to in the post here?:
https://github.com/iperov/DeepFaceLab/issues/5237#issuecomment-757109639

**Comment by ghost** [comment]
Did you ever find the answer?

**Comment by xRoyBx** [comment]
> Did you ever find the answer?

Yes, just enable/increase pagefile.sys where DFL in installed (set to 64GB)
