### ISSUE TITLE
starting today, issue on google colab + dfl_colab:  "KeyError: 'APPDATA'"

### ISSUE THREAD

**Issue by protocolGITHUB** [iperov/DeepFaceLab#5315]
starting today, any workspaces I try to start I get this:

Time to end session: 12 hours
Process Process-1:
Traceback (most recent call last):
File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
self.run()
File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
self._target(*self._args, **self._kwargs)
File "/content/DeepFaceLab/core/leras/device.py", line 95, in _get_tf_devices_proc
compute_cache_path = Path(os.environ['APPDATA']) / 'NVIDIA' / ('ComputeCache_ALL')
File "/usr/lib/python3.7/os.py", line 681, in getitem
raise KeyError(key) from None
KeyError: 'APPDATA'

Sorry if this is not your problem, but I thought you might be able to help since its related to today's commits.

thanks!

**Comment by protocolGITHUB** [comment]
new commit fixed it!

thanks!
