### ISSUE TITLE
3070 and XSeg training

### ISSUE THREAD

**Issue by gregtorn** [iperov/DeepFaceLab#5317]
Any chance of fixing this - Pagefile is too small to complete the operation? I tried full clean windows reinstall, different CUDA, different drivers, making pagefile 64-128GB(my ram is 32GB). Tried all build versions and Nothing. I just get this all the time.

Running trainer.

Model first run.

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce RTX 3070

[0] Which GPU indexes to choose? :
0

[wf] Face type ( h/mf/f/wf/head ?:help ) :
wf
[4] Batch_size ( 2-16 ?:help ) :
4
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\__init__.py", line 1, in <module>
    from .nn import nn
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\nn.py", line 26, in <module>
    from core.interact import interact as io
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from .interact import interact
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
    import cv2
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: DLL load failed: Файл подкачки слишком мал для завершения операции.
  File "multiprocessing\spawn.py", line 115, in _main
Traceback (most recent call last):
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\__init__.py", line 1, in <module>
  File "<string>", line 1, in <module>
    from .nn import nn
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\nn.py", line 26, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
    from core.interact import interact as io
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\__init__.py", line 1, in <module>
    from .interact import interact
    from .nn import nn
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\nn.py", line 26, in <module>
    import cv2
    from core.interact import interact as io
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
    from .cv2 import *
    from .interact import interact
ImportError: DLL load failed: Файл подкачки слишком мал для завершения операции.
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
    import cv2
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
MemoryError
Traceback (most recent call last):
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: Файл подкачки слишком мал для завершения операции.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
    from tensorflow.python.ops import init_ops
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "f:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: Файл подкачки слишком мал для завершения операции.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by gnivler** [comment]
YMMV, but I had this and had static pagefile sizes, so I changed it to fully automatic and it worked.

**Comment by gregtorn** [comment]
> 
> 
> YMMV, but I had this and had static pagefile sizes, so I changed it to fully automatic and it worked. Also with a 3070, 8GB, 32GB RAM.

tried that too. still didnt helped =(

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?
