### ISSUE TITLE
Getting errors with 3090

### ISSUE THREAD

**Issue by seanawesome** [iperov/DeepFaceLab#5322]
## Expected behavior

I've used this program before, so I know that after naming a model after running 6) train Quick96.bat is supposed to initialize, then bring up a preview box.

## Actual behavior

Initializing models: 100%|###############################################################| 5/5 [00:03<00:00,  1.56it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "C:\DEEPFAKE\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
    from .Sample import Sample
  File "C:\DEEPFAKE\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 7, in <module>
    from core.cv2ex import *
  File "C:\DEEPFAKE\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\cv2ex.py", line 5, in <module>
    from core import imagelib
  File "C:\DEEPFAKE\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\__init__.py", line 9, in <module>
    from .morph import morph_by_points
  File "C:\DEEPFAKE\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\morph.py", line 3, in <module>
    from scipy.spatial import Delaunay
  File "C:\DEEPFAKE\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\scipy\spatial\__init__.py", line 102, in <module>
    from ._procrustes import procrustes
  File "C:\DEEPFAKE\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\scipy\spatial\_procrustes.py", line 11, in <module>
    from scipy.linalg import orthogonal_procrustes
  File "C:\DEEPFAKE\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\scipy\linalg\__init__.py", line 195, in <module>
    from .misc import *
  File "C:\DEEPFAKE\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\scipy\linalg\misc.py", line 6, in <module>
    from .lapack import get_lapack_funcs
  File "C:\DEEPFAKE\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\scipy\linalg\lapack.py", line 664, in <module>
    from scipy.linalg import _flapack
ImportError: DLL load failed: The paging file is too small for this operation to complete.

This isn't the only error I've gotten. I've ran the batch file multiple times, and have even gotten tensorflow and numpy import errors, so I don't even know what to do at this point.

## Steps to reproduce

Run the quick96 training .bat on a Zotac 3090, I guess.

## Other relevant information
Windows: Version 10.0.19042 Build 19042
Python 3.6.8

**Comment by StickerMouth** [comment]
I had the same issues. I did some research and this is what I did to fix this:

1. Navigate to "DeepFaceLab_NVIDIA_RTX3000_series\_internal\python_console" and open the console.
2. First you need to upgrade pip so type in the command "python -m pip install --upgrade pip". This should update pip to the latest version
3. Then you need to update tensor flow. Type in the command "pip install --upgrade tensorflow" This should update tensor flow.
4. Now to fix the paging file error. You want to follow the steps [here](https://www.tomshardware.com/news/how-to-manage-virtual-memory-pagefile-windows-10,36929.html) to change pagefile size. DFL is not installed on the C drive for me though so I had to change the values on the drive I had it installed on. I was able to just leave it on "system managed size" but if you are still getting the paging file error you can try manually setting the numbers. If you do it manually you should try setting the minimum to 2 times your RAM and the maximum to 4 times your RAM. For example my minimum would be 64,000MB and my maximum would be 128,000MB (I have 32GB of RAM).

Hopefully this works for you too. If this doesn't work maybe check out [this](https://github.com/iperov/DeepFaceLab/issues/906) post which was pretty helpful for me as well.

**Comment by rylyguy** [comment]
It's not relevant but may I ask why you're using quick96 on a 3090?

**Comment by StickerMouth** [comment]
Ah. Didn't see they were using Quick96. I use SAEHD but I would think the fixes I used should still work.

**Comment by seanawesome** [comment]
> It's not relevant but may I ask why you're using quick96 on a 3090?

I'm using quick96 because that's what I was taught how to use. Every tutorial I've seen so far has used quick96 as the process for deepfaking.

**Comment by StickerMouth** [comment]
> > It's not relevant but may I ask why you're using quick96 on a 3090?
> 
> I'm using quick96 because that's what I was taught how to use. Every tutorial I've seen so far has used quick96 as the process for deepfaking. That's also what I used on my previous 2080.

The guide recommends using SAEHD for high end GPUs with more than 6GB of VRAM. It's also adjustable whereas Quick69 isn't.

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?
