### ISSUE TITLE
XSeg training error when using backup function

### ISSUE THREAD

**Issue by xRoyBx** [iperov/DeepFaceLab#5329]
During Xseg training, when i press the "b" key on my keyboard to make a backup, i always get this error (no problems during training models): maybe because it search for "xseg_xseg_256_opt.npy" where the word "xseg" is repeated two times IDK...

=============== Model Summary ===============
==                                         ==
==        Model name: XSeg                 ==
==                                         ==
== Current iteration: 36                   ==
==                                         ==
==------------- Model Options -------------==
==                                         ==
==         face_type: wf                   ==
==        batch_size: 4                    ==
==                                         ==
==-------------- Running On ---------------==
==                                         ==
==      Device index: 0                    ==
==              Name: GeForce GTX 1060 6GB ==
==              VRAM: 4.74GB               ==
==                                         ==
=============================================
Starting. Press "Enter" to stop training and save model.
Error: [Errno 2] No such file or directory: 'F:\\DeepFaceLab\\workspace\\model\\XSeg_XSeg_256_opt.npy'
Traceback (most recent call last):
  File "F:\DeepFaceLab\_internal\DeepFaceLab\mainscripts\Trainer.py", line 192, in trainerThread
    model_backup()
  File "F:\DeepFaceLab\_internal\DeepFaceLab\mainscripts\Trainer.py", line 79, in model_backup
    model.create_backup()
  File "F:\DeepFaceLab\_internal\DeepFaceLab\models\ModelBase.py", line 435, in create_backup
    shutil.copy ( str(filename), str(idx_backup_path / Path(filename).name) )
  File "shutil.py", line 245, in copy
  File "shutil.py", line 120, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\DeepFaceLab\\workspace\\model\\XSeg_XSeg_256_opt.npy'
Done.

**Comment by Putinv11** [comment]
This happens on colab too with the following error:


[CPU] : CPU
 [0] : Tesla V100-SXM2-16GB

[0] Which GPU index to choose? :
0

Traceback (most recent call last):
 File "/content/DeepFaceLab/main.py", line 336, in <module>
   arguments.func(arguments)
 File "/content/DeepFaceLab/main.py", line 297, in process_xsegapply
   XSegUtil.apply_xseg (Path(arguments.input_dir), Path(arguments.model_dir))
 File "/content/DeepFaceLab/mainscripts/XSegUtil.py", line 57, in apply_xseg
   raise_on_no_model_files=True)
 File "/content/DeepFaceLab/facelib/XSegNet.py", line 73, in __init__
   raise Exception(f'{model_file_path} does not exists.')
Exception: /content/workspace/model/XSeg_256.npy does not exists.

**Comment by 108368115** [comment]
Same ERROR happened on press 'b' to save XSeg model while training XSeg mask model.
As you can see the output show the ERROR that was result in a double 'XSeg_' in path of XSeg_256_opt.npy .
![螢幕擷取畫面 2021-07-14 013324](https://user-images.githubusercontent.com/56882408/125500022-26933ed4-00dc-4f40-abaf-21b18150674b.png)

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?
