### ISSUE TITLE
Will M1 Mac support this?

### ISSUE THREAD

**Issue by DavideVito** [iperov/DeepFaceLab#5335]
Hi,

Well this is not an Issue, but I was wondering if you're planning to make this program available also in M1 Macs,

Thanks.

**Comment by iperov** [comment]
i don't support linux systems, but DFL works on linux.

**Comment by luisdemarchi** [comment]
@iperov  maybe you are mistaken. I'm having a hard time finding all the dependencies already working on the ARM64 architecture (m1 mac), but at first it's going.

Command I couldn't run:
extract --detector manual NOK
extract --detector s3fd OK

train --model SAEHD NOK
train --model Quick96 OK

PS: I'm exactly in training. I hope to reach the end of the process successfully.

After that, would it be possible to have your collaboration (in new issues) for the manual detector and SAEHD training? Both cases fall into "suggest_best_multi_gpu" and the counter starts at zero, where zero is METAL (from Apple) and then fails with trying to read an empty array.

**Comment by luisdemarchi** [comment]
The end result was disastrous, I found it strange that the video took milliseconds to be ready. But I'm happy that I managed to run all the steps with the mac m1.

<img width="745" alt="Captura de Tela 2021-07-09 às 23 18 44" src="https://user-images.githubusercontent.com/461642/125148919-0aae8a00-e10c-11eb-92a1-e3d7becd7b0c.png">

**Comment by datamouth01** [comment]
> The end result was disastrous, I found it strange that the video took milliseconds to be ready. But I'm happy that I managed to run all the steps with the mac m1.
> 
> <img alt="Captura de Tela 2021-07-09 às 23 18 44" width="745" src="https://user-images.githubusercontent.com/461642/125148919-0aae8a00-e10c-11eb-92a1-e3d7becd7b0c.png">

Any luck with this? i have an M1 too.

**Comment by mateuspestana** [comment]
Hey, I'm getting the same (or I think it's the same): 

```
Error: 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/Users/mateuspestana/Downloads/DeepFaceLab_MacOS/.dfl/DeepFaceLab/mainscripts/Trainer.py", line 46, in trainerThread
    model = models.import_model(model_class_name)(
  File "/Users/mateuspestana/Downloads/DeepFaceLab_MacOS/.dfl/DeepFaceLab/models/ModelBase.py", line 161, in __init__
    self.device_config = nn.DeviceConfig.GPUIndexes( force_gpu_idxs or nn.ask_choose_device_idxs(suggest_best_multi_gpu=True)) \
  File "/Users/mateuspestana/Downloads/DeepFaceLab_MacOS/.dfl/DeepFaceLab/core/leras/nn.py", line 215, in ask_choose_device_idxs
    best_device_indexes = [device.index for device in devices.get_equal_devices(devices.get_best_device()) ]
  File "/Users/mateuspestana/Downloads/DeepFaceLab_MacOS/.dfl/DeepFaceLab/core/leras/device.py", line 78, in get_equal_devices
    device_name = device.name
AttributeError: 'NoneType' object has no attribute 'name'
```

How did you manage to fix it?

**Comment by Smiril** [comment]
@luisdemarchi i hung on training on a Mac ... Metal Device ... yes working but there's a problem with libs

specialy with "from utils import Path_utils" and "from utils import std_utils"

have you there a solution? 

Traceback (most recent call last):
  File "/Users/Smiril/Documents/deep/DeepFaceLab_MacOS/.dfl/DeepFaceLab/main.py", line 348, in <module>
    arguments.func(arguments)
  File "/Users/Smiril/Documents/deep/DeepFaceLab_MacOS/.dfl/DeepFaceLab/main.py", line 136, in process_train
    from mainscripts import Trainer
  File "/Users/Smiril/Documents/deep/DeepFaceLab_MacOS/.dfl/DeepFaceLab/mainscripts/Trainer.py", line 13, in <module>
    import models
  File "/Users/Smiril/Documents/deep/DeepFaceLab_MacOS/.dfl/DeepFaceLab/models/__init__.py", line 1, in <module>
    from .ModelBase import ModelBase
  File "/Users/Smiril/Documents/deep/DeepFaceLab_MacOS/.dfl/DeepFaceLab/models/ModelBase.py", line 9, in <module>
    from utils import Path_utils
ImportError: cannot import name 'Path_utils' from 'utils' (/Users/Smiril/Documents/deep/DeepFaceLab_MacOS/.dfl/env/lib/python3.10/site-packages/utils/__init__.py)

**Comment by luisdemarchi** [comment]
unfortunately I had to give up

**Comment by Smiril** [comment]
> unfortunately I had to give up

I'll got success with that source >>> [https://github.com/Smiril/DeepFaceLab_MacOS](https://github.com/Smiril/DeepFaceLab_MacOS)
