### ISSUE TITLE
Failed to load the native TensorFlow runtime 

### ISSUE THREAD

**Issue by JeanBop** [iperov/DeepFaceLab#5344]
**So i've recently installed the deepfacelab direct x 12 build 06_02_2021 on my toshiba laptop with Processor Intel(R) Celeron(R) CPU 1005M @ 1.90GHz, 1900 Mhz, 2 Core(s), 2 Logical Processor(s), and intel(r) hd graphics

and i tried running the 2) extract images from video data_src to test the program but it doesnt work, it just says this:**

_Process Process-1:
Traceback (most recent call last):
  File "C:\Deeplab\DeepFaceLab_DirectX12\_internal\python-3.6.8\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Deeplab\DeepFaceLab_DirectX12\_internal\python-3.6.8\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Deeplab\DeepFaceLab_DirectX12\_internal\python-3.6.8\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 258, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "C:\Deeplab\DeepFaceLab_DirectX12\_internal\DeepFaceLab\core\leras\device.py", line 102, in _get_tf_devices_proc
    import tensorflow
  File "C:\Deeplab\DeepFaceLab_DirectX12\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 102, in <module>
    from tensorflow_core import *
  File "C:\Deeplab\DeepFaceLab_DirectX12\_internal\python-3.6.8\lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Deeplab\DeepFaceLab_DirectX12\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Deeplab\DeepFaceLab_DirectX12\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "importlib\__init__.py", line 126, in import_module
  File "C:\Deeplab\DeepFaceLab_DirectX12\_internal\python-3.6.8\lib\site-packages\tensorflow_core\python\__init__.py", line 55, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Deeplab\DeepFaceLab_DirectX12\_internal\python-3.6.8\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Deeplab\DeepFaceLab_DirectX12\_internal\python-3.6.8\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Deeplab\DeepFaceLab_DirectX12\_internal\python-3.6.8\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Deeplab\DeepFaceLab_DirectX12\_internal\python-3.6.8\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help._

**so after that i tried 10.misc) make CPU only and after it was finished I tried running the 2) again but the same error happened, i searched hours for a fix online but couldn't find any, and solutions or tips? really eager to try this program thanks in advance**

**Comment by iTaKK** [comment]
Your CPU is old and weak.  It doesn't support Directx 12.

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
