### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by benlanben** [iperov/DeepFaceLab#5356]
Windows 10, AMD RX580 8GB, DeepFaceLab_DirectX12_build_07_01_2021

Trying to get back into DFL after I learned there is a DX12 version but getting this error on executing 5) data_dst faceset extract,bat and most other bat files also giving the same error. Am I missing dependencies? DFL 1.0 worked with no problems.

Traceback (most recent call last):
  File "D:\DeepFaceLab_DirectX12\_internal\DeepFaceLab\main.py", line 343, in <module>
    arguments.func(arguments)
  File "D:\DeepFaceLab_DirectX12\_internal\DeepFaceLab\main.py", line 32, in process_extract
    from mainscripts import Extractor
  File "D:\DeepFaceLab_DirectX12\_internal\DeepFaceLab\mainscripts\Extractor.py", line 15, in <module>
    import facelib
  File "D:\DeepFaceLab_DirectX12\_internal\DeepFaceLab\facelib\__init__.py", line 3, in <module>
    from .FANExtractor import FANExtractor
  File "D:\DeepFaceLab_DirectX12\_internal\DeepFaceLab\facelib\FANExtractor.py", line 9, in <module>
    from facelib import FaceType, LandmarksProcessor
  File "D:\DeepFaceLab_DirectX12\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 9, in <module>
    from core import imagelib
  File "D:\DeepFaceLab_DirectX12\_internal\DeepFaceLab\core\imagelib\__init__.py", line 5, in <module>
    from .text import get_text_image, get_draw_text_lines
  File "D:\DeepFaceLab_DirectX12\_internal\DeepFaceLab\core\imagelib\text.py", line 3, in <module>
    from PIL import Image, ImageDraw, ImageFont
ModuleNotFoundError: No module named 'PIL'

**Comment by iperov** [comment]
download build again
