### ISSUE TITLE
After Your Update, DFL Colab 1 Stop Working ModuleNotFoundError: No module named 'tensorflow.compat.v2

### ISSUE THREAD

**Issue by hargums** [iperov/DeepFaceLab#5360]
im facing issue with DFL_Colab_1-0.ipynb (because im using AMD in my physical pc so i choose DFL_Colab_1-0.ipynb in colab)
it stop working, i already use this version of colab for couple week and working fine, but it stop working after new update, please help

Using TensorFlow backend.
Error: No module named 'tensorflow.compat.v2'
Traceback (most recent call last):
File "/content/DeepFaceLab/mainscripts/Trainer.py", line 52, in trainerThread
device_args=device_args)
File "/content/DeepFaceLab/models/ModelBase.py", line 142, in init
nnlib.import_all(self.device_config)
File "/content/DeepFaceLab/nnlib/nnlib.py", line 1613, in import_all
nnlib.import_keras(device_config)
File "/content/DeepFaceLab/nnlib/nnlib.py", line 229, in import_keras
import keras as keras_
File "/usr/local/lib/python3.7/dist-packages/keras/init.py", line 3, in
from . import utils
File "/usr/local/lib/python3.7/dist-packages/keras/utils/init.py", line 27, in
from .multi_gpu_utils import multi_gpu_model
File "/usr/local/lib/python3.7/dist-packages/keras/utils/multi_gpu_utils.py", line 7, in
from ..layers.merge import concatenate
File "/usr/local/lib/python3.7/dist-packages/keras/layers/init.py", line 4, in
from ..engine.base_layer import Layer
File "/usr/local/lib/python3.7/dist-packages/keras/engine/init.py", line 3, in
from .input_layer import Input
File "/usr/local/lib/python3.7/dist-packages/keras/engine/input_layer.py", line 7, in
from .base_layer import Layer
File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 12, in
from .. import initializers
File "/usr/local/lib/python3.7/dist-packages/keras/initializers/init.py", line 17, in
import tensorflow.compat.v2 as tf
ModuleNotFoundError: No module named 'tensorflow.compat.v2'

please help

**Comment by iperov** [comment]
why 1.0? use latest

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
