### ISSUE TITLE
Error message: XSeg_256.npy does not exists, when I tried to apply mask to images

### ISSUE THREAD

**Issue by dsyrock** [iperov/DeepFaceLab#5365]
Traceback (most recent call last):
  File "main.py", line 343, in <module>
    arguments.func(arguments)
  File "main.py", line 304, in process_xsegapply
    XSegUtil.apply_xseg (Path(arguments.input_dir), Path(arguments.model_dir))
  File "/content/drive/My Drive/DeepFaceLab/DeepFaceLab_Colab/mainscripts/XSegUtil.py", line 57, in apply_xseg
    raise_on_no_model_files=True)
  File "/content/drive/My Drive/DeepFaceLab/DeepFaceLab_Colab/facelib/XSegNet.py", line 73, in __init__
    raise Exception(f'{model_file_path} does not exists.')
Exception: /content/drive/My Drive/DeepFaceLab/workspace/model/XSeg_256.npy does not exists.

I'm sure the file is there. When I use the v2.06.19 of DFL, it's totally OK.

**Comment by dsyrock** [comment]
I know what's wrong now. I'm using the old xseg model created by old version of DFL.

**Comment by iperov** [comment]
v2.06.19 ? are you serious?

**Comment by dsyrock** [comment]
Yep, I'm using a new version and an old version at the same time.

**Comment by aravindcheruvu** [comment]
Hello,
I am getting this same error. Could you please let me know how to resolve this?

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?
