### ISSUE TITLE
When merging with this parameter: --force-gpu-idxs 0 get wrong message

### ISSUE THREAD

**Issue by dsyrock** [iperov/DeepFaceLab#5366]
Loading gong_SAEHD model...
Traceback (most recent call last):
  File "/content/drive/My Drive/DeepFaceLab2/DeepFaceLab_Colab/mainscripts/Merger.py", line 53, in main
    cpu_only=cpu_only)
  File "/content/drive/My Drive/DeepFaceLab2/DeepFaceLab_Colab/models/ModelBase.py", line 162, in __init__
    if not cpu_only else nn.DeviceConfig.CPU()
  File "/content/drive/My Drive/DeepFaceLab2/DeepFaceLab_Colab/core/leras/nn.py", line 294, in GPUIndexes
    devices = Devices.getDevices().get_devices_from_index_list(indexes)
  File "/content/drive/My Drive/DeepFaceLab2/DeepFaceLab_Colab/core/leras/device.py", line 73, in get_devices_from_index_list
    if device.index in idx_list:
TypeError: 'in <string>' requires string as left operand, not int

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?

**Comment by gteachey** [comment]
There's a bug in the main.py script.

Line 176 - [https://github.com/iperov/DeepFaceLab/blob/46fc2397c582b9fc375a023418257924112e292b/main.py#L176](url)
 force_gpu_idxs         = arguments.force_gpu_idxs,

needs to be like line 130 - [https://github.com/iperov/DeepFaceLab/blob/46fc2397c582b9fc375a023418257924112e292b/main.py#L130C18-L130C154](url)
'force_gpu_idxs'           : [ int(x) for x in arguments.force_gpu_idxs.split(',') ] if arguments.force_gpu_idxs is not None else None,

After updating my file, this parameter starts working properly for me
