### ISSUE TITLE
Tensorflow Error

### ISSUE THREAD

**Issue by Carlisms** [iperov/DeepFaceLab#5377]
Hey,
I am using the prebuilt version of DFL, but could not get it to run:
My setup:

RTX3090

NVIDIA 471.41
CUDA 11.2
CUDNN 8.1 for CUDA 11.2

tensorflow 2.5.0
tensorflow-gpu 2.5.0

VC_redist.x64 is installed

The error:

Extracting faces...
Running on NVIDIA GeForce RTX 3090
  0%|                                                                                                                                             | 0/4624 [00:00<?, ?it/s]

Error while processing data: Traceback (most recent call last):
  File "C:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "C:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "C:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node Conv2D}}]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node Conv2D}}]]
         [[Add_29/_4049]]
0 successful operations.
0 derived errors ignored.

I have 2 PCs (one with a 1060) and I get the same error there.
Any ideas?

**Comment by Cioscos** [comment]
Did you download the RTX3000 version?

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?
