### ISSUE TITLE
xseg dll 

### ISSUE THREAD

**Issue by fullmetal1221** [iperov/DeepFaceLab#5382]
normal process until 5.XSeg) data_dst mask-edit.bat

when running receive this error
Traceback (most recent call last):
  File "F:\deepface labs\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\main.py", line 343, in <module>
    arguments.func(arguments)
  File "F:\deepface labs\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\main.py", line 291, in process_xsegeditor
    from XSegEditor import XSegEditor
  File "F:\deepface labs\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\XSegEditor\XSegEditor.py", line 15, in <module>
    from PyQt5.QtCore import *
ImportError: DLL load failed: The specified procedure could not be found.
Press any key to continue . . .

using windows 10 2080TI with updated drivers and hardware accelerated gpu scheduling on

**Comment by jsilva89** [comment]
hey fullmetal, did you resolve this? im having the same exact error. Xseg simply wont work for me and I have python installed if that makes a difference
