### ISSUE TITLE
xseg train not working 

### ISSUE THREAD

**Issue by gili12345** [iperov/DeepFaceLab#5389]
after i finished to do " mask edit " to destination file and source file ,i have a problem with the "xseg train " it show me the next message - " error oom when allocating tensor with shape " 
what could be the problem ? 
![error](https://user-images.githubusercontent.com/88238786/131175825-b1d5ddb6-6372-4dda-8941-00382bbde232.JPG)

**Comment by sofianbello** [comment]
Im also struggeling to make it work. 

I either
- receive the above mentioned Error,
- my display flashes some apps crash and the XsegTrain.bat is not doing anything at all (Froze/Crashed)
- or I receive this error:
`Loading samples: 100%|##############################################################| 592/592 [00:01<00:00, 477.63it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "X:\BRIVALS\DEEPFAKE\DeepFaceLab_NVIDIA_up_to_RTX2080Ti_2021\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
    from .Sample import Sample
  File "X:\BRIVALS\DEEPFAKE\DeepFaceLab_NVIDIA_up_to_RTX2080Ti_2021\_internal\DeepFaceLab\samplelib\Sample.py", line 7, in <module>
    from core.cv2ex import *
  File "X:\BRIVALS\DEEPFAKE\DeepFaceLab_NVIDIA_up_to_RTX2080Ti_2021\_internal\DeepFaceLab\core\cv2ex.py", line 5, in <module>
    from core import imagelib
  File "X:\BRIVALS\DEEPFAKE\DeepFaceLab_NVIDIA_up_to_RTX2080Ti_2021\_internal\DeepFaceLab\core\imagelib\__init__.py", line 5, in <module>
    from .text import get_text_image, get_draw_text_lines
  File "X:\BRIVALS\DEEPFAKE\DeepFaceLab_NVIDIA_up_to_RTX2080Ti_2021\_internal\DeepFaceLab\core\imagelib\text.py", line 3, in <module>
    from PIL import Image, ImageDraw, ImageFont
  File "X:\BRIVALS\DEEPFAKE\DeepFaceLab_NVIDIA_up_to_RTX2080Ti_2021\_internal\python-3.6.8\lib\site-packages\PIL\Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: DLL load failed: Die Auslagerungsdatei ist zu klein, um diesen Vorgang durchzuführen.`

![image](https://user-images.githubusercontent.com/87645100/137499152-2641407f-ec74-4419-b36c-f369213c6347.png)

Running on Win 10
2080 TI driver 472.12 (Studio)
CUDA 11.4

**Comment by Smiril** [comment]
`Die Auslagerungsdatei ist zu klein, um diesen Vorgang durchzuführen`

that means too less space on hard drive ... solution ... delete some files

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
