### ISSUE TITLE
Exception: pretraining_data_path is not defined

### ISSUE THREAD

**Issue by onefish51** [iperov/DeepFaceLab#5394]
I found a model form 

[@aymanalz](https://mrdeepfakes.com/forums/user-aymanalz)

DF-UD - res: 160, dims: 320/80/80/32, 875.000 iterations, Whole face (SFW - FFHQ Female Only)
https://drive.google.com/file/d/113QfJzj...YKrbk/view

when I export the SHEAD model to dfm into the deepfacelive app  , occur this error
```sh
Choose one of saved models, or enter a name to create a new model.
[r] : rename
[d] : delete

[0] : new - latest
 : 0
0
Loading new_SAEHD model...
Traceback (most recent call last):
  File "./DeepFaceLab/main.py", line 344, in <module>
    arguments.func(arguments)
  File "./DeepFaceLab/main.py", line 155, in process_exportdfm
    ExportDFM.main(model_class_name = arguments.model_name, saved_models_path = Path(arguments.model_dir))
  File "/app/DeepFaceLab/mainscripts/ExportDFM.py", line 21, in main
    cpu_only=True)
  File "/app/DeepFaceLab/models/ModelBase.py", line 180, in __init__
    self.on_initialize_options()
  File "/app/DeepFaceLab/models/Model_SAEHD/Model.py", line 178, in on_initialize_options
    raise Exception("pretraining_data_path is not defined")
Exception: pretraining_data_path is not defined
```
How do I fix this error?

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?
