### ISSUE TITLE
AttributeError: module 'ffmpeg' has no attribute 'input'

### ISSUE THREAD

**Issue by Sxmyyy** [iperov/DeepFaceLab#5408]
Traceback (most recent call last):
  File "main.py", line 331, in <module>
    arguments.func(arguments)
  File "main.py", line 221, in process_videoed_extract_video
    VideoEd.extract_video (arguments.input_file, arguments.output_dir, arguments.output_ext, arguments.fps)
  File "/Users/samy/Documents/Dev/DeepFake/DeepFaceLab/mainscripts/VideoEd.py", line 35, in extract_video
    job = ffmpeg.input(str(input_file_path))
AttributeError: module 'ffmpeg' has no attribute 'input'

**Comment by Cfrolich13** [comment]
Sorry to comment on a closed issue, but I got this exact same error today while trying to extract frames from a video. I ran into this error on a fresh version of DeepFaceLab straight from the master branch of this repo. Do you mind sharing how you resolved this?
