### ISSUE TITLE
Error after updating the code

### ISSUE THREAD

**Issue by labels168** [iperov/DeepFaceLab#5426]
The version I use is normal
"DeepFaceLab_NVIDIA_up_to_RTX2080Ti_build_10_20_2021"

But updated the code
https://github.com/iperov/DeepFaceLab.git
These error messages appear.
Traceback (most recent call last):
  File "C:\DF_2021_1020\_internal\DeepFaceLab\main.py", line 343, in <module>arguments.func(arguments)
  File "C:\DF_2021_1020\_internal\DeepFaceLab\main.py", line 131, in process_train from mainscripts import Trainer
  File "C:\DF_2021_1020\_internal\DeepFaceLab\mainscripts\Trainer.py", line 11, in <module> from core import imagelib
  File "C:\DF_2021_1020\_internal\DeepFaceLab\core\imagelib\__init__.py", line 15,in <module> from .color_transfer importcolor_transfer,color_transfer_mix, color_transfer_sot, color_transfer_mkl, color_transfer_idt, color_hist_match, reinhard_color_transfer, linear_color_transfer
  File "C:\DF_2021_1020\_internal\DeepFaceLab\core\imagelib\color_transfer.py", line 2, in <module> import numexpr as ne
ModuleNotFoundError: No module named 'numexpr'

I did something wrong there, please help, thank you very much!

**Comment by NvrTdp** [comment]
Same. Happens on everything. Sorting faces, training...

**Comment by iTaKK** [comment]
Just use the one in package and don't update the code from Git.  He didn't update the package to include numexpr yet.  If you can't wait then you can open the python console and run 'pip install numexpr'

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?
