### ISSUE TITLE
please ㅠㅠ

### ISSUE THREAD

**Issue by zeothemd** [iperov/DeepFaceLab#5427]
Starting. Press "Enter" to stop training and save model.

Trying to do the first iteration. If an error occurs, reduce the model parameters.

!!!
Windows 10 users IMPORTANT notice. You should set this setting in order to work correctly.
https://i.imgur.com/B7cmDCB.jpg
!!!
You are training the model from scratch. It is strongly recommended to use a pretrained model to speed up the training and improve the quality.

Error:
Traceback (most recent call last):
  File "C:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\Trainer.py", line 159, in trainerThread
    model_save()
  File "C:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\Trainer.py", line 68, in model_save
    model.save()
  File "C:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\ModelBase.py", line 393, in save
    self.onSave()
  File "C:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 759, in onSave
    model.save_weights ( self.get_strpath_storage_for_file(filename) )
  File "C:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\Saveable.py", line 61, in save_weights
    d_dumped = pickle.dumps (d, 4)
MemoryError

Can I know some solution?

**Comment by zabique** [comment]
Not enough system RAM to save  pickle file. Upgrade to 32GB or increase Page file to 64 GB

**Comment by qkum** [comment]
Maybe you should start your programming journey with something n00b friendly instead of professional-level stuff :) 

(he just created his github account in November 2021)

Kali Linux video tutorials are a great start imo.

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
