### ISSUE TITLE
September and October versions do not work

### ISSUE THREAD

**Issue by crueldarkness** [iperov/DeepFaceLab#5430]
My System
cpu : i9-10900
gpu : rtx3070 8GB
ram : 64GB

It worked fine until the August version.  (DeepFaceLab_NVIDIA_RTX3000_series_build_8_12_2021)

But September and October versions do not work.
When I executed 'train SAEHD' on 'NVIDIA_RTX3000_series_build_10_20_2021',  the following error message appears

How can i solve this problem?

ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last): 
  File "<string>", line 1, in <module> 
  File "multiprocessing\spawn.py", line 105, in spawn_main 
  File "multiprocessing\spawn.py", line 115, in _main 
  File "D:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\__init_py", line 1, in <module> from .SubprocessorBase import Subprocessor 
  File "D:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 5, in <module> from core.interact import interact as io 
  File "D:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\__init_py", line 1, in <module> from .interact import interact 
  File "D:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module> import cv2 
  File "D:\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\1ib\site-packages\cv2\__init_py", line 3, in <module>  from .cv2 import *
ImportError: numpy.core.multiarray failed to import 

The options I used are as follows:
resolution: 192                 
face_type: wf                     
models_opt_on_gpu: True                
archi: liae-ud              
ae_dims: 256                   
e_dims: 64                   
d_dims: 64           
d_mask_dims: 22                  
masked_training: True              
eyes_mouth_prio: False       
uniform_yaw: False               
adabelief: True                 
lr_dropout: n                      
random_warp: True                
true_face_power: 0.0                   
face_style_power: 0.0                
bg_style_power: 0.0                  
ct_mode: none               
clipgrad: False                
pretrain: False                
autobackup_hour: 0                   
write_preview_history: False          
target_iter: 0                      
random_src_flip: False               
random_dst_flip: True                   
batch_size: 16                   
gan_power: 0.0                  
gan_patch_size: 40                    
gan_dims: 16

**Comment by havetc** [comment]
Same problem for me!

**Comment by Nerogante** [comment]
A little late but make sure to run **"1) clear workspace.bat"** so the program uses the correct python version and its packages (the ones on _internal)
and/or uninstall python from your system to avoid conflicts.
:)

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
