### ISSUE TITLE
Dual core CPU problem

### ISSUE THREAD

**Issue by zungmg** [iperov/DeepFaceLab#5431]
I try 2 different PC. First Dualcore xeon + Rtx 2080ti and Second CoreI7 + Rtx 2080. And Second Pc single Core working smooth. First PC dualcore only Quick96 working and SAEHD, XSeg mask training stuck or error, pageing file problem. Is it a problem with Dualcore Pc ?

**Comment by zungmg** [comment]
Running trainer.

Loading XSeg model...

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce RTX 2080 Ti

[0] Which GPU indexes to choose? :
0

Loading samples: 100%|###############################################################| 281/281 [00:04<00:00, 59.02it/s]
Loading samples: 100%|##############################################################| 242/242 [00:01<00:00, 127.71it/s]
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: numpy.core.multiarray failed to import
  File "multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
    from .Sample import Sample
    from .Sample import Sample
    from .Sample import Sample
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\Sample.py", line 4, in <module>
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\Sample.py", line 4, in <module>
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\Sample.py", line 4, in <module>
    import cv2
    import cv2
    import cv2
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
    from .cv2 import *
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
ImportError: numpy.core.multiarray failed to import
  File "multiprocessing\spawn.py", line 115, in _main
Traceback (most recent call last):
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
  File "<string>", line 1, in <module>
    from .Sample import Sample
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\Sample.py", line 4, in <module>
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
  File "multiprocessing\spawn.py", line 115, in _main
ImportError: numpy.core.multiarray failed to import
    import cv2
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
    from .Sample import Sample
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from .cv2 import *
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\Sample.py", line 4, in <module>
  File "<string>", line 1, in <module>
ImportError: numpy.core.multiarray failed to import
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 115, in _main
    import cv2
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
    from .Sample import Sample
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
    from .Sample import Sample
    from .cv2 import *
  File "multiprocessing\spawn.py", line 115, in _main
    from .Sample import Sample
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\Sample.py", line 4, in <module>
    from .Sample import Sample
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\Sample.py", line 4, in <module>
ImportError: numpy.core.multiarray failed to import
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\Sample.py", line 4, in <module>
    import cv2
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\Sample.py", line 4, in <module>
    import cv2
    from .Sample import Sample
    import cv2
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
    import cv2
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\samplelib\Sample.py", line 4, in <module>
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
    import cv2
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
  File "D:\_Programs\AI\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import

**Comment by qkum** [comment]
Bro, dual-core is totally outdated hardware in 2021.
Dual-core = 2 CPU cores.
Any average western gaming pc got like 16 CPU cores in 2021.

Intel Wiki page even says they were discontinued back in 2006.

Sorry fren, this is professional-grade machine learning software. 
You need some powerful hardware to run cutting-edge software.

**Comment by qkum** [comment]
Read the error message bro.

`ImportError: numpy.core.multiarray failed to import`

**Comment by ghost** [comment]
There is no hope to save you, please close the issue.
