### ISSUE TITLE
Issue when using "6) export AMP as dfm"

### ISSUE THREAD

**Issue by dread1900** [iperov/DeepFaceLab#5433]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior
When trying to use "6) train AMP SRC-SRC" to use for DeepFaceLive, everything looked fine. No errors.

## Actual behavior

After letting it train for an hour, I wanted to test it and see if it will work. When trying to export it as a .dfm model this error ocurrs.

Error Logs:
  File "C:\Users\dread\Desktop\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\tf2onnx\onnx_opset\tensor.py", line 274, in version_1
    if inp.is_const() and inp.get_tensor_value(as_list=False).size == 0:
AttributeError: 'NoneType' object has no attribute 'is_const'
Traceback (most recent call last):
  File "C:\Users\dread\Desktop\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\main.py", line 343, in <module>
    arguments.func(arguments)
  File "C:\Users\dread\Desktop\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\main.py", line 154, in process_exportdfm
    ExportDFM.main(model_class_name = arguments.model_name, saved_models_path = Path(arguments.model_dir))
  File "C:\Users\dread\Desktop\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\mainscripts\ExportDFM.py", line 22, in main
    model.export_dfm ()
  File "C:\Users\dread\Desktop\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\DeepFaceLab\models\Model_AMP\Model.py", line 628, in export_dfm
    output_path=output_path)
  File "C:\Users\dread\Desktop\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\tf2onnx\convert.py", line 153, in _convert_common
    g = process_tf_graph(tf_graph, const_node_values=const_node_values, **kwargs)
  File "C:\Users\dread\Desktop\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\tf2onnx\tfonnx.py", line 535, in process_tf_graph
    output_names, initialized_tables, outputs_to_values, outputs_to_dtypes, op_cnt, attr_cnt)
  File "C:\Users\dread\Desktop\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\tf2onnx\tfonnx.py", line 637, in process_parsed_graph
    raise exceptions[0]
  File "C:\Users\dread\Desktop\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\tf2onnx\tfonnx.py", line 294, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File "C:\Users\dread\Desktop\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\tf2onnx\onnx_opset\tensor.py", line 343, in version_1
    _ = GraphBuilder(ctx).make_slice(kwargs, name=node.name)
  File "C:\Users\dread\Desktop\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\tf2onnx\graph_builder.py", line 40, in make_slice
    starts = self.convert_to_attribute(kwargs.pop("starts"))
  File "C:\Users\dread\Desktop\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\tf2onnx\graph_builder.py", line 224, in convert_to_attribute
    res = const_node.get_tensor_value(as_list=True)
  File "C:\Users\dread\Desktop\DeepFaceLab_NVIDIA_up_to_RTX2080Ti\_internal\python-3.6.8\lib\site-packages\tf2onnx\graph.py", line 317, in get_tensor_value
    raise ValueError("get tensor value: '{}' must be Const".format(self.name))
ValueError: get tensor value: 'Slice_3/begin_Concat__109' must be Const
Press any key to continue . . .

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version: Windows 10 Build  Version 10.0.19043 Build 19043
- **Python version:** 3.5, 3.6.4, ... (if you are not using prebuilt windows binary)

**Comment by BlankFX1** [comment]
This is already issued in #5422.

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
