### ISSUE TITLE
Any chance to run FaceLab on M1 pro/max

### ISSUE THREAD

**Issue by OhWhoYouAre** [iperov/DeepFaceLab#5442]
Apple Release new powerful silicon M1 pro/max.
It is a good platform to develop.
Please!

**Comment by iTaKK** [comment]
Probably not, Dev doesn't support Linux.  Also training a model with a CPU, M1 for example will be very slow.  It's better to use the GPU (Nvidia/AMD) as they're ALOT faster than CPU when it comes to training.

**Comment by qkum** [comment]
Stop falling for marketing hype.

A "good platform" just means it is "good" lol.

Nothing more or less.

**Comment by gimmel** [comment]
> Probably not, Dev doesn't support Linux. Also training a model with a CPU, M1 for example will be very slow. It's better to use the GPU (Nvidia/AMD) as they're ALOT faster than CPU when it comes to training.

Don’t underestimate the Apple Silicon M1 Chip. It has up to 10-Core CPU, 32-Core GPU, 16‑Core Neural Engine with 200GB/s memory bandwidth in one Chip. In a laptop! Should be perfect for DeepFaceLab.

**Comment by mateuspestana** [comment]
I'm training models on my M1 Pro and it's better than many GPUs here. With a little change from TensorFlow to tensorflow-metal and tensorflow-macos, and you are good to go. There is a repository here: [DeepFaceLab_MacOS](https://github.com/chychkan/DeepFaceLab_MacOS)

**Comment by gimmel** [comment]
Wohoooo! Great! Finally! Thank you! I searched for hours but did not find any MacOS Silicon implementations.

Unfortunately the compiler breaks with some errors:
```
ERROR: Could not find a version that satisfies the requirement opencv-contrib-python-headless==4.5.1.48 (from versions: 3.4.0.14, 3.4.11.45, 3.4.13.47, 3.4.14.51, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 4.4.0.46, 4.5.1.48, 4.5.2.52, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62)
ERROR: No matching distribution found for opencv-contrib-python-headless==4.5.1.48
```
and
```
Ignoring numpy: markers 'python_version == "3.8" and platform_machine != "aarch64"' don't match your environment
```
because my python3 version seems to be too new (3.9.10). Will need some work. Sigh.

(I bought my MacBook Pro M1 for 3D rendering and cutting videos, but my most used app is Terminal for compiling really hot shit for the silicon processor. 😁)

**Comment by Smiril** [comment]
> > Probably not, Dev doesn't support Linux. Also training a model with a CPU, M1 for example will be very slow. It's better to use the GPU (Nvidia/AMD) as they're ALOT faster than CPU when it comes to training.
> 
> Don’t underestimate the Apple Silicon M1 Chip. It has up to 10-Core CPU, 32-Core GPU, 16‑Core Neural Engine with 200GB/s memory bandwidth in one Chip. In a laptop! Should be perfect for DeepFaceLab.

it gave me following error:

`Traceback (most recent call last):
  File "/Users/Smiril/Documents/deep/DeepFaceLab_MacOS-master/.dfl/DeepFaceLab/main.py", line 6, in <module>
    from core.leras import nn
  File "/Users/Smiril/Documents/deep/DeepFaceLab_MacOS-master/.dfl/DeepFaceLab/core/leras/__init__.py", line 1, in <module>
    from .nn import nn
  File "/Users/Smiril/Documents/deep/DeepFaceLab_MacOS-master/.dfl/DeepFaceLab/core/leras/nn.py", line 25, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'`

**Comment by dschingh1s** [comment]
I got the same issue as @Smiril have somebody any updates?
There are 2 ways here on github i am not very familiar with programming but did everything more then once exactly as descripted but i don´t get it

**Comment by Smiril** [comment]
@dschingh1s see: https://github.com/Smiril/DeepFaceLab_MacOS

**Comment by ngardelis** [comment]
@Smiril what does the below do from the repo? Please explain. cd scripts
./2_extract_images_from_video_data_src.sh  
./3_extract_images_from_video_data_dst.sh
./4.1_data_src_extract_faces_S3FD.sh <<< on GPU
./5_data_dst_extract_faces_S3FD_best_GPU.sh <<< on GPU
./6_train_Quick96.sh <<< on GPU
./7_convert_Quick96.sh <<< on CPU
./8_converted_to_avi.sh

**Comment by ngardelis** [comment]
> > > Probably not, Dev doesn't support Linux. Also training a model with a CPU, M1 for example will be very slow. It's better to use the GPU (Nvidia/AMD) as they're ALOT faster than CPU when it comes to training.
> > 
> > 
> > Don’t underestimate the Apple Silicon M1 Chip. It has up to 10-Core CPU, 32-Core GPU, 16‑Core Neural Engine with 200GB/s memory bandwidth in one Chip. In a laptop! Should be perfect for DeepFaceLab.
> 
> it gave me following error:
> 
> `Traceback (most recent call last): File "/Users/Smiril/Documents/deep/DeepFaceLab_MacOS-master/.dfl/DeepFaceLab/main.py", line 6, in <module> from core.leras import nn File "/Users/Smiril/Documents/deep/DeepFaceLab_MacOS-master/.dfl/DeepFaceLab/core/leras/__init__.py", line 1, in <module> from .nn import nn File "/Users/Smiril/Documents/deep/DeepFaceLab_MacOS-master/.dfl/DeepFaceLab/core/leras/nn.py", line 25, in <module> import numpy as np ModuleNotFoundError: No module named 'numpy'`
> 
> # Metal Info:
> Metal.Version.: 261.13
> 
> Backend Device ID #1 (Alias: #2) Type...........: GPU Vendor.ID......: 2 Vendor.........: Apple Name...........: Apple M1 Max Processor(s)...: 32 Clock..........: N/A Memory.Total...: 49152 MB (limited to 18432 MB allocatable in one block) Memory.Free....: 24512 MB Local.Memory...: 32 KB Phys.Location..: built-in Feature.Set....: macOS GPU Family 2 v1 Registry.ID....: 2292 Max.TX.Rate....: N/A GPU.Properties.: headless 0, low-power 0, removable 0
> 
> # OpenCL Info:
> OpenCL Platform ID #1 Vendor..: Apple Name....: Apple Version.: OpenCL 1.2 (Feb 12 2022 01:56:48)
> 
> Backend Device ID #2 (Alias: #1) Type...........: GPU Vendor.ID......: 2 Vendor.........: Apple Name...........: Apple M1 Max Version........: OpenCL 1.2 Processor(s)...: 32 Clock..........: 1000 Memory.Total...: 49152 MB (limited to 4608 MB allocatable in one block) Memory.Free....: 24512 MB Local.Memory...: 32 KB OpenCL.Version.: OpenCL C 1.2 Driver.Version.: 1.2 1.0

Hey man did you fix the error? got the same as you

**Comment by ngardelis** [comment]
I got the same error as @Smiril and @dschingh1s  did you manage to fix it guys??

**Comment by ngardelis** [comment]
@mateuspestana do you happen to know how to solve the errors we get? since you manage to run it

**Comment by Smiril** [comment]
@ngradelis

See full run on my repo
Some work with GPU some with CPU 

see @dschingh1s posted the link

**Comment by ngardelis** [comment]
Hi @Smiril I have mbp m1 and tried out your repo for all Python versions. The one version I was most successful was the 3.10 Python version but whenever I run quicktrain96 the preview wouldn't open and the frames between the cropped faces didn't update they where gray columns even after 10.000 iterations. I think there is something wrong with the requirements for each Python version because I followed every step in the tutorial

**Comment by Smiril** [comment]
Run from 100000-1000000 iterations 
Use a mp4 source and target

**Comment by Smiril** [comment]
> Hi @Smiril I have mbp m1 and tried out your repo for all Python versions. The one version I was most successful was the 3.10 Python version but whenever I run quicktrain96 the preview wouldn't open and the frames between the cropped faces didn't update they where gray columns even after 10.000 iterations. I think there is something wrong with the requirements for each Python version because I followed every step in the tutorial

@ngradelis what repo do you use ?

**Comment by bhuiyanmobasshir94** [comment]
I am failing to set up the environment. Does anyone have a better solution for the environment setup for Mac M1?

**Comment by Smiril** [comment]
> I am failing to set up the environment. Does anyone have a better solution for the environment setup for Mac M1?

Did you install brew? -> virtualenviroment?
