### ISSUE TITLE
getting this error after reinstalling windows

### ISSUE THREAD

**Issue by CYBORGX002** [iperov/DeepFaceLab#5443]
Traceback (most recent call last):
  File "D:\dfl\DeepFaceLab_DirectX12\_internal\DeepFaceLab\main.py", line 6, in <module>
    from core.leras import nn
  File "D:\dfl\DeepFaceLab_DirectX12\_internal\DeepFaceLab\core\leras\__init__.py", line 1, in <module>
    from .nn import nn
  File "D:\dfl\DeepFaceLab_DirectX12\_internal\DeepFaceLab\core\leras\nn.py", line 26, in <module>
    from core.interact import interact as io
  File "D:\dfl\DeepFaceLab_DirectX12\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
    from .interact import interact
  File "D:\dfl\DeepFaceLab_DirectX12\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
    import cv2
  File "D:\dfl\DeepFaceLab_DirectX12\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: DLL load failed: The spec
![Capture](https://user-images.githubusercontent.com/95993897/145700999-f4c5a85e-1f8d-44f0-aba8-2508c0a3fb5f.PNG)
ified module could not be found.
Press any key to continue . . .

**Comment by qkum** [comment]
Try reading the 2d last line of the output.

It is telling you the DLL module is missing.

You should google what the "DDL" module is and how to install it.

But now the developer will see this post and can fix it if the problem is on his side.

Thanks for the heads up on his behalf :)

( I'm not a developer on this repo btw)

**Comment by CYBORGX002** [comment]
> It is telling you the "cv2" module is missing. ( that is the module it tried to import but failed, line 3) `from .cv2 import * ` (* means import everything)
> 
> You should google what the "cv2" module is and how to install it.
> 
> But now the developer will see this post and can fix it if the problem is on his side.
> 
> Thanks for the heads up on his behalf :)
> 
> ( I'm not a developer on this repo btw)

tnq
bt now im getting new error it wont let me to train stuck by saying press any key to continue

**Comment by deyu260** [comment]
don't use windows 10 with n version , n meaning The N version of Windows comes without a media player baked into the system. available to customers in Europe, does not include Media Play back capabilities, but can be downloaded separately. It is available in Home, Pro and Enterprise editions too.

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?
