### ISSUE TITLE
Preview Crash related to get_loss_history_preview

### ISSUE THREAD

**Issue by BlankFX1** [iperov/DeepFaceLab#5448]
## Expected behavior

Training continues without giving out an Error.

## Actual behavior

The following error is given out and the preview window stops working (or does not even appear the training was just re-started).
The training itself *seems* to continue, but instead of giving valid loss values, the cmd-log only shows "[nan]".

The error does not appear to relate to an OutOfMemory-Issue. Tested this by reducing the batch size.

`Running trainer.

Choose one of saved models, or enter a name to create a new model.
[r] : rename
[d] : delete

[0] : SiaV2 - latest
[1] : SiaV1
 :
0
Loading SiaV2_AMP model...

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : NVIDIA GeForce RTX 3080 Ti

[0] Which GPU indexes to choose? :
0

Press enter in 2 seconds to override model settings.
[1] Autobackup every N hour ( 0..24 ?:help ) :
1
[y] Write preview history ( y/n ?:help ) :
y
[n] Choose image for the preview history ( y/n ) :
n
[0] Target iteration :
0
[n] Flip SRC faces randomly ( y/n ?:help ) :
n
[y] Flip DST faces randomly ( y/n ?:help ) :
y
[10] Batch_size ( ?:help ) : 9
9
[y] Uniform yaw distribution of samples ( y/n ?:help ) :
y
[n] Blur out mask ( y/n ?:help ) :
n
[y] Use learning rate dropout ( n/y/cpu ?:help ) :
y
[y] Place models and optimizer on GPU ( y/n ?:help ) :
y
[n] Enable random warp of samples ( y/n ?:help ) :
n
[0.0] GAN power ( 0.0 .. 5.0 ?:help ) :
0.0
[none] Color transfer for src faceset ( none/rct/lct/mkl/idt/sot ?:help ) :
none
[n] Enable gradient clipping ( y/n ?:help ) :
n
Initializing models: 100%|###############################################################| 5/5 [00:02<00:00,  2.26it/s]
Loaded 11230 packed faces from S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\workspace\data_src\aligned
Sort by yaw: 100%|##################################################################| 128/128 [00:00<00:00, 463.36it/s]
Sort by yaw: 100%|##################################################################| 128/128 [00:00<00:00, 448.71it/s]
==================== Model Summary ====================
==                                                   ==
==            Model name: SiaV2_AMP        ==
==                                                   ==
==     Current iteration: 407587                     ==
==                                                   ==
==------------------ Model Options ------------------==
==                                                   ==
==            resolution: 320                        ==
==             face_type: wf                         ==
==     models_opt_on_gpu: True                       ==
==               ae_dims: 256                        ==
==            inter_dims: 320                        ==
==                e_dims: 72                         ==
==                d_dims: 72                         ==
==           d_mask_dims: 22                         ==
==          morph_factor: 0.5                        ==
==           uniform_yaw: True                       ==
==         blur_out_mask: False                      ==
==            lr_dropout: y                          ==
==           random_warp: False                      ==
==               ct_mode: none                       ==
==              clipgrad: False                      ==
==       autobackup_hour: 1                          ==
== write_preview_history: True                       ==
==           target_iter: 0                          ==
==       random_src_flip: False                      ==
==       random_dst_flip: True                       ==
==            batch_size: 9                          ==
==             gan_power: 0.0                        ==
==        gan_patch_size: 40                         ==
==              gan_dims: 16                         ==
==                                                   ==
==------------------- Running On --------------------==
==                                                   ==
==          Device index: 0                          ==
==                  Name: NVIDIA GeForce RTX 3080 Ti ==
==                  VRAM: 9.22GB                     ==
==                                                   ==
=======================================================
Starting. Press "Enter" to stop training and save model.
Traceback (most recent call last):an]
  File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\main.py", line 343, in <module>
    arguments.func(arguments)
  File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\main.py", line 132, in process_train
    Trainer.main(**kwargs)
  File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\Trainer.py", line 317, in main
    lh_img = models.ModelBase.get_loss_history_preview(loss_history_to_show, iter, w, c)
  File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\ModelBase.py", line 627, in get_loss_history_preview
    ph_max = int ( (plist_max[col][p] / plist_abs_max) * (lh_height-1) )
ValueError: cannot convert float NaN to integer
Process Process-36:[0527ms][nan][nan]
Traceback (most recent call last):
  File "multiprocessing\process.py", line 258, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\ModelBase.py", line 668, in process
    preview_lh = ModelBase.get_loss_history_preview(loss_history, iter, preview.shape[1], preview.shape[2])
  File "S:\DeepFaceLab3080Ti\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\ModelBase.py", line 627, in get_loss_history_preview
    ph_max = int ( (plist_max[col][p] / plist_abs_max) * (lh_height-1) )
ValueError: cannot convert float NaN to integer
[14:49:18][#407694][0529ms][nan][nan]
`

## Steps to reproduce

After hours of training it just suddenly gave out this error. Since then the error keeps being given out right after re-starting the training.
The used parameters are included above.

## Other relevant information
- Win10/64x, 64 GiByte RAM, 700 GiByte Paging File, Ryzen 9 3950X, RTX 1080Ti
- DeepFaceLab_NVIDIA_RTX3000_series_build_11_20_2021

**Comment by BlankFX1** [comment]
Going back two hours in training using a backup allowed to continue training - at least for the moment.

**Comment by BlankFX1** [comment]
Given the fact that the errorous model only weighted 90 MiByte when compressed as rar, I assume my Model just collapsed and therefor caused this error. If you can confirm that, I guess you can just close this issues. :)

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
