### ISSUE TITLE
Exception in thread

### ISSUE THREAD

**Issue by phatwila** [iperov/DeepFaceLab#55]
Hello,
While training models in H128 and LIAEF128 after some time I get the following fatal error. This is from the latest torrent release (plus a git pull last commit of 646e2e38071744c251e6123eb7e415c4871753f7).

```
Saving...[#040351][0612ms] loss_src: 0.06915 loss_dst: 0.04916
Exception in thread Thread-1:ss_src: 0.07147 loss_dst: 0.05013
Traceback (most recent call last):
  File "D:\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Trainer.py", line 75, in trainerThread
    print (loss_string, end='\r')
OSError: [WinError 6] The handle is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "D:\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Trainer.py", line 117, in trainerThread
    print ('Error: %s' % (str(e)))
OSError: [WinError 6] The handle is invalid
```

**Comment by iperov** [comment]
OS version ?

**Comment by phatwila** [comment]
Operating System: Windows 10 Home 64-bit (10.0, Build 15063) (15063.rs2_release.170317-1834)
Processor: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 CPUs), ~3.7GHz
Memory: 32768MB RAM
Available OS Memory: 32694MB RAM
Card name: NVIDIA GeForce GTX 1080 Ti

**Comment by iperov** [comment]
try last commit

**Comment by phatwila** [comment]
Thanks! I'll let this run and let you know if it shows up again.
