### ISSUE TITLE
No module named 'numpy' when accessing leras/__init__.py. python -mpip install numpy is not working.

### ISSUE THREAD

**Issue by rolandinthedeep** [iperov/DeepFaceLab#5509]
## Expected behavior

I am running my extract script for the MacOS version of DeepFaceLab. The script (`2_extract_images_from_video_data_src.sh`) is simply:
```
#!/usr/bin/env bash
cd "$(dirname $0)/.."
source scripts/env.sh

python "$DFL_MAIN" videoed extract-video \
  --input-file "$WORKSPACE/data_src.*" \
  --output-dir "$WORKSPACE/data_src"
```

## Actual behavior

The error is as follows:
```
Traceback (most recent call last):
File "/Users/myusername/DeepFaceLab_MacOS/.dfl/DeepFaceLab/main.py", line 6, in
from core.leras import nn
File "/Users/myusername/DeepFaceLab_MacOS/.dfl/DeepFaceLab/core/leras/init.py", line 1, in
from .nn import nn
File "/Users/myusername/DeepFaceLab_MacOS/.dfl/DeepFaceLab/core/leras/nn.py", line 25, in
import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

## Steps to reproduce

I have tried all of the suggestions listed in https://github.com/numpy/numpy/issues/15424. 

Using `python -mpip install numpy` yields: 
```
Requirement already satisfied: numpy in /Users/myusername/opt/anaconda3/envs/deepfake_env/lib/python3.6/site-packages (1.16.4)
```
I also receive the same message when I do `pip3 install numpy`.

I attempted to uninstall/reinstall. It throws an error. The only thing that changed is that when I attempt to `python -mpip install numpy`, I get:
```
Requirement already satisfied: numpy in /Users/myusername/opt/anaconda3/envs/deepfake_env/lib/python3.6/site-packages (1.19.5)
```

Additionally, uninstalling my Python IDE (as suggested in https://github.com/numpy/numpy/issues/15424) also did **not** work.

If it helps, if I do `which python` once I activate my environment, I get:
```
/Users/myusername/opt/anaconda3/envs/deepfake_env/bin/python
```

## Other relevant information
- **Operating system and version:** macOS
- **Python version:** 3.6

**Comment by mattAndruff** [comment]
I have the same issue on centos 7

**Comment by mattAndruff** [comment]
For what it's worth. This project requires Python 3.7.  This is set in Conda environment, and also in env.sh script.  because the python version is set in the script to use "Python3.7" it will override the conda environment and develop a mismatch and use the native python3.7 environment.  If you upgrade your native environment to 3.7 you can resolve this issue. (or it seemed to resolve the issue for me.)

**Comment by ngardelis** [comment]
Same error here have you guys fixed it?

**Comment by ngardelis** [comment]
@mattAndruff how did you update to 3.7 ? when I tried it said: python@3.7 has been deprecated!
python@3.7: The x86_64 architecture is required for this software.

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?
