### ISSUE TITLE
pretraining Xseg error data path is not defined on ubuntu linux

### ISSUE THREAD

**Issue by cedricgallet** [iperov/DeepFaceLab#5520]
Hello all and very great job !!

I have an error when I start the xseg pre-training, I looked in the solutions mentioned here and I found but the solution is for windows and I'm on ubuntu can someone explain to me how to do and what file I have to modify please?

**Comment by cedricgallet** [comment]
[](url)

**Comment by cedricgallet** [comment]
Running trainer.


Model first run.
[wf] Face type ( h/mf/f/wf/head ?:help ) : 
wf
[4] Batch_size ( 2-16 ?:help ) : 
4
[n] Enable pretraining mode ( y/n ) : y
Error: pretraining_data_path is not defined
Traceback (most recent call last):
  File "/home/cedric/LAB/DeepFaceLab_Linux/DeepFaceLab/mainscripts/Trainer.py", line 58, in trainerThread
    debug=debug)
  File "/home/cedric/LAB/DeepFaceLab_Linux/DeepFaceLab/models/Model_XSeg/Model.py", line 17, in __init__
    super().__init__(*args, force_model_class_name='XSeg', **kwargs)
  File "/home/cedric/LAB/DeepFaceLab_Linux/DeepFaceLab/models/ModelBase.py", line 180, in __init__
    self.on_initialize_options()
  File "/home/cedric/LAB/DeepFaceLab_Linux/DeepFaceLab/models/Model_XSeg/Model.py", line 38, in on_initialize_options
    raise Exception("pretraining_data_path is not defined")
Exception: pretraining_data_path is not defined
