### ISSUE TITLE
nan errors 5-10 min into the training.

### ISSUE THREAD

**Issue by zabique** [iperov/DeepFaceLab#5525]
VM ( Epyc 2.3ghz x48 cores,128GB RAM, RTX A100 80GB)

Tested on own workspace (data)
aligned extracted at 512 res
Test model is 416 res, liae-udt, slightly bumpped dims, tried with gradient clipping on/off and with on training last a little bit longer.

Training start and last 400-4000 iter then crash with Nan in src/dst loss line, preview window crash.

================================================================================
Starting. Press "Enter" to stop training and save model.
Traceback (most recent call last):an].6185]
  File "G:\DeepFaceLab_NVIDIA_RTX3000_series_build_11_20_2021\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\main.py", line 343, in <module>
    arguments.func(arguments)
  File "G:\DeepFaceLab_NVIDIA_RTX3000_series_build_11_20_2021\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\main.py", line 132, in process_train
    Trainer.main(**kwargs)
  File "G:\DeepFaceLab_NVIDIA_RTX3000_series_build_11_20_2021\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\Trainer.py", line 317, in main
    lh_img = models.ModelBase.get_loss_history_preview(loss_history_to_show, iter, w, c)
  File "G:\DeepFaceLab_NVIDIA_RTX3000_series_build_11_20_2021\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\ModelBase.py", line 627, in get_loss_history_preview
    ph_max = int ( (plist_max[col][p] / plist_abs_max) * (lh_height-1) )
ValueError: cannot convert float NaN to integer
[22:56:26][#001284][0175ms][nan][nan]

=================================================================================
SO FAR:
-Tested on lower spec model  RTM 224 res model + stock Elon/Stark footage and same result, but takes longer to crash.
-limited core number in system to 8.
-tried different fork
-unable to enable GPU scheduling as option does not exist  for some reason and I know how to set it on different systems.

I appreciate any feedback

**Comment by jeremybarbaud** [comment]
Hello, 

Same issue .. Did you fix it ?

**Comment by zabique** [comment]
By switching to conda linux version.

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
