### ISSUE TITLE
Trouble with train Quick 96 and SAEHD in deep face lab

### ISSUE THREAD

**Issue by DynaRIT** [iperov/DeepFaceLab#5546]
I tryd to train quick 96, an error appeared Error: No training data provided.
Traceback (most recent call last):
File "C:\Users\kadik\Downloads\DeepFaceLab_DirectX12_internal\DeepFaceLab\mainscripts\Trainer.py", line 58, in trainerThread
debug=debug)
File "C:\Users\kadik\Downloads\DeepFaceLab_DirectX12_internal\DeepFaceLab\models\ModelBase.py", line 193, in init
self.on_initialize()
File "C:\Users\kadik\Downloads\DeepFaceLab_DirectX12_internal\DeepFaceLab\models\Model_Quick96\Model.py", line 240, in on_initialize
generators_count=src_generators_count ),
File "C:\Users\kadik\Downloads\DeepFaceLab_DirectX12_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 48, in init
raise ValueError('No training data provided.')
ValueError: No training data provided.

**Comment by CodeSmith2000** [comment]
Well, this is a bit of an obvious question. But did you provide training data? Specifically you need to have frames of your videos in the src and dst folders, then run faceset extract src and faceset extract dst. Then you can run Quick 96 and SAEHD.

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?
