### ISSUE TITLE
Fail to start training with numpy import error

### ISSUE THREAD

**Issue by okingjo** [iperov/DeepFaceLab#5554]
So, the same "ImportError: numpy.core.multiarray failed to import" message appears everytime when training with SAEHD. Tried updating pip, numpy and tensorflow but the issue still exists. AMP shares the same issue, but Quick96 works perfectly.

My rig is: AMD 5950X, 128G RAM, dual RTX3090. Win10 19044.1889. No WSL nor local Python installed.

The error message is:
`Initializing models: 100%|###############################################################| 5/5 [00:01<00:00,  3.12it/s]
Loading samples: 100%|##############################################################| 654/654 [00:01<00:00, 478.71it/s]
Sort by yaw: 100%|#################################################################| 128/128 [00:00<00:00, 8525.55it/s]
Loading samples: 100%|############################################################| 1619/1619 [00:03<00:00, 488.73it/s]
Sort by yaw: 100%|#################################################################| 128/128 [00:00<00:00, 3119.13it/s]
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\__init__.py", line 1, in <module>
    from .SubprocessorBase import Subprocessor
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 5, in <module>
    from core.interact import interact as io
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
    from .interact import interact
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
    import cv2
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
Traceback (most recent call last):
ImportError: numpy.core.multiarray failed to import
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\__init__.py", line 1, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 115, in _main
ImportError: numpy.core.multiarray failed to import
  File "multiprocessing\spawn.py", line 115, in _main
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "<string>", line 1, in <module>
    from .SubprocessorBase import Subprocessor
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\__init__.py", line 1, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\__init__.py", line 1, in <module>
Traceback (most recent call last):
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\__init__.py", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 5, in <module>
    from .SubprocessorBase import Subprocessor
    from .SubprocessorBase import Subprocessor
  File "<string>", line 1, in <module>
    from .SubprocessorBase import Subprocessor
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 115, in _main
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\__init__.py", line 1, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\__init__.py", line 1, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
    from core.interact import interact as io
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 5, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 5, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 5, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\__init__.py", line 1, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\__init__.py", line 1, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\__init__.py", line 1, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\__init__.py", line 1, in <module>
    from .SubprocessorBase import Subprocessor
    from .SubprocessorBase import Subprocessor
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\__init__.py", line 1, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
    from core.interact import interact as io
    from core.interact import interact as io
  File "multiprocessing\spawn.py", line 115, in _main
    from core.interact import interact as io
    from .SubprocessorBase import Subprocessor
    from .SubprocessorBase import Subprocessor
    from .SubprocessorBase import Subprocessor
    from .SubprocessorBase import Subprocessor
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 5, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 5, in <module>
    from .SubprocessorBase import Subprocessor
    from .interact import interact
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\__init__.py", line 1, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 5, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 5, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 5, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 5, in <module>
    from core.interact import interact as io
    from core.interact import interact as io
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 5, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
    from .interact import interact
    from .interact import interact
    from .SubprocessorBase import Subprocessor
    from .interact import interact
    from core.interact import interact as io
    from core.interact import interact as io
    from core.interact import interact as io
    from core.interact import interact as io
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
    from core.interact import interact as io
    import cv2
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 5, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
    from .interact import interact
    from .interact import interact
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
    import cv2
    import cv2
    from core.interact import interact as io
    import cv2
    from .interact import interact
    from .interact import interact
    from .interact import interact
    from .interact import interact
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
    from .interact import interact
    from .cv2 import *
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\__init__.py", line 1, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
    import cv2
    import cv2
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
ImportError: numpy.core.multiarray failed to import
    from .cv2 import *
    from .cv2 import *
    from .interact import interact
    from .cv2 import *
    import cv2
    import cv2
    import cv2
    import cv2
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
    import cv2
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\interact.py", line 9, in <module>
ImportError: numpy.core.multiarray failed to import
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
    from .cv2 import *
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
    import cv2
    from .cv2 import *
    from .cv2 import *
    from .cv2 import *
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
    from .cv2 import *
  File "E:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\cv2\__init__.py", line 3, in <module>
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import`

What I have tried:
- Upgrade pip, numpy to the latest version (here is also another thing I found weird: pip list numpy ver is 1.19.5, but what in the folder is 1.19.3)
- import CV2 and numpy.core.multiarray directly with python_console.bat, no error message
- run training through the python_console.bat directly, same error message.
- Clean workspace folder and start from zero
- redownload the file and run with the original Ironman vs Musk file.

**Comment by saguaro3** [comment]
I have the same problem ;-;

**Comment by WesleyNery** [comment]
What is your paging file size?

**Comment by saguaro3** [comment]
Nvm, I fixed the issue. I just tweaked Auto Encoder Dims, Encoder Dims, Decoder Dims and Decoder Mask Dims.

**Comment by saguaro3** [comment]
Nvm, I fixed the issue, I just downloaded the latest build (from 2022), u cant torrent it, its in mega.nz files

**Comment by JDTCC** [comment]
Issue solved / already answered (or it seems like user error), please close it.

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?
