### ISSUE TITLE
Train Error from existing model

### ISSUE THREAD

**Issue by blanuk** [iperov/DeepFaceLab#558]
Hi there
If i wanna load my "old" model files with the new Cuda Version (DeepFaceLab_CUDA_build_01_11_2020) i got some errors:

`Loading model...
Press enter in 2 seconds to override model settings.Using TensorFlow backend.
Error: Dimension 0 in both shapes must be equal, but are 1 and 3. Shapes are [1,1,128,3] and [3,128,5,5]. for 'Assign_68' (op: 'Assign') with input shapes: [1,1,128,3], [3,128,5,5].
Traceback (most recent call last):
  File "N:\xy\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 1628, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 1 and 3. Shapes are [1,1,128,3] and [3,128,5,5]. for 'Assign_68' (op: 'Assign') with input shapes: [1,1,128,3], [3,128,5,5].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "N:\xy\_internal\DeepFaceLab\mainscripts\Trainer.py", line 52, in trainerThread
    device_args=device_args)
  File "N:\xy\_internal\DeepFaceLab\models\ModelBase.py", line 146, in __init__
    self.onInitialize()
  File "N:\xy\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 432, in onInitialize
    loaded, not_loaded = self.load_weights_safe(not_loaded)
  File "N:\xy\_internal\DeepFaceLab\models\ModelBase.py", line 424, in load_weights_safe
    model.load_weights(filename)
  File "N:\xy\_internal\python-3.6.8\lib\site-packages\keras\engine\network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "N:\xy\_internal\python-3.6.8\lib\site-packages\keras\engine\saving.py", line 1058, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "N:\xy\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2465, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "N:\xy\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\variables.py", line 1718, in assign
    name=name)
  File "N:\xy\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\state_ops.py", line 221, in assign
    validate_shape=validate_shape)
  File "N:\xy\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 61, in assign
    use_locking=use_locking, name=name)
  File "N:\xy\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "N:\xy\_internal\python-3.6.8\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "N:\xy\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "N:\xy\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 1792, in __init__
    control_input_ops)
  File "N:\xy\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 1631, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 3. Shapes are [1,1,128,3] and [3,128,5,5]. for 'Assign_68' (op: 'Assign') with input shapes: [1,1,128,3], [3,128,5,5].`

Previous i used DeepFaceLab_CUDA_10.1_AVX_build_12_26_2019
How can i fix that? and please dont say me that i have to retrain :/

**Comment by TooMuchFun** [comment]
sry bro you have to retrain
