### ISSUE TITLE
NEW to DFL wanna try it with the DFL, it works fine with 3090 but cant run SAEHD with 4080 HELP! Can run with QUICK tho

### ISSUE THREAD

**Issue by kknpnfrom** [iperov/DeepFaceLab#5609]
Running trainer.

[new] No saved models found. Enter a name of a new model :
new

Model first run.

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : NVIDIA GeForce RTX 4080

[0] Which GPU indexes to choose? :
0

[0] Autobackup every N hour ( 0..24 ?:help ) :
0
[n] Write preview history ( y/n ?:help ) :
n
[0] Target iteration :
0
[n] Flip SRC faces randomly ( y/n ?:help ) :
n
[y] Flip DST faces randomly ( y/n ?:help ) :
y
[8] Batch_size ( ?:help ) : 12
12
[128] Resolution ( 64-640 ?:help ) : 320
320
[f] Face type ( h/mf/f/wf/head ?:help ) : wf
wf
[liae-ud] AE architecture ( ?:help ) :
liae-ud
[256] AutoEncoder dimensions ( 32-1024 ?:help ) :
256
[64] Encoder dimensions ( 16-256 ?:help ) :
64
[64] Decoder dimensions ( 16-256 ?:help ) :
64
[22] Decoder mask dimensions ( 16-256 ?:help ) :
22
[y] Masked training ( y/n ?:help ) :
y
[n] Eyes and mouth priority ( y/n ?:help ) :
n
[n] Uniform yaw distribution of samples ( y/n ?:help ) :
n
[n] Blur out mask ( y/n ?:help ) :
n
[y] Place models and optimizer on GPU ( y/n ?:help ) :
y
[y] Use AdaBelief optimizer? ( y/n ?:help ) :
y
[n] Use learning rate dropout ( n/y/cpu ?:help ) :
n
[y] Enable random warp of samples ( y/n ?:help ) :
y
[0.0] Random hue/saturation/light intensity ( 0.0 .. 0.3 ?:help ) :
0.0
[0.0] GAN power ( 0.0 .. 5.0 ?:help ) :
0.0
[0.0] Face style power ( 0.0..100.0 ?:help ) :
0.0
[0.0] Background style power ( 0.0..100.0 ?:help ) :
0.0
[none] Color transfer for src faceset ( none/rct/lct/mkl/idt/sot ?:help ) :
none
[n] Enable gradient clipping ( y/n ?:help ) :
n
[n] Enable pretraining mode ( y/n ?:help ) :
n
Initializing models: 100%|###############################################################| 5/5 [00:01<00:00,  3.10it/s]
Loading samples: 100%|############################################################| 1053/1053 [00:04<00:00, 231.28it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
  File "multiprocessing\spawn.py", line 115, in _main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
    from .Sample import Sample
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 4, in <module>
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: numpy.core.multiarray failed to import
  File "multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
ImportError: numpy.core.multiarray failed to import
  File "multiprocessing\spawn.py", line 115, in _main
    from .Sample import Sample
Traceback (most recent call last):
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 4, in <module>
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
  File "<string>", line 1, in <module>
    from .Sample import Sample
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 4, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
    from .Sample import Sample
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 4, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
    from .Sample import Sample
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 7, in <module>
    from core.cv2ex import *
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\cv2ex.py", line 5, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\heap.py", line 55, in __setstate__
OSError: [WinError 1455] The paging file is too small for this operation to complete
    from core import imagelib
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\__init__.py", line 9, in <module>
Process Process-18:
Process Process-16:
Traceback (most recent call last):
Traceback (most recent call last):
      File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 134, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 134, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
from .morph import morph_by_points  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 113, in process
    warp_rnd_state=warp_rnd_state,
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 56, in process
    sample_bgr = sample.load_bgr()

  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\warp.py", line 133, in gen_warp_params
    mapy = cv2.resize(mapy, (w+cell_size,)*2 )[half_cell_size:-half_cell_size,half_cell_size:-half_cell_size].astype(np.float32)
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 112, in load_bgr
    img = cv2_imread (self.filename, loader_func=self.read_raw_file).astype(np.float32) / 255.0
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\morph.py", line 3, in <module>
MemoryError: Unable to allocate 400. KiB for an array with shape (320, 320) and data type float32
MemoryError: Unable to allocate 3.00 MiB for an array with shape (512, 512, 3) and data type float32

During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
  File "multiprocessing\process.py", line 258, in _bootstrap
  File "multiprocessing\process.py", line 258, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "multiprocessing\process.py", line 93, in run
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessGenerator.py", line 54, in process_func
    gen_data = next (self.generator_func)
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessGenerator.py", line 54, in process_func
    gen_data = next (self.generator_func)
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 136, in batch_func
    raise Exception ("Exception occured in sample %s. Error: %s" % (sample.filename, traceback.format_exc() ) )
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 136, in batch_func
    raise Exception ("Exception occured in sample %s. Error: %s" % (sample.filename, traceback.format_exc() ) )
Exception: Exception occured in sample F:\DeepFaceLab_NVIDIA_RTX3000_series\workspace\data_src\aligned\00731_0.jpg. Error: Traceback (most recent call last):
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 134, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 113, in process
    warp_rnd_state=warp_rnd_state,
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\warp.py", line 133, in gen_warp_params
    mapy = cv2.resize(mapy, (w+cell_size,)*2 )[half_cell_size:-half_cell_size,half_cell_size:-half_cell_size].astype(np.float32)
MemoryError: Unable to allocate 400. KiB for an array with shape (320, 320) and data type float32

Exception: Exception occured in sample F:\DeepFaceLab_NVIDIA_RTX3000_series\workspace\data_src\aligned\01047_0.jpg. Error: Traceback (most recent call last):
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 134, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 56, in process
    sample_bgr = sample.load_bgr()
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 112, in load_bgr
    img = cv2_imread (self.filename, loader_func=self.read_raw_file).astype(np.float32) / 255.0
MemoryError: Unable to allocate 3.00 MiB for an array with shape (512, 512, 3) and data type float32

    from scipy.spatial import Delaunay
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\scipy\spatial\__init__.py", line 97, in <module>
    from .kdtree import *
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\scipy\spatial\kdtree.py", line 8, in <module>
    import scipy.sparse
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\scipy\sparse\__init__.py", line 232, in <module>
    from .lil import *
  File "F:\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\scipy\sparse\lil.py", line 20, in <module>
    from . import _csparsetools
ImportError: DLL load failed: The paging file is too small for this operation to complete.

**Comment by RazoR2k2** [comment]
Hello,

How much RAM do you have?

**Comment by kknpnfrom** [comment]
> 

32GB 3200

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
