### ISSUE TITLE
Can't extract data_src faceset on DeepFaceLab_NVIDIA_RTX3000_series

### ISSUE THREAD

**Issue by ivand321** [iperov/DeepFaceLab#5633]
I have an error message when trying to extract faceset.

Error while processing data: Traceback (most recent call last):
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: No algorithm worked!
         [[{{node Conv2D}}]]
         [[Add_29/_141]]
  (1) Not found: No algorithm worked!
         [[{{node Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\Extractor.py", line 104, in process_data
    rects_extractor=self.rects_extractor,
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\Extractor.py", line 145, in rects_stage
    rects = data.rects = rects_extractor.extract (rotated_image, is_bgr=True)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\facelib\S3FDExtractor.py", line 193, in extract
    olist = self.model.run ([ input_image[None,...] ] )
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\models\ModelBase.py", line 167, in run
    return nn.tf_sess.run ( self.run_output, feed_dict=feed_dict)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 968, in run
    run_metadata_ptr)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1369, in _do_run
    run_metadata)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: No algorithm worked!
         [[node Conv2D (defined at C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\Conv2D.py:101) ]]
         [[Add_29/_141]]
  (1) Not found: No algorithm worked!
         [[node Conv2D (defined at C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\Conv2D.py:101) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node Conv2D:
 S3FD/conv1_1/weight/read (defined at C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\Conv2D.py:61)
 Pad (defined at C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\Conv2D.py:87)

Input Source operations connected to node Conv2D:
 S3FD/conv1_1/weight/read (defined at C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\Conv2D.py:61)
 Pad (defined at C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\Conv2D.py:87)

Original stack trace for 'Conv2D':
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 118, in _main
  File "multiprocessing\process.py", line 258, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 62, in _subprocess_run
    self.on_initialize(client_dict)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\Extractor.py", line 73, in on_initialize
    self.rects_extractor = facelib.S3FDExtractor(place_model_on_cpu=place_model_on_cpu)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\facelib\S3FDExtractor.py", line 170, in __init__
    self.model.build_for_run ([ ( tf.float32, nn.get4Dshape (None,None,3) ) ])
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\models\ModelBase.py", line 154, in build_for_run
    self.run_output = self.__call__(self.run_placeholders)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\models\ModelBase.py", line 117, in __call__
    return self.forward(*args, **kwargs)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\facelib\S3FDExtractor.py", line 93, in forward
    x = tf.nn.relu(self.conv1_1(x))
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\LayerBase.py", line 14, in __call__
    return self.forward(*args, **kwargs)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\Conv2D.py", line 101, in forward
    x = tf.nn.conv2d(x, weight, strides, 'VALID', dilations=dilations, data_format=nn.data_format)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2397, in conv2d
    name=name)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 972, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 3569, in _create_op_internal
    op_def=op_def)
  File "C:\Users\ivand\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

  0%|                                                                                          | 0/655 [00:04<?, ?it/s]
-------------------------
Images found:        655
Faces detected:      0
-------------------------

I think this error could be caused by Memory allocation failure so it is important to note that I have 16 GB of RAM. Can someone please explain how to fix this issue

**Comment by JDTCC** [comment]
Did you resolve the issue yet?

**Comment by ivand321** [comment]
no, I have no idea what the problem is. However, the issue did not occur when I used the DirectX version. The issue is only present for the RTX 3000 version

**Comment by BigSegun** [comment]
please which of the DirectX version did you use ?


> no, I have no idea what the problem is. However, the issue did not occur when I used the DirectX version. The issue is only present for the RTX 3000 version

please what type of version of DirectX did you use i am also having the same issue 
![Screenshot (23)](https://user-images.githubusercontent.com/68261548/232203382-97f55dd9-a937-4345-b2ab-43af012fb19d.png)

**Comment by ivand321** [comment]
I think I used 2022 version, I do not know for sure because I deinstalled it because I did not use it anymore. My logic probably was newer is better xd.

**Comment by BigSegun** [comment]
> I think I used 2022 version, I do not know for sure because I deinstalled it because I did not use it anymore. My logic probably was newer is better xd.

 Thanks you so much it worked

**Comment by BigSegun** [comment]
I want to ask a question where you able to TRAIN YOUR SAEHD SUCCESSFULLY ????

**Comment by BigSegun** [comment]
I’m having an error when training my SAEHD 
![Uploading 4E891B46-A174-49DB-8AFD-AE91DC01B923.jpeg…]()

**Comment by BigSegun** [comment]
> Did you resolve the issue yet?

Hello have you been able to train you SAEHD SUCCESSFULLY ????

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
