### ISSUE TITLE
解压报错并使用4) data_src faceset extract.bat时无法切下人脸图

### ISSUE THREAD

**Issue by zjh2765400096** [iperov/DeepFaceLab#5639]
![image](https://user-images.githubusercontent.com/88066528/224728367-07c6866a-4a45-4321-a977-819f4a526826.png)

An error was reported during decompression. I will use 4) data later_ Src faceset extract.bat failed to cut the face image, but no solution was found.
Error message:
解压时报告了一个错误，后续我在使用4) data_src faceset extract.bat时就无法切下人脸图，但是没有找到解决方法。
报错信息：

Error while processing data: Traceback (most recent call last):
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflo
w\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflo
w\python\client\session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflo
w\python\client\session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking
to see if a warning log message was printed above.
         [[{{node Conv2D}}]]
         [[Add_31/_143]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking
to see if a warning log message was printed above.
         [[{{node Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase
.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\Extractor.py", l
ine 104, in process_data
    rects_extractor=self.rects_extractor,
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\Extractor.py", l
ine 145, in rects_stage
    rects = data.rects = rects_extractor.extract (rotated_image, is_bgr=True)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\facelib\S3FDExtractor.py", l
ine 193, in extract
    olist = self.model.run ([ input_image[None,...] ] )
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\models\ModelBase.
py", line 167, in run
    return nn.tf_sess.run ( self.run_output, feed_dict=feed_dict)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflo
w\python\client\session.py", line 968, in run
    run_metadata_ptr)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflo
w\python\client\session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflo
w\python\client\session.py", line 1369, in _do_run
    run_metadata)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflo
w\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking
to see if a warning log message was printed above.
         [[node Conv2D (defined at D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\c
ore\leras\layers\Conv2D.py:101) ]]
         [[Add_31/_143]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking
to see if a warning log message was printed above.
         [[node Conv2D (defined at D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\c
ore\leras\layers\Conv2D.py:101) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node Conv2D:
 Pad (defined at D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\C
onv2D.py:87)
 S3FD/conv1_1/weight/read (defined at D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLa
b\core\leras\layers\Conv2D.py:61)

Input Source operations connected to node Conv2D:
 Pad (defined at D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\C
onv2D.py:87)
 S3FD/conv1_1/weight/read (defined at D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLa
b\core\leras\layers\Conv2D.py:61)

Original stack trace for 'Conv2D':
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 118, in _main
  File "multiprocessing\process.py", line 258, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase
.py", line 62, in _subprocess_run
    self.on_initialize(client_dict)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\Extractor.py", l
ine 73, in on_initialize
    self.rects_extractor = facelib.S3FDExtractor(place_model_on_cpu=place_model_on_cpu)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\facelib\S3FDExtractor.py", l
ine 170, in __init__
    self.model.build_for_run ([ ( tf.float32, nn.get4Dshape (None,None,3) ) ])
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\models\ModelBase.
py", line 154, in build_for_run
    self.run_output = self.__call__(self.run_placeholders)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\models\ModelBase.
py", line 117, in __call__
    return self.forward(*args, **kwargs)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\facelib\S3FDExtractor.py", l
ine 93, in forward
    x = tf.nn.relu(self.conv1_1(x))
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\LayerBase.
py", line 14, in __call__
    return self.forward(*args, **kwargs)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\Conv2D.py"
, line 101, in forward
    x = tf.nn.conv2d(x, weight, strides, 'VALID', dilations=dilations, data_format=nn.data_format)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflo
w\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflo
w\python\ops\nn_ops.py", line 2397, in conv2d
    name=name)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflo
w\python\ops\gen_nn_ops.py", line 972, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflo
w\python\framework\op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflo
w\python\framework\ops.py", line 3569, in _create_op_internal
    op_def=op_def)
  File "D:\fdm-download\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflo
w\python\framework\ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

**Comment by JDTCC** [comment]
Were you able to resolve the issue?

**Comment by zjh2765400096** [comment]
> Were you able to resolve the issue?

no,I used other one.
