### ISSUE TITLE
SAEHD it fails using the 30s build but it works using DirectX12

### ISSUE THREAD

**Issue by Profogt** [iperov/DeepFaceLab#5655]
Windows 10 , i5-13600KF, 32gb ram, nvidia rtx 3060 eagle 12gb

When I try to train SAEHD it fails using the 30s build but it works using DirectX12

Loading LIAE-UD-HighRes_SAEHD model...

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : NVIDIA GeForce RTX 3060

[0] Which GPU indexes to choose? : 0
0

Press enter in 2 seconds to override model settings.
[1] Autobackup every N hour ( 0..24 ?:help ) :
1
[n] Write preview history ( y/n ?:help ) :
n
[1000000] Target iteration :
1000000
[y] Flip SRC faces randomly ( y/n ?:help ) :
y
[y] Flip DST faces randomly ( y/n ?:help ) :
y
[10] Batch_size ( ?:help ) :
10
[y] Masked training ( y/n ?:help ) :
y
[y] Eyes and mouth priority ( y/n ?:help ) :
y
[n] Uniform yaw distribution of samples ( y/n ?:help ) :
n
[n] Blur out mask ( y/n ?:help ) :
n
[n] Place models and optimizer on GPU ( y/n ?:help ) :
n
[n] Use AdaBelief optimizer? ( y/n ?:help ) :
n
[n] Use learning rate dropout ( n/y/cpu ?:help ) :
n
[y] Enable random warp of samples ( y/n ?:help ) :
y
[0.0] Random hue/saturation/light intensity ( 0.0 .. 0.3 ?:help ) :
0.0
[0.0] GAN power ( 0.0 .. 5.0 ?:help ) :
0.0
[0.0] Face style power ( 0.0..100.0 ?:help ) :
0.0
[0.0] Background style power ( 0.0..100.0 ?:help ) :
0.0
[none] Color transfer for src faceset ( none/rct/lct/mkl/idt/sot ?:help ) :
none
[n] Enable gradient clipping ( y/n ?:help ) :
n
[n] Enable pretraining mode ( y/n ?:help ) :
n
Initializing models: 100%|###############################################################| 5/5 [00:08<00:00,  1.64s/it]
Loading samples: 100%|##########################################################| 12456/12456 [00:33<00:00, 366.63it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
Process Process-17:
  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\__init__.py", line 1, in <module>
        from .Sample import Samplefrom .Sample import Sample

  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 7, in <module>
  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 7, in <module>
Traceback (most recent call last):
  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 134, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 206, in process
    img = np.clip(img.astype(np.float32), 0, 1)
MemoryError: Unable to allocate 1.17 MiB for an array with shape (320, 320, 3) and data type float32

During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
Process Process-15:
from core.cv2ex import *from core.cv2ex import *
Traceback (most recent call last):
  File "multiprocessing\process.py", line 258, in _bootstrap

  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\cv2ex.py", line 5, in <module>
  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 134, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "multiprocessing\process.py", line 93, in run
  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\cv2ex.py", line 5, in <module>
  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 56, in process
    sample_bgr = sample.load_bgr()
      File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessGenerator.py", line 54, in process_func
    gen_data = next (self.generator_func)
      File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 112, in load_bgr
    img = cv2_imread (self.filename, loader_func=self.read_raw_file).astype(np.float32) / 255.0
from core import imagelib   File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 136, in batch_func
    raise Exception ("Exception occured in sample %s. Error: %s" % (sample.filename, traceback.format_exc() ) )
from core import imagelib MemoryError: Unable to allocate 3.00 MiB for an array with shape (512, 512, 3) and data type float32

Exception: Exception occured in sample C:\DFL\DFL_NVIDIA_RTX3000_series\workspace\data_src\aligned\20863_0.jpg. Error: Traceback (most recent call last):
  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 134, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 206, in process
    img = np.clip(img.astype(np.float32), 0, 1)
MemoryError: Unable to allocate 1.17 MiB for an array with shape (320, 320, 3) and data type float32

During handling of the above exception, another exception occurred:

  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\__init__.py", line 9, in <module>
  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\__init__.py", line 9, in <module>
Traceback (most recent call last):
          File "multiprocessing\process.py", line 258, in _bootstrap
from .morph import morph_by_pointsfrom .morph import morph_by_points  File "multiprocessing\process.py", line 93, in run

  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessGenerator.py", line 54, in process_func
    gen_data = next (self.generator_func)
  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\morph.py", line 3, in <module>
  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\imagelib\morph.py", line 3, in <module>
  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 136, in batch_func
    raise Exception ("Exception occured in sample %s. Error: %s" % (sample.filename, traceback.format_exc() ) )
        Exception: Exception occured in sample C:\DFL\DFL_NVIDIA_RTX3000_series\workspace\data_src\aligned\06605_0.jpg. Error: Traceback (most recent call last):
  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 134, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 56, in process
    sample_bgr = sample.load_bgr()
  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 112, in load_bgr
    img = cv2_imread (self.filename, loader_func=self.read_raw_file).astype(np.float32) / 255.0
MemoryError: Unable to allocate 3.00 MiB for an array with shape (512, 512, 3) and data type float32

from scipy.spatial import Delaunayfrom scipy.spatial import Delaunay

  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\scipy\spatial\__init__.py", line 99, in <module>
  File "C:\DFL\DFL_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\scipy\spatial\__init__.py", line 99, in <module>
        from .qhull import *from .qhull import *

ImportErrorImportError: : DLL load failed: El archivo de paginación es demasiado pequeño para completar la operación.DLL load failed: El archivo de paginación es demasiado pequeño para completar la operación.

[message.txt](https://github.com/iperov/DeepFaceLab/files/11142787/message.txt)

**Comment by JDTCC** [comment]
What res is this model?
