### ISSUE TITLE
HELP! Merge96 won't work

### ISSUE THREAD

**Issue by 0zymandia55** [iperov/DeepFaceLab#5667]
I'm running on the RTX3000 series. I keep getting this long error and I have no idea what to do. This is on a completely new PC. My previous one didn't have any issues. 

3070 TI
16 GB 

-------------------------------------------------------------------------------------------------------------------------------------
 File "C:\Users\USER1\OneDrive\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)

  File "C:\Users\USER1\OneDrive\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1360, in _run_fn
    target_list, run_metadata)

  File "C:\Users\USER1\OneDrive\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1453, in _call_tf_sessionrun
    run_metadata)

tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: No algorithm worked!
         [[{{node Conv2D}}]]
         [[Sigmoid_1/_349]]
  (1) Not found: No algorithm worked!
         [[{{node Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER1\OneDrive\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\Merger.py", line 209, in main
    subprocess_count       = subprocess_count,
  File "C:\Users\USER1\OneDrive\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 268, in run
    if self.on_tick() and all ([cli.state == 0 for cli in self.clis]):
  File "C:\Users\USER1\OneDrive\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 361, in on_tick
    io.process_messages()
  File "C:\Users\USER1\OneDrive\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\interact.py", line 186, in process_messages
    func()
  File "C:\Users\USER1\OneDrive\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\MPFunc.py", line 17, in io_callback
    self.s2c.put ( self.func (*func_args, **func_kwargs) )
  File "C:\Users\USER1\OneDrive\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\Model_Quick96\Model.py", line 311, in predictor_func
    bgr, mask_dst_dstm, mask_src_dstm = [ nn.to_data_format(x, "NHWC", self.model_data_format).astype(np.float32) for x in self.AE_merge (face) ]
  File "C:\Users\USER1\OneDrive\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\Model_Quick96\Model.py", line 200, in AE_merge
    return nn.tf_sess.run ( [gpu_pred_src_dst, gpu_pred_dst_dstm, gpu_pred_src_dstm], feed_dict={self.warped_dst:warped_dst})
  File "C:\Users\USER1\OneDrive\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 968, in run
    run_metadata_ptr)
  File "C:\Users\USER1\OneDrive\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\USER1\OneDrive\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1369, in _do_run
    run_metadata)
  File "C:\Users\USER1\OneDrive\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: No algorithm worked!
         [[node Conv2D (defined at \DeepFaceLab\core\leras\layers\Conv2D.py:101) ]]
         [[Sigmoid_1/_349]]
  (1) Not found: No algorithm worked!
         [[node Conv2D (defined at \DeepFaceLab\core\leras\layers\Conv2D.py:101) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node Conv2D:
 Pad (defined at \DeepFaceLab\core\leras\layers\Conv2D.py:87)
 encoder/down1/downs_0/conv1/weight/read (defined at \DeepFaceLab\core\leras\layers\Conv2D.py:61)

Input Source operations connected to node Conv2D:
 Pad (defined at \DeepFaceLab\core\leras\layers\Conv2D.py:87)
 encoder/down1/downs_0/conv1/weight/read (defined at \DeepFaceLab\core\leras\layers\Conv2D.py:61)

Original stack trace for 'Conv2D':
  File "\DeepFaceLab\main.py", line 343, in <module>
    arguments.func(arguments)
  File "\DeepFaceLab\main.py", line 172, in process_merge
    cpu_only               = arguments.cpu_only)
  File "\DeepFaceLab\mainscripts\Merger.py", line 53, in main
    cpu_only=cpu_only)
  File "\DeepFaceLab\models\ModelBase.py", line 193, in __init__
    self.on_initialize()
  File "\DeepFaceLab\models\Model_Quick96\Model.py", line 194, in on_initialize
    gpu_dst_code     = self.inter(self.encoder(self.warped_dst))
  File "\DeepFaceLab\core\leras\models\ModelBase.py", line 117, in __call__
    return self.forward(*args, **kwargs)
  File "\DeepFaceLab\core\leras\archis\DeepFakeArchi.py", line 119, in forward
    x = self.down1(x)
  File "\DeepFaceLab\core\leras\models\ModelBase.py", line 117, in __call__
    return self.forward(*args, **kwargs)
  File "\DeepFaceLab\core\leras\archis\DeepFakeArchi.py", line 63, in forward
    x = down(x)
  File "\DeepFaceLab\core\leras\models\ModelBase.py", line 117, in __call__
    return self.forward(*args, **kwargs)
  File "\DeepFaceLab\core\leras\archis\DeepFakeArchi.py", line 43, in forward
    x = self.conv1(x)
  File "\DeepFaceLab\core\leras\layers\LayerBase.py", line 14, in __call__
    return self.forward(*args, **kwargs)
  File "\DeepFaceLab\core\leras\layers\Conv2D.py", line 101, in forward
    x = tf.nn.conv2d(x, weight, strides, 'VALID', dilations=dilations, data_format=nn.data_format)
  File "\python-3.6.8\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "\python-3.6.8\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2397, in conv2d
    name=name)
  File "\python-3.6.8\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 972, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "\python-3.6.8\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 3569, in _create_op_internal
    op_def=op_def)
  File "\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?
