### ISSUE TITLE
I am using Deepface lab on google colab and facing this issue 

### ISSUE THREAD

**Issue by AbuKashan** [iperov/DeepFaceLab#5684]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 3.5, 3.6.4, ... (if you are not using prebuilt windows binary)

**Comment by AbuKashan** [comment]
Traceback (most recent call last):   File "/content/DeepFaceLab/samplelib/SampleGeneratorFace.py", line 134, in batch_func     x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)   File "/content/DeepFaceLab/samplelib/SampleProcessor.py", line 106, in process     warp_params = imagelib.gen_warp_params(resolution,   File "/content/DeepFaceLab/core/imagelib/warp.py", line 146, in gen_warp_params     random_transform_mat = cv2.getRotationMatrix2D((w // 2, w // 2), rotation, scale) TypeError: Can't parse 'center'. Sequence item with index 0 has a wrong type
