### ISSUE TITLE
Error when launching trainer

### ISSUE THREAD

**Issue by Subzero710** [iperov/DeepFaceLab#5685]
Seems to be a memory error, what should i do to fix it (im running my model on an external ssd btw)

Initializing models: 100%|###############################################################| 5/5 [00:01<00:00,  3.56it/s]
Loading samples: 100%|##########################################################| 49160/49160 [03:02<00:00, 269.20it/s]
Loading samples: 100%|#####################################################################################################################################################| 34200/34200 [02:11<00:00, 260.94it/s]
Error:
Traceback (most recent call last):
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Attempting to perform BLAS operation using StreamExecutor without BLAS support
         [[{{node MatMul}}]]
         [[Sigmoid_3/_9]]
  (1) Internal: Attempting to perform BLAS operation using StreamExecutor without BLAS support
         [[{{node MatMul}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\ModelBase.py", line 263, in update_sample_for_preview
    self.get_history_previews()
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\ModelBase.py", line 383, in get_history_previews
    return self.onGetPreview (self.sample_for_preview, for_history=True)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 789, in onGetPreview
    S, D, SS, DD, DDM, SD, SDM = [ np.clip( nn.to_data_format(x,"NHWC", self.model_data_format), 0.0, 1.0) for x in ([target_src,target_dst] + self.AE_view (target_src, target_dst) ) ]
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 611, in AE_view
    self.warped_dst:warped_dst})
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 968, in run
    run_metadata_ptr)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1369, in _do_run
    run_metadata)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Attempting to perform BLAS operation using StreamExecutor without BLAS support
         [[node MatMul (defined at R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\Dense.py:66) ]]
         [[Sigmoid_3/_9]]
  (1) Internal: Attempting to perform BLAS operation using StreamExecutor without BLAS support
         [[node MatMul (defined at R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\Dense.py:66) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node MatMul:
 inter_AB/dense1/weight/read (defined at R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\Dense.py:47)
 mul (defined at R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\ops\__init__.py:400)

Input Source operations connected to node MatMul:
 inter_AB/dense1/weight/read (defined at R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\Dense.py:47)
 mul (defined at R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\ops\__init__.py:400)

Original stack trace for 'MatMul':
  File "threading.py", line 884, in _bootstrap
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\Trainer.py", line 58, in trainerThread
    debug=debug)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\ModelBase.py", line 193, in __init__
    self.on_initialize()
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 416, in on_initialize
    gpu_src_inter_AB_code = self.inter_AB (gpu_src_code)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\models\ModelBase.py", line 117, in __call__
    return self.forward(*args, **kwargs)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\archis\DeepFakeArchi.py", line 151, in forward
    x = self.dense1(x)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\LayerBase.py", line 14, in __call__
    return self.forward(*args, **kwargs)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\Dense.py", line 66, in forward
    x = tf.matmul(x, weight)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\math_ops.py", line 3655, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 5713, in mat_mul
    name=name)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 3569, in _create_op_internal
    op_def=op_def)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\Trainer.py", line 58, in trainerThread
    debug=debug)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\ModelBase.py", line 216, in __init__
    self.update_sample_for_preview(choose_preview_history=self.choose_preview_history)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\ModelBase.py", line 265, in update_sample_for_preview
    self.sample_for_preview = self.generate_next_samples()
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\ModelBase.py", line 461, in generate_next_samples
    sample.append ( generator.generate_next() )
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleGeneratorBase.py", line 21, in generate_next
    self.last_generation = next(self)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 112, in __next__
    return next(generator)
  File "R:\Info\IA\Private\Deepfake\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\joblib\SubprocessGenerator.py", line 73, in __next__
    gen_data = self.cs_queue.get()
  File "multiprocessing\queues.py", line 94, in get
  File "multiprocessing\connection.py", line 216, in recv_bytes
  File "multiprocessing\connection.py", line 318, in _recv_bytes
  File "multiprocessing\connection.py", line 340, in _get_more_data
MemoryError

**Comment by Subzero710** [comment]
This is the first time i train a model from my external ssd, this is also the first time i train on such a large dataset (49 000 for src and  34 000 for dst)

**Comment by Subzero710** [comment]
I tried with smaller dataset (1300 src and 3000 dst) this is less than what i trained with before. When launching the trainer, the graphic card does not seem to be triggered, so i dont think the program can find the graphic card

**Comment by Subzero710** [comment]
I tried again with DeepFaceLab DirectX12 instead of DeepFaceLab_NVIDIA_RTX3000_series and it worked.
DeepFaceLab_NVIDIA_RTX3000_series seems to require more VRAM to work
