### ISSUE TITLE
Could Someone Help Me?

### ISSUE THREAD

**Issue by mirfsz** [iperov/DeepFaceLab#5694]
Not really sure what any of these means... Or what I can do to fix it. Happens when i try to train SAEHD (step 6)

Error:
Traceback (most recent call last):
  File "D:\DeepFaceLab\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\Trainer.py", line 159, in trainerThread
    model_save()
  File "D:\DeepFaceLab\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\mainscripts\Trainer.py", line 68, in model_save
    model.save()
  File "D:\DeepFaceLab\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\ModelBase.py", line 393, in save
    self.onSave()
  File "D:\DeepFaceLab\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 759, in onSave
    model.save_weights ( self.get_strpath_storage_for_file(filename) )
  File "D:\DeepFaceLab\DeepFaceLab\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\leras\layers\Saveable.py", line 61, in save_weights
    d_dumped = pickle.dumps (d, 4)
MemoryError

**Comment by Cioscos** [comment]
Hi! You've too few RAM memory or you finish your paging file. Try to increase it.
