### ISSUE TITLE
DFL 2.0 GPU Memory not used..

### ISSUE THREAD

**Issue by blanuk** [iperov/DeepFaceLab#570]
Hi, me again.
DFL 2 dont use the memory on card in a right way.
In Dfl 1.0 i was able to run res 240 with batch size 8 on my Titan RTX (24GB)
If i try now res 240 with batch size 4 (all other on default) it consumed 8gb GPU Memory and then quits with errors.

Please tell me if u need some additional infos :)

**Comment by xomnow327** [comment]
As a Titan RTX owner, I'm not having this issue.  I'm running 256 res dfhd with defaults on batch 8 just fine.  If you're running in Windows, have you put your card into TCC mode?

**Comment by blanuk** [comment]
u run under windows or linux?
TCC Mode is just for quadro. and now, i did nothing like this.
just installed the newest nvidia driver, load the windows prebuilt exe, update it with the fix from this morning and let it run after

**Comment by blanuk** [comment]
here the full log:

Model first run.

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : TITAN RTX
  [1] : GeForce RTX 2080 Ti

[0] Which GPU indexes to choose? : 0
0

Caching GPU kernels...
[n] Enable autobackup ( y/n ?:help ) : n
[n] Write preview history ( y/n ?:help ) :
n
[0] Target iteration :
0
[y] Flip faces randomly ( y/n ?:help ) :
y
[8] Batch_size ( ?:help ) :
8
[128] Resolution ( 64-256 ?:help ) : 240
240
[f] Face type ( h/mf/f ?:help ) :
f
[y] Place models and optimizer on GPU ( y/n ?:help ) :
y
[dfhd] AE architecture ( dfhd/liaehd/df/liae ?:help ) :
dfhd
[256] AutoEncoder dimensions ( 32-1024 ?:help ) :
256
[64] Encoder dimensions ( 16-256 ?:help ) :
64
[64] Decoder dimensions ( 16-256 ?:help ) :
64
[22] Decoder mask dimensions ( 16-256 ?:help ) :
22
[y] Learn mask ( y/n ?:help ) :
y
[n] Use learning rate dropout ( y/n ?:help ) :
n
[y] Enable random warp of samples ( y/n ?:help ) :
y
[n] Enable 'true face' training ( y/n ?:help ) :
n
[0.0] Face style power ( 0.0..100.0 ?:help ) :
0.0
[0.0] Background style power ( 0.0..100.0 ?:help ) :
0.0
[none] Color transfer for src faceset ( none/rct/lct/mkl/idt/sot ?:help ) :
none
[n] Enable gradient clipping ( y/n ?:help ) :
n
[n] Enable pretraining mode ( y/n ?:help ) :
n
Initializing models: 100%|###############################################################| 5/5 [00:31<00:00,  6.26s/it]
Loading samples: 100%|###########################################################| 2275/2275 [00:02<00:00, 1080.52it/s]
Loading samples: 100%|###########################################################| 2240/2240 [00:02<00:00, 1007.42it/s]
2020-01-23 15:07:20.373233: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 4.00G (4294967296 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:20.435022: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 3.60G (3865470464 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:20.496346: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 3.24G (3478923264 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:20.556664: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.92G (3131030784 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:20.619149: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.62G (2817927680 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:20.679574: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.36G (2536134912 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:20.740630: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2282521344 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:21.191593: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:21.195894: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:21.200081: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:21.205459: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:21.270090: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:21.275233: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:21.319389: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:21.330864: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:21.546273: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:21.559052: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:21.571068: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:21.577559: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:21.730301: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:21.735474: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:22.123158: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:22.128272: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:22.325431: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:22.343070: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:22.533636: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:22.552854: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:22.644428: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:22.660059: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:22.690200: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:22.695322: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:22.751101: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:22.760155: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:22.798512: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:22.803652: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:22.878325: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:22.885971: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:22.893124: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:22.901087: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:23.012823: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:23.020479: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:23.026203: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:23.033341: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:23.092633: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-01-23 15:07:23.098922: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
Error:
Traceback (most recent call last):
  File "N:\xy\_internal\DeepFaceLab\models\ModelBase.py", line 232, in __init__
    self.get_static_preview()
  File "N:\xy\_internal\DeepFaceLab\models\ModelBase.py", line 340, in get_static_preview
    return self.onGetPreview (self.sample_for_preview)[0][1] #first preview, and bgr
  File "N:\xy\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 749, in onGetPreview
    st_m.append ( np.concatenate ( ar, axis=1) )
  File "<__array_function__ internals>", line 6, in concatenate
numpy.core._exceptions.MemoryError: Unable to allocate array with shape (240, 1200, 3) and data type float32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "N:\xy\_internal\DeepFaceLab\mainscripts\Trainer.py", line 57, in trainerThread
    debug=debug,
  File "N:\xy\_internal\DeepFaceLab\models\ModelBase.py", line 234, in __init__
    self.sample_for_preview = self.generate_next_samples()
  File "N:\xy\_internal\DeepFaceLab\models\ModelBase.py", line 405, in generate_next_samples
    self.last_sample = sample = [ generator.generate_next() for generator in self.generator_list]
  File "N:\xy\_internal\DeepFaceLab\models\ModelBase.py", line 405, in <listcomp>
    self.last_sample = sample = [ generator.generate_next() for generator in self.generator_list]
  File "N:\xy\_internal\DeepFaceLab\samplelib\SampleGeneratorBase.py", line 25, in generate_next
    self.last_generation = next(self)
  File "N:\xy\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 73, in __next__
    return next(generator)
  File "N:\xy\_internal\DeepFaceLab\core\joblib\SubprocessGenerator.py", line 48, in __next__
    gen_data = self.cs_queue.get()
  File "multiprocessing\queues.py", line 94, in get
  File "multiprocessing\connection.py", line 216, in recv_bytes
  File "multiprocessing\connection.py", line 318, in _recv_bytes
  File "multiprocessing\connection.py", line 340, in _get_more_data
MemoryError

**Comment by blanuk** [comment]
Did a complete new windows Installation, changes nothing :/ still the same problem

**Comment by iperov** [comment]
@blanuk not enough RAM. (not vram)

**Comment by blanuk** [comment]
@iperov 
I have 64 GB RAM and its not used (maybe about 16gb in use)

**Comment by iperov** [comment]
@blanuk send teamviewer access to deepfakescovery@gmail.om

**Comment by blanuk** [comment]
@iperov  well, i think i fixed it...
Its crazy. i increased my swap under windows to 200gb an now it works. 
crazy... but anyway, thanks for help :) (ps: the 100 bucks Donation yesterday was from me :) )

**Comment by xomnow327** [comment]
@blanuk You can indeed set a Titan to TCC in Windows:

There's an nvidia tool in: C:\Program Files\NVIDIA Corporation\NVSMI

nvidia-smi.exe -L

to list graphics adapters in the system.

and:

nvidia-smi.exe -g 0 -dm 1

to enable tcc mode on adapter 0.  -dm 0 to turn it off.  You'll have to reboot for it to change.

**Comment by kilerb** [comment]
What do you mean by you "increased your swap under windows to 200gb"?  What
is swap?  I have a titan 24gb too.  Was wondering how to make it as
efficient as possible.  Also, did you set it to TCC?  Did that make a
difference?  Thanks!

**Comment by blanuk** [comment]
u can set swap file for each drive, sso i set there a bigger one and my problem was gone.
i will not set it to tcc, have no use case for me

**Comment by robustini** [comment]
Same problem here with RTX 2080:

Initializing models: 100%|###############################################################| 5/5 [00:19<00:00,  3.82s/it]
Loading samples: 100%|############################################################| 1748/1748 [00:01<00:00, 916.04it/s]
Loading samples: 100%|##############################################################| 227/227 [00:00<00:00, 441.10it/s]
2020-04-29 21:45:23.968455: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:23.973423: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
=============== Model Summary ===============
==                                         ==
==            Model name: Putin_SAEHD      ==
==                                         ==
==     Current iteration: 0                ==
==                                         ==
==------------- Model Options -------------==
==                                         ==
==            resolution: 128              ==
==             face_type: f                ==
==     models_opt_on_gpu: True             ==
==                 archi: df               ==
==               ae_dims: 256              ==
==                e_dims: 64               ==
==                d_dims: 64               ==
==           d_mask_dims: 22               ==
==       masked_training: True             ==
==             eyes_prio: False            ==
==            lr_dropout: False            ==
==           random_warp: True             ==
==             gan_power: 0.0              ==
==       true_face_power: 0.0              ==
==      face_style_power: 0.0              ==
==        bg_style_power: 0.0              ==
==               ct_mode: none             ==
==              clipgrad: False            ==
==              pretrain: False            ==
==       autobackup_hour: 0                ==
== write_preview_history: False            ==
==           target_iter: 0                ==
==           random_flip: True             ==
==            batch_size: 8                ==
==                                         ==
==-------------- Running On ---------------==
==                                         ==
==          Device index: 0                ==
==                  Name: GeForce RTX 2080 ==
==                  VRAM: 8.00GB           ==
==                                         ==
=============================================
Starting. Press "Enter" to stop training and save model.

Trying to do the first iteration. If an error occurs, reduce the model parameters.

2020-04-29 21:45:25.871797: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:25.877536: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:25.901106: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:25.905150: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.010353: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.015380: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.033048: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.038134: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.061835: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.066704: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.102862: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.107000: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.133845: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.138649: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.377547: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.382345: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory

**Comment by robustini** [comment]
Same problem here, but work fine with GTX 1060 6 Gb, damn:


Initializing models: 100%|###############################################################| 5/5 [00:19<00:00,  3.82s/it]
Loading samples: 100%|############################################################| 1748/1748 [00:01<00:00, 916.04it/s]
Loading samples: 100%|##############################################################| 227/227 [00:00<00:00, 441.10it/s]
2020-04-29 21:45:23.968455: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:23.973423: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
=============== Model Summary ===============
==                                         ==
==            Model name: Putin_SAEHD      ==
==                                         ==
==     Current iteration: 0                ==
==                                         ==
==------------- Model Options -------------==
==                                         ==
==            resolution: 128              ==
==             face_type: f                ==
==     models_opt_on_gpu: True             ==
==                 archi: df               ==
==               ae_dims: 256              ==
==                e_dims: 64               ==
==                d_dims: 64               ==
==           d_mask_dims: 22               ==
==       masked_training: True             ==
==             eyes_prio: False            ==
==            lr_dropout: False            ==
==           random_warp: True             ==
==             gan_power: 0.0              ==
==       true_face_power: 0.0              ==
==      face_style_power: 0.0              ==
==        bg_style_power: 0.0              ==
==               ct_mode: none             ==
==              clipgrad: False            ==
==              pretrain: False            ==
==       autobackup_hour: 0                ==
== write_preview_history: False            ==
==           target_iter: 0                ==
==           random_flip: True             ==
==            batch_size: 8                ==
==                                         ==
==-------------- Running On ---------------==
==                                         ==
==          Device index: 0                ==
==                  Name: GeForce RTX 2080 ==
==                  VRAM: 8.00GB           ==
==                                         ==
=============================================
Starting. Press "Enter" to stop training and save model.

Trying to do the first iteration. If an error occurs, reduce the model parameters.

2020-04-29 21:45:25.871797: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:25.877536: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:25.901106: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:25.905150: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.010353: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.015380: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.033048: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.038134: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.061835: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.066704: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.102862: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.107000: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.133845: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.138649: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.377547: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-29 21:45:26.382345: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.13G (2287871488 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory

**Comment by hyyz17200** [comment]
Me too!  1950x / 32GB RAM / 2060Super 8G
After changing page file to 200GB max, issues solved.
