### ISSUE TITLE
TypeError: Can't parse 'center'. Sequence item with index 0 has a wrong type

### ISSUE THREAD

**Issue by KDR622** [iperov/DeepFaceLab#5713]
This is an error when I run the 6) train SAEHD.bat command on linux, how to solve it?
-----------------------------------------------------------------------------------------------------------------------------------
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/deepfacelab/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/anaconda3/envs/deepfacelab/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/deepfacelab/core/joblib/SubprocessGenerator.py", line 54, in process_func
    gen_data = next (self.generator_func)
  File "/usr/local/deepfacelab/samplelib/SampleGeneratorFace.py", line 136, in batch_func
    raise Exception ("Exception occured in sample %s. Error: %s" % (sample.filename, traceback.format_exc() ) )
Exception: Exception occured in sample /usr/local/deepfacelab/workspace/data_dst/aligned/00143_0.jpg. Error: Traceback (most recent call last):
  File "/usr/local/deepfacelab/samplelib/SampleGeneratorFace.py", line 134, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "/usr/local/deepfacelab/samplelib/SampleProcessor.py", line 92, in process
    params_per_resolution[resolution] = imagelib.gen_warp_params(resolution,
  File "/usr/local/deepfacelab/core/imagelib/warp.py", line 37, in gen_warp_params
    random_transform_mat = cv2.getRotationMatrix2D((w // 2, w // 2), rotation, scale)
TypeError: Can't parse 'center'. Sequence item with index 0 has a wrong type`

**Comment by KDR622** [comment]
Change the opencv-python version to 4.5.1.48.
