### ISSUE TITLE
traceback(most recent call last)

### ISSUE THREAD

**Issue by Ujah0** [iperov/DeepFaceLab#5728]
![Screenshot 2023-09-23 122437](https://github.com/iperov/DeepFaceLab/assets/145894376/941aa802-8226-4cd2-97de-a35294e8e310)
how do i solve this.

Running DeepFaceLive.
Traceback (most recent call last):
  File "_internal\DeepFaceLive\main.py", line 95, in <module>
    main()
  File "_internal\DeepFaceLive\main.py", line 88, in main
    args.func(args)
  File "_internal\DeepFaceLive\main.py", line 30, in run_DeepFaceLive
    from apps.DeepFaceLive.DeepFaceLiveApp import DeepFaceLiveApp
  File "C:\Users\HP Victus\Documents\met\DeepFaceLive_DirectX12\_internal\DeepFaceLive\apps\DeepFaceLive\DeepFaceLiveApp.py", line 11, in <module>
    from . import backend
  File "C:\Users\HP Victus\Documents\met\DeepFaceLive_DirectX12\_internal\DeepFaceLive\apps\DeepFaceLive\backend\__init__.py", line 1, in <module>
    from .BackendBase import (BackendConnection, BackendConnectionData, BackendDB,
  File "C:\Users\HP Victus\Documents\met\DeepFaceLive_DirectX12\_internal\DeepFaceLive\apps\DeepFaceLive\backend\BackendBase.py", line 7, in <module>
    from xlib import time as lib_time
  File "C:\Users\HP Victus\Documents\met\DeepFaceLive_DirectX12\_internal\DeepFaceLive\xlib\time\__init__.py", line 1, in <module>
    from .time_ import timeit, measure, FPSCounter, AverageMeasurer
  File "C:\Users\HP Victus\Documents\met\DeepFaceLive_DirectX12\_internal\DeepFaceLive\xlib\time\time_.py", line 11, in <module>
    if not kernel32.QueryPerformanceFrequency(_perf_freq):
  File "C:\Users\HP Victus\Documents\met\DeepFaceLive_DirectX12\_internal\DeepFaceLive\xlib\api\win32\wintypes\wintypes.py", line 37, in wrapper
    raise RuntimeError(f'Unable to load {dll_name} library.')
RuntimeError: Unable to load kernel32 library.

**Comment by BigSegun** [comment]
have you gotten a way out ?
