### ISSUE TITLE
Multi-GPU Issue (Titan RTX x2)

### ISSUE THREAD

**Issue by The-Digital-Void** [iperov/DeepFaceLab#586]
My training runs perfectly fine if I use either index 0 or 1. However, when I try to use both I get the following error.

==------------- Running On -------------==
==                                      ==
==          Device index: 0             ==
==                  Name: TITAN RTX     ==
==                  VRAM: 24.00GB       ==
==          Device index: 1             ==
==                  Name: TITAN RTX     ==
==                  VRAM: 24.00GB       ==
==                                      ==
==========================================
Starting. Target iteration: 100000. Press "Enter" to stop training and save model.
2020-01-27 19:09:33.301000: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory

**(The above line repeats about 40 times, removed for readability)**

Error: OOM when allocating tensor with shape[2,276480,384] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cuda_host_bfc
         [[node concat_49 (defined at C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\tensor_ops.py:58) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'concat_49', defined at:
  File "threading.py", line 884, in _bootstrap
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Trainer.py", line 57, in trainerThread
    debug=debug,
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\ModelBase.py", line 173, in __init__
    self.on_initialize()
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 563, in on_initialize
    src_dst_loss_gv = nn.tf_average_gv_list (gpu_src_dst_loss_gvs)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\tensor_ops.py", line 58, in tf_average_gv_list
    result[i] = ( tf.reduce_mean( tf.concat (gs, 0), 0 ), v )
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1256, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1149, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[2,276480,384] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cuda_host_bfc
         [[node concat_49 (defined at C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\tensor_ops.py:58) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Traceback (most recent call last):
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[2,276480,384] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cuda_host_bfc
         [[{{node concat_49}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Trainer.py", line 119, in trainerThread
    iter, iter_time = model.train_one_iter()
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\ModelBase.py", line 411, in train_one_iter
    losses = self.onTrainOneIter()
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 704, in onTrainOneIter
    src_loss, dst_loss = self.src_dst_train (warped_src, target_src, target_srcm, warped_dst, target_dst, target_dstm)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 580, in src_dst_train
    self.target_dstm:target_dstm,
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[2,276480,384] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cuda_host_bfc
         [[node concat_49 (defined at C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\tensor_ops.py:58) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'concat_49', defined at:
  File "threading.py", line 884, in _bootstrap
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Trainer.py", line 57, in trainerThread
    debug=debug,
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\ModelBase.py", line 173, in __init__
    self.on_initialize()
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 563, in on_initialize
    src_dst_loss_gv = nn.tf_average_gv_list (gpu_src_dst_loss_gvs)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\tensor_ops.py", line 58, in tf_average_gv_list
    result[i] = ( tf.reduce_mean( tf.concat (gs, 0), 0 ), v )
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1256, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1149, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[2,276480,384] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cuda_host_bfc
         [[node concat_49 (defined at C:\Users\Dantevus\Desktop\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\tensor_ops.py:58) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Done.
Press any key to continue . . .

**Comment by blanuk** [comment]
ur system specs? RAM?

**Comment by The-Digital-Void** [comment]
RAM: 64GB 
CPU: i9-9940X
OS: Windows 10 64-bit

**Comment by The-Digital-Void** [comment]
So, weird solution I've found. Forcing my Windows pagefile to be at minimum 64gb seems to have fixed the issue. I'm not sure why this worked, but it did.

**Comment by blanuk** [comment]
was the same in my case :)

**Comment by The-Digital-Void** [comment]
I've only used it for simultaneous processing so far, no multi-gpu on a single model yet since fixing it. Closing this issue so it doesn't clutter up the logs. :)

**Comment by fuorissimo** [comment]
I have the same problem with 2 x GTX 1080 TI. 
And if i run only one, not work, if disab le second, work again.
