### ISSUE TITLE
TypeError: object of type 'PosixPath' has no len()

### ISSUE THREAD

**Issue by l0ophole** [iperov/DeepFaceLab#599]
OS: Debian Linux
GPU: Nvidia T4
CUDA: 10.0.130-1
Python: 3.6
Command line: python3.6 DeepFaceLab/main.py merge --input-dir workspace/data_dst --output-dir workspace/data_dst/merged --output-mask-dir workspace/data_dst/merged_mask --aligned-dir workspace/data_dst/aligned --model-dir workspace/model --model "SAEHD"

I've been training a model for the past 48 hours and I have already merged the model and exported it to a video twice with no problems. I just tried to merge the model again and now it gets to frame 95 and crashes. See the error log below this paragraph. Is my model useless now? I've been training it on a Google Compute VM so if the model is useless then I've wasted $10 on the Google Compute VM so far.

Merging:   3% 95/3623 [00:05<03:27, 17.00it/s]Exception while process data [/content/workspace/data_dst/00096.jpg]: Traceback (most recent call last):
  File "/content/DeepFaceLab/mainscripts/Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "/content/DeepFaceLab/merger/MergeMasked.py", line 327, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "/content/DeepFaceLab/merger/MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "/content/DeepFaceLab/facelib/LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "/content/DeepFaceLab/facelib/LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'PosixPath' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/DeepFaceLab/core/joblib/SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "/content/DeepFaceLab/mainscripts/Merger.py", line 157, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [/content/workspace/data_dst/00096.jpg]: Traceback (most recent call last):
  File "/content/DeepFaceLab/mainscripts/Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "/content/DeepFaceLab/merger/MergeMasked.py", line 327, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "/content/DeepFaceLab/merger/MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "/content/DeepFaceLab/facelib/LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "/content/DeepFaceLab/facelib/LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'PosixPath' has no len()

/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
Exception while process data [/content/workspace/data_dst/00097.jpg]: Traceback (most recent call last):
  File "/content/DeepFaceLab/mainscripts/Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "/content/DeepFaceLab/merger/MergeMasked.py", line 327, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "/content/DeepFaceLab/merger/MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "/content/DeepFaceLab/facelib/LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "/content/DeepFaceLab/facelib/LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'PosixPath' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/DeepFaceLab/core/joblib/SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "/content/DeepFaceLab/mainscripts/Merger.py", line 157, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [/content/workspace/data_dst/00097.jpg]: Traceback (most recent call last):
  File "/content/DeepFaceLab/mainscripts/Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "/content/DeepFaceLab/merger/MergeMasked.py", line 327, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "/content/DeepFaceLab/merger/MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "/content/DeepFaceLab/facelib/LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "/content/DeepFaceLab/facelib/LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'PosixPath' has no len()

/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))

**Comment by iperov** [comment]
unable to reproduce the issue


>  I've wasted $10 on the Google Compute VM so far.

15. Disclaimer of Warranty.

  THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY
APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT
HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY
OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM
IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF
ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

**Comment by l0ophole** [comment]
I'm not asking to be reimbursed. I'd just like to know why it's happening and how I can fix it. I forgot to mention that I did the training on the Google Compute VM and I did the merge on a Google Colab notebook. I think they have slightly different CUDA versions. They do have the same model GPU, though.

**Comment by wa407** [comment]
也许你可以把模型文件发给baiyunkaka@163.com,我可以帮助修复。
Maybe you can send the model file to baiyunkaka@163.com, and I can help repair it.

**Comment by TooMuchFun** [comment]
Re-run with newest DFL release. Then try re-extract images.

also kindly use official Issue template next time thx

**Comment by l0ophole** [comment]
Is there a way to run the merge on Linux without running an xserver? I'm getting a cannot connect to display :0 error.

**Comment by l0ophole** [comment]
I tried the merge again on the Colab version and it worked this time after I let the model train for a few more hours first. I don't know if it was a bug that was fixed upstream or if the training fixed the model somehow. I haven't gotten the error that I was receiving in the OP again yet.

**Comment by iperov** [comment]
fixed
