### ISSUE TITLE
merge SAE HD ERROR

### ISSUE THREAD

**Issue by lhw5348** [iperov/DeepFaceLab#600]
File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 157, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\00001.png]: Traceback (most recent call last):
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 331, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'WindowsPath' has no len()

Exception while process data [C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\00001.png]: Traceback (most recent call last):
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 331, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'WindowsPath' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 157, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\00001.png]: Traceback (most recent call last):
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 331, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'WindowsPath' has no len()

Exception while process data [C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\00001.png]: Traceback (most recent call last):
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 331, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'WindowsPath' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 157, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\00001.png]: Traceback (most recent call last):
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 331, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'WindowsPath' has no len()

Exception while process data [C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\00001.png]: Traceback (most recent call last):
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 331, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'WindowsPath' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 157, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\00001.png]: Traceback (most recent call last):
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 331, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'WindowsPath' has no len()

Exception while process data [C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\00001.png]: Traceback (most recent call last):
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 331, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'WindowsPath' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 157, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\00001.png]: Traceback (most recent call last):
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 331, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'WindowsPath' has no len()

Exception while process data [C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\00001.png]: Traceback (most recent call last):
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 331, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'WindowsPath' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 157, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\00001.png]: Traceback (most recent call last):
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 151, in process_data
    final_img = MergeMasked (self.predictor_func, self.predictor_input_shape, cfg, frame_info)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 331, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 13, in MergeMaskedFace
    img_face_mask_a = LandmarksProcessor.get_image_hull_mask (img_bgr.shape, img_face_landmarks)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 355, in get_image_hull_mask
    lmrks = expand_eyebrows(image_landmarks, eyebrows_expand_mod)
  File "C:\Users\guita\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\facelib\LandmarksProcessor.py", line 324, in expand_eyebrows
    if len(lmrks) != 68:
TypeError: object of type 'WindowsPath' has no len()

Merging:   0%|                                        | 0/3711 [00:58<?, ?it/s]
Session is saved to model/new_Quick96_merger_session.dat
Done.

**Comment by lhw5348** [comment]
DFL = 2020.02.02 VER

**Comment by labels168** [comment]
This is the case for me

**Comment by iperov** [comment]
fixed
