### ISSUE TITLE
Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED

### ISSUE THREAD

**Issue by bxjxxyy** [iperov/DeepFaceLab#63]
When I run step7:  7) convert H128 with all default settings.This error happens:
Choose mode: (1) hist match, (2) hist match bw, (3) seamless (default), (4) seamless hist match :
Choose erode mask modifier [-100..100] (default 0) :
Choose blur mask modifier [-100..200] (default 0) :
Choose output face scale modifier [-50..50] (default 0) :
Transfer color from original DST image? [0..1] (default 0) :
Degrade color power of final image [0..100] (default 0) :
Export png with alpha channel? [0..1] (default 0) :
Running converter.

Loading model...
===== Model summary =====
== Model name: H128
==
== Current epoch: 3712
==
== Options:
== |== batch_size : 1
== |== multi_gpu : False
== |== created_vram_gb : 8.0
== Running on:
== |== [0 : GeForce GTX 1070]
=========================
2018-12-12 20:41:01.078817: E tensorflow/stream_executor/cuda/cuda_blas.cc:464] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2018-12-12 20:41:01.091446: E tensorflow/stream_executor/cuda/cuda_blas.cc:464] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2018-12-12 20:41:02.724756: E tensorflow/stream_executor/cuda/cuda_dnn.cc:353] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED

**Comment by iperov** [comment]
try prebuilt windows binary

**Comment by gessyoo** [comment]
bxjxxyy, use a BitTorrent client to download the prebuilt DeepFaceLab binary from this forum: https://rutracker.org/forum/viewtopic.php?p=75318742.  There's a magnet link there to download a prebuilt DeepFaceLab, ready to run under Windows 10.  You may need to update the video drivers for your GTX card.

**Comment by DMKITServices** [comment]
im having the same problem on training i have downloaded the torrent for windows and im still getting

===== Model summary =====
== Model name: H64
==
== Current iteration: 0
==
== Model options:
== |== autobackup : True
== |== write_preview_history : True
== |== batch_size : 2
== |== sort_by_yaw : True
== |== random_flip : True
== |== lighter_ae : True
== |== pixel_loss : True
== Running on:
== |== [0 : GeForce GTX 1060 3GB]
=========================
Starting. Press "Enter" to stop training and save model.
2019-06-21 11:48:34.145093: E tensorflow/stream_executor/cuda/cuda_blas.cc:464] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED

US_ALLOC_FAILED
Error: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node loss/model_2_loss/convolution}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](loss/model_2_loss/convolution-0-TransposeNHWCToNCHW-LayoutOptimizer, loss/model_2_loss/Const)]]
         [[{{node loss/add_2/_551}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3706_loss/add_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Traceback (most recent call last):
  File "G:\torrents\DeepFaceLab\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 107, in trainerThread
    iter, iter_time = model.train_one_iter()
  File "G:\torrents\DeepFaceLab\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\models\ModelBase.py", line 472, in train_one_iter
    losses = self.onTrainOneIter(sample, self.generator_list)
  File "G:\torrents\DeepFaceLab\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\models\Model_H64\Model.py", line 89, in onTrainOneIter
    total, loss_src_bgr, loss_src_mask, loss_dst_bgr, loss_dst_mask = self.ae.train_on_batch( [warped_src, target_src_full_mask, warped_dst, target_dst_full_mask], [target_src, target_src_full_mask, target_dst, target_dst_full_mask] )
  File "G:\torrents\DeepFaceLab\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "G:\torrents\DeepFaceLab\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "G:\torrents\DeepFaceLab\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "G:\torrents\DeepFaceLab\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "G:\torrents\DeepFaceLab\DeepFaceLabCUDA9.2SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node loss/model_2_loss/convolution}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](loss/model_2_loss/convolution-0-TransposeNHWCToNCHW-LayoutOptimizer, loss/model_2_loss/Const)]]
         [[{{node loss/add_2/_551}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3706_loss/add_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Done.
Press any key to continue . . .
