### ISSUE TITLE
Export with alpha channel error

### ISSUE THREAD

**Issue by tfis2** [iperov/DeepFaceLab#64]
Stops after exporting 303 frames. All models and modes

Exception while process data [E:\DeepFaceLab_build_02_12_2018\DeepFaceLabTorrent\workspace\data_dst\00304.png]: Traceback (most recent call last):
  File "E:\DeepFaceLab_build_02_12_2018\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 233, in subprocess
    result = self.onClientProcessData (data)
  File "E:\DeepFaceLab_build_02_12_2018\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Converter.py", line 175, in onClientProcessData
    image = self.converter.convert_face(image, image_landmarks, self.debug)
  File "E:\DeepFaceLab_build_02_12_2018\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\models\ConverterMasked.py", line 161, in convert_face
    hist_match_2[ hist_match_1 > 1.0 ] = 1.0
IndexError: boolean index did not match indexed array along dimension 2; dimension is 4 but corresponding boolean dimension is 3.

**Comment by tfis2** [comment]
Didn't see your fix 1h agor. TY
