### ISSUE TITLE
RESOLVED  - My fault - Merging quick 96 & SAEHD both displaying this error when i tab from keyboard shortcut into main screen

### ISSUE THREAD

**Issue by defacedproductions** [iperov/DeepFaceLab#645]
I'm migrating from the old version to the new and i'm Trying to merge quick 96, training works perfectly but when i hit tab on the interactive converter to go to the image screen i get this error immediately.  

Error: OpenCV(4.1.0) c:\projects\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0xe227985e::Set<3,4,-1>,struct cv::impl::A0xe227985e::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 5

Traceback (most recent call last):
  File "C:\Deepfacelab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 832, in main
    model_iter             = model.get_iter()
  File "C:\Deepfacelab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 271, in run
    if self.on_tick() and all ([cli.state == 0 for cli in self.clis]):
  File "C:\Deepfacelab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 472, in on_tick
    self.screen_manager.switch_screens()
  File "C:\Deepfacelab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\MergerScreen\MergerScreen.py", line 140, in switch_screens
    self.screens[self.current_screen_id].show(force=True)
  File "C:\Deepfacelab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\MergerScreen\MergerScreen.py", line 105, in show
    io.show_image(self.scrn_manager.wnd_name, screen)
  File "C:\Deepfacelab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\interact\interact.py", line 125, in show_image
    self.on_show_image(wnd_name,img)
  File "C:\Deepfacelab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\interact\interact.py", line 430, in on_show_image
    cv2.imshow (wnd_name, img)
cv2.error: OpenCV(4.1.0) c:\projects\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0xe227985e::Set<3,4,-1>,struct cv::impl::A0xe227985e::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 5

-------------------------------------
I Just used the merge quick 96 command
Happens every time. 
Windows 10 gtx1080 8gb vram

**Comment by defacedproductions** [comment]
I assume i was the stray frames left in where they should have been cleared out. because when i cleared out the model and deleted any frames i didnt want in the training it seemed to work fine

**Comment by sandstrand** [comment]
Could you elaborate on exactly what was the cause, and the solution to this issue? I am having a similar problem:
```
Traceback (most recent call last):
  File "D:\projects\DeepFake\Iamthearm\DFL_smith_to_midget\_internal\DeepFaceLab\mainscripts\Merger.py", line 208, in main
    subprocess_count       = subprocess_count,
  File "D:\projects\DeepFake\Iamthearm\DFL_smith_to_midget\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 268, in run
    if self.on_tick() and all ([cli.state == 0 for cli in self.clis]):
  File "D:\projects\DeepFake\Iamthearm\DFL_smith_to_midget\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 414, in on_tick
    self.screen_manager.switch_screens()
  File "D:\projects\DeepFake\Iamthearm\DFL_smith_to_midget\_internal\DeepFaceLab\merger\MergerScreen\MergerScreen.py", line 140, in switch_screens
    self.screens[self.current_screen_id].show(force=True)
  File "D:\projects\DeepFake\Iamthearm\DFL_smith_to_midget\_internal\DeepFaceLab\merger\MergerScreen\MergerScreen.py", line 105, in show
    io.show_image(self.scrn_manager.wnd_name, screen)
  File "D:\projects\DeepFake\Iamthearm\DFL_smith_to_midget\_internal\DeepFaceLab\core\interact\interact.py", line 131, in show_image
    self.on_show_image(wnd_name,img)
  File "D:\projects\DeepFake\Iamthearm\DFL_smith_to_midget\_internal\DeepFaceLab\core\interact\interact.py", line 466, in on_show_image
    cv2.imshow (wnd_name, img)
cv2.error: OpenCV(4.1.0) c:\projects\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0xe227985e::Set<3,4,-1>,struct cv::impl::A0xe227985e::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 5
```
