### ISSUE TITLE
Run initialize_main_env()

### ISSUE THREAD

**Issue by boreltaf** [iperov/DeepFaceLab#647]
I am trying to run data_src extract faces S3FD to extract the faces but have this errors message

Traceback (most recent call last):                                                                                                                                    File "C:\Users\qwerty\Downloads\Programs\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 350, in <module>                                                     arguments.func(arguments)                                                                                                                                         File "C:\Users\qwerty\Downloads\Programs\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 41, in process_extract                                               force_gpu_idxs          = [ int(x) for x in arguments.force_gpu_idxs.split(',') ] if arguments.force_gpu_idxs is not None else None,                              File "C:\Users\qwerty\Downloads\Programs\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Extractor.py", line 702, in main                                        if not cpu_only else nn.DeviceConfig.CPU()                                                                                                                        File "C:\Users\qwerty\Downloads\Programs\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\nn.py", line 247, in ask_choose_device_idxs                              devices = Devices.getDevices()                                                                                                                                    File "C:\Users\qwerty\Downloads\Programs\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\device.py", line 144, in getDevices                                      raise Exception("nn devices are not initialized. Run initialize_main_env() in main process.")                                                                   Exception: nn devices are not initialized. Run initialize_main_env() in main process.                                                                               Press any key to continue . . .                       

please what is the problem?

**Comment by iperov** [comment]
unable to reproduce
all works fine at 99.9% of users

**Comment by AeonPrime** [comment]
Having the same issue, running on CPU since I'm sporting an AMD GPU. Not sure what causes this and can't find a decent explanation for this either.

**Comment by pascaaaal** [comment]
I have the same error. I even tried to run it with my CPU but then it raises:
Exception: Unable to start subprocesses.

**Comment by gosdeepak** [comment]
Have the same issue. Using AMD radeon RX 570

**Comment by Avazut** [comment]
This error occurs only if CUDA is not installed properly, because it is exactly as pascaaaal had said, this line refers to CUDA.

Excuse my bad English, I am from Germany.

**Comment by ghost** [comment]
Does this issue still persist? If not, would you mind closing it?
