### ISSUE TITLE
xseg training - latest update error

### ISSUE THREAD

**Issue by jejz** [iperov/DeepFaceLab#692]
Loading samples: 100%|############################################################| 6256/6256 [00:22<00:00, 281.68it/s]
Loading samples: 100%|##########################################################| 34188/34188 [00:47<00:00, 725.82it/s]
Using 290 segmented samples.
Exception in thread Thread-14:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "C:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessGenerator.py", line 11, in launch_thread
    generator._start()
  File "C:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessGenerator.py", line 43, in _start
    p.start()
  File "multiprocessing\process.py", line 105, in start
  File "multiprocessing\context.py", line 223, in _Popen
  File "multiprocessing\context.py", line 322, in _Popen
  File "multiprocessing\popen_spawn_win32.py", line 65, in __init__
  File "multiprocessing\reduction.py", line 60, in dump
OverflowError: cannot serialize a bytes object larger than 4 GiB

Exception in thread Thread-15:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "C:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessGenerator.py", line 11, in launch_thread
    generator._start()
  File "C:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessGenerator.py", line 43, in _start
    p.start()
  File "multiprocessing\process.py", line 105, in start
  File "multiprocessing\context.py", line 223, in _Popen
  File "multiprocessing\context.py", line 322, in _Popen
  File "multiprocessing\popen_spawn_win32.py", line 65, in __init__
  File "multiprocessing\reduction.py", line 60, in dump
OverflowError: cannot serialize a bytes object larger than 4 GiB
Exception in thread Thread-16:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "C:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessGenerator.py", line 11, in launch_thread
    generator._start()
  File "C:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessGenerator.py", line 43, in _start
    p.start()
  File "multiprocessing\process.py", line 105, in start
  File "multiprocessing\context.py", line 223, in _Popen
  File "multiprocessing\context.py", line 322, in _Popen
  File "multiprocessing\popen_spawn_win32.py", line 65, in __init__
  File "multiprocessing\reduction.py", line 60, in dump
OverflowError: cannot serialize a bytes object larger than 4 GiB

Exception in thread Thread-17:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "C:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessGenerator.py", line 11, in launch_thread
    generator._start()
  File "C:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessGenerator.py", line 43, in _start
    p.start()
  File "multiprocessing\process.py", line 105, in start
  File "multiprocessing\context.py", line 223, in _Popen
  File "multiprocessing\context.py", line 322, in _Popen
  File "multiprocessing\popen_spawn_win32.py", line 65, in __init__
  File "multiprocessing\reduction.py", line 60, in dump
OverflowError: cannot serialize a bytes object larger than 4 GiB

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
EOFError: Ran out of input
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
EOFError: Ran out of input
  File "multiprocessing\spawn.py", line 115, in _main
EOFError: Ran out of input
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
EOFError: Ran out of input

**Comment by iperov** [comment]
fixed
