### ISSUE TITLE
Face extraction not working: Failed to load the native TensorFlow runtime

### ISSUE THREAD

**Issue by fakirmac** [iperov/DeepFaceLab#694]
I'm using DeepFaceLab_CUDA_9.2_SSE
I'm trying to extract faces from jpg or png files. When I launch any of the face extraction bat files (in order to extract from either data_src or data_dst), I have this message:

Performing 1st pass...
Running on CPU0.
Exception: Traceback (most recent call last):
  File "D:\DFL\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\DFL\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\DFL\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\DFL\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\joblib\SubprocessorBase.py", line 59, in _subprocess_run
    self.on_initialize(client_dict)
  File "D:\DFL\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\mainscripts\Extractor.py", line 72, in on_initialize
    nnlib.import_all (device_config)
  File "D:\DFL\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\nnlib\nnlib.py", line 1159, in import_all
    nnlib.import_keras(device_config)
  File "D:\DFL\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\nnlib\nnlib.py", line 180, in import_keras
    nnlib._import_tf(device_config)
  File "D:\DFL\DeepFaceLab_CUDA_9.2_SSE\_internal\DeepFaceLab\nnlib\nnlib.py", line 152, in _import_tf
    import tensorflow as tf
  File "D:\DFL\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "D:\DFL\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "D:\DFL\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "D:\DFL\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\DFL\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\DFL\DeepFaceLab_CUDA_9.2_SSE\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

Win 10 Home 64-bit
NVIDIA GeForce GTX 1050
Processor: Intel Core i5
RAM 8GB
Python 3.8
Cuda 9.2 installed with its compatible cudnn
Tensorflow installed automatically with Python I guess cuz I can't get around installing it from the website.... I really don't have any programming experience at all.

PLEASE HELP

**Comment by iperov** [comment]
where did you read to install cuda for DFL ?

**Comment by fakirmac** [comment]
https://www.youtube.com/watch?v=nboXZlXGFWM

**Comment by iperov** [comment]
2018 srsly ?

**Comment by fakirmac** [comment]
Oh ! but I didn't install the old version of Cuda I checked ! I saw that it was old but I installed the latest toolkits.

**Comment by fakirmac** [comment]
But I still have the problem why close the issue ?
