### ISSUE TITLE
Error extracting data_src frames from video 

### ISSUE THREAD

**Issue by hensing2020** [iperov/DeepFaceLab#703]
Always get an error at Command #5 : **Extract data_src frames from Video**

(base) iMac:DeepFaceLab hernning$ python main.py videoed extract-video --input-file WORKSPACE/data_src.mp4  --output-dir WORKSPACE/data_src 
Traceback (most recent call last):
  File "main.py", line 11, in <module> 
from interact import interact as io
  File "/Users/hernning/Documents/deepfakes/DeepFaceLab/interact/__init__.py", line 1, in <module> 
from .interact import interact
     File "/Users/hernning/Documents/deepfakes/DeepFaceLab/interact/interact.py", line 7, in <module> 
import cv2
ModuleNotFoundError: No module named 'cv2'

any idea ???  THANKS IN ADVANCE !!!!

Using macOS Catalina 10.15.4
with python 3.7

**Comment by iperov** [comment]
macos is unsupported

**Comment by TalosOfCrete** [comment]
Just run
`pip install opencv-python` in a terminal window.  You’re just missing the opencv module.

**Comment by hensing2020** [comment]
I did install python. before, but now I get the following:

(base) iMac:DeepFaceLab hernning$ python main.py videoed extract-video --input-file WORKSPACE/data_src.mp4  --output-dir WORKSPACE/data_src 
Traceback (most recent call last):
  File "main.py", line 331, in <module>
    arguments.func(arguments)
  File "main.py", line 220, in process_videoed_extract_video
    from mainscripts import VideoEd
  File "/Users/hernning/Documents/deepfakes/DeepFaceLab/mainscripts/VideoEd.py", line 3, in <module>
    import ffmpeg
ModuleNotFoundError: No module named 'ffmpeg'

WHAT IS THE PROBLEM ?!?
I DONT UNDERSTAND ???

**Comment by feepdakenoob** [comment]
If you don't understand:

"ModuleNotFoundError: No module named 'ffmpeg'"

This might not be for you

**Comment by jeremybarbaud** [comment]
pip install ffmpeg 
or 
pip install ffmpeg-python if the first not working ;)

**Comment by ghost** [comment]
Issue solved (or it seems like user error), please close it.
