### ISSUE TITLE
Some problem about merge Quick96.bat

### ISSUE THREAD

**Issue by Rocky-17** [iperov/DeepFaceLab#722]
**### ==----------- Model Options -----------==
==                                     ==
==        batch_size: 4                ==
==                                     ==
==------------ Running On -------------==
==                                     ==
==      Device index: 0                ==
==              Name: GeForce GTX 1050 ==
==              VRAM: 2.00GB           ==
==                                     ==
=========================================**

### **when I run 7) merge Quick96.bat，if I chose use interactive merger, and next frame to a image which have face, it would be like this:**

```
[y] Use interactive merger? ( y/n ) : y
Collecting alignments: 100%|########################################################| 203/203 [00:00<00:00, 349.73it/s]
Computing motion vectors: 100%|####################################################| 203/203 [00:00<00:00, 1049.03it/s]
Running on CPU3.
Running on CPU0.
Running on CPU1.
Running on CPU2.
Merging:   0%|                                                                                 | 0/203 [00:00<?, ?it/s]Exception while process data [D:\DeepFaceLab\DeepFaceLab_NVIDIA\workspace\data_dst\00018.jpg]: Traceback (most recent call last):
  File "D:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "D:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "D:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "D:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [D:\DeepFaceLab\DeepFaceLab_NVIDIA\workspace\data_dst\00018.jpg]: Traceback (most recent call last):
  File "D:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "D:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "D:\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment
```
 
But if I chose not use interactive merger, it will work well.How could I handle this?

**Comment by iperov** [comment]
use last build
