### ISSUE TITLE
ImportError: cannot import name `XSegEditor`

### ISSUE THREAD

**Issue by Rakloedder** [iperov/DeepFaceLab#723]
This error I get when starting 5.XSeg) data_dst mask for XSeg trainer - edit.bat (build 15_4_2020):

```
Traceback (most recent call last):
  File "D:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 318, in <module>
    arguments.func(arguments)
  File "D:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 266, in process_xsegeditor
    from XSegEditor import XSegEditor
ImportError: cannot import name 'XSegEditor'

```

**Comment by capsmanofficial** [comment]
https://www.youtube.com/watch?v=1smpMsfC3ls

**Comment by Rakloedder** [comment]
> 
> 
> https://www.youtube.com/watch?v=1smpMsfC3ls

I don`t see any reference to this issue in the linked video.

**Comment by capsmanofficial** [comment]
in these cases, wait for the software creator to respond to you

**Comment by ghost** [comment]
Does this issue still persist? If not, would you mind closing it?
