### ISSUE TITLE
Please consider pinning pipqt5 to version

### ISSUE THREAD

**Issue by elemantalcode** [iperov/DeepFaceLab#729]
## Expected behavior

`python3 -m pip install -r requirements-cuda.txt`

Expect PIP to install requirements

## Actual behavior

```
Collecting pyqt5
  Using cached https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-_2yekith/pyqt5/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-_2yekith/pyqt5/
```

## Possible fixes

* One solution is to pin specific version of `pyqt5` to version `5.14`. This would be ideal, but caution is needed to ensure this does not interfere with Windows/Colab installations.

In `requirements-cuda.txt` set `pyqt5==5.14`

* Another solution is to use `sed` to modify requirements-cuda.txt to do this post-clone for Linux installation. I am happy to modify requirements file for centos linux if you deem the change too risky.

I'm not able to submit a PR due to 403 error 😞 

Your view on a way forward would be appreciated 😃

**Comment by ghost** [comment]
Does this issue still persist? If not, would you mind closing it?
