### ISSUE TITLE
Some issues with reading faces

### ISSUE THREAD

**Issue by TheKingLozo** [iperov/DeepFaceLab#731]
## Expected behavior

Reading faces from video.

## Actual behavior

Functions "Video A,B , Images A,b" works, Faces A, B didnt work so MODEL ,SWAPS and MOVIE dont work too

## Steps to reproduce

This code is showing

Traceback (most recent call last):
  File "faceswap\faceswap.py", line 8, in <module>
    from lib.cli import FullHelpArgumentParser
  File "C:\OpenFaceSwap\faceswap\lib\cli.py", line 7, in <module>
    from lib.FaceFilter import FaceFilter
  File "C:\OpenFaceSwap\faceswap\lib\FaceFilter.py", line 3, in <module>
    import face_recognition
  File "C:\OpenFaceSwap\python\python-3.6.3.amd64\lib\site-packages\face_recognition\__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "C:\OpenFaceSwap\python\python-3.6.3.amd64\lib\site-packages\face_recognition\api.py", line 4, in <module>
    import dlib
ImportError: DLL load failed:

I've tried instal "pip install nymp" , "pip install pillow" but nothing change

## Other relevant information
- Windows 10, 64x
- Python 3.8.2

**Comment by ghost** [comment]
Does this issue still persist? If not, would you mind closing it?

**Comment by ITger** [comment]
What the f* is happening? I’m receiving tens of mails per minute and cannot
unsubscribe

**Comment by ghost** [comment]
Welcome to hell, ITger.
