### ISSUE TITLE
"5.XSeg) train.bat" Crashes with a Failed To Load Tensorflow runtime

### ISSUE THREAD

**Issue by AtlasKoalas** [iperov/DeepFaceLab#735]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

I expect it to just train my masks as I've seen in a few YouTube Videos.

## Actual behavior

It gives me an error after selecting what I want to use

Model first run.

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce RTX 2080 SUPER

[0] Which GPU indexes to choose? :
0

[wf] Face type ( h/mf/f/wf/head ?:help ) :
wf
Traceback (most recent call last):
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: The paging file is too small for this operation to complete.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "Z:\DeepFaceLab\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
    from tensorflow.python.ops import init_ops
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
Traceback (most recent call last):
      File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
Traceback (most recent call last):
from tensorflow.python import pywrap_tensorflow
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>

  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()_pywrap_tensorflow_internal = swig_import_helper()

      File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
raise ImportError(msg)Traceback (most recent call last):
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>

Traceback (most recent call last):

ImportError      File "imp.py", line 243, in load_module
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "imp.py", line 243, in load_module
: from tensorflow.python.pywrap_tensorflow_internal import *  File "imp.py", line 343, in load_dynamic
      File "imp.py", line 343, in load_dynamic
from tensorflow.python.pywrap_tensorflow_internal import *Traceback (most recent call last):
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: The paging file is too small for this operation to complete.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

ImportError
: DLL load failed: The paging file is too small for this operation to complete.

During handling of the above exception, another exception occurred:

  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
ImportError  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
Traceback (most recent call last):
    : _pywrap_tensorflow_internal = swig_import_helper()DLL load failed: The paging file is too small for this operation to complete.
  File "<string>", line 1, in <module>

  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper

During handling of the above exception, another exception occurred:

  File "multiprocessing\spawn.py", line 105, in spawn_main
    _pywrap_tensorflow_internal = swig_import_helper()
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    Traceback (most recent call last):
  File "<string>", line 1, in <module>
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "multiprocessing\spawn.py", line 115, in _main
  File "imp.py", line 343, in load_dynamic
  File "multiprocessing\spawn.py", line 105, in spawn_main
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
ImportError:   File "Z:\DeepFaceLab\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
  File "imp.py", line 343, in load_dynamic
DLL load failed: The paging file is too small for this operation to complete.  File "multiprocessing\spawn.py", line 115, in _main
  File "Z:\DeepFaceLab\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>

ImportError    : from tensorflow.python.ops import init_opsDLL load failed: The paging file is too small for this operation to complete.
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
from tensorflow.python.ops import init_ops

  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>

During handling of the above exception, another exception occurred:

          File "multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-importfrom tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>

  File "multiprocessing\spawn.py", line 115, in _main
  File "<string>", line 1, in <module>
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "Z:\DeepFaceLab\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
        from tensorflow.python import pywrap_tensorflow      File "multiprocessing\spawn.py", line 115, in _main
from tensorflow.python.ops import init_ops
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>

from tensorflow.python import pywrap_tensorflow  File "Z:\DeepFaceLab\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
raise ImportError(msg)  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
ImportError:
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>

  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    from tensorflow.python.ops import init_opsfrom tensorflow.python import pywrap_tensorflow    Traceback (most recent call last):
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: The paging file is too small for this operation to complete.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: The paging file is too small for this operation to complete.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Traceback (most recent call last):
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: The paging file is too small for this operation to complete.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "Z:\DeepFaceLab\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: The paging file is too small for this operation to complete.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

## Steps to reproduce

I just ran 5.Xseg train.bat and it happened.

## Other relevant information
I'm using Windows 10, the latest build 
I'm using the prebuilt Windows 10 file.

**Comment by iperov** [comment]
DLL load failed: The paging file is too small for this operation to complete.
