### ISSUE TITLE
[WinError 1455] model train has an error

### ISSUE THREAD

**Issue by ElDova** [iperov/DeepFaceLab#737]
Initializing models: 100%|###############################################################| 5/5 [00:12<00:00,  2.58s/it]
Loading samples: 100%|##########################################################| 72787/72787 [01:24<00:00, 858.30it/s]
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\heap.py", line 55, in __setstate__
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
OSError  File "multiprocessing\heap.py", line 55, in __setstate__
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\heap.py", line 55, in __setstate__
: [WinError 1455] The paging file is too small for this operation to complete  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\heap.py", line 55, in __setstate__
OSErrorOSError
:   File "multiprocessing\heap.py", line 55, in __setstate__
OSError: : [WinError 1455] The paging file is too small for this operation to complete[WinError 1455] The paging file is too small for this operation to complete

[WinError 1455] The paging file is too small for this operation to complete
OSError: [WinError 1455] The paging file is too small for this operation to complete

same in train for mask face Loading samples: 

Running trainer.

Loading XSeg model...

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce RTX 2080

[0] Which GPU indexes to choose? :
0

Loading samples: 100%|##########################################################| 72787/72787 [01:22<00:00, 883.85it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\heap.py", line 55, in __setstate__
OSError: [WinError 1455] The paging file is too small for this operation to complete
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\heap.py", line 55, in __setstate__
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\spawn.py", line 115, in _main
OSError  File "multiprocessing\heap.py", line 55, in __setstate__
  File "multiprocessing\heap.py", line 55, in __setstate__
: OSErrorOSError: : [WinError 1455] The paging file is too small for this operation to complete[WinError 1455] The paging file is too small for this operation to complete

[WinError 1455] The paging file is too small for this operation to complete

**Comment by ghost** [comment]
Try increasing the page file in your OS. 
This is not an issue (or related to deepfacelab), please close it.
