### ISSUE TITLE
SAEHD Merge Failure

### ISSUE THREAD

**Issue by User435656743** [iperov/DeepFaceLab#745]
## System gets to a specific image and returns
Exception while process data [C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\03475.png]: Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\03475.png]: Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

Merging:  19%|#############                                                       | 3466/18108 [11:23<48:06,  5.07it/s]

no faces found for 03477.png, copying without faces
Merging:  19%|#############                                                       | 3467/18108 [11:23<48:05,  5.07it/s]

no faces found for 03478.png, copying without faces
Merging:  19%|#############                                                       | 3468/18108 [11:23<48:04,  5.08it/s]

no faces found for 03479.png, copying without faces
Merging:  19%|#############                                                       | 3469/18108 [11:23<48:03,  5.08it/s]

no faces found for 03480.png, copying without faces
Merging:  19%|#############                                                       | 3470/18108 [11:23<48:02,  5.08it/s]

no faces found for 03481.png, copying without faces
Merging:  19%|#############                                                       | 3471/18108 [11:23<48:01,  5.08it/s]

no faces found for 03482.png, copying without faces
Merging:  19%|#############                                                       | 3473/18108 [11:23<47:59,  5.08it/s]Exception while process data [C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\03475.png]: Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\03475.png]: Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

Merging:  19%|#############                                                       | 3474/18108 [11:24<48:01,  5.08it/s]Exception while process data [C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\03475.png]: Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\03475.png]: Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

Exception while process data [C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\03475.png]: Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\03475.png]: Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

Exception while process data [C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\03475.png]: Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\03475.png]: Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

Exception while process data [C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\03475.png]: Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\03475.png]: Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

Exception while process data [C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\03475.png]: Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\03475.png]: Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

Exception while process data [C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\03475.png]: Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\03475.png]: Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

Exception while process data [C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\03475.png]: Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\03475.png]: Traceback (most recent call last):
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 326, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "C:\Users\[User]\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 311, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

## I used 7)merge SAEHD

Windows 10 GTX 1070

**Comment by User435656743** [comment]
removed the frame and it worked perfectly

**Comment by ghost** [comment]
Does this issue still persist? If not, would you mind closing it?
