### ISSUE TITLE
Xseg Mask applyed dataset training, Possible Memory Leak

### ISSUE THREAD

**Issue by s1242001** [iperov/DeepFaceLab#758]
## Expected behavior
folling the Xseg Mini tutorial video
after Xseg has been applyed to dataset, the mask is checked mask some more if needed then train some more
I also train the SAEHD mode with Xesg mask applyed.
I've try this workflow (with good result) with data set size of 5,000 faces.
but when try the same thing on a larger **datset of 60,000 faces, I couldent start the trainer.**

## Actual behavior
when initializing traing for Xseg and SAEHD model with Dataset have Xseg mask Applyed
it's useing so much RAM as to filled up the Ram and Pagefiles.
this happens when I have a large datasets (on my computer it's 30K~60K of aligned frames)
not able to start training, even after I set the max pagefile size to a very large ammount (160GB) it still won't start training
I check in the task manager at the time and found that DFL was useing around 30GB~~60GB of ram & pagefile.
(lot of RAM but still hasent reach the pagefile limit)
I consider this to be Memory Leaking.

this happend on **both Xsrg and SAEHD** training, during initializing phase after loadind in the sample, the prpgram erros and stops
memory usege start climbing while loading the Xseg mask applyed facesets

##  Consol logs
**4 cases both for the SAEHD and Xseg, and with enough and not enough pagefile:**
**SAEHD with Enough Pagefile:**
```
Running trainer.
Choose one of saved models, or enter a name to create a new model.
[r] : rename
[d] : delete
[0] : 128 DF 256 64 64 16 - latest
 :
0
Loading 128 DF 256 64 64 16_SAEHD model...
Choose one or several GPU idxs (separated by comma).
[CPU] : CPU
  [0] : GeForce GTX 1650
[0] Which GPU indexes to choose? :
0
Initializing models: 100%|####################| 5/5 [00:02<00:00,  1.80it/s]
Loading samples: 100%|####################| 1794/1794 [00:05<00:00, 350.12it/s]
Loading samples: 100%|####################| 62987/62987 [02:15<00:00, 464.19it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\heap.py", line 55, in __setstate__
OSError: [WinError 1450] Insufficient system resources exist to complete the requested service
```

**SAEHD with not Enough Pagefile**
```
Initializing models: 100%|####################| 5/5 [00:02<00:00,  1.89it/s]
Loading samples: 100%|####################| 1794/1794 [00:04<00:00, 412.70it/s]
Loading samples: 100%|####################| 62987/62987 [02:15<00:00, 466.56it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\heap.py", line 55, in __setstate__
OSError: [WinError 1455] The paging file is too small for this operation to complete
```

**Xseg with Enough Pagefile**
```
Running trainer.
Loading XSeg model...
Choose one or several GPU idxs (separated by comma).
[CPU] : CPU
  [0] : GeForce GTX 1650
[0] Which GPU indexes to choose? :
0
Loading samples: 100%|####################| 1794/1794 [00:03<00:00, 450.25it/s]
Loading samples: 100%|####################| 62987/62987 [02:12<00:00, 475.27it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\heap.py", line 55, in __setstate__
OSError: [WinError 1450] Insufficient system resources exist to complete the requested service
```

**Xseg with not Enough Pagefile**
```
Loading samples: 100%|####################| 1794/1794 [00:03<00:00, 490.42it/s]
Loading samples: 100%|####################| 62987/62987 [02:11<00:00, 478.69it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\heap.py", line 55, in __setstate__
OSError: [WinError 1455] The paging file is too small for this operation to complete
```

**note: the error log are cleaned, some time it randomly prints out the same thing multiple times**

## Steps to reproduce
train a large data set's Xseg mode, (for system of 16GB ram, try using 30k~60k faces)
apply the Xseg Mask on to the data set,
train the dataset either Xseg or SAEHD
monitor RAM usage with Task Manager
memory usage shoud clim, Error should occur after Sample are loaded in.

## Other relevant information
DFL Windows build: DeepFaceLab_NVIDIA_build_05_06_2020
OS: Win10 64bit
CPU: i5-9300H (yes I am useing a laptop)
RAM: 16G
GPU: GTX1650 VRAM 4G
Storage: 2 500GB SSD
dst faceset size of 60,000

**Comment by iperov** [comment]
RAM: 16G is very small for 60k samples.

You need more size of pagefile and/or ram.

Also try to pack the faceset before use.

**Comment by s1242001** [comment]
as I mentioned, I set the pagefile limit to **160G (not a typo)**, but its only useing about 30~60 GB.
at the peak befor the error message.
different Behavior with the different pagefile size limit
low pagefile limit (defult~I forgot)
[WinError 1455] The paging file is too small for this operation to complete
high pagefile limit (I forgot~160GB)
[WinError 1450] Insufficient system resources exist to complete the requested service

ps: not sure, but it seams to me that the ram/pagefile use and the faceset size does not scale linearly.

**Comment by s1242001** [comment]
only when thrining with Xseg mask apply to the faceset has issue,
without apply 60k faceset traing use about 2 to 4 GB of ram
but when with Xseg, it suddenly uses 60+GB

correct me if I'm wrong
as I understand, the process of training with Xseg mask apply is no different, except, it using the apply Xseg mask instead of the detected mask from face extraction, and because the Xseg mask is applyed prior to training, so there should be little to no resource / performance difference,

**Comment by s1242001** [comment]
Just tested packing the faceset before training
it make no difference,
sitll the same error [WinError 1450] for both Xseg and SAEHD Training (large pagefiles limit)

**Comment by s1242001** [comment]
Just noticed something. don't know if you are aware of.
then the faceset is packed
the package file size of the faceset with Xseg mask applyed is significantly larger the then without.

for the 60k dst set I am useing
the original extracted faceset size is 1.77GB,
when packaged original extracted faceset becomes 1.86GB,
after the trained Xseg mask applyed faceset size in **1.84GB**,
when the dataset is package with Xsag applyed mask applyed, the package size is **17.3GB**.
I don't think this is normal.

**Comment by ghost** [comment]
This is not an issue (or related to deepfacelab), please close it.

**Comment by w-e-w** [comment]
can't remeber what this is after 3 years
