### ISSUE TITLE
Face extraction error, this is CUDA problem?

### ISSUE THREAD

**Issue by forkSkill** [iperov/DeepFaceLab#766]
Extracting faces...
Traceback (most recent call last):
  File "F:\AiFace\2_soft\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 302, in <module>
    arguments.func(arguments)
  File "F:\AiFace\2_soft\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 40, in process_extract
    force_gpu_idxs          = [ int(x) for x in arguments.force_gpu_idxs.split(',') ] if arguments.force_gpu_idxs is not None else None,
  File "F:\AiFace\2_soft\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Extractor.py", line 762, in main
    device_config=device_config).run()
  File "F:\AiFace\2_soft\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 219, in run
    raise Exception ( "Unable to start subprocesses." )
Exception: Unable to start subprocesses.

**Comment by ghost** [comment]
Does this issue still persist? If not, would you mind closing it?
