### ISSUE TITLE
[WinError 32] when trying to run Xseg trainer-edit

### ISSUE THREAD

**Issue by KL1969** [iperov/DeepFaceLab#770]
My system: Intel Core i7-9750H cpu 2.6 GHz, Ram 24 GB, Graphic Card Nvidia RTX2060

Trying to run src/dst mask for Xseg trainer-edit on Window10 ver.1909 and it ran for a while and I get WinError32 as shown below:

```
Starting. Press "Enter" to stop training and save model.
Error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ASUS\\Documents\\DeepFaceLab_NVIDIA\\workspace\\model\\XSeg_data.dat.tmp' -> 'C:\\Users\\ASUS\\Documents\\DeepFaceLab_NVIDIA\\workspace\\model\\XSeg_data.dat'
Traceback (most recent call last):
  File "C:\Users\ASUS\Documents\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Trainer.py", line 163, in trainerThread
    model_save()
  File "C:\Users\ASUS\Documents\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Trainer.py", line 68, in model_save
    model.save()
  File "C:\Users\ASUS\Documents\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\ModelBase.py", line 372, in save
    pathex.write_bytes_safe (self.model_data_path, pickle.dumps(model_data) )
  File "C:\Users\ASUS\Documents\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\pathex.py", line 14, in write_bytes_safe
    p_tmp.rename (p)
  File "pathlib.py", line 1309, in rename
  File "pathlib.py", line 393, in wrapped
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ASUS\\Documents\\DeepFaceLab_NVIDIA\\workspace\\model\\XSeg_data.dat.tmp' -> 'C:\\Users\\ASUS\\Documents\\DeepFaceLab_NVIDIA\\workspace\\model\\XSeg_data.dat'
Done.
Press any key to continue . . .
```

how can I get rid of this error?

**Comment by ghost** [comment]
Does this issue still persist? If not, would you mind closing it?
