### ISSUE TITLE
Option to use CPU only for compatibility with non CUDA systems

### ISSUE THREAD

**Issue by tommaier123** [iperov/DeepFaceLab#772]
I can understand that you dont want to support both CUDA and OpenCl at the same time. but it would be really useful to do at least support merging with CPU only for systems that dont support CUDA.
I am using the google colab version to train my model and it would be nice to have the GUI for merging.

**Comment by iperov** [comment]
use 10.misc) make CPU only.bat

**Comment by pohar** [comment]
using 10.misc) make CPU only.bat give me the following error:
`[wf] Face type ( f/wf/head ?:help ) :
wf
[0] Max number of faces from image ( ?:help ) :
0
[512] Image size ( 256-2048 ?:help ) :
512
[90] Jpeg quality ( 1-100 ?:help ) :
90
[n] Write debug images to aligned_debug? ( y/n ) :
n
Extracting faces...
Error while subprocess initialization: Traceback (most recent call last):
  File "c:\DFL\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\DFL\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\DFL\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\DFL\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 62, in _subprocess_run
    self.on_initialize(client_dict)
  File "c:\DFL\_internal\DeepFaceLab\mainscripts\Extractor.py", line 68, in on_initialize
    nn.initialize (device_config)
  File "c:\DFL\_internal\DeepFaceLab\core\leras\nn.py", line 80, in initialize
    import tensorflow as tf
  File "c:\DFL\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "c:\DFL\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\DFL\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\DFL\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\DFL\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\DFL\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Error while subprocess initialization: Traceback (most recent call last):
  File "c:\DFL\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\DFL\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\DFL\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\DFL\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 62, in _subprocess_run
    self.on_initialize(client_dict)
  File "c:\DFL\_internal\DeepFaceLab\mainscripts\Extractor.py", line 68, in on_initialize
    nn.initialize (device_config)
  File "c:\DFL\_internal\DeepFaceLab\core\leras\nn.py", line 80, in initialize
    import tensorflow as tf
  File "c:\DFL\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "c:\DFL\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\DFL\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\DFL\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\DFL\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\DFL\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Traceback (most recent call last):
  File "c:\DFL\_internal\DeepFaceLab\main.py", line 324, in <module>
    arguments.func(arguments)
  File "c:\DFL\_internal\DeepFaceLab\main.py", line 45, in process_extract
    force_gpu_idxs          = [ int(x) for x in arguments.force_gpu_idxs.split(',') ] if arguments.force_gpu_idxs is not None else None,
  File "c:\DFL\_internal\DeepFaceLab\mainscripts\Extractor.py", line 840, in main
    device_config=device_config).run()
  File "c:\DFL\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 210, in run
    raise Exception ( "Unable to start subprocesses." )
Exception: Unable to start subprocesses.
Press any key to continue . . .`
