### ISSUE TITLE
Windows Error 1450 with Xseg and train SAE 

### ISSUE THREAD

**Issue by wasyleque** [iperov/DeepFaceLab#778]
Made everything step by step from the tutorial from YT, and with the last step (train SAE), I`ve got an error.

`Running trainer.

[new] No saved models found. Enter a name of a new model : hindu_SAE
hindu_SAE

Model first run.

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce GTX 1080 Ti

[0] Which GPU indexes to choose? :
0

[0] Autobackup every N hour ( 0..24 ?:help ) : 0
0
[n] Write preview history ( y/n ?:help ) :
n
[0] Target iteration :
0
[y] Flip faces randomly ( y/n ?:help ) :
y
[8] Batch_size ( ?:help ) :
8
[128] Resolution ( 64-512 ?:help ) :
128
[wf] Face type ( h/mf/f/wf/head ?:help ) : wf
wf
[dfuhd] AE architecture ( df/liae/dfhd/liaehd/dfuhd/liaeuhd ?:help ) : df
df
[688] AutoEncoder dimensions ( 32-1024 ?:help ) :
688
[64] Encoder dimensions ( 16-256 ?:help ) :
64
[64] Decoder dimensions ( 16-256 ?:help ) :
64
[22] Decoder mask dimensions ( 16-256 ?:help ) :
22
[y] Masked training ( y/n ?:help ) :
y
[n] Eyes priority ( y/n ?:help ) :
n
[y] Place models and optimizer on GPU ( y/n ?:help ) :
y
[n] Use learning rate dropout ( n/y/cpu ?:help ) : ?
When the face is trained enough, you can enable this option to get extra sharpness and reduce subpixel shake for less amount of iterations.
n - disabled.
y - enabled
cpu - enabled on CPU. This allows not to use extra VRAM, sacrificing 20% time of iteration.
[n] Use learning rate dropout ( n/y/cpu ?:help ) :
n
[y] Enable random warp of samples ( y/n ?:help ) :
y
[0.0] GAN power ( 0.0 .. 10.0 ?:help ) :
0.0
[0.0] 'True face' power. ( 0.0000 .. 1.0 ?:help ) :
0.0
[0.0] Face style power ( 0.0..100.0 ?:help ) :
0.0
[0.0] Background style power ( 0.0..100.0 ?:help ) :
0.0
[none] Color transfer for src faceset ( none/rct/lct/mkl/idt/sot ?:help ) :
none
[n] Enable gradient clipping ( y/n ?:help ) :
n
[n] Enable pretraining mode ( y/n ?:help ) :
n
Initializing models: 100%|############################| 5/5 [00:34<00:00,  6.98s/it]
Loading samples: 100%|#######################| 48929/48929 [02:29<00:00, 328.19it/s]
Loading samples: 100%|#######################| 38226/38226 [02:14<00:00, 284.53it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "multiprocessing\heap.py", line 55, in __setstate__
OSError: [WinError 1450] Zasoby systemowe nie wystarczają do ukończenia żądanej usługi
`
OSError: [WinError 1450] **System resources are not sufficient to complete the requested service**
My configuration:
Ryzen 5 1600X, 32GB DDR4, 11GB GTX 1080Ti, 64GB Virtual Memory on Win 10 x64BIT
The DF Master i current from today.
Please help

**Comment by ghost** [comment]
Does this issue still persist? If not, would you mind closing it?
