### ISSUE TITLE
error face extraccion

### ISSUE THREAD

**Issue by molo32** [iperov/DeepFaceLab#782]
```
[wf] Face type ( f/wf/head ?:help ) :
wf
[n] Write debug images to aligned_debug? ( y/n ) :
n
Performing manual extract...
Traceback (most recent call last):
  File "C:\deep\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 318, in
<module>
    arguments.func(arguments)
  File "C:\deep\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 42, in p
rocess_extract
    force_gpu_idxs          = [ int(x) for x in arguments.force_gpu_idxs.split('
,') ] if arguments.force_gpu_idxs is not None else None,
  File "C:\deep\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Extractor.p
y", line 805, in main
    data = ExtractSubprocessor ([ ExtractSubprocessor.Data(Path(filename)) for f
ilename in input_path_image_paths ], 'landmarks-manual', image_size, face_type,
output_debug_path if output_debug else None, manual_window_size=manual_window_si
ze, device_config=device_config).run()
  File "C:\deep\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\Subprocesso
rBase.py", line 219, in run
    raise Exception ( "Unable to start subprocesses." )
Exception: Unable to start subprocesses.
Presione una tecla para continuar . . .
```

**Comment by ghost** [comment]
Does this issue still persist? If not, would you mind closing it?
