### ISSUE TITLE
Error while XSeg) Train

### ISSUE THREAD

**Issue by Ananth-Eswar** [iperov/DeepFaceLab#785]
**System config: (Just reinstalled OS, but again same errors)
Windows 10 2004 Pro
RTX 2070 Super
Ryzen 9 3900x
X570 Aorus master
32GB RAM
128 GB SSD (1 TB failed, so replaced)

Drivers installed: All motherboard drivers and Nvidia Game ready driver.

Frames and face extractions of source and destination files are done well but the problem comes when I train XSeg (Xseg edit is no prob). And while on Merge Quick96 also errors.
The errors are,**

Traceback (most recent call last):
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
Traceback (most recent call last):
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
        Traceback (most recent call last):
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
from tensorflow.python.pywrap_tensorflow_internal import *_pywrap_tensorflow_internal = swig_import_helper()Traceback (most recent call last):

  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>

  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
      File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)    from tensorflow.python.pywrap_tensorflow_internal import *_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)from tensorflow.python.pywrap_tensorflow_internal import *

  File "imp.py", line 243, in load_module
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "imp.py", line 243, in load_module
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "imp.py", line 343, in load_dynamic
      File "imp.py", line 343, in load_dynamic
    ImportError: DLL load failed: The paging file is too small for this operation to complete.
_pywrap_tensorflow_internal = swig_import_helper()ImportError_pywrap_tensorflow_internal = swig_import_helper()
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
:

  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
      File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)    DLL load failed: The paging file is too small for this operation to complete.

  File "imp.py", line 243, in load_module
  File "multiprocessing\spawn.py", line 115, in _main

During handling of the above exception, another exception occurred:

_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)  File "imp.py", line 343, in load_dynamic
  File "D:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: DLL load failed: The paging file is too small for this operation to complete.  File "multiprocessing\spawn.py", line 105, in spawn_main
    from tensorflow.python.ops import init_ops
  File "multiprocessing\spawn.py", line 115, in _main
  File "D:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>

  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>

During handling of the above exception, another exception occurred:

  File "imp.py", line 243, in load_module
from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-importTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "imp.py", line 343, in load_dynamic

      File "multiprocessing\spawn.py", line 105, in spawn_main
ImportError  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
from tensorflow.python.ops import init_ops  File "multiprocessing\spawn.py", line 115, in _main
:
from tensorflow.python import pywrap_tensorflowDLL load failed: The paging file is too small for this operation to complete.  File "D:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>

        from tensorflow.python.ops import init_ops
During handling of the above exception, another exception occurred:

  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>

Traceback (most recent call last):
    raise ImportError(msg)  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-importfrom tensorflow.python import pywrap_tensorflow  File "<string>", line 1, in <module>

ImportError  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
:   File "multiprocessing\spawn.py", line 115, in _main
        Traceback (most recent call last):
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: The paging file is too small for this operation to complete.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.  File "D:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
from tensorflow.python import pywrap_tensorflowraise ImportError(msg)

from tensorflow.python.ops import init_ops
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
ImportError:     Traceback (most recent call last):
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: The paging file is too small for this operation to complete.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
raise ImportError(msg)    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
ImportError:
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
Traceback (most recent call last):
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: The paging file is too small for this operation to complete.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
    from tensorflow.python import pywrap_tensorflow
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: The paging file is too small for this operation to complete.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by iperov** [comment]
> ImportError: DLL load failed: The paging file is too small for this operation to complete.

try set more pagefile
