### ISSUE TITLE
Unable to start subprocesses

### ISSUE THREAD

**Issue by Wotty** [iperov/DeepFaceLab#791]
## Expected behavior

Successfully run 4) data_src faceset extract.bat

## Actual behavior

[wf] Face type ( f/wf/head ?:help ) : wf
wf
Choose one or several GPU idxs (separated by comma).
[CPU] : CPU
  [0] : GeForce GTX 980 Ti
[0] Which GPU indexes to choose? : CPU
CPU
[n] Write debug images to aligned_debug? ( y/n ) : y
Extracting faces...
Traceback (most recent call last):
  File "...\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 318, in <module>
    arguments.func(arguments)
  File "...\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 42, in process_extract
    force_gpu_idxs          = [ int(x) for x in arguments.force_gpu_idxs.split(',') ] if arguments.force_gpu_idxs is not None else None,
  File "...\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Extractor.py", line 819, in main
    device_config=device_config).run()
  File "...\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 219, in run
    raise Exception ( "Unable to start subprocesses." )
Exception: Unable to start subprocesses.
Press any key to continue . . .

## Steps to reproduce

My specs are: Intel 10th Gen i5 (laptop) and a GTX 980Ti eGPU. Using both CPU or 980Ti, I am unable to run. Could the issue be due to environment variables?

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 3.5, 3.6.4, ... (if you are not using prebuilt windows binary)

**Comment by iperov** [comment]
try set page file 16gb

**Comment by reinhardrobin** [comment]
> 
> 
> try set page file 16gb


If you wish, can you explain it in more detail? I also get the same problem. thank you

**Comment by Bogdan4305** [comment]
If you managed to solve the problem, write how you solved it

> > try set page file 16gb
> 
> If you wish, can you explain it in more detail? I also get the same problem. thank you

If you managed to solve the problem, write how you solved it

**Comment by ghost** [comment]
Click the Start Button
    Right-click Computer
    Select Properties
    Click Advanced System Settings
    Select the Advanced tab
    Under Performance, click Settings
    Select the Advanced tab
    Under Virtual Memory, click Change...

**Comment by ghost** [comment]
Does this issue still persist? If not, would you mind closing it?
