### ISSUE TITLE
Step 4: take the picture out of the picture and make a mistake

### ISSUE THREAD

**Issue by shiranII** [iperov/DeepFaceLab#803]
[wf] Face type ( f/wf/head ?:help ) :
wf
[0] Max number of faces from image ( ?:help ) :
0
[512] Image size ( 256-2048 ?:help ) :
512
[90] Jpeg quality ( 1-100 ?:help ) :
90
[n] Write debug images to aligned_debug? ( y/n ) : n
Extracting faces...
Traceback (most recent call last):
  File "C:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 324, in <module>
    arguments.func(arguments)
  File "C:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 45, in process_extract
    force_gpu_idxs          = [ int(x) for x in arguments.force_gpu_idxs.split(',') ] if arguments.force_gpu_idxs is not None else None,
  File "C:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Extractor.py", line 840, in main
    device_config=device_config).run()
  File "C:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 199, in run
    raise Exception ("Unable to start Subprocessor '%s' " % (self.name))
Exception: Unable to start Subprocessor 'Extractor'
![image](https://user-images.githubusercontent.com/67699534/86258718-b665f580-bbed-11ea-83f0-97749ca3db73.png)

**Comment by developefake** [comment]
[0] Max number of faces from image ( ?:help ) :
0 

this value must be 1, right?
but It can happen cause of codes, ı think you should try

**Comment by shiranII** [comment]
[wf] Face type ( f/wf/head ?:help ) :
wf
[0] Max number of faces from image ( ?:help ) : 1
1
[512] Image size ( 256-2048 ?:help ) :
512
[90] Jpeg quality ( 1-100 ?:help ) :
90
[n] Write debug images to aligned_debug? ( y/n ) :
n
Extracting faces...
Traceback (most recent call last):
  File "C:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 324, in <module>
    arguments.func(arguments)
  File "C:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 45, in process_extract
    force_gpu_idxs          = [ int(x) for x in arguments.force_gpu_idxs.split(',') ] if arguments.force_gpu_idxs is not None else None,
  File "C:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Extractor.py", line 840, in main
    device_config=device_config).run()
  File "C:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 199, in run
    raise Exception ("Unable to start Subprocessor '%s' " % (self.name))
Exception: Unable to start Subprocessor 'Extractor'


----------------------------

[0] Max number of faces from image ( ?:help ) : 1
1
Or is it wrong!!!

**Comment by developefake** [comment]
First download DFL1. Second extract faces from DFL1 files. Copy extracted photos and paste to your own
DFL file. I think it will be successful.

**Comment by developefake** [comment]
I also ask you to indicate if it is successful

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?
