### ISSUE TITLE
ValueError: cannot reshape array of size 4800 into shape (5,5,3,32)

### ISSUE THREAD

**Issue by Rocky-17** [iperov/DeepFaceLab#805]
I trained a Quick96 model on Google Colab. When I downloaded the trained model to the local, the following error occurred when used the model on my PC:

```
Traceback (most recent call last):
  File "C:\DEEP\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 50, in main
    cpu_only=cpu_only)
  File "C:\DEEP\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\ModelBase.py", line 188, in __init__
    self.on_initialize()
  File "C:\DEEP\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_Quick96\Model.py", line 213, in on_initialize
    do_init = not model.load_weights( self.get_strpath_storage_for_file(filename) )
  File "C:\DEEP\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\layers\Saveable.py", line 93, in load_weights
    w_val = np.reshape( w_val, w.shape.as_list() )
  File "<__array_function__ internals>", line 6, in reshape
  File "C:\DEEP\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\numpy\core\fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "C:\DEEP\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\numpy\core\fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 4800 into shape (5,5,3,32)
```

What is the cause of the problem?
And how what can I do to fix it?

=========================================================
And then,I uploaded the model trained on my PC to Google Colab and run it, as shown below:

```
Initializing models:   0% 0/5 [00:00<?, ?it/s]Error: cannot reshape array of size 2400 into shape (5,5,3,64)
Traceback (most recent call last):
  File "/content/drive/My Drive/DeepFaceLab/DeepFaceLab/mainscripts/Trainer.py", line 57, in trainerThread
    debug=debug,
  File "/content/drive/My Drive/DeepFaceLab/DeepFaceLab/models/ModelBase.py", line 188, in __init__
    self.on_initialize()
  File "/content/drive/My Drive/DeepFaceLab/DeepFaceLab/models/Model_Quick96/Model.py", line 214, in on_initialize
    do_init = not model.load_weights( self.get_strpath_storage_for_file(filename) )
  File "/content/drive/My Drive/DeepFaceLab/DeepFaceLab/core/leras/layers/Saveable.py", line 93, in load_weights
    w_val = np.reshape( w_val, w.shape.as_list() )
  File "<__array_function__ internals>", line 6, in reshape
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 2400 into shape (5,5,3,64)
```

**Comment by Rocky-17** [comment]
OK,everything is work well now.
It looks like a version conflict.

**Comment by avfmsk** [comment]
I have the same problem. 
> ValueError: cannot reshape array of size 2400 into shape (5,5,3,64)
How did you solve it?

**Comment by Rocky-17** [comment]
> I have the same problem. How did you solve it?
> 
> > ValueError: cannot reshape array of size 2400 into shape (5,5,3,64)

maybe Maybe you try to update the DFL to the latest version? I have this problem because the DFL versions I used on Google colab and the local  are inconsistent.
