### ISSUE TITLE
Exception: Unable to start subprocesses.

### ISSUE THREAD

**Issue by TheAwesomeYT** [iperov/DeepFaceLab#812]
## Expected behavior

I'm trying to extract the faces from data_src.

## Actual behavior

After I enter all the preferences, this happens:
```
Error while subprocess initialization: Traceback (most recent call last):
  File "C:\Users\HP Pavilion\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\HP Pavilion\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\HP Pavilion\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: %1 is not a valid Win32 application.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP Pavilion\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 62, in _subprocess_run
    self.on_initialize(client_dict)
  File "C:\Users\HP Pavilion\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Extractor.py", line 68, in on_initialize
    nn.initialize (device_config)
  File "C:\Users\HP Pavilion\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\nn.py", line 80, in initialize
    import tensorflow as tf
  File "C:\Users\HP Pavilion\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\HP Pavilion\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\HP Pavilion\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\HP Pavilion\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\HP Pavilion\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\HP Pavilion\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: %1 is not a valid Win32 application.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Traceback (most recent call last):
  File "C:\Users\HP Pavilion\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 324, in <module>
    arguments.func(arguments)
  File "C:\Users\HP Pavilion\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 45, in process_extract
    force_gpu_idxs          = [ int(x) for x in arguments.force_gpu_idxs.split(',') ] if arguments.force_gpu_idxs is not None else None,
  File "C:\Users\HP Pavilion\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Extractor.py", line 840, in main
    device_config=device_config).run()
  File "C:\Users\HP Pavilion\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 210, in run
    raise Exception ( "Unable to start subprocesses." )
Exception: Unable to start subprocesses.
```

## Steps to reproduce

Face type: wf, Max number of faces from image: 3, Image size: 512, Jpeg quality: 95, Write debug images to aligned_debug?: n
My specs are AMD Radeon R3 for GPU, and AMD A4-9120 RADEON R3, 4 COMPUTE CORES 2C+2G for CPU.

## Other relevant information
- Windows
- Python version 2.7

**Comment by iperov** [comment]
AMD gpu is not supported

**Comment by optimus27** [comment]
Hey guys I also have the same problem im using nvidia gpu only
Can anyone help me

**Comment by KolasikOmetov** [comment]
the same problem nvidia GeForce GTX 1050

`Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce GTX 1050

[0] Which GPU indexes to choose? : 0
0

[wf] Face type ( f/wf/head ?:help ) :
wf
[0] Max number of faces from image ( ?:help ) : 1
1
[512] Image size ( 256-2048 ?:help ) : 1280
1280
[90] Jpeg quality ( 1-100 ?:help ) : 90
90
[n] Write debug images to aligned_debug? ( y/n ) :
n
Extracting faces...
Caching GPU kernels...
Error while subprocess initialization: Traceback (most recent call last):
  File "D:\для работы\DeepFaceLab\DeepFaceLab_NVIDIA_build_01_04_2021\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 62, in _subprocess_run
    self.on_initialize(client_dict)
  File "D:\для работы\DeepFaceLab\DeepFaceLab_NVIDIA_build_01_04_2021\_internal\DeepFaceLab\mainscripts\Extractor.py", line 68, in on_initialize
    nn.initialize (device_config)
  File "D:\для работы\DeepFaceLab\DeepFaceLab_NVIDIA_build_01_04_2021\_internal\DeepFaceLab\core\leras\nn.py", line 123, in initialize
    nn.tf_sess = tf.Session(config=nn.tf_sess_config)
  File "D:\для работы\DeepFaceLab\DeepFaceLab_NVIDIA_build_01_04_2021\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1596, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "D:\для работы\DeepFaceLab\DeepFaceLab_NVIDIA_build_01_04_2021\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 711, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: initialization error

Traceback (most recent call last):
  File "D:\для работы\DeepFaceLab\DeepFaceLab_NVIDIA_build_01_04_2021\_internal\DeepFaceLab\main.py", line 324, in <module>
    arguments.func(arguments)
  File "D:\для работы\DeepFaceLab\DeepFaceLab_NVIDIA_build_01_04_2021\_internal\DeepFaceLab\main.py", line 45, in process_extract
    force_gpu_idxs          = [ int(x) for x in arguments.force_gpu_idxs.split(',') ] if arguments.force_gpu_idxs is not None else None,
  File "D:\для работы\DeepFaceLab\DeepFaceLab_NVIDIA_build_01_04_2021\_internal\DeepFaceLab\mainscripts\Extractor.py", line 853, in main
    device_config=device_config).run()
  File "D:\для работы\DeepFaceLab\DeepFaceLab_NVIDIA_build_01_04_2021\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 210, in run
    raise Exception ( "Unable to start subprocesses." )
Exception: Unable to start subprocesses.`
