### ISSUE TITLE
Broken model, new update.

### ISSUE THREAD

**Issue by GamingLucas** [iperov/DeepFaceLab#814]
## Behavior

Error: cannot reshape array of size 2400 into shape (5,5,3,64)
Traceback (most recent call last):
  File "E:\DeepFaking\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Trainer.py", line 57, in trainerThread
    debug=debug,
  File "E:\DeepFaking\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\ModelBase.py", line 188, in __init__
    self.on_initialize()
  File "E:\DeepFaking\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_Quick96\Model.py", line 214, in on_initialize
    do_init = not model.load_weights( self.get_strpath_storage_for_file(filename) )
  File "E:\DeepFaking\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\layers\Saveable.py", line 93, in load_weights
    w_val = np.reshape( w_val, w.shape.as_list() )
  File "<__array_function__ internals>", line 6, in reshape
  File "E:\DeepFaking\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\numpy\core\fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "E:\DeepFaking\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\numpy\core\fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 2400 into shape (5,5,3,64)

## Other relevant information
Creating a new model, works completly fine...

**Comment by avfmsk** [comment]
I have the same problem. Write if there is a solution.

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?
