### ISSUE TITLE
Can't solve this XSeg train error

### ISSUE THREAD

**Issue by mynameis2cool4u** [iperov/DeepFaceLab#816]
![Deepfacelab](https://user-images.githubusercontent.com/49737689/86893329-7318f480-c0cf-11ea-9b95-572c84f15ec2.png)

Ryzen 5 2600
16GB ram 2400mhz
1070 8GB
using on a 4TB hardrive with a 200GB paging file
Python 3.8.1

I tried moving DFL to the OS folder, putting it in the shortest relative path for both my hardrive and OS drive, downgraded to an April build (same issue), tried a batch size of 2, and switched users.

**Comment by mynameis2cool4u** [comment]
I went and repeated the error so I could paste a text log for convenience

`Running trainer.


Model first run.

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce GTX 1070

[0] Which GPU indexes to choose? : 0
0

[wf] Face type ( h/mf/f/wf/head ?:help ) : wf
wf
[2] Batch_size ( 2-16 ?:help ) :
2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 115, in _main
  File "E:\DeepFaceLab_NVIDIA_build_07_04_2020\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\initializers\__init__.py", line 2, in <module>
    from tensorflow.python.ops import init_ops
  File "E:\DeepFaceLab_NVIDIA_build_07_04_2020\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "E:\DeepFaceLab_NVIDIA_build_07_04_2020\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 103, in <module>
    from tensorflow.python.ops import gen_boosted_trees_ops as _gen_boosted_trees_ops
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 771, in get_code
  File "<frozen importlib._bootstrap_external>", line 482, in _validate_bytecode_header
`MemoryError``

**Comment by mynameis2cool4u** [comment]
I managed to fix it by using an entirely different drive and giving that 62GB of paging file space. Not sure why it didn't work on my OS drive since the paging space was fine.
