### ISSUE TITLE
Error when attempting to merge SAEHD.

### ISSUE THREAD

**Issue by DarkAlchy** [iperov/DeepFaceLab#817]
Expected behavior
Not to error to the point it crashes.
*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*
Run the Merge SAEHD.bat interactively or manually results in the same errors.

Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.

```
MergerConfig 00871.png:
Mode: overlay
mask_mode: learned-dst
erode_mask_modifier: 20
blur_mask_modifier: 48
motion_blur_power: 0
output_face_scale: 0
color_transfer_mode: mkl-m
sharpen_mode : gaussian
blursharpen_amount : 8
super_resolution_power: 1
image_denoise_power: 0
bicubic_degrade_power: 0
color_degrade_power: 0
================
Merging:  31%|#####################5                                               | 1014/3250 [05:25<11:58,  3.11it/s]

no faces found for 01025.png, copying without faces
Merging:  31%|#####################5                                               | 1015/3250 [05:25<11:57,  3.12it/s]

no faces found for 01026.png, copying without faces
Merging:  35%|########################1                                            | 1139/3250 [05:36<10:23,  3.38it/s]

no faces found for 01150.png, copying without faces
Merging:  35%|########################2                                            | 1144/3250 [05:37<10:20,  3.39it/s]

no faces found for 01155.png, copying without faces
Merging:  35%|########################3                                            | 1145/3250 [05:37<10:19,  3.40it/s]

no faces found for 01156.png, copying without faces
Merging:  38%|##########################1                                          | 1233/3250 [05:44<09:23,  3.58it/s]

no faces found for 01244.png, copying without faces
Merging:  39%|##########################9                                          | 1270/3250 [05:47<09:02,  3.65it/s]

no faces found for 01281.png, copying without faces
Merging:  57%|#######################################1                             | 1843/3250 [06:40<05:05,  4.61it/s]

no faces found for 01854.png, copying without faces
Merging:  57%|#######################################1                             | 1844/3250 [06:40<05:05,  4.61it/s]

no faces found for 01855.png, copying without faces
Merging:  57%|#######################################1                             | 1845/3250 [06:40<05:04,  4.61it/s]

no faces found for 01856.png, copying without faces
Merging:  57%|#######################################3                             | 1852/3250 [06:40<05:02,  4.62it/s]

Error while processing data: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [E:\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\01861.png]: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment




Error while processing data: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [E:\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\01860.png]: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment


Merging:  57%|#######################################3                             | 1853/3250 [06:41<05:02,  4.62it/s]

Error while processing data: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [E:\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\01862.png]: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment


Merging:  57%|#######################################3                             | 1855/3250 [06:41<05:01,  4.62it/s]

Error while processing data: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [E:\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\01861.png]: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment


Merging:  57%|#######################################4                             | 1856/3250 [06:41<05:01,  4.62it/s]

Error while processing data: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [E:\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\01860.png]: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment


Merging:  57%|#######################################4                             | 1858/3250 [06:41<05:00,  4.63it/s]

Error while processing data: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [E:\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\01862.png]: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment


Merging:  57%|#######################################4                             | 1859/3250 [06:41<05:00,  4.63it/s]

Error while processing data: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [E:\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\01861.png]: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment




Error while processing data: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [E:\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\01860.png]: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment




Error while processing data: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [E:\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\01862.png]: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment




Error while processing data: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [E:\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\01861.png]: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment




Error while processing data: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [E:\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\01860.png]: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment




Error while processing data: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 118, in process_data
    raise Exception( f'Error while merging file [{filepath}]: {e_str}' )
Exception: Error while merging file [E:\Downloads\DeepFaceLab_NVIDIA\workspace\data_dst\01861.png]: Traceback (most recent call last):
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 112, in process_data
    frame_info=frame_info)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 330, in MergeMasked
    out_img, out_img_merging_mask = MergeMaskedFace (predictor_func, predictor_input_shape, face_enhancer_func, xseg_256_extract_func, cfg, frame_info, img_bgr_uint8, img_bgr, img_landmarks)
  File "E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergeMasked.py", line 315, in MergeMaskedFace
    return out_img, out_merging_mask_a
UnboundLocalError: local variable 'out_img' referenced before assignment
```

The first warning I run into is this: `Merging:  25%|#################5                                                   | 825/3250 [00:04<00:14, 171.24it/s]E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\imagelib\color_transfer.py:89: ComplexWarning: Casting complex values to real discards the imaginary part
  return np.clip ( result.reshape ( (h,w,c) ).astype(x0.dtype), 0, 1)`
## Steps to reproduce
Run the Merge SAEHD.bat with my src and dst (training and XSeg masking works without issues)

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
I only use the batch files.
- **Operating system and version:** Windows, macOS, Linux 
Windows 10 1909
- **Python version:** 3.5, 3.6.4, ... (if you are not using prebuilt windows binary)
3.7

**Comment by iperov** [comment]
fixed in last commit

**Comment by DarkAlchy** [comment]
My version is 7/4 and I looked and did not see a newer version.

**Comment by DarkAlchy** [comment]
Just to let you know it still does have this warning that pops up on a lot of frames - "Merging:  26%|#################8                                                    | 830/3250 [00:36<01:47, 22.56it/s]E:\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\imagelib\color_transfer.py:89: ComplexWarning: Casting complex values to real discards the imaginary part
  return np.clip ( result.reshape ( (h,w,c) ).astype(x0.dtype), 0, 1)"

**Comment by iperov** [comment]
I dont have such warnings last 2 years

**Comment by DarkAlchy** [comment]
As you see I am getting them and I mean I am getting them a lot too.
