### ISSUE TITLE
Train SAEHD error

### ISSUE THREAD

**Issue by tureentle** [iperov/DeepFaceLab#821]
I got an error when I try to run train SAEHD. What did I do wrong? How do I fix it? Thank you

Running trainer.

Choose one of saved models, or enter a name to create a new model.
[r] : rename
[d] : delete

[0] : new - latest
 :
0
Loading new_SAEHD model...

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce GTX 1070

[0] Which GPU indexes to choose? :
0

Initializing models:   0%|                                                                       | 0/5 [00:00<?, ?it/s]
Error: invalid load key, '\x00'.
Traceback (most recent call last):
  File "E:\Users\Luan Nguyen\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Trainer.py", line 57, in trainerThread
    debug=debug,
  File "E:\Users\Luan Nguyen\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\ModelBase.py", line 188, in __init__
    self.on_initialize()
  File "E:\Users\Luan Nguyen\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 553, in on_initialize
    do_init = not model.load_weights( self.get_strpath_storage_for_file(filename) )
  File "E:\Users\Luan Nguyen\Downloads\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\layers\Saveable.py", line 70, in load_weights
    d = pickle.loads(d_dumped)
_pickle.UnpicklingError: invalid load key, '\x00'.

**Comment by JaredTurck** [comment]
I have had the exact same issue, i think it happens if you shut the trainer down without saving the model properly, you should press enter twice to stop the trainer. Unfortunately your model is likely corrupt and not retrievable.

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
