### ISSUE TITLE
Save ERROR

### ISSUE THREAD

**Issue by THE-MATT-222** [iperov/DeepFaceLab#826]
The SAEHD and Quick96 training run as expected however it crashes every time I wanted to press save. This makes all of the previous progress useless. This error message pops up

2020-07-12 09:48:02.749598: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 517.44M (542572544 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
[09:48:09][#000002][0912ms][5.9417][4.6986]
Error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\USER\\Downloads\\DeepFaceLab_NVIDIA\\workspace\\model\\ _SAEHD_encoder.npy.tmp' -> 'C:\\Users\\USER\\Downloads\\DeepFaceLab_NVIDIA\\workspace\\model\\ _SAEHD_encoder.npy'
Traceback (most recent call last):
  File "C:\Users\USER\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Trainer.py", line 178, in trainerThread
    model_save()
  File "C:\Users\USER\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Trainer.py", line 68, in model_save
    model.save()
  File "C:\Users\USER\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\ModelBase.py", line 374, in save
    self.onSave()
  File "C:\Users\USER\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 604, in onSave
    model.save_weights ( self.get_strpath_storage_for_file(filename) )
  File "C:\Users\USER\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\layers\Saveable.py", line 60, in save_weights
    pathex.write_bytes_safe ( Path(filename), d_dumped )
  File "C:\Users\USER\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\pathex.py", line 14, in write_bytes_safe
    p_tmp.rename (p)
  File "pathlib.py", line 1309, in rename
  File "pathlib.py", line 393, in wrapped
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\USER\\Downloads\\DeepFaceLab_NVIDIA\\workspace\\model\\ _SAEHD_encoder.npy.tmp' -> 'C:\\Users\\USER\\Downloads\\DeepFaceLab_NVIDIA\\workspace\\model\\ _SAEHD_encoder.npy'

It did not happened to me on last year's version so I tried using the previous version 06_27_2020 instead of 07_04_2020 but it didn't seem to fix the problem at all. Furthermore, I tried deleting new _SAEHD_encoder.npy.tmp but it recreated the file everytime I pressed save so I tried removing the permission to manage files from new_SAEHD_encoder.npy.tmp but when I tried to save, there is an error saying that new_SAEHD_encoder.npy.tmp doesn't have permission so I don't know what to do with the file.
![108002476_2671415746459545_2096267356288105485_n](https://user-images.githubusercontent.com/68173463/87237994-1ac35900-c427-11ea-9e22-ee95b86ed9b8.png)

**Comment by THE-MATT-222** [comment]
Update: I fixed it! turns out, I have to disable permission to manage files for new_SAEHD_encoder.npy instead of new_SAEHD_encoder.npy.tmp For people who faced the same problem go to file explorer Workspace > Model > new_"insert what you are training with"_encoder.npy and then right-click >properties > security (tab on top) > edit > tick deny for everything.
