### ISSUE TITLE
SAVE ERROR 2

### ISSUE THREAD

**Issue by THE-MATT-222** [iperov/DeepFaceLab#827]
The SAEHD and Quick96 training run as expected however it crashes every time I wanted to press save. This makes all of the previous progress useless. This error message pops up

2020-07-12 09:48:02.749598: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 517.44M (542572544 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
[09:48:09][#2][0912ms][5.9417][4.6986]
Error: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\Users\USER\Downloads\DeepFaceLab_NVIDIA\workspace\model\ _SAEHD_encoder.npy.tmp' -> 'C:\Users\USER\Downloads\DeepFaceLab_NVIDIA\workspace\model\ _SAEHD_encoder.npy'
Traceback (most recent call last):
File "C:\Users\USER\Downloads\DeepFaceLab_NVIDIA_internal\DeepFaceLab\mainscripts\Trainer.py", line 178, in trainerThread
model_save()
File "C:\Users\USER\Downloads\DeepFaceLab_NVIDIA_internal\DeepFaceLab\mainscripts\Trainer.py", line 68, in model_save
model.save()
File "C:\Users\USER\Downloads\DeepFaceLab_NVIDIA_internal\DeepFaceLab\models\ModelBase.py", line 374, in save
self.onSave()
File "C:\Users\USER\Downloads\DeepFaceLab_NVIDIA_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 604, in onSave
model.save_weights ( self.get_strpath_storage_for_file(filename) )
File "C:\Users\USER\Downloads\DeepFaceLab_NVIDIA_internal\DeepFaceLab\core\leras\layers\Saveable.py", line 60, in save_weights
pathex.write_bytes_safe ( Path(filename), d_dumped )
File "C:\Users\USER\Downloads\DeepFaceLab_NVIDIA_internal\DeepFaceLab\core\pathex.py", line 14, in write_bytes_safe
p_tmp.rename (p)
File "pathlib.py", line 1309, in rename
File "pathlib.py", line 393, in wrapped
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\Users\USER\Downloads\DeepFaceLab_NVIDIA\workspace\model\ _SAEHD_encoder.npy.tmp' -> 'C:\Users\USER\Downloads\DeepFaceLab_NVIDIA\workspace\model\ _SAEHD_encoder.npy'

It did not happened to me on last year's version so I tried using the previous version 06_27_2020 instead of 07_04_2020 but it didn't seem to fix the problem at all. Furthermore, I tried deleting new _SAEHD_encoder.npy.tmp but it recreated the file everytime I pressed save so I tried removing the permission to manage files from new_SAEHD_encoder.npy.tmp but when I tried to save, there is an error saying that new_SAEHD_encoder.npy.tmp doesn't have permission so I don't know what to do with the file. I also tried the same with new_SAEHD_encoder.npy and it did work temporally before facing the same problem again but this time new_SAEHD_encoder.npy file disappears.

**Comment by THE-MATT-222** [comment]
Update: Still not a perminant solution but it's better than nothing. Delete what ever was generated in model folder before pressing save but if you delete the files without saving it will start all over again, however, if you keep it there it would risk the chance of autosave crashing the file. I'm sure this could be done automatically but doing it manually is a nightmare.

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?
