### ISSUE TITLE
Always error when try Converter AVATAR.

### ISSUE THREAD

**Issue by ZeroCool22** [iperov/DeepFaceLab#84]
Error:

`Running converter.

Loading model...
===== Model summary =====
== Model name: AVATAR
==
== Current epoch: 1177
==
== Options:
== |== batch_size : 48
== |== multi_gpu : False
== |== created_vram_gb : 11
== Running on:
== |== [0 : GeForce GTX 1080 Ti]
=========================
Running on CPU0.
Running on CPU1.
Running on CPU2.
Running on CPU3.
Running on CPU4.
Running on CPU5.
Converting:   0%|                                                                              | 0/866 [00:00<?, ?it/s]Exception while process data [C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\workspace\data_dst\00004.png]: Traceback (most recent call last):
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 244, in subprocess
    result = self.onClientProcessData (data)
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Converter.py", line 159, in onClientProcessData
    image_landmarks = DFLPNG.load( str(filename_path), throw_on_no_embedded_data=True ).get_landmarks()
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\DFLPNG.py", line 262, in load
    raise ValueError("No DFL data found in %s" % (filename) )
ValueError: No DFL data found in C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\workspace\data_dst\00004.png

Exception while process data [C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\workspace\data_dst\00006.png]: Traceback (most recent call last):
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 244, in subprocess
    result = self.onClientProcessData (data)
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Converter.py", line 159, in onClientProcessData
    image_landmarks = DFLPNG.load( str(filename_path), throw_on_no_embedded_data=True ).get_landmarks()
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\DFLPNG.py", line 262, in load
    raise ValueError("No DFL data found in %s" % (filename) )
ValueError: No DFL data found in C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\workspace\data_dst\00006.png
Exception while process data [C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\workspace\data_dst\00005.png]: Traceback (most recent call last):
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 244, in subprocess
    result = self.onClientProcessData (data)
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Converter.py", line 159, in onClientProcessData
    image_landmarks = DFLPNG.load( str(filename_path), throw_on_no_embedded_data=True ).get_landmarks()
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\DFLPNG.py", line 262, in load
    raise ValueError("No DFL data found in %s" % (filename) )
ValueError: No DFL data found in C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\workspace\data_dst\00005.png
Exception while process data [C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\workspace\data_dst\00003.png]: Traceback (most recent call last):
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 244, in subprocess
    result = self.onClientProcessData (data)
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Converter.py", line 159, in onClientProcessData
    image_landmarks = DFLPNG.load( str(filename_path), throw_on_no_embedded_data=True ).get_landmarks()
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\DFLPNG.py", line 262, in load
    raise ValueError("No DFL data found in %s" % (filename) )
ValueError: No DFL data found in C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\workspace\data_dst\00003.png
Exception while process data [C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\workspace\data_dst\00002.png]: Traceback (most recent call last):
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 244, in subprocess
    result = self.onClientProcessData (data)
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Converter.py", line 159, in onClientProcessData
    image_landmarks = DFLPNG.load( str(filename_path), throw_on_no_embedded_data=True ).get_landmarks()
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\DFLPNG.py", line 262, in load
    raise ValueError("No DFL data found in %s" % (filename) )
ValueError: No DFL data found in C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\workspace\data_dst\00002.png
Exception while process data [C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\workspace\data_dst\00001.png]: Traceback (most recent call last):
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 244, in subprocess
    result = self.onClientProcessData (data)
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Converter.py", line 159, in onClientProcessData
    image_landmarks = DFLPNG.load( str(filename_path), throw_on_no_embedded_data=True ).get_landmarks()
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\DFLPNG.py", line 262, in load
    raise ValueError("No DFL data found in %s" % (filename) )
ValueError: No DFL data found in C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\workspace\data_dst\00001.png
`

**DEBUG mode:**

`Running converter.

Loading model...
===== Model summary =====
== Model name: AVATAR
==
== Current epoch: 1177
==
== Options:
== |== batch_size : 1
== |== multi_gpu : False
== |== created_vram_gb : 11
== Running on:
== |== [0 : GeForce GTX 1080 Ti]
=========================
Running on CPU0.
Converting:   0%|                                                                              | 0/866 [00:00<?, ?it/s]Exception while process data [C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\workspace\data_dst\00001.png]: Traceback (most recent call last):
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 244, in subprocess
    result = self.onClientProcessData (data)
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Converter.py", line 159, in onClientProcessData
    image_landmarks = DFLPNG.load( str(filename_path), throw_on_no_embedded_data=True ).get_landmarks()
  File "C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\DFLPNG.py", line 262, in load
    raise ValueError("No DFL data found in %s" % (filename) )
ValueError: No DFL data found in C:\Users\ZeroCool22\Documents\DeepFaceLabTorrent\workspace\data_dst\00001.png
`

Yes, EPOCH number is low because i want to see if it works or not, before i let the PC training all night and like i suspect it shows a error.
All other Converters works fine, the only one i have issues is with AVATAR.
I have the last Repo Version.

**Comment by iperov** [comment]
looks like you did something wrong with images.
AVATAR cannot be automateed by .bat files and requires some hand operations with images.

Actually I dont want to support this model, its just for demo.

**Comment by ytn2001** [comment]
7) convert AVATAR.bat
Change
--input-dir %WORKSPACE%\data_dst ^
To
--input-dir %WORKSPACE%\data_dst\aligned ^

**Comment by ZeroCool22** [comment]
> 
> 
>     1. convert AVATAR.bat
>        Change
>        --input-dir %WORKSPACE%\data_dst ^
>        To
>        --input-dir %WORKSPACE%\data_dst\aligned ^

Thx so much man, It's wotking!

**Comment by baejun10** [comment]
> 1. convert AVATAR.bat
>    Change
>    --input-dir %WORKSPACE%\data_dst ^
>    To
>    --input-dir %WORKSPACE%\data_dst\aligned ^

it's working but merged body is not data_dst. body is src
