### ISSUE TITLE
Don't run 4) data_src faceset extract and 5) data_dst faceset extract

### ISSUE THREAD

**Issue by Danielfoit** [iperov/DeepFaceLab#842]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

Successfully run 4) data_src faceset extract.bat

## Actual behavior

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce GTX 1050 Ti
[0] Which GPU indexes to choose? :
0
[wf] Face type ( f/wf/head ?:help ) :
wf
[0] Max number of faces from image ( ?:help ) :
0
[512] Image size ( 256-2048 ?:help ) : 256
256
[90] Jpeg quality ( 1-100 ?:help ) :
90
[n] Write debug images to aligned_debug? ( y/n ) :
n
Extracting faces...
Error while subprocess initialization: Traceback (most recent call last):
  File "C:\Users\Daniel\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 62, in _subprocess_run
    self.on_initialize(client_dict)
  File "C:\Users\Daniel\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Extractor.py", line 68, in on_initialize
    nn.initialize (device_config)
  File "C:\Users\Daniel\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\nn.py", line 109, in initialize
    nn.tf_sess = tf.Session(config=nn.tf_sess_config)
  File "C:\Users\Daniel\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 1551, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "C:\Users\Daniel\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\client\session.py", line 676, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version

Traceback (most recent call last):
  File "C:\Users\Daniel\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 324, in <module>
    arguments.func(arguments)
  File "C:\Users\Daniel\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\main.py", line 45, in process_extract
    force_gpu_idxs          = [ int(x) for x in arguments.force_gpu_idxs.split(',') ] if arguments.force_gpu_idxs is not None else None,
  File "C:\Users\Daniel\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Extractor.py", line 853, in main
    device_config=device_config).run()
  File "C:\Users\Daniel\Desktop\DeepFaceLab\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 210, in run
    raise Exception ( "Unable to start subprocesses." )
Exception: Unable to start subprocesses.
Presione una tecla para continuar . . .

## Steps to reproduce

My specs are: Intel Pentium G4400 and a GTX 1050 TI. The weird thing is that when I select the CPU it works (very slow, but it works), the problem is when I select the GPU (GTX 1050 TI)

## Other relevant information
- Windows 10 Pro 1903
- Windows Binary = DeepFaceLab_NVIDIA_build_07_18_2020.exe

**Comment by iperov** [comment]
update geforce drivers

**Comment by Danielfoit** [comment]
I updated the GeForce drivers and saw that I had two versions of CUDA installed, uninstall and reinstall CUDA 9 and all works fine.

**Comment by iperov** [comment]
you don't need to install cuda
