### ISSUE TITLE
Error on DeepFaceLab

### ISSUE THREAD

**Issue by Bogdan4305** [iperov/DeepFaceLab#843]
## Hello, I wanted to make my DeepFake in your program, but an error occurred:

Performing manual extract...
Error while subprocess initialization: Traceback (most recent call last):
  File "C:\Users\Богдан\Desktop\DFL\DeepFaceLab_NVIDIA\_internal\python-3.6.8\li
b\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Богдан\Desktop\DFL\DeepFaceLab_NVIDIA\_internal\python-3.6.8\li
b\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <m
odule>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Богдан\Desktop\DFL\DeepFaceLab_NVIDIA\_internal\python-3.6.8\li
b\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in sw
ig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: Не найден указанный модуль.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Богдан\Desktop\DFL\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\cor
e\joblib\SubprocessorBase.py", line 62, in _subprocess_run
    self.on_initialize(client_dict)
  File "C:\Users\Богдан\Desktop\DFL\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mai
nscripts\Extractor.py", line 68, in on_initialize
    nn.initialize (device_config)
  File "C:\Users\Богдан\Desktop\DFL\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\cor
e\leras\nn.py", line 80, in initialize
    import tensorflow as tf
  File "C:\Users\Богдан\Desktop\DFL\DeepFaceLab_NVIDIA\_internal\python-3.6.8\li
b\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Users\Богдан\Desktop\DFL\DeepFaceLab_NVIDIA\_internal\python-3.6.8\li
b\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Богдан\Desktop\DFL\DeepFaceLab_NVIDIA\_internal\python-3.6.8\li
b\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Богдан\Desktop\DFL\DeepFaceLab_NVIDIA\_internal\python-3.6.8\li
b\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Богдан\Desktop\DFL\DeepFaceLab_NVIDIA\_internal\python-3.6.8\li
b\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <m
odule>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Богдан\Desktop\DFL\DeepFaceLab_NVIDIA\_internal\python-3.6.8\li
b\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in sw
ig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed: Не найден указанный модуль.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Traceback (most recent call last):
  File "C:\Users\Богдан\Desktop\DFL\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mai
n.py", line 324, in <module>
    arguments.func(arguments)
  File "C:\Users\Богдан\Desktop\DFL\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mai
n.py", line 45, in process_extract
    force_gpu_idxs          = [ int(x) for x in arguments.force_gpu_idxs.split('
,') ] if arguments.force_gpu_idxs is not None else None,
  File "C:\Users\Богдан\Desktop\DFL\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mai
nscripts\Extractor.py", line 838, in main
    data = ExtractSubprocessor ([ ExtractSubprocessor.Data(Path(filename)) for f
ilename in input_image_paths ], 'landmarks-manual', image_size, jpeg_quality, fa
ce_type, output_debug_path if output_debug else None, manual_window_size=manual_
window_size, device_config=device_config).run()
  File "C:\Users\Богдан\Desktop\DFL\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\cor
e\joblib\SubprocessorBase.py", line 210, in run
    raise Exception ( "Unable to start subprocesses." )
Exception: Unable to start subprocesses.

**Comment by test1230-lab** [comment]
is this the latest commit?

**Comment by Bogdan4305** [comment]
> is this the latest commit?

Yes

**Comment by Bishal786** [comment]
I get the same problem

**Comment by ghost** [comment]
Did you ever find the answer? If so, would you mind sharing it and closing this issue?
