### ISSUE TITLE
Same Errors on the all training models

### ISSUE THREAD

**Issue by orangedid** [iperov/DeepFaceLab#849]
My graphic card is opencl_intel_hd_graphics_620.0. on window.
It's not so good graphic card so I'm trying only 5 seconds video both for data_src and data_dst. 
Extracting faces was fine but at the training step, it doesn't work. I tried all the 8 models but nothing worked and showing same errors.

There was errors for my 5 seconds videos so I tried the initial data_src and data_dst videos from the first download of the program but there was the same errors.

## Actual behavior

Process Process-1:
Traceback (most recent call last):
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 99, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 112, in process
    params = imagelib.gen_warp_params(sample_bgr, sample_process_options.random_flip, rotation_range=sample_process_options.rotation_range, scale_range=sample_process_options.scale_range, tx_range=sample_process_options.tx_range, ty_range=sample_process_options.ty_range, rnd_seed=sample_rnd_seed )
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\imagelib\warp.py", line 8, in gen_warp_params
    raise ValueError ('gen_warp_params accepts only square images.')
ValueError: gen_warp_params accepts only square images.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 258, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\utils\iter_utils.py", line 49, in process_func
    gen_data = next (self.generator_func)
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 101, in batch_func
    raise Exception ("Exception occured in sample %s. Error: %s" % (sample.filename, traceback.format_exc() ) )
Exception: Exception occured in sample C:\DeepFaceLab_OpenCL\workspace\data_src\aligned\00003_0.jpg. Error: Traceback (most recent call last):
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 99, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 112, in process
    params = imagelib.gen_warp_params(sample_bgr, sample_process_options.random_flip, rotation_range=sample_process_options.rotation_range, scale_range=sample_process_options.scale_range, tx_range=sample_process_options.tx_range, ty_range=sample_process_options.ty_range, rnd_seed=sample_rnd_seed )
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\imagelib\warp.py", line 8, in gen_warp_params
    raise ValueError ('gen_warp_params accepts only square images.')
ValueError: gen_warp_params accepts only square images.

Process Process-2:
Traceback (most recent call last):
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 99, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 112, in process
    params = imagelib.gen_warp_params(sample_bgr, sample_process_options.random_flip, rotation_range=sample_process_options.rotation_range, scale_range=sample_process_options.scale_range, tx_range=sample_process_options.tx_range, ty_range=sample_process_options.ty_range, rnd_seed=sample_rnd_seed )
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\imagelib\warp.py", line 8, in gen_warp_params
    raise ValueError ('gen_warp_params accepts only square images.')
ValueError: gen_warp_params accepts only square images.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 258, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\utils\iter_utils.py", line 49, in process_func
    gen_data = next (self.generator_func)
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 101, in batch_func
    raise Exception ("Exception occured in sample %s. Error: %s" % (sample.filename, traceback.format_exc() ) )
Exception: Exception occured in sample C:\DeepFaceLab_OpenCL\workspace\data_src\aligned\00018_0.jpg. Error: Traceback (most recent call last):
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 99, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 112, in process
    params = imagelib.gen_warp_params(sample_bgr, sample_process_options.random_flip, rotation_range=sample_process_options.rotation_range, scale_range=sample_process_options.scale_range, tx_range=sample_process_options.tx_range, ty_range=sample_process_options.ty_range, rnd_seed=sample_rnd_seed )
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\imagelib\warp.py", line 8, in gen_warp_params
    raise ValueError ('gen_warp_params accepts only square images.')
ValueError: gen_warp_params accepts only square images.

Process Process-3:
Traceback (most recent call last):
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 99, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 112, in process
    params = imagelib.gen_warp_params(sample_bgr, sample_process_options.random_flip, rotation_range=sample_process_options.rotation_range, scale_range=sample_process_options.scale_range, tx_range=sample_process_options.tx_range, ty_range=sample_process_options.ty_range, rnd_seed=sample_rnd_seed )
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\imagelib\warp.py", line 8, in gen_warp_params
    raise ValueError ('gen_warp_params accepts only square images.')
ValueError: gen_warp_params accepts only square images.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 258, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\utils\iter_utils.py", line 49, in process_func
    gen_data = next (self.generator_func)
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 101, in batch_func
    raise Exception ("Exception occured in sample %s. Error: %s" % (sample.filename, traceback.format_exc() ) )
Exception: Exception occured in sample C:\DeepFaceLab_OpenCL\workspace\data_src\aligned\00005_0.jpg. Error: Traceback (most recent call last):
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 99, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 112, in process
    params = imagelib.gen_warp_params(sample_bgr, sample_process_options.random_flip, rotation_range=sample_process_options.rotation_range, scale_range=sample_process_options.scale_range, tx_range=sample_process_options.tx_range, ty_range=sample_process_options.ty_range, rnd_seed=sample_rnd_seed )
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\imagelib\warp.py", line 8, in gen_warp_params
    raise ValueError ('gen_warp_params accepts only square images.')
ValueError: gen_warp_params accepts only square images.

Loading:   0%|                                                                                 | 0/156 [00:00<?, ?it/s]Process Process-4:
Traceback (most recent call last):
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 99, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 112, in process
    params = imagelib.gen_warp_params(sample_bgr, sample_process_options.random_flip, rotation_range=sample_process_options.rotation_range, scale_range=sample_process_options.scale_range, tx_range=sample_process_options.tx_range, ty_range=sample_process_options.ty_range, rnd_seed=sample_rnd_seed )
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\imagelib\warp.py", line 8, in gen_warp_params
    raise ValueError ('gen_warp_params accepts only square images.')
ValueError: gen_warp_params accepts only square images.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 258, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\utils\iter_utils.py", line 49, in process_func
    gen_data = next (self.generator_func)
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 101, in batch_func
    raise Exception ("Exception occured in sample %s. Error: %s" % (sample.filename, traceback.format_exc() ) )
Exception: Exception occured in sample C:\DeepFaceLab_OpenCL\workspace\data_src\aligned\00015_0.jpg. Error: Traceback (most recent call last):
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 99, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleProcessor.py", line 112, in process
    params = imagelib.gen_warp_params(sample_bgr, sample_process_options.random_flip, rotation_range=sample_process_options.rotation_range, scale_range=sample_process_options.scale_range, tx_range=sample_process_options.tx_range, ty_range=sample_process_options.ty_range, rnd_seed=sample_rnd_seed )
  File "C:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\imagelib\warp.py", line 8, in gen_warp_params
    raise ValueError ('gen_warp_params accepts only square images.')
ValueError: gen_warp_params accepts only square images.

Loading: 100%|#######################################################################| 156/156 [00:02<00:00, 57.95it/s]

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** Windows
- **Python version:** 3.7.4

**Comment by orangedid** [comment]
It was because my data_src.mp4 was not square
