### ISSUE TITLE
Exception: FaceType.fromString value error

### ISSUE THREAD

**Issue by Alex99zx** [iperov/DeepFaceLab#875]
i'm new to dfl & any training method will end up with

 "Loading:   0%|                                                                                | 0/3075 [00:00<?, ?it/s]Error: FaceType.fromString value error
Traceback (most recent call last):
  File "C:\Users\d\Documents\DeepFaceLab_1.0_OpenCL_build_01_11_2020\DeepFaceLab_OpenCL\_internal\DeepFaceLab\mainscripts\Trainer.py", line 52, in trainerThread
    device_args=device_args)
  File "C:\Users\d\Documents\DeepFaceLab_1.0_OpenCL_build_01_11_2020\DeepFaceLab_OpenCL\_internal\DeepFaceLab\models\ModelBase.py", line 146, in __init__
    self.onInitialize()
  File "C:\Users\d\Documents\DeepFaceLab_1.0_OpenCL_build_01_11_2020\DeepFaceLab_OpenCL\_internal\DeepFaceLab\models\Model_SAEHD\Model.py", line 546, in onInitialize
    {'types' : (t.IMG_TRANSFORMED, face_type, t.MODE_M), 'resolution': resolution } ]
  File "C:\Users\d\Documents\DeepFaceLab_1.0_OpenCL_build_01_11_2020\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 39, in __init__
    samples = SampleHost.load (SampleType.FACE, self.samples_path)
  File "C:\Users\d\Documents\DeepFaceLab_1.0_OpenCL_build_01_11_2020\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleHost.py", line 61, in load
    result = SampleHost.load_face_samples( Path_utils.get_image_paths(samples_path) )
  File "C:\Users\d\Documents\DeepFaceLab_1.0_OpenCL_build_01_11_2020\DeepFaceLab_OpenCL\_internal\DeepFaceLab\samplelib\SampleHost.py", line 82, in load_face_samples
    face_type=FaceType.fromString ( dflimg.get_face_type() ),
  File "C:\Users\d\Documents\DeepFaceLab_1.0_OpenCL_build_01_11_2020\DeepFaceLab_OpenCL\_internal\DeepFaceLab\facelib\FaceType.py", line 18, in fromString
    raise Exception ('FaceType.fromString value error')
Exception: FaceType.fromString value error"

**Comment by ghost** [comment]
Did you ever find the answer?
