### ISSUE TITLE
Help! I am getting this error: Error: No segmented faces found.

### ISSUE THREAD

**Issue by Bluepower2** [iperov/DeepFaceLab#881]
Hi All,

I am trying to do some deepfakes for my English assignment, so some help would greatly be appreciated. I am doing a basic, short deepfake, replacing my face with Elon Musk's. I have extracted the faces, and all was going well. When I tried to train it, I got and error message. I have copied the whole console window bellow:

Running trainer.

Model first run.
[f] Face type ( h/mf/f/wf/head ?:help ) : wf
wf
[5] Batch_size ( 2-16 ?:help ) : 2
2
Loaded 0 packed faces from C:\Users\[MyUsername]\Documents\DeepFaceLab_NVIDIA\workspace\data_src\aligned
Loading samples: 100%|##############################################################| 256/256 [00:00<00:00, 402.45it/s]
Filtering: 100%|####################################################################| 256/256 [00:00<00:00, 421.73it/s]
Error: No segmented faces found.
Traceback (most recent call last):
  File "C:\Users\[MyUsername]\Documents\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Trainer.py", line 57, in trainerThread
    debug=debug,
  File "C:\Users\[MyUsername]\Documents\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_XSeg\Model.py", line 17, in __init__
    super().__init__(*args, force_model_class_name='XSeg', **kwargs)
  File "C:\Users\[MyUsername]\Documents\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\ModelBase.py", line 189, in __init__
    self.on_initialize()
  File "C:\Users\[MyUsername]\Documents\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\models\Model_XSeg\Model.py", line 133, in on_initialize
    data_format=nn.data_format)
  File "C:\Users\[MyUsername]\Documents\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\samplelib\SampleGeneratorFaceXSeg.py", line 31, in __init__
    raise Exception(f"No segmented faces found.")
Exception: No segmented faces found.

That was the error message I got. I would greatly appreciated help quickly, because I need to get this done quickly. Also, I set all the settings to there lowest, so that processing power wouldn't be the problem.

Thanks,

**Comment by test1230-lab** [comment]
this is xseg.

**Comment by Bluepower2** [comment]
> this is xseg.

Okay, so what can I do to fix the problem?

**Comment by test1230-lab** [comment]
xseg is the face masker. read the guide linked on the github

**Comment by wrecche** [comment]
Dont train with xseg if you didn't use it prior. Use quick96, sounds like you used that. Came across this myself.  test1230-lab pointed me to resolve it.

**Comment by sergiobd** [comment]
I'm facing the same problem. I mask a few faces, train with XSeg and results are pretty good. Then I apply the masks, to both src and dst. In the XSeg viewer there is a mask an all faces. However, when I'm merging, around 40 % of the frames "do not have a face". In my merged_mask folder there are only a few faces, and a small percentage of them have the mask applied. 


clues?

**Comment by adamandersen** [comment]
> I'm facing the same problem. I mask a few faces, train with XSeg and results are pretty good. Then I apply the masks, to both src and dst. In the XSeg viewer there is a mask on all faces. However, when I'm merging, around 40 % of the frames "do not have a face". In my merged_mask folder there are only a few faces, and a small percentage of them have the mask applied.
> 
> clues?

Did you get any clues on this? I'm having the same results, random missing faces....

**Comment by Insomniaxd1100** [comment]
> "No segmented faces found." What this means is that there are literally no segments. You will Launch the XSeg editor to create one or more segments.
> 
> * XSeg) data_dst mask - edit.bat
> * XSeg) data_src mask - edit.bat

I have used xseg for a long time and now have this error 

DeepFaceLab\samplelib\SampleGeneratorFaceXSeg.py", line 86, in gen_img_mask img = sample.load_bgr() File     bg_img, bg_mask = gen_img_mask(bg_sample)
  File "I:\DeepReagan\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\SampleGeneratorFaceXSeg.py", line 86, in gen_img_mask
    img = sample.load_bgr()
  File "I:\DeepReagan\DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\samplelib\Sample.py", line 112, in load_bgr
    img = cv2_imread (self.filename, loader_func=self.read_raw_file).astype(np.float32) / 255.0
AttributeError: 'NoneType' object has no attribute 'astype'

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
