### ISSUE TITLE
How do I fix this error on  step 4?

### ISSUE THREAD

**Issue by iankinzel** [iperov/DeepFaceLab#884]
> [n] Write debug images to aligned_debug? ( y/n ) : n
> Extracting faces...
> Exception: Traceback (most recent call last):
>   File "C:\Users\ianki\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Users\ianki\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Users\ianki\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "imp.py", line 243, in load_module
>   File "imp.py", line 343, in load_dynamic
> ImportError: DLL load failed: The specified module could not be found.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\ianki\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 62, in _subprocess_run
>     self.on_initialize(client_dict)
>   File "C:\Users\ianki\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Extractor.py", line 66, in on_initialize
>     nn.initialize (device_config)
>   File "C:\Users\ianki\Downloads\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\leras\nn.py", line 80, in initialize
>     import tensorflow as tf
>   File "C:\Users\ianki\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "C:\Users\ianki\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "C:\Users\ianki\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "C:\Users\ianki\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Users\ianki\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Users\ianki\Downloads\DeepFaceLab_NVIDIA\_internal\python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "imp.py", line 243, in load_module
>   File "imp.py", line 343, in load_dynamic
> ImportError: DLL load failed: The specified module could not be found.
> 
> 
> Failed to load the native TensorFlow runtime.

**Comment by damengdameng** [comment]
hi,  have you fix this?

**Comment by jiteshm17** [comment]
Looks like you are missing cuDNN. Check [here](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-windows) to install the correct version and see if it works

**Comment by ghost** [comment]
Issue solved / already answered (or it seems like user error), please close it.
