### ISSUE TITLE
module functions cannot set METH_CLASS or METH_STATIC

### ISSUE THREAD

**Issue by Qing93** [iperov/DeepFaceLab#888]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

*run 4_data_src_extract_faces_S3FD*

## Actual behavior

*bash 4_data_src_extract_faces_S3FD.sh*

## Steps to reproduce

*Extracting faces...

(main.py:15223): dbind-WARNING **: 21:29:45.432: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Error while subprocess initialization: Traceback (most recent call last):
  File "/home/ubuntu/user_space/DeepFaceLab/DeepFaceLab/core/joblib/SubprocessorBase.py", line 62, in _subprocess_run
    self.on_initialize(client_dict)
  File "/home/ubuntu/user_space/DeepFaceLab/DeepFaceLab/mainscripts/Extractor.py", line 68, in on_initialize
    nn.initialize (device_config)
  File "/home/ubuntu/user_space/DeepFaceLab/DeepFaceLab/core/leras/nn.py", line 80, in initialize
    import tensorflow as tf
  File "/usr/lib/python3.6/site-packages/tensorflow/__init__.py", line 29, in <module>
    from tensorflow._api.v1 import compat
  File "/usr/lib/python3.6/site-packages/tensorflow/_api/v1/compat/__init__.py", line 21, in <module>
    from tensorflow._api.v1.compat import v1
  File "/usr/lib/python3.6/site-packages/tensorflow/_api/v1/compat/v1/__init__.py", line 626, in <module>
    child_package_str=('tensorflow_estimator.python.estimator.api.estimator'))
  File "/usr/lib/python3.6/site-packages/tensorflow/python/tools/component_api_helper.py", line 56, in package_hook
    child_pkg = importlib.import_module(child_package_str)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.6/site-packages/tensorflow_estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/usr/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/usr/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 8, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/usr/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/__init__.py", line 25, in <module>
    import tensorflow_estimator.python.estimator.estimator_lib
  File "/usr/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator_lib.py", line 53, in <module>
    from tensorflow_estimator.python.estimator.inputs import inputs
  File "/usr/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/inputs/inputs.py", line 22, in <module>
    from tensorflow_estimator.python.estimator.inputs.numpy_io import numpy_input_fn
  File "/usr/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/inputs/numpy_io.py", line 26, in <module>
    from tensorflow_estimator.python.estimator.inputs.queues import feeding_functions
  File "/usr/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/inputs/queues/feeding_functions.py", line 40, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.6/dist-packages/pandas/__init__.py", line 57, in <module>
    from pandas.io.api import *
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/api.py", line 19, in <module>
    from pandas.io.packers import read_msgpack, to_msgpack
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/packers.py", line 69, in <module>
    from pandas.util._move import (
ValueError: module functions cannot set METH_CLASS or METH_STATIC

/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
Traceback (most recent call last):
  File "./DeepFaceLab/main.py", line 324, in <module>
    arguments.func(arguments)
  File "./DeepFaceLab/main.py", line 45, in process_extract
    force_gpu_idxs          = [ int(x) for x in arguments.force_gpu_idxs.split(',') ] if arguments.force_gpu_idxs is not None else None,
  File "/home/ubuntu/user_space/DeepFaceLab/DeepFaceLab/mainscripts/Extractor.py", line 853, in main
    device_config=device_config).run()
  File "/home/ubuntu/user_space/DeepFaceLab/DeepFaceLab/core/joblib/SubprocessorBase.py", line 210, in run
    raise Exception ( "Unable to start subprocesses." )*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: bash 4_data_src_extract_faces_S3FD.sh
- **Operating system and version:** Ubuntu 
- **Python version:** 3.6.7
- **Tensorflow version:** 1.13.1

**Comment by Qing93** [comment]
I solved this problem by "pip uninstall pandas"...
