### ISSUE TITLE
some errors when i strated Quick96 

### ISSUE THREAD

**Issue by caileimeng** [iperov/DeepFaceLab#890]
GPU: 5700xt 
software:DeepFaceLab_1.0_OpenCL_build_01_11_2020
problem:6) train Quick96 
Traceback (most recent call last):an]
  File "D:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\main.py", line 331, in <module>
    arguments.func(arguments)
  File "D:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\main.py", line 175, in process_train
    Trainer.main(args, device_args)
  File "D:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\mainscripts\Trainer.py", line 290, in main
    lh_img = models.ModelBase.get_loss_history_preview(loss_history_to_show, iter, w, c)
  File "D:\DeepFaceLab_OpenCL\_internal\DeepFaceLab\models\ModelBase.py", line 631, in get_loss_history_preview
    ph_max = int ( (plist_max[col][p] / plist_abs_max) * (lh_height-1) )
ValueError: cannot convert float NaN to integer

**Comment by ghost** [comment]
Does this issue still persist?
