### ISSUE TITLE
Merger(SAEHD) crashes in interactive mode when switching from help screen to main screen.

### ISSUE THREAD

**Issue by sandstrand** [iperov/DeepFaceLab#917]
## Expected behavior

Running '_7) merge SAEHD.bat_' launches the merger.   
If you select 'Yes' on the interactive merger option the merger launches with a GUI which starts on the help screen.  
From the help screen you can switch to the main / preview screen by pressing tab. 

## Actual behavior

When attempting to switch from _help_ screen to _main_ screen by pressing tab the merger crashes with a curious error: 
```
> Invalid number of channels in input image:
> 'VScn::contains(scn)'
> where
> 'scn' is 5
```
See full dump and trace below.

Only the first merged image is created in data_dst/merged.

If I run the merger as non-interactive, the merge is successful.

The error seems similar to #645  but that issue is resolved without any solution. 

## Steps to reproduce

Unable to determine triggers, cannot reproduce in other projects.

## Other relevant information

- **Operating system and version:** Windows 10 
- **Application version:** DeepFaceLab_NVIDIA_build_08_02_2020.exe  
- XSeg trained for 40K iterations  
- SAEHD trained for ~70K iterations with different options along the way

## Full dump
```
Running merger.

Choose one of saved models, or enter a name to create a new model.
[r] : rename
[d] : delete

[0] : 192 liae-ud - latest
 : 0
0
Loading 192 liae-ud_SAEHD model...

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce RTX 2060 SUPER

[0] Which GPU indexes to choose? : 0
0

Initializing models: 100%|###############################################################| 4/4 [00:01<00:00,  3.74it/s]
================== Model Summary ==================
==                                               ==
==            Model name: 192 liae-ud_SAEHD      ==
==                                               ==
==     Current iteration: 73595                  ==
==                                               ==
==---------------- Model Options ----------------==
==                                               ==
==            resolution: 192                    ==
==             face_type: f                      ==
==     models_opt_on_gpu: True                   ==
==                 archi: liae-ud                ==
==               ae_dims: 256                    ==
==                e_dims: 64                     ==
==                d_dims: 64                     ==
==           d_mask_dims: 22                     ==
==       masked_training: True                   ==
==             eyes_prio: True                   ==
==           uniform_yaw: False                  ==
==            lr_dropout: n                      ==
==           random_warp: False                  ==
==             gan_power: 0.0                    ==
==       true_face_power: 0.0                    ==
==      face_style_power: 0.0                    ==
==        bg_style_power: 0.0                    ==
==               ct_mode: none                   ==
==              clipgrad: True                   ==
==              pretrain: False                  ==
==       autobackup_hour: 2                      ==
== write_preview_history: True                   ==
==           target_iter: 1000000                ==
==           random_flip: True                   ==
==            batch_size: 8                      ==
==                                               ==
==----------------- Running On ------------------==
==                                               ==
==          Device index: 0                      ==
==                  Name: GeForce RTX 2060 SUPER ==
==                  VRAM: 8.00GB                 ==
==                                               ==
===================================================
[y] Use interactive merger? ( y/n ) : y
[12] Number of workers? ( 1-12 ?:help ) : 6
6
Collecting alignments: 100%|#########################################################| 942/942 [00:18<00:00, 52.18it/s]
Computing motion vectors: 100%|##################################################| 2031/2031 [00:00<00:00, 3304.05it/s]
Running on CPU4.
Running on CPU0.
Running on CPU1.
Running on CPU2.
Running on CPU3.
Running on CPU5.
Merging:   0%|                                                                                | 0/2031 [00:00<?, ?it/s]

no faces found for dst_000_000000.png, copying without faces


MergerConfig dst_000_000000.png:
Mode: overlay
mask_mode: learned-prd*learned-dst
erode_mask_modifier: 0
blur_mask_modifier: 0
motion_blur_power: 0
output_face_scale: 0
color_transfer_mode: rct
sharpen_mode : None
blursharpen_amount : 0
super_resolution_power: 0
image_denoise_power: 0
bicubic_degrade_power: 0
color_degrade_power: 0
================
Traceback (most recent call last):
  File "D:\projects\DeepFake\Iamthearm\DFL_smith_to_midget\_internal\DeepFaceLab\mainscripts\Merger.py", line 208, in main
    subprocess_count       = subprocess_count,
  File "D:\projects\DeepFake\Iamthearm\DFL_smith_to_midget\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 268, in run
    if self.on_tick() and all ([cli.state == 0 for cli in self.clis]):
  File "D:\projects\DeepFake\Iamthearm\DFL_smith_to_midget\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 414, in on_tick
    self.screen_manager.switch_screens()
  File "D:\projects\DeepFake\Iamthearm\DFL_smith_to_midget\_internal\DeepFaceLab\merger\MergerScreen\MergerScreen.py", line 140, in switch_screens
    self.screens[self.current_screen_id].show(force=True)
  File "D:\projects\DeepFake\Iamthearm\DFL_smith_to_midget\_internal\DeepFaceLab\merger\MergerScreen\MergerScreen.py", line 105, in show
    io.show_image(self.scrn_manager.wnd_name, screen)
  File "D:\projects\DeepFake\Iamthearm\DFL_smith_to_midget\_internal\DeepFaceLab\core\interact\interact.py", line 131, in show_image
    self.on_show_image(wnd_name,img)
  File "D:\projects\DeepFake\Iamthearm\DFL_smith_to_midget\_internal\DeepFaceLab\core\interact\interact.py", line 466, in on_show_image
    cv2.imshow (wnd_name, img)
cv2.error: OpenCV(4.1.0) c:\projects\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0xe227985e::Set<3,4,-1>,struct cv::impl::A0xe227985e::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 5

Done.
Press any key to continue . . .
```

**Comment by deepspan** [comment]
Did you ever get this figured out? I am getting the exact same issue, not sure what I did differently to make it stop working.

**Comment by deepspan** [comment]
Running merger.

Choose one of saved models, or enter a name to create a new model.
[r] : rename
[d] : delete

[0] : munson - latest
 : 0
0
Loading munson_SAEHD model...

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce RTX 2080 Ti

[0] Which GPU indexes to choose? : 0
0

Initializing models: 100%|###############################################################| 4/4 [00:00<00:00,  7.25it/s]
================ Model Summary =================
==                                            ==
==            Model name: munson_SAEHD        ==
==                                            ==
==     Current iteration: 132546              ==
==                                            ==
==-------------- Model Options ---------------==
==                                            ==
==            resolution: 128                 ==
==             face_type: f                   ==
==     models_opt_on_gpu: True                ==
==                 archi: df                  ==
==               ae_dims: 256                 ==
==                e_dims: 64                  ==
==                d_dims: 64                  ==
==           d_mask_dims: 22                  ==
==       masked_training: True                ==
==             eyes_prio: False               ==
==           uniform_yaw: False               ==
==            lr_dropout: n                   ==
==           random_warp: True                ==
==             gan_power: 0.0                 ==
==       true_face_power: 0.0                 ==
==      face_style_power: 0.0                 ==
==        bg_style_power: 0.0                 ==
==               ct_mode: none                ==
==              clipgrad: False               ==
==              pretrain: False               ==
==       autobackup_hour: 0                   ==
== write_preview_history: False               ==
==           target_iter: 150000              ==
==           random_flip: True                ==
==            batch_size: 8                   ==
==                                            ==
==---------------- Running On ----------------==
==                                            ==
==          Device index: 0                   ==
==                  Name: GeForce RTX 2080 Ti ==
==                  VRAM: 11.00GB             ==
==                                            ==
================================================
[y] Use interactive merger? ( y/n ) :
y
[16] Number of workers? ( 1-16 ?:help ) :
16
Collecting alignments: 100%|########################################################| 777/777 [00:05<00:00, 147.42it/s]

Warning: multiple faces detected. Only one alignment file should refer one source file.

alignment 02258.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_11809.png
alignment 07913.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_11809.png

alignment 02270.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_11812.png
alignment 09454.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_11812.png

alignment 02288.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_11805.png
alignment 07914.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_11805.png

alignment 02613.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12437.png
alignment 02614.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12437.png

alignment 02642.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12442.png
alignment 02643.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12442.png

alignment 03715.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12699.png
alignment 08130.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12699.png

alignment 03740.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12399.png
alignment 03741.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12399.png

alignment 03870.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12427.png
alignment 03877.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12427.png

alignment 03871.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12428.png
alignment 03878.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12428.png

alignment 03872.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12429.png
alignment 03879.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12429.png

alignment 03873.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12426.png
alignment 03874.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12426.png

alignment 05050.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12397.png
alignment 05052.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12397.png

alignment 05054.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12395.png
alignment 05055.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12395.png

alignment 05056.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12382.png
alignment 08450.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12382.png

alignment 05067.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12391.png
alignment 05068.jpg refers to Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_12391.png

It is strongly recommended to process the faces separatelly.
Use 'recover original filename' to determine the exact duplicates.

Warning: multiple faces detected. Motion blur will not be used.

Running on CPU1.
Running on CPU3.
Running on CPU0.
Running on CPU2.
Running on CPU5.
Running on CPU7.
Running on CPU4.
Running on CPU6.
Running on CPU9.
Running on CPU11.
Running on CPU13.
Running on CPU8.
Running on CPU10.
Running on CPU12.
Running on CPU15.
Running on CPU14.
Merging:   0%|                                                                                | 0/2702 [00:00<?, ?it/s]

no faces found for Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_10000.png, copying without faces


MergerConfig Kingpin.1996.1080p.Bluray.x265.10bit.AAC.5.1-3xO_10000.png:
Mode: overlay
mask_mode: learned-prd*learned-dst
erode_mask_modifier: 0
blur_mask_modifier: 0
motion_blur_power: 0
output_face_scale: 0
color_transfer_mode: rct
sharpen_mode : None
blursharpen_amount : 0
super_resolution_power: 0
image_denoise_power: 0
bicubic_degrade_power: 0
color_degrade_power: 0
================
Traceback (most recent call last):
  File "D:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\mainscripts\Merger.py", line 208, in main
    subprocess_count       = subprocess_count,
  File "D:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\joblib\SubprocessorBase.py", line 268, in run
    if self.on_tick() and all ([cli.state == 0 for cli in self.clis]):
  File "D:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\InteractiveMergerSubprocessor.py", line 414, in on_tick
    self.screen_manager.switch_screens()
  File "D:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergerScreen\MergerScreen.py", line 140, in switch_screens
    self.screens[self.current_screen_id].show(force=True)
  File "D:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\merger\MergerScreen\MergerScreen.py", line 105, in show
    io.show_image(self.scrn_manager.wnd_name, screen)
  File "D:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\interact\interact.py", line 131, in show_image
    self.on_show_image(wnd_name,img)
  File "D:\DeepFaceLab_NVIDIA\_internal\DeepFaceLab\core\interact\interact.py", line 466, in on_show_image
    cv2.imshow (wnd_name, img)
cv2.error: OpenCV(4.1.0) c:\projects\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0xe227985e::Set<3,4,-1>,struct cv::impl::A0xe227985e::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 5


Done.
Press any key to continue . . .

**Comment by sandstrand** [comment]
No solution yet :/

**Comment by Boomkop3** [comment]
@sandstrand I see you're using the interactive merger. Using it I just had the same problem, and I found that the issue was with displaying the image on screen. Processing the whole video without showing it ( `shift`+`>` ) does work for me.  From the stacktrace you provided I see that the Exception occurs in the same location in your case ` cv2.imshow (wnd_name, img)`

To patch it up, I just added a try catch in the location where `cv2.imshow` was called and causing an issue. This worked for me, even if I could not see the problematic frames anymore. Which, for me, is fine for now.

**The (*not quite*) fix:**
FILE: `DeepFaceLab_NVIDIA_RTX3000_series\_internal\DeepFaceLab\core\interact\interact.py` -> line `466`

change this function:
```python
    def on_show_image (self, wnd_name, img):
        cv2.imshow (wnd_name, img)
```

to this:
```python
    def on_show_image (self, wnd_name, img):
        try:
            cv2.imshow (wnd_name, img)
        except Exception:
            pass
```

**Comment by Boomkop3** [comment]
@deepspan tip for dumping code or logs onto github or any website that supports Markdown
using \`\`\` triple backtics: \`\`\` around any block of text turns it into `monospace` making it a lot more readable

**Comment by Sefeng** [comment]
i got the same error when no faces in the first frame

**Comment by ghost** [comment]
Did you ever find the answer?
