### ISSUE TITLE
GPU Issue

### ISSUE THREAD

**Issue by jeffkorea** [iperov/DeepFaceLab#97]
Getting this error when attempting to run "4) data_src extract faces DLIB best GPU" "You have no capable GPUs. Try to close programs which can consume VRAM, and run again

Any help would be very much appreciated. 
Cheers.

Running on GeForce RTX 2080.
Exception while initialization: Traceback (most recent call last):
  File "C:\Users\Jeff\Desktop\cUDA\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 215, in subprocess
    fail_message = self.onClientInitialize(client_dict)
  File "C:\Users\Jeff\Desktop\cUDA\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 261, in onClientInitialize
    self.e.__enter__()
  File "C:\Users\Jeff\Desktop\cUDA\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\DLIBExtractor.py", line 17, in __enter__
    self.dlib_cnn_face_detector ( np.zeros ( (self.scale_to, self.scale_to, 3), dtype=np.uint8), 0 )
RuntimeError: Error while calling cudnnConvolutionForward( context(), &alpha, descriptor(data), data.device(), (const cudnnFilterDescriptor_t)filter_handle, filters.device(), (const cudnnConvolutionDescriptor_t)conv_handle, (cudnnConvolutionFwdAlgo_t)forward_algo, forward_workspace, forward_workspace_size_in_bytes, &beta, descriptor(output), output.device()) in file D:\Python365\_internal\bin\dlib\dlib\dnn\cudnn_dlibapi.cpp:1056. code: 8, reason: CUDNN_STATUS_EXECUTION_FAILE

**Comment by jeffkorea** [comment]
I'm also getting this error when I try to run "train DF best GPU" 

Running trainer.

Loading model...
Loading: 0it [00:00, ?it/s]
Loading: 0it [00:00, ?it/s]
Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 258, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "C:\Users\Jeff\Desktop\cUDA\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\iter_utils.py", line 39, in process_func
    gen_data = next (self.generator_func)
  File "C:\Users\Jeff\Desktop\cUDA\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\models\TrainingDataGeneratorBase.py", line 73, in batch_func
    raise ValueError('No training data provided.')
ValueError: No training data provided.

**Comment by iperov** [comment]
RTX 2080 not supported yet
